### ISSUE TITLE
confidence intervals in KM survival analysis

### ISSUE THREAD

**Issue by Siji-chl** [CamDavidsonPilon/lifelines#1000]
Is there any way to calculate CI for the _S(t)_ given a specific _t_ in KM fitter？

**Comment by CamDavidsonPilon** [comment]
Hi @Siji-chl, there is: 
```
kmf.confidence_interval_.loc[t]
```

Is this what you are looking for?

**Comment by Siji-chl** [comment]
Thanks a lot @CamDavidsonPilon ! _kmf.confidence_interval__ returns a dataframe that contains CIs at many time points, but it is possible that the CI at a specific time that I want is not in the dataframe. What should I do in this situation?

**Comment by CamDavidsonPilon** [comment]
I see. You'll have to do some Pandas queries:
```
t = 10.5
kmf.confidence_interval_.iloc[kmf.confidence_interval_.index.get_loc(t, 'pad')]

```

**Comment by Siji-chl** [comment]
Thank you @CamDavidsonPilon very much! This solved my problem. 🙏
