### ISSUE TITLE
GammaFitter

### ISSUE THREAD

**Issue by fegarcia-bcam** [CamDavidsonPilon/lifelines#1001]
I would be very grateful if you could implement a GammaFitter.

For now I am exploring the GeneralizedGammaFitter, which you say may have convergence instabilities. Perhaps, by simplifying it down, these issues are less severe?

Or is there maybe a manner of enforcing `lambda` equals `sigma`? At first sight at the source code, I haven't found a simple one (for instance, an extra argument).

Thank you very much.

**Comment by CamDavidsonPilon** [comment]
Hi @fegarcia-bcam, you can do this with a custom model: 

```
import autograd.numpy as np
from lifelines.fitters import ParametricUnivariateFitter
from autograd_gamma import gammainccln, gammaincln


class GammaFitter(ParametricUnivariateFitter):

    _fitted_parameter_names = ["mu_", "lambda_"]
    _bounds = [(None, None), (0, None)]
    _compare_to_values = np.array([0.0, 1.0])


    def _cumulative_hazard(self, params, times):
        mu_, lambda_ = params

        Z = (np.log(times) - mu_) / lambda_
        ilambda_2 = 1 / lambda_ ** 2
        clipped_exp = np.clip(np.exp(lambda_ * Z) * ilambda_2, 1e-15, 1e20)

        v = -gammainccln(ilambda_2, clipped_exp)


        return v


T = np.random.exponential(1, size=100)
gf = GammaFitter()
gf.fit(T)
gf.print_summary()
```

Maybe one day I'll add it to lifelines

**Comment by fegarcia-bcam** [comment]
Thank you so much @CamDavidsonPilon 

It works perfectly, it's really clean code and you've been super helpful and quick!
