### ISSUE TITLE
Gompertz Regression doesn't converge properly

### ISSUE THREAD

**Issue by fmardero** [CamDavidsonPilon/lifelines#1007]
Hi, 
I'm tring to work with a custom `ParametricRegressionFitter` following the Gompertz low. I've tried with the waltons dataset, just to compare the results with what is reported [here](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Piecewise%20Exponential%20Models%20and%20Creating%20Custom%20Models.html#Gompertz).  

```
from lifelines.fitters import ParametricRegressionFitter
import autograd.numpy as auto_np

class GompertzFitter(ParametricRegressionFitter):
    # we tell the model what we want the names of the unknown parameters to be
    _fitted_parameter_names = ['alpha_', 'beta_']

    # this is the only function we need to define. It always takes two arguments:
    #   params: an dictionary that unpacks the parameters you'll need in the order of _fitted_parameter_names
    #   t: a vector of times that will be passed in.
    #   Xs: a dictionary that maps unknown parameters to a numpy 2d array
    def _cumulative_hazard(self, params, t, Xs):
        alpha = auto_np.dot(Xs['alpha_'], params['alpha_'])
        beta = auto_np.dot(Xs['beta_'], params['beta_'])
        
        return auto_np.expm1(beta * t) * alpha# / beta
```

The model seems to converge but in reality it keeps all the parameters at zero, during the whole training phase. All the scores are also `NaN`.

```
from lifelines.datasets import load_waltons
waltons = load_waltons()
waltons.group = waltons.group.apply(lambda x: 0 if x == 'control' else 1)
waltons['intercept'] = 1.0
#waltons

gf = GompertzFitter(penalizer=1.0)
covariates = {
    'alpha_': waltons.columns, #['intercept'],
    'beta_': waltons.columns,
}

gf.fit(waltons,
       'T',
       event_col='E',
       regressors=covariates,
       timeline=range(int(waltons['T'].min()), int(waltons['T'].max())+1))
gf.print_summary(2)

'''
                  coef  exp(coef)  se(coef)  coef lower 95%  coef upper 95%  \
alpha_ group       0.0        1.0       NaN             NaN             NaN   
       intercept   0.0        1.0       NaN             NaN             NaN   
beta_  group       0.0        1.0       NaN             NaN             NaN   
       intercept   0.0        1.0       NaN             NaN             NaN   

                  exp(coef) lower 95%  exp(coef) upper 95%   z   p  -log2(p)  
alpha_ group                      NaN                  NaN NaN NaN       NaN  
       intercept                  NaN                  NaN NaN NaN       NaN  
beta_  group                      NaN                  NaN NaN NaN       NaN  
       intercept                  NaN                  NaN NaN NaN       NaN 
'''
```

Am I missing something?

Thanks for help in advance,
Fabio

**Comment by CamDavidsonPilon** [comment]
Hi @fmardero, a few points:

1. `alpha` and `beta` need to be positive, so we should exponentiate them:

```
from lifelines.utils.safe_exp import safe_exp

class GompertzFitter(ParametricRegressionFitter):
    _fitted_parameter_names = ['alpha_', 'beta_']

    def _cumulative_hazard(self, params, t, Xs):
        alpha = safe_exp(auto_np.dot(Xs['alpha_'], params['alpha_']))
        beta =  safe_exp(auto_np.dot(Xs['beta_'], params['beta_']))
        return auto_np.expm1(beta * t) * alpha
```

2. Even with this change, the convergence is unfortunately unstable. That's because `expm1` has some overflow issues. We can use the `safe_exp` there too:

```
    def _cumulative_hazard(self, params, t, Xs):
        alpha = safe_exp(auto_np.dot(Xs['alpha_'], params['alpha_']))
        beta =  safe_exp(auto_np.dot(Xs['beta_'], params['beta_']))
        return (safe_exp(beta * t)-1) * alpha
```

This should give the results:
```
<lifelines.GompertzFitter: fitted with 163 total observations, 7 right-censored observations>
             duration col = 'T'
                event col = 'E'
                penalizer = 1.0
   number of observations = 163
number of events observed = 156
           log-likelihood = 805.83
         time fit was run = 2020-05-04 03:25:53 UTC

---
                   coef  exp(coef)   se(coef)   coef lower 95%   coef upper 95%  exp(coef) lower 95%  exp(coef) upper 95%
alpha_ group       0.46       1.58       0.18             0.09             0.82                 1.10                 2.26
       intercept  -4.74       0.01       0.37            -5.46            -4.02                 0.00                 0.02
beta_  group       0.23       1.25       0.05             0.13             0.33                 1.13                 1.39
       intercept   6.69     803.50       0.07             6.55             6.83               697.90               925.09

                      z      p   -log2(p)
alpha_ group       2.47   0.01       6.20
       intercept -12.87 <0.005     123.41
beta_  group       4.39 <0.005      16.42
       intercept  93.04 <0.005        inf
---
Log-likelihood ratio test = 39.23 on 2 df, -log2(p)=28.30

```

**Comment by fmardero** [comment]
Thank you very much for the anwser, didn't know `safe_exp` function. But what if, instead of accounting for a multiplicative model[*] in `beta`, i want to define

<img src="https://render.githubusercontent.com/render/math?math=\alpha = \alpha(X) = \sum_{i=1}^n \alpha_i x_i">
<img src="https://render.githubusercontent.com/render/math?math=\beta= \beta(X) = \sum_{i=1}^n \beta_i x_i"> 
so that
<img src="https://render.githubusercontent.com/render/math?math=H(t|X)=\frac{e^\alpha}{\beta} \left (e^{\beta t} - 1  \right )">

How can I handle the <img src="https://render.githubusercontent.com/render/math?math=\beta^{-1}"> factor without dividing by zero?

[*] Above I defined <img src="https://render.githubusercontent.com/render/math?math=\beta= \beta(X) = e^{\sum_{i=1}^n \beta_i x_i}">

**Comment by CamDavidsonPilon** [comment]
Yes, and the interpretation changes too. since alpha and beta must be positive, but the linear combination of covariates can be [-inf, inf], we have to make _some_ transformation to it. (This is similar to link functions in GLMs).

**Comment by fmardero** [comment]
Make sense, thank you. I have two more questions. 
1. How can i handle parameters that can take all values except zero? Let's say Perks mortality law for example.
   <img src="https://render.githubusercontent.com/render/math?math=H(t)= \frac{1}{\beta} log\left(\frac{1 %2B e^{\alpha %2B \beta t}}{1 %2B e^\alpha}\right)"> 

   Should I act on parameters'bounds and initialization? How?

2. If I have left-truncaded data an I use the `fit_left_censoring` function, how is this variable `entry` passed to `_cumulative_hazard`?

**Comment by CamDavidsonPilon** [comment]
1. I'm guessing you are referring the `beta`? Well, it's needs to be strictly positive, so again, you can use the `exp` trick. `exp` is never 0! The initialization will set all covariate's parameters to 0, so exp(0) = 1, and it'll be okay. 

2. Here's the code for how we handle left-truncated (late entries): https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/__init__.py#L1290-L1294 You, the model author, do not need to change anything as left-trunc information is incorporated in the likelihood. Does that make sense?

**Comment by fmardero** [comment]
Very clear, thanks.
