### ISSUE TITLE
Prediction on right-censored data  - Possible typo in documentation?

### ISSUE THREAD

**Issue by jlim13** [CamDavidsonPilon/lifelines#1036]
I was reading the tutorials and ran into this section
https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#id1

You start off this section by saying "When predicting time remaining for uncensored individuals, you can use the conditional_after kwarg:" Did you mean censored individuals? (Individuals whose arrest we have not observed in this study)

```
censored_X = rossi.loc[~rossi['arrest'].astype(bool)] 
censored_subjects_last_obs = censored_X['week']
aft.predict_cumulative_hazard(censored_X, ancillary_df=censored_X, conditional_after=censored_subjects_last_obs)
aft.predict_survival_function(censored_X, ancillary_df=censored_X, conditional_after=censored_subjects_last_obs)
aft.predict_median(censored_X, ancillary_df=censored_X, conditional_after=censored_subjects_last_obs)
aft.predict_percentile(X, p=0.9, ancillary_df=censored_X, conditional_after=censored_subjects_last_obs)
```

**Comment by CamDavidsonPilon** [comment]
Ah yes! I did mean censored individuals.

**Comment by jlim13** [comment]
Ok, great. Thanks for the clarification!

**Comment by CamDavidsonPilon** [comment]
reopening so I know to fix it :)

**Comment by jlim13** [comment]
are we able to make pull requests for small doc changes?

**Comment by CamDavidsonPilon** [comment]
Yes, of course!
