### ISSUE TITLE
How to increase max number of iterations

### ISSUE THREAD

**Issue by zxp567** [CamDavidsonPilon/lifelines#1038]
I recently upgraded the lifelines version. 
When using WeibullAFTFitter, I found it throws a "convergence error" and it seems the max number of iterations was reduced to 200, while in the past it could exceed that.
Is there any way that we could increase the max number of iterations? Didn't find any option in the fitter to do so?

Thank you.

**Comment by zxp567** [comment]
It seems there are hard-coded fitting options within "WeibullAFTFitter" and "LoglogisticAFTFitter", but not "LognormalAFTFitter".

```
_scipy_fit_method = "SLSQP"
_scipy_fit_options = {"ftol": 1e-10, "maxiter": 200}
```

**Comment by CamDavidsonPilon** [comment]
Hi @zxp567, these are hardcoded because they seem to "work" for most problems, but they can be overwritten quite easily:
```python
wf = WeibullAFTFitter()
wf. _scipy_fit_options = {"ftol": 1e-10, "maxiter": 500}
wf.fit(...)
```

**Comment by zxp567** [comment]
> Hi @zxp567, these are hardcoded because they seem to "work" for most problems, but they can be overwritten quite easily:
> 
> ```python
> wf = WeibullAFTFitter()
> wf._scipy_fit_options = {"ftol": 1e-10, "maxiter": 500}
> wf.fit(...)
> ```

That's great to hear! Thanks for the quick response!
