### ISSUE TITLE
Has anyone here run into a scenario in which one has a high c-index but low absolute mean error? 

### ISSUE THREAD

**Issue by jlim13** [CamDavidsonPilon/lifelines#1046]
absolute mean error is the average of the differences between the predicted time values and the actual observation time values.

my c-index is .85, but my absolute mean error is over 100. this means that my predictions are, on average, off by 100 days. any intuition as to how to proceed?

**Comment by CamDavidsonPilon** [comment]
This is definitely possible. The c-index is a rank-based score, so it does not penalize (or reward) extreme predictions being very wrong (or right). I would suggest relying less on the c-index (I'm slowly phasing out it's importance in lifelines), and focusing more on mean errors or log-likelihood based scores.

**Comment by jlim13** [comment]
thanks again for the quick response! i'm new to survival analysis (my background is in computer vision) and this has been a huge help :)
i see, good to know. to calculate the predicted duration of a given datapoint i see two options. 1 is to use the `predict_expectation()` or `predict_median()` functions. The other is to output the survival function with `predict_survival_function()` and use some threshold probability to determine the predicted duration. what is the correct option in your experience?

**Comment by CamDavidsonPilon** [comment]
Well, it depends on what you need a predicted duration for. If you are using it in downstream decision making, my preference is to output the survival function and integrate it against some loss function (like a business rule / outcome). If you are only focused on duration prediction, than `prediction_median` is good as it is robust against long tails.

**Comment by jlim13** [comment]
I see thanks for the insight. 

I actually have a follow questions on the `predict_survival_function()`. I see in the documentation that we assume that the individual just entered the study. https://github.com/CamDavidsonPilon/lifelines/blob/9cc5e2bb68682f7efc9babeb9fd7b136bc283d73/lifelines/fitters/coxph_fitter.py#L1559-L1560

If I am using this function for my censored test data, how can I account for the fact that I know the exact amount of time a given individual in my test data has been alive for. Do I use the `conditional_after` ?

**Comment by jlim13** [comment]
sorry idk why it was closed

**Comment by CamDavidsonPilon** [comment]
Yes, the `conditional_after` arg was designed for predicted uncensored subjects. (The docs may need to be updated to reflect that better)

**Comment by jlim13** [comment]
https://github.com/CamDavidsonPilon/lifelines/blob/9cc5e2bb68682f7efc9babeb9fd7b136bc283d73/lifelines/fitters/coxph_fitter.py#L1573-L1577

so `This is useful for knowing the *remaining* hazard/survival of censored subjects.` should be changed to `This is useful for knowing the *remaining* hazard/survival of uncensored subjects.`?

**Comment by CamDavidsonPilon** [comment]
Ack, I misspoke in my previous comment. I should have said: 

> Yes, the conditional_after arg was designed for predicted **censored** subjects. (The docs may need to be updated to reflect that better)

Sorry about the confusion!

**Comment by jlim13** [comment]
ok, thanks for the clarification. so for censored observation, I can just use the function without any additional arguments?

**Comment by CamDavidsonPilon** [comment]
Well, you could leave `conditional_after` blank, but you are then not using information (the fact that they lived to X years). I recommend putting in the censored subject's observed duration in `conditional_after`: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction

**Comment by jlim13** [comment]
ah, i overlooked that. thanks!
