### ISSUE TITLE
probability calibration

### ISSUE THREAD

**Issue by ioannis12** [CamDavidsonPilon/lifelines#1048]
hello, 

congrats for your work. I was wondering if there is any way to do probability calibration on predictions with lifelines. 
In sklearn there is CalibratedClassifierCV, but I don't know if it can be used for lifelines models.

greetings

**Comment by CamDavidsonPilon** [comment]
Hi @ioannis12, there's no built in way to help with that. I haven't given it much though tbh - have you come across a paper / technique that does this?

**Comment by ioannis12** [comment]
I use sigmoid calibration for other predictions, it reduces the difference between predicted and true probabilities, but I haven't seen anything for censored data.

**Comment by CamDavidsonPilon** [comment]
This new paper just came across my desk: https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8570 - reading it now

**Comment by CamDavidsonPilon** [comment]
Here's a start, I'll be expanding on this over the next week or so: https://github.com/CamDavidsonPilon/lifelines/blob/master/examples/survival_calibration.py

**Comment by ioannis12** [comment]
great, that's very interesting, I'm following

**Comment by CamDavidsonPilon** [comment]
This is now in the latest lifelines under `lifelines.calibration.survival_probability_calibration`
