### ISSUE TITLE
Cox PH Regression Baseline Hazard - Categorical Variables

### ISSUE THREAD

**Issue by EvanYathon** [CamDavidsonPilon/lifelines#1066]
Hi, 

I'm performing survival analysis on a data set, and getting some strange results.  I've created a reprex using the `gbsb` dataset from the lifelines datasets.

I'm new to survival analysis, so it's quite possible that my interpretation is at fault.  The issue is when I am looking at the coefficients of categorical variables in tandem with plotting covariate groups.  Here is the reprex:

```
# stats
from lifelines import *
from patsy import ModelDesc, dmatrix

# utility
import pandas as pd
import numpy as np

from lifelines.datasets import load_gbsg2
gbsb = load_gbsg2()

# select a few columns, including one categorical
gbsb_regr = gbsb[["tgrade", "time", "cens", "age", "tsize", "pnodes", "progrec"]]

# specify group III as the reference group
formula = ModelDesc.from_formula("""C(tgrade, Treatment('III')) + time + cens + age + tsize + pnodes + progrec""")

# get the dataframe using the formula - no intercept for CoxPH
gbsb_regr_encode = dmatrix(formula, data = gbsb_regr, return_type = "dataframe").drop(columns = ["Intercept"])

# Cox model - no regularization as we are trying to estimate coefficients
gbsb_cph = CoxPHFitter()
gbsb_cph.fit(gbsb_regr_encode, duration_col = "time", event_col = "cens")

gbsb_cph.print_summary()
```

`print_summary()` results:

![image](https://user-images.githubusercontent.com/26232281/85622623-5aff9a80-b624-11ea-925a-8b848ccda486.png)

```
gbsb_cph.plot_covariate_groups(["C(tgrade, Treatment('III'))[T.I]", "C(tgrade, Treatment('III'))[T.II]"], np.eye(2))
```
![image](https://user-images.githubusercontent.com/26232281/85622655-6bb01080-b624-11ea-8348-190e17e98352.png)

What I am confused about are the survival curves for the different encoded categorical variables.  The orange curve (level TII) has a higher hazard function (or lower survival) compared to baseline, which seems contrary to the coefficient estimate of `-0.18`.  From the coefficient estimate, I would expect a lowering of the hazard function.

I've read the issue #543 that states in `lifelines` the baseline hazard function is equal to the mean of the covariates - what does that mean for the reference-treatment coding I applied using `patsy`?

Thanks for writing a great package - the docs are excellent.

**Comment by CamDavidsonPilon** [comment]
Hi @EvanYathon, 

The baseline hazard function is a bit misleading here. Because we use the mean of the covariates, the baseline is evaluated at:
```
C(tgrade, Treatment('III'))[T.I]        0.118076
C(tgrade, Treatment('III'))[T.II]       0.647230
time                                 1124.489796
cens                                    0.435860
age                                    53.052478
tsize                                  29.329446
pnodes                                  5.010204
progrec                               109.995627
dtype: float64
```
The other two curves are evaluated at:
```
C(tgrade, Treatment('III'))[T.I]        0
C(tgrade, Treatment('III'))[T.II]       1
time                                 1124.489796
cens                                    0.435860
age                                    53.052478
tsize                                  29.329446
pnodes                                  5.010204
progrec                               109.995627
dtype: float64
```
and 

```
C(tgrade, Treatment('III'))[T.I]        1
C(tgrade, Treatment('III'))[T.II]       0
time                                 1124.489796
cens                                    0.435860
age                                    53.052478
tsize                                  29.329446
pnodes                                  5.010204
progrec                               109.995627
dtype: float64
```

So the baseline should be inbetween the other two curves. 

The problem is not your interpretation - it's how lifelines handles categorical variables for the baseline estimation. We do the naive thing (mean), but we should set categorical variables to all zeros (to be part of a refactor including #1060). I think you could hack this:
```python
values = np.array([
    [1, 0],
    [0, 1],
    [0, 0],
])
gbsb_cph.plot_covariate_groups(["C(tgrade, Treatment('III'))[T.I]", "C(tgrade, Treatment('III'))[T.II]"], values, plot_baseline=False)
```

produces:
<img width="727" alt="Screen Shot 2020-06-24 at 4 43 53 PM" src="https://user-images.githubusercontent.com/884032/85625739-e8011e80-b639-11ea-8958-c77a108159b5.png">

**Comment by EvanYathon** [comment]
That makes sense.  Thank you for the quick reply!
