### ISSUE TITLE
Dataset reading

### ISSUE THREAD

**Issue by shiven304** [CamDavidsonPilon/lifelines#1071]
Hi Cameron,
So I was trying to upload an excel file to perform a parametric hazard-based duration modelling, but the function Weibullaftfitter doesn't read anything except the event column btw the datframe i have created is reading the data from the xlsx file but that function is giving certain errors, maybe it is only reading the integer datatype but not the float. kindly help.
####################
The error that i am getting is:
KeyError                                  Traceback (most recent call last)
~\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2645             try:
-> 2646                 return self._engine.get_loc(key)
   2647             except KeyError:

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas\_libs\hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'time'

During handling of the above exception, another exception occurred:
#############

Thank you

**Comment by CamDavidsonPilon** [comment]
Hi @shiven304, can you provide the snippet of code that is causing this error? Are you able to show the columns in the dataframe?

**Comment by shiven304** [comment]
I got it @CamDavidsonPilon I was creating series of data that were there in the data frame and was providing the same for the attributes durationcol and event which later i got an error that some of my datapoints were not float but some other string and eventually resolved it. Btw you have done a nice work by creating this package , much appreciated
Thank you
