### ISSUE TITLE
For CoxPH - Parametric(baseline_estimation_method='spline'), the given below scenarios mentioned in 'Red' need to be fixed for censored observations

### ISSUE THREAD

**Issue by SurajitTest** [CamDavidsonPilon/lifelines#1074]
These scenarios are for censored observations. Attached file helps to replicate the scenario.
[1.3.Cox_PH_Model_Parametric_GridSearchCV_sent_Cam.txt](https://github.com/CamDavidsonPilon/lifelines/files/4867270/1.3.Cox_PH_Model_Parametric_GridSearchCV_sent_Cam.txt)

![image](https://user-images.githubusercontent.com/59294362/86421965-14dec100-bd1f-11ea-9a1a-4dbe3c5117b0.png)

**Comment by CamDavidsonPilon** [comment]
These should be fixed in the latest, v0.24.14
