### ISSUE TITLE
For CoxPH - Parametric(baseline_estimation_method='spline'), given below scenarios need to be fixed for censored observations

### ISSUE THREAD

**Issue by SurajitTest** [CamDavidsonPilon/lifelines#1076]
1) Methods predict_cumulative_hazard() and predict_survival_function() when used with 'times' parameter do not show the effect of using 'times' parameter - means that the output of methods predict_cumulative_hazard() and predict_survival_function() have all time periods starting from min time period of training dataset to max time period of training dataset and the 'times' parameter does not have any effect on the output.

2) With regards to method predict_median(), I did observe many censored subjects for whom all(corresponding to different time periods) of survival probabilities are greater than 0.5 , but still then the corresponding median lifetime value is INFINITY.

Attaching python program (Cox_PH_Model_Parametric_GridSearchCV_sent_Cam_July_07_2020.txt) to replicate scenario.
[Cox_PH_Model_Parametric_GridSearchCV_sent_Cam_July_07_2020.txt](https://github.com/CamDavidsonPilon/lifelines/files/4887689/Cox_PH_Model_Parametric_GridSearchCV_sent_Cam_July_07_2020.txt)

**Comment by CamDavidsonPilon** [comment]
1. is fixed in the latest lifelines, as for 2. can you isolate the problem into a smaller script and please open a more specific issue?
