### ISSUE TITLE
AttributeError: 'CoxPHFitter' object has no attribute 'predict_hazard'

### ISSUE THREAD

**Issue by jlim13** [CamDavidsonPilon/lifelines#1092]
I can't seem to call `fitter.predict_hazard()` 
I am using version 0.24.9

**Comment by CamDavidsonPilon** [comment]
Hi @jlim13, this is by design. The hazard for the cox model is very noisy, due to it being non-parametric. Instead, we encourage use of either `predict_cumulative_hazard`, `predict_partial_hazard`  or `predict_log_partial_hazard`.

**Comment by jlim13** [comment]
gotcha, thanks! I was actually reading through more of the comments in the source code and `predict_log_partial_hazard` is what I was looking for. Thanks for the prompt response
