### ISSUE TITLE
Right after upgrading to 0.25.0, CoxPHFitter complains about not finding "patsy"

### ISSUE THREAD

**Issue by greencrab** [CamDavidsonPilon/lifelines#1100]
Seems like the latest version require the "patsy" library, but it's not in `reqs/base-requirements.txt`.  There's a "statsmodel" requirement in `reqs/dev-requirements.txt` that might get you patsy.  But it was not pull when I did `pip install -U lifelines`

**Comment by CamDavidsonPilon** [comment]
uh oh, did I forget to add patsy 😓
