### ISSUE TITLE
Difficulty determining confidence intervals on median survival times of left-censured data

### ISSUE THREAD

**Issue by mikekoss** [CamDavidsonPilon/lifelines#1124]
I am trying to determine the confidence intervals on the median on some left-censured data.  For some reason I keep getting inf when I run median_survival_times(kmf1.confidence_interval_). Below is the code where I am trying to estimate the median CI at 0.95 and 0.84 (1 sigma).  I do get an estimate from the kmf plot, but I don't understand why the values are so similar.  Here's the data file and code.

import pandas as pd
from lifelines import KaplanMeierFitter
from lifelines.utils import median_survival_times

test_df = pd.read_csv("out.csv")
T, E = test_df['loggasfrac'], test_df['lf_censor']

kmf1=KaplanMeierFitter().fit_left_censoring(T,E,label="0.95 cf")
kmf2=KaplanMeierFitter().fit_left_censoring(T,E,alpha=0.16,label="0.84 cf")

median_ci1_test1 = median_survival_times(kmf1.confidence_interval_)
print(median_ci1_test1)

median_ci1_test2 = median_survival_times(kmf2.confidence_interval_)
print(median_ci1_test2)

median_ci_idx1 = kmf1.confidence_interval_.index.get_loc(kmf1.median_survival_time_,
                                                       method='nearest')
median_ci1 = kmf1.confidence_interval_.iloc[median_ci_idx1]

median_ci_idx2 = kmf2.confidence_interval_.index.get_loc(kmf2.median_survival_time_,
                                                       method='nearest')
median_ci2 = kmf2.confidence_interval_.iloc[median_ci_idx2]

print(median_ci1)
print(median_ci2)

kmf1.plot()
kmf2.plot()
[out.csv.zip](https://github.com/CamDavidsonPilon/lifelines/files/5137975/out.csv.zip)

**Comment by CamDavidsonPilon** [comment]
Hi @mikekoss - 

Ah, this is an inconsistency in the API that I should make more clear. For left censored data, `confidence_interval_` returns the  CIs for the _CDF_, not the survival function (1-CDF). Try
```
median_survival_times(kmf.confidence_interval_survival_function_)
```

**Comment by mikekoss** [comment]
Ah great that solve my issue. Thanks!
