### ISSUE TITLE
Schoenfeld plots settings

### ISSUE THREAD

**Issue by nyousefi2020** [CamDavidsonPilon/lifelines#1126]
Hello,
I'm using CoxPHfitter to perform a survival analysis. I use check_assumptions to check PH assumptions. 
I wonder if it's possible to adjust the y-axis for the Schoenfeld plots using check_assumptions or any alternative way. For example, I want to see just the part of the plot between -1 and 1 (y-axis). Any advice is appreciated.
Nasrin

**Comment by CamDavidsonPilon** [comment]
Hi @nyousefi2020, hm, unfortunately not, but I can add support in a future release.

**Comment by nyousefi2020** [comment]
Thanks! Yes, that would be great as it'll facilitate visual inspection.

**Comment by CamDavidsonPilon** [comment]
@nyousefi2020 actually this can be done currently - the function returns a list of axes, each of which can be modified: 
```
axes = cph.check_assumptions(rossi, show_plots=True)
for _ in axes:
   for ax in _:
     ax.set_ylim(0, 1)

plt.show()
```
