### ISSUE TITLE
Trying to understand why confidence limits are so large for left censured data with only a few limits

### ISSUE THREAD

**Issue by mikekoss** [CamDavidsonPilon/lifelines#1128]
I am trying to understand why data where we have only a few left-censured data points, returns a larger than expected confidence limit.  So for example we have an array below with just 1,2,3,4,5 where the lowest data point (1) is left censured.  So we would normally say that no matter what that left censured data point is (0,-1,-infinity), the median would still be 3.  But the 95 percent confidence limits list 0 to 5.  This is really surprising to me, is survival analysis somehow incorporating the fact we only have a small dataset, and thus gives a large 95% CI or 0 to 5.

import pandas as pd
import numpy as np
from lifelines import KaplanMeierFitter
from lifelines.utils import median_survival_times

T=[1,2,3,4,5]
E=[False,True,True,True, True]

kmf1=KaplanMeierFitter().fit_left_censoring(T,E,label="0.95 cf")

median_ci1_test1 = median_survival_times(kmf1.confidence_interval_survival_function_)

print(f'median is {np.median(T):0.2f}')
print(f'median survival is {kmf1.median_survival_time_}')
print(f'median_ci survival is {median_ci1_test1}')

kmf1.plot()

**Comment by CamDavidsonPilon** [comment]
> This is really surprising to me, is survival analysis somehow incorporating the fact we only have a small dataset, and thus gives a large 95% CI or 0 to 5.

This seems likely - with only 5 data points we should have lots of uncertainty in _any_ point estimate (regardless of censoring or not)
