### ISSUE TITLE
Predicting the survival function of some individuals do not reach zero

### ISSUE THREAD

**Issue by jwayne2978** [CamDavidsonPilon/lifelines#1132]
Hi, when I call  `predict_survival_function` on a dataset using `CoxPHFitter`, some individuals never reach zero. If I extend the time out and plot, for some individuals/lines, they just extend out horizontally above zero. Any ideas on how to get the prediction to get time-phased survival function at zero for these individuals?

`df = predict_survival_function(X, times=range(0, 3000, 1))`
`df.plot.line()`

**Comment by CamDavidsonPilon** [comment]
Hi @jwayne2978, 

That's a consequence of using the semi-parametric Cox model - it's can't extrapolate into the future since there is no parametric model to rely on! You can try using the spline option with Cox (makes it fully parametric), or any other regression model.

**Comment by jwayne2978** [comment]
@CamDavidsonPilon Thanks!
