### ISSUE TITLE
cannot import name 'root_scalar' from 'scipy.optimize'

### ISSUE THREAD

**Issue by NoaKel** [CamDavidsonPilon/lifelines#1139]
When importing the package I get the following error:

ImportError: cannot import name 'root_scalar' from 'scipy.optimize' (/Users/noalubin/patient2rank/venv/lib/python3.7/site-packages/scipy/optimize/__init__.py)

**Comment by CamDavidsonPilon** [comment]
Hi there, 

1. what version of lifelines are you using? 
2. what version of scipy are you using?

**Comment by roliu-ea** [comment]
I have the same issue.

My version of lifeline 0.23.9
scipy: 1.4.1
