### ISSUE TITLE
Batch Mode and Tied Data

### ISSUE THREAD

**Issue by GregoryCG** [CamDavidsonPilon/lifelines#1153]
I am using the CoxPHFitter() and am wondering how the model deals with tied data. I got the same log-likelihoods scores when fitting the model with batch_mode=True and batch_mode=False. How is the model batching the tied data? Is there a way to know the batch size?

**Comment by CamDavidsonPilon** [comment]
Hi @GregoryCG, 

batch mode is a more efficient implementation of the Cox likelihood, and should always produce identical results. It should be faster when you dataset has more ties. You can read about it here: https://dataorigami.net/blogs/napkin-folding/using-statistics-to-make-statistical-computations-faster

**Comment by GregoryCG** [comment]
Great. Thank you for sharing!
