### ISSUE TITLE
add_at_risk_counts overlapping text information with X-axis label

### ISSUE THREAD

**Issue by andradekc** [CamDavidsonPilon/lifelines#1155]
Hello,

I'm creating plots side by side, but the text from add_risk_count overlaps with the X-axis label in my left-most plot. This happens only if I have more than one plot and always for the same position (axes[0]). All other plots have appropriate spacing.

Any thoughts on this? I'm using lifelines version 25.4.
Thank you very much.

**Comment by CamDavidsonPilon** [comment]
Hi @andradekc, can you provide some code and a screenshot of the figure? That will help me debug what's going on.
