### ISSUE TITLE
Why ~10% Cure Rate in This Example?

### ISSUE THREAD

**Issue by invictus2010** [CamDavidsonPilon/lifelines#1156]
At the bottom of this [page](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Modelling%20time-lagged%20conversion%20rates.html), we see the following chart:

![image](https://user-images.githubusercontent.com/17661001/96921775-fabb2100-147c-11eb-876f-16f8d8c94ccb.png)

The commentary is: `Under this model, it suggests that only ~10% of subjects are ever cured (however, there is a lot of variance in the estimate of the p parameter).` 

I see the above chart as suggesting ~20-70% of patients are ever cured. Am I interpreting this incorrectly or is this an error in the documentation? If an error, I can submit a PR.

**Comment by CamDavidsonPilon** [comment]
The 10% comes from the parameter estimates (`p`):
<img width="687" alt="Screen Shot 2020-10-22 at 4 29 06 PM" src="https://user-images.githubusercontent.com/884032/96926600-c303a780-1483-11eb-89cc-b14681127d0c.png">

If we were to extend out the plot to infinity, the survival function would be asymptotic to 0.1

**Comment by invictus2010** [comment]
d'oh! thank you.
