### ISSUE TITLE
Issue with interval censoring for CoxPHFitter

### ISSUE THREAD

**Issue by kennylee15** [CamDavidsonPilon/lifelines#1158]
Hi there,

Calling fit_interval_censoring on an instance of CoxPHFitter leads to an odd error. 

For example, running the test codes below leads to the following result:

<b>Test Codes</b>

```
from lifelines import CoxPHFitter
from lifelines.datasets import load_diabetes

df = load_diabetes()
df['gender'] = df['gender'] == 'male'

print(df.head())

cph = CoxPHFitter()
cph.fit_interval_censoring(df, lower_bound_col='left', upper_bound_col='right')
cph.print_summary()

```

<b>Errors</b>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-870e534d8026> in <module>
      8 
      9 cph = CoxPHFitter()
---> 10 cph.fit_interval_censoring(df, lower_bound_col='left', upper_bound_col='right')
     11 cph.print_summary()

~/opt/anaconda3/lib/python3.8/site-packages/lifelines/fitters/coxph_fitter.py in __getattr__(self, attr)
    296             raise AttributeError("Must call `fit` first.")
    297 
--> 298         if hasattr(self._model, attr):
    299             return getattr(self._model, attr)
    300 

~/opt/anaconda3/lib/python3.8/site-packages/lifelines/fitters/coxph_fitter.py in __getattr__(self, attr)
    294     def __getattr__(self, attr):
    295         if attr == "_model":
--> 296             raise AttributeError("Must call `fit` first.")
    297 
    298         if hasattr(self._model, attr):

AttributeError: Must call `fit` first.
```
I am running 

- Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
- lifelines 0.25.5

on JupyterLab.

Reading up the [doc](https://lifelines.readthedocs.io/en/latest/fitters/regression/CoxPHFitter.html#lifelines.fitters.coxph_fitter.CoxPHFitter.fit_interval_censoring) I thought I could just call it directly on a CoxPHFitter class. Am I doing something wrong here?

Thanks!

**Comment by CamDavidsonPilon** [comment]
Right, I'll need to put a control in for this case. So the _semi_-parameteric `CoxPHFitter`(i.e. `breslow` baseline estimation, the default) can't do interval censoring - you need to instead use a different baseline estimator, like so:
```
CoxPHFitter(baseline_estimation_method="spline").fit_interval_censoring(...)
```

**Comment by kennylee15** [comment]
Thanks for the advice. At the moment, other options for estimating the baseline function also run into the same error. I'll switch over to a parametric model for now.

**Comment by CamDavidsonPilon** [comment]
??? really? Oh wow you are right. Hm, I'll probably fix this asap then

**Comment by CamDavidsonPilon** [comment]
Huh, this never worked, and I always thought it did haha. I'll push something later today.
