### ISSUE TITLE
CoxPHFitter duration_col of right-censored observations impacts results?

### ISSUE THREAD

**Issue by beerzyp** [CamDavidsonPilon/lifelines#1163]
Hi I'm running into a problem wich probably is occurring by misusage but any help is appreciated.

My dataset contains 539 total observations, 346 right-censored observations. The right-censored observations have no value for duration_col (as they are right-censored obviously).
However to run CoxPHFitter.fit I can't pass it NaN values even in the duration_col (which doesn't make a lot of sense to me).

The problem is when I fill the NA values of the duration_col of right-censored observations I get different performances depending on the fill value. So what is the proper usage for this, am I missing something?

**Comment by CamDavidsonPilon** [comment]
Hi @beerzyp, 

So the right-censored observations _should_ have a value. It should be equal to how long you observed them for (however, you didn't see their "end", hence their _entire_ duration is censored). I can help more if you provide more details about the domain and dataset.

**Comment by beerzyp** [comment]
Hi Cam, first of all, thank you for your prompt answer.

I'm working in survival analysis for cancer patients using TCGA datasets. 
My dataset has no follow-up records (only 1 record by patient) and I'm using days_to_death (number of days until the patient dies) as the duration_col.

I'm following this example [Survival Analysis TCGA](https://www.bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/analysis.html#TCGAanalyze_survival:_Survival_Analysis).
I'm confused as to what I should impute the duration_col for missing values as the event (death) hasn't occurred but maybe I'm not modelling the problem correctly.

I'll post a snippet of my data below [here](https://pastebin.com/VWghQSLa) but the only variables I have relating to time are days_to_last_follow_up, days_to_collection, days_to_birth, days_to_death.

Thank you in advance for your help 👍

**Comment by CamDavidsonPilon** [comment]
The duration col should be the difference between 
1. entry into study (the "birth" event)
2. date of death _or_ date of last follow up.

Do you lack one of those values?

**Comment by beerzyp** [comment]
I do have the columns you suggest, of course, date_of_death is missing for right-censored observers and date_of _last_followup is missing for the event observers.

I don't understand the logic of that subtraction but do you suggest I do the following?

1. _event observers_: duration = days_to_birth - days_to_death
2. _right-censored observers_: duration = days_to_birth - days_to_last_followup

**Comment by CamDavidsonPilon** [comment]
> I don't understand the logic of that subtraction but do you suggest I do the following?

I'm guessing `days_to_birth` is how old they are? Which is maybe useful as a variable, but it looks like the day of interest is time 0 - when they entered the study. So 

Subject 1: T = 1559, E = 0
Subject 2: T = 385, E = 1

**Comment by beerzyp** [comment]
Thanks again for your help! I found a piece of documentation that explains both variables:

- days_to_death - The number of days from the date of the initial pathological diagnosis to the date of death for the case in the investigation.
- days_to_last_followup - Time interval from the date of last follow up to the date of initial pathologic diagnosis, represented as a calculated number of days.

Your answer seems to make sense, thank you very much for clarifying that for me, I was misinterpreting the variables. 
However, I'm still confused about 1 case present in the dataset. Some patients who are dead (E=1) have both days_to_last_followup and days_to_death with values, so for these cases, I should guide myself only by the days_to_death right?

**Comment by CamDavidsonPilon** [comment]
> However, I'm still confused about 1 case present in the dataset. Some patients who are dead (E=1) have both days_to_last_followup and days_to_death with values, so for these cases, I should guide myself only by the days_to_death right?

that seems right - are the values equal? That would make thing simpler, if so. 

Glad this helped - I'll close the issue now
