### ISSUE TITLE
[bug] label attribute overwritten in fit method for ParametricUnivariateFitter

### ISSUE THREAD

**Issue by jamesmyatt** [CamDavidsonPilon/lifelines#1170]
Using the following code gives an assertion error

```
fitter = WeibullFitter(label="Weibull")
fitter.fit(observed_lifetimes, event_observed=death_observed)
assert fitter._label == "Weibull"
```

For `fitter = KaplanMeierFitter(label="KM")`, the assertion passes.

I think that this is due to the following line in `ParametricUnivariateFitter._fit` where the _label is overwritten:

https://github.com/CamDavidsonPilon/lifelines/blob/3d92bb6884b7655960aecd9bcf1cad97f41d00ed/lifelines/fitters/__init__.py#L936

I'm using lifelines 0.25.4

**Comment by CamDavidsonPilon** [comment]
Hi @jamesmyatt - indeed, this is a bug. Thanks for letting me know! 

If this is blocking, you can use the `label` kwarg in `fit`: 

```
fitter = WeibullFitter()
fitter.fit(observed_lifetimes, event_observed=death_observed, label="Weibull")
assert fitter._label == "Weibull"
```
