### ISSUE TITLE
Function cumulative_hazard_at_times(timeline) of NelsonAalenFitter is not implemented

### ISSUE THREAD

**Issue by Dekermanjian** [CamDavidsonPilon/lifelines#1174]
Hi, I am trying to get the cumulative hazards that are estimated by the NelsonAalenFitter for a specific time but the function throws a not implemented error. Is this intentional?

**Comment by CamDavidsonPilon** [comment]
Hi @Dekermanjian, hm, looks like a problem on my end - that _should_ exist. For now, you can use the `naf.predict` method to get c.hazard at specific times. Let me know if that works or not!

**Comment by Dekermanjian** [comment]
Yes! That works. Thank you very much.

**Comment by CamDavidsonPilon** [comment]
Reopen so I fix this
