### ISSUE TITLE
delta contains nan value(s). Convergence halted.

### ISSUE THREAD

**Issue by simonjuleseric2** [CamDavidsonPilon/lifelines#1176]
I'm having trouble with the Cox Proportional Hazard Model, it always gives me the errors:
"delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:
https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model"

However my dataset's feature don't seem to heavily correletad (as is suggested) and trying do display steps (as sugested in the documentation) doesn't give any information (no step displayed).

Link to the table with my data (anonymized):
https://drive.google.com/file/d/136q977Djq80jB1TLFJZ2lSVS2m7oltzv/view?usp=sharing

**Comment by CamDavidsonPilon** [comment]
Hi @simonjuleseric2 - there is some missing data in the csv you linked - is that expected? If so, you'll definitely need to drop those. What is the duration / event col in your dataset?

**Comment by simonjuleseric2** [comment]
Yes indeed, sorry for that..
