### ISSUE TITLE
How to add factors (categorical variables) when fitting WeibullAFT model

### ISSUE THREAD

**Issue by leavor** [CamDavidsonPilon/lifelines#1179]
## Problem
Here are some data, the response is arbitrarily censored, the predictor variables have factors(Category data) and covariates, the question is: How to add factors and crossed terms when fitting a model.
I tried to add factors, but no success
I have made some attempts with these data (No factor used), the code,data and minitab result is as follows
## Code
No factor and crossed term used
```python
import numpy as np
import pandas as pd
from lifelines import WeibullAFTFitter
data = pd.read_excel('data.xlsx',sheet_name='Sheet1')
data['start'] = data['start'].fillna(0)#left censor
data['end'] = data['end'].fillna(np.inf)#right censor
wAFT = WeibullAFTFitter()
wAFT.fit_interval_censoring(data.loc[:,['start','end','weight']],
                            lower_bound_col='start',
                            upper_bound_col='end')
index=['weight','intercept','shape']
params = wAFT.params_
params.index = index
params.loc['shape'] = np.exp(params.loc['shape'])
print(params)
```
Console Output:
weight      -0.116205
intercept    7.083171
shape        2.442632
dtype: float64
## Data
The "design" is factor
[data.xlsx](https://github.com/CamDavidsonPilon/lifelines/files/5607054/data.xlsx)

## Minitab Result (No factor crossed term used)
![image](https://user-images.githubusercontent.com/1759365/100434785-fc10e680-30d7-11eb-9707-1202ccc7c2d8.png)
Minitab result is the same as the Python code result.

## Minitab Result (factor and crossed item used)
response: "start" "end"
predictive variable: "design" "weight"  "design"*"weight"
distribution:Weibull
![image](https://user-images.githubusercontent.com/1759365/100435704-46469780-30d9-11eb-8bef-8f7fac5c9e74.png)

![image](https://user-images.githubusercontent.com/1759365/100435732-50689600-30d9-11eb-99d0-9dc4c1a0ad06.png)

**Comment by CamDavidsonPilon** [comment]
Hi @leavor, Are you looking for the use of `formula`s? 

```
wAFT = WeibullAFTFitter()
wAFT.fit_interval_censoring(data,
                            lower_bound_col='start',
                            upper_bound_col='end',
                            formula="design * weight")
print(wAFT.summary)
```

This will produce the interaction (and individual terms) between `design` variable and `weight` variable. More docs here: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html?highlight=formula#fitting-the-regression

**Comment by leavor** [comment]
Thanks for your help @CamDavidsonPilon ,I have done as you said,but I failed.
Finally, I prepared the design matrix in advance, without using ```formula```, I can get the correct result.
The code and traceback are as follow:
## Failed code
```python
import numpy as np
import pandas as pd
from lifelines import WeibullAFTFitter
data = pd.read_excel('data.xlsx',sheet_name='Sheet1')
data['start'] = data['start'].fillna(0)#left censor
data['end'] = data['end'].fillna(np.inf)#right censor
wAFT = WeibullAFTFitter()
wAFT.fit_interval_censoring(data,
                            lower_bound_col='start',
                            upper_bound_col='end',
                            formula="design * weight")
```
## Traceback of failed code
```python-traceback
File "E:\work\Amos\练习测试\wiebull寿命数据回归.py", line 25, in <module>
    formula="design * weight")
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\lifelines\utils\__init__.py", line 72, in f
    return function(model, *args, **kwargs)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\lifelines\fitters\__init__.py", line 2981, in fit_interval_censoring
    entry_col=entry_col,
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\lifelines\fitters\__init__.py", line 1762, in _fit
    Xs = self.regressors.transform_df(df)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\lifelines\utils\__init__.py", line 1907, in transform_df
    X = df[transform]
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\pandas\core\frame.py", line 2908, in __getitem__
    indexer = self.loc._get_listlike_indexer(key, axis=1, raise_missing=True)[1]
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\pandas\core\indexing.py", line 1254, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "C:\Users\Admin\Anaconda3\envs\python3.7.9\lib\site-packages\pandas\core\indexing.py", line 1304, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['design * weight'] not in index"
```

## Successful code
```python
import numpy as np
import pandas as pd
import patsy
from lifelines import WeibullAFTFitter
data['start'] = data['start'].fillna(0)
data['end'] = data['end'].fillna(np.inf)
wAFT3 = WeibullAFTFitter()
design_infos = 'start~design+weight+design:weight+0'
_,X = patsy.dmatrices(design_infos, data, return_type="dataframe")
X = X.drop('design[new]',axis=1)
X['start'] = data['start']
X['end'] = data['end']
wAFT3.fit_interval_censoring(X,'start','end')
print(wAFT3.params_)
```
Console Output:
```
param    covariate           
lambda_  design[T.old]:weight   -0.024693
         design[old]            -0.496114
         weight                 -0.052302
         Intercept               6.648893
rho_     Intercept               1.676082
dtype: float64
```
The result is the same as Minitab Result (factor and crossed item used) above

**Comment by CamDavidsonPilon** [comment]
Thanks for the report @leavor, I'll dig into what when wrong. By chance, are you able to share the dataset? That would help

**Comment by leavor** [comment]
> Thanks for the report @leavor, I'll dig into what when wrong. By chance, are you able to share the dataset? That would help
The dataset(JetEngineReliability.MTW) comes from the minitab example, I just use it for testing.
[https://support.minitab.com/en-us/minitab/19/help-and-how-to/statistical-modeling/reliability/how-to/regression-with-life-data/before-you-start/example/](url)
