### ISSUE TITLE
How is it possible to plot calibration curves for deep-learning output with lifelines?

### ISSUE THREAD

**Issue by Jaqen00** [CamDavidsonPilon/lifelines#1182]
Hi,
Thanks for this awesome package!
My Question:
How is it possible to plot calibration curves for DL output with lifelines?
I trained the deep-learning(DeepSurv) model, which produced hazards. How do I draw the calibration curves with this output?

**Comment by CamDavidsonPilon** [comment]
Hi @Jaqen00 - it's not possible, but you can follow the code in `lifelines.calibration` to do it outside the library. Also take a lok at the paper https://onlinelibrary.wiley.com/doi/full/10.1002/sim.8570
