### ISSUE TITLE
KM at_risk_counts intervals do not align with manually selected plot interval

### ISSUE THREAD

**Issue by kadufendach** [CamDavidsonPilon/lifelines#1184]
I am trying to generate a K-M curve over 60 months with interval 12 (instead of 10, which is automatically selected). As demonstrated below, at_risk_counts do not align with 12 month intervals which I've manually set using set_xticks.

![KM_issue](https://user-images.githubusercontent.com/74421108/101014537-00a02980-3534-11eb-80a6-3945096e535a.png)

Example code is as follows:
```
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lifelines import KaplanMeierFitter

df = pd.DataFrame({
    'durations': [5, 32, 14, 55, 18, 29, 28, 39, 2, 1, 60, 7],
    'events': [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0]})

D = df['durations']
E = df['events']

kmf = KaplanMeierFitter() 
kmf.fit(D, E,label="Kaplan-Meier Estimate")

ax = kmf.plot(ci_show=False, at_risk_counts=True) ## want at_risk_counts to be 12 month intervals
plt.tight_layout()

ax.set_xticks(range(0,61,12)) ## set x-axis ticks to represent 12 month intervals
ax.set_xlabel('Months')
ax.grid(b=True, axis='y')
plt.show()
```

I have also tried adding timeline=range(0,61,12) to kmf.fit, but this does not change the at_risk_counts interval. For ex:

```
kmf.fit(D, E, label="Kaplan-Meier Estimate", timeline=range(0,61,12))
ax = kmf.plot(ci_show=False, at_risk_counts=True) ## want at_risk_counts to be 12 month intervals
plt.tight_layout()

ax.set_xticks(range(0,61,12)) ## set x-axis ticks to represent 12 month intervals
ax.set_xlabel('Months')
ax.grid(b=True, axis='y')
plt.show()
```
Thank you in advance for any help.

**Comment by CamDavidsonPilon** [comment]
Hi @kadufendach, try this:

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lifelines import KaplanMeierFitter

df = pd.DataFrame({
    'durations': [5, 32, 14, 55, 18, 29, 28, 39, 2, 1, 60, 7],
    'events': [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0]})

D = df['durations']
E = df['events']

kmf = KaplanMeierFitter() 
kmf.fit(D, E,label="Kaplan-Meier Estimate")

ax = kmf.plot(ci_show=False) 
plt.tight_layout()

ax.set_xticks(range(0,61,12)) 

# now add the table:
from lifelines.plotting import add_at_risk_counts
add_at_risk_counts(kmf, ax=ax)

ax.set_xlabel('Months')
ax.grid(b=True, axis='y')
plt.show()
```

**Comment by kadufendach** [comment]
Worked perfectly @CamDavidsonPilon, thanks for your help!

**Comment by CamDavidsonPilon** [comment]
Glad to hear - I'm going to reopen this so it remind me to add a note to the documentation on this.

**Comment by chrispoptic** [comment]
Hi @CamDavidsonPilon I'm in a similar situation where I'm passing in the `at_risk_counts` parameter to `True` in the call to `plot_survival_function()` rather than calling the `add_at_risk_counts()` on that KMfitter.

Is it possible to specify the `xticks` intervals for the survival table in the `plot_survival_function()` function call?

**Comment by CamDavidsonPilon** [comment]
Hi @chrispoptic,

I'm hestitant to add a new kwarg to `plot_survival_function` - but here's something you can try to specify the interval:
```
interval = 5
ax = plt.subplot()
ax.set_xticks(np.arange(0, 100, interval))

kmf = KaplanMeierFitter(...)
kmf.plot(ax=ax, at_risk_counts=True)

plt.show()
```

Something like that?
