### ISSUE TITLE
Updates to the model serialization example

### ISSUE THREAD

**Issue by mekomlusa** [CamDavidsonPilon/lifelines#1196]
First of all, thanks for this awesome package - it's really helpful for newbies as me to quickly get started in the field of survival analysis. I've trained a `CoxPHFitter` model and would like to save it to the disk for future inference. I was able to find the following codes from [this file](https://github.com/CamDavidsonPilon/lifelines/blob/master/docs/Examples.rst#serialize-a-lifelines-model-to-disk) but looks like there's a typo below: (see my comments next to those lines) 

```
from dill import loads, dumps
from pickle import loads, dumps

s_cph = dumps(cph)
cph_new = loads(s_cph)
cph.summary # shouldn't it be cph_new.summary?


s_kmf = dumps(kmf)
kmf_new = loads(s_kmf)
kmf.survival_function_ # shouldn't it be kmf_new.summary?
```

The codes above only serialize binary objects in memory. It would be helpful if the following example codes could be added, too, to help others save their trained models to local path:

```
import pickle

with open('/path/my.pickle', 'bw') as f:
    pickle.dump(cph, f) # saving my trained cph model

with open('/path/my.pickle', 'rb') as f:
    cph_new = pickle.load(f)

cph_new.summary # should produce the same output as cph.summary
```

I can submit a merge request for this, if anybody finds it interested.

**Comment by CamDavidsonPilon** [comment]
I love this suggestion (and agree that it's a typo) - feel free to send a PR and I'll merge it
