### ISSUE TITLE
sklearnadapater - KaplanMeierFitter demands a label

### ISSUE THREAD

**Issue by willking2** [CamDavidsonPilon/lifelines#1198]
Hi Cameron, awesome library!
My issue is that when I try to use the Lifelines (v0.25.7) sklearn_adapter with KaplanMeierFitter, it seems to be missing the ["label" attribute](https://lifelines.readthedocs.io/en/latest/fitters/univariate/KaplanMeierFitter.html). I googled around but didn't find any obvious solutions. I'd appreciate any suggestions you might have. Thank you.

Adapting your [Cox Regression example](https://lifelines.readthedocs.io/en/latest/Compatibility%20with%20scikit-learn.html#compatibility-with-scikit-learn) to demonstrate the issue:
```
from lifelines import KaplanMeierFitter
from lifelines.utils.sklearn_adapter import sklearn_adapter
from lifelines.datasets import load_rossi

X = load_rossi().drop('week', axis=1) # keep as a dataframe
Y = load_rossi().pop('week')

KaplanMeierEstimator = sklearn_adapter(KaplanMeierFitter, event_col='arrest')
sk_kme = KaplanMeierEstimator()
sk_kme
```
Error message:
`AttributeError: 'KaplanMeierFitter' object has no attribute 'label'
`

**Comment by CamDavidsonPilon** [comment]
Hey there, I don't think you should be using `KaplanMeierFitter` with `sk_kme`. At least, I didn't design it so. What are you trying to achieve here?

**Comment by willking2** [comment]
Thanks for your quick response. I'm exploring the possibility of using `sklearn_adapater` as a nice wrapper to conveniently log fitted KM models in `MLflow`, which has an existing [flavor](https://www.mlflow.org/docs/latest/models.html#scikit-learn-sklearn) for logging `sklearn` models. Based on your response, this path is probably not useful to continue exploring -- which is helpful to know.
