### ISSUE TITLE
sklearnadapter - CoxPHFitter not supported as estimator for RFECV()

### ISSUE THREAD

**Issue by jrbihn-va** [CamDavidsonPilon/lifelines#1200]
Hello,

I have been attempting to use the Lifelines (v0.25.7) sklearn_adapter to apply the CoxPHFitter as an estimator for [sklearn.feature_selection.RFECV](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFECV.html#sklearn.feature_selection.RFECV). However, I am running into an error where the fit method within sklearn_adapter requires a DataFrame, but is being passed an nparray from the RFECV function. Do you have any suggestions at how to adjust the sklearn_adapter to be compatible with RFECV?

I demonstrate the error below:

```
from lifelines import CoxPHFitter
from lifelines.utils.sklearn_adapter import sklearn_adapter
from lifelines.datasets import load_rossi
from sklearn.feature_selection import RFECV

X = load_rossi().drop('week', axis=1) # keep as a dataframe
Y = load_rossi().pop('week')

CoxRegression = sklearn_adapter(CoxPHFitter, event_col='arrest')
cph = CoxRegression(penalizer=0.1)
selector = RFECV(cph)

selector.fit(X, Y)
```

This results in the following error thrown from line 46 of sklearn_adapter:

`ValueError: X must be a DataFrame. Got type: <class 'numpy.ndarray'>`

Thank you for any guidance you can give.

**Comment by felipe0216** [comment]
I have the same problem.

I tried with other models as well and the same problem. Have you received any solutions for it?
