### ISSUE TITLE
Univariate Cox Regression with a categorical variable

### ISSUE THREAD

**Issue by elopezfune** [CamDavidsonPilon/lifelines#1203]
Hi
How could one perform a univariate Cox Regression with a categorical variable?
I read the reply [here](https://gist.github.com/CamDavidsonPilon/2e52966b72e62491935a38c7a20d91ca), but it is only for numerical.

**Comment by CamDavidsonPilon** [comment]
Something like this?
```
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi

rossi = load_rossi()

cph = CoxPHFitter()
cph.fit(rossi, 'week', 'arrest', formula="C(mar)")
cph.print_summary()
```

where `mar` can be a categorical variable

**Comment by elopezfune** [comment]
`mar` has two categories: 0 and 1, however, in cph.print_summary appears only one risk and not the risks associated to each category.

**Comment by CamDavidsonPilon** [comment]
Yea, but it works for any number of levels:
```
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi

rossi = load_rossi()

rossi['mar'] = np.random.choice(['a', 'b', 'c', 'd'], size=rossi.shape[0])

cph = CoxPHFitter()
cph.fit(rossi, 'week', 'arrest', formula="C(mar)")
cph.print_summary()
```

**Comment by elopezfune** [comment]
Ah Thanks
I didn't know about the use of `formula`
However, while trying this piece of code, I don't get the risk of the class 'a'
```
	coef	exp(coef)	se(coef)	coef lower 95%	coef upper 95%	exp(coef) lower 95%	exp(coef) upper 95%	z	p	-log2(p)
C(mar)[T.b]	-0.21	0.81	0.29	-0.77	0.35	0.46	1.42	-0.73	0.46	1.11
C(mar)[T.c]	0.12	1.12	0.26	-0.39	0.62	0.68	1.86	0.45	0.65	0.62
C(mar)[T.d]	0.14	1.15	0.25	-0.36	0.64	0.70	1.90	0.56	0.57	0.80
```

**Comment by CamDavidsonPilon** [comment]
You won't! A category must be dropped to serve as a reference group. Esentially, `cat A` has coef 0, and all other coefficients are relative to that.

**Comment by elopezfune** [comment]
Ah!
Thank you very much!
It is not quite evident in the documentation.
This is very useful.

**Comment by elopezfune** [comment]
Another question
What happens if the categorical variable contains missing values (NaNs).
I just got an error.

**Comment by CamDavidsonPilon** [comment]
1. Yes, that's expected - it's up to you to fix missing data
2. Yes, you can, formulas are very [flexible](https://patsy.readthedocs.io/en/latest/quickstart.html):
```
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi

rossi = load_rossi()

rossi['mar'] = np.random.choice(['a', 'b', 'c', 'd'], size=rossi.shape[0])

cph = CoxPHFitter()
cph.fit(rossi, 'week', 'arrest', formula="C(mar, Treatment('c'))")
cph.print_summary()

```

**Comment by Theophilus-Baidoo** [comment]
Hi Davidson,
In testing the cox proportional assumption of a categorical variable using the example you've given above(the one where you set a reference category), let's say 'mar' does not satisfy the assumption, how do you stratify in the formula given above.

Thank you.

**Comment by CamDavidsonPilon** [comment]
@Theophilus-Baidoo like this:

```
cph.fit(rossi, 'week', 'arrest', formula="prio", strata=["mar"])
```

**Comment by CamDavidsonPilon** [comment]
Oh I just put it in since you need a nontrivial formula. You mentioned you wanted "mar" as a strata variable, so I put another variable into the formula

**Comment by naity2** [comment]
Hi @CamDavidsonPilon,

May I ask you a quick question? What does the `T` mean in the result `C(mar)[T.b]`? Thank you!

**Comment by CamDavidsonPilon** [comment]
It's a notation to say "this is element `b` from the categorical variable `mar` " - it doesn't mean anything really - just notation.

**Comment by naity2** [comment]
> It's a notation to say "this is element `b` from the categorical variable `mar` " - it doesn't mean anything really - just notation.

Got it, thank you!

**Comment by sapaca** [comment]
> 
Hey @CamDavidsonPilon , I tried the above code to target treatment c as the baseline and this is what I get:

`FactorEvaluationError: Unable to evaluate factor `C(mar, Treatment('c'))`. [NameError: name 'Treatment' is not defined]
`
