### ISSUE TITLE
CoxPHFitter predicts `inf` when R `coxph` predicts sensible values

### ISSUE THREAD

**Issue by joshlk** [CamDavidsonPilon/lifelines#1221]
# `CoxPHFitter` predicts `inf` when R `coxph` predicts sensible values

Simple example. `duration` monotonically increases. `x=duration+error`:

```python
import pandas as pd
from lifelines import CoxPHFitter
from sklearn.preprocessing import StandardScaler

data = pd.DataFrame({
    'event': True,
    'duration': np.arange(20)
    })
np.random.seed(42)
data['x'] = np.random.normal(data['duration'], 1)
```

Data in CSV format:

```
event,duration,x
True,0,0.4967141530112327
True,1,0.8617356988288154
True,2,2.6476885381006925
True,3,4.523029856408026
True,4,3.765846625276664
True,5,4.765863043050819
True,6,7.5792128155073915
True,7,7.7674347291529084
True,8,7.530525614065048
True,9,9.542560043585965
True,10,9.536582307187537
True,11,10.534270246429744
True,12,12.241962271566035
True,13,11.086719755342202
True,14,12.275082167486968
True,15,14.437712470759028
True,16,14.987168879665576
True,17,17.314247332595272
True,18,17.09197592447879
True,19,17.58769629866471
```

Train and make predictions when `x` is out of range from train data (by not too much):

```python
T = 15

regr = CoxPHFitter()
regr.fit(data.iloc[:T], duration_col='duration', event_col='event')

pred = regr.predict_median(data.iloc[T:])
```

pred output are all infinity:

```
15    inf
16    inf
17    inf
18    inf
19    inf
```

If you make predictions that are within the original `x` range it's ok. Note that scaling `x` also does not help:

```python
data_2 = data.copy()
scalar = StandardScaler()
data_2.loc[:15, ['x']] = scalar.fit_transform(data_2.loc[:15, ['x']])
data_2.loc[15:, ['x']] = scalar.transform(data_2.loc[15:, ['x']])

regr_2 = CoxPHFitter()
regr_2.fit(data_2.iloc[:T], duration_col='duration', event_col='event')

pred_2 = regr.predict_median(data_2.iloc[T:])
```

However the R implementation produces good results:

```R
install.packages("survival")
library("survival")

x = c(0.4967141530112327,0.8617356988288154,2.6476885381006925,4.523029856408026,3.765846625276664,4.765863043050819,7.5792128155073915,7.7674347291529084,7.530525614065048,9.542560043585965,9.536582307187537,10.534270246429744,12.241962271566035,11.086719755342202,12.275082167486968,14.437712470759028,14.987168879665576,17.314247332595272,17.09197592447879,17.58769629866471)

data = data.frame(status=rep(2, times=20), duration=seq(from=1, to=20), x=x)

res.cox <- coxph(Surv(duration, status) ~ x, data=data[1:15, ])
predict(res.cox, newdata=data[16:20, ])
```

R pred output:
```
       16        17        18        19        20 
-13.73912 -14.75550 -19.06012 -18.64897 -19.56595
```

Just as a sanity check, here is the summary from the Python model:

<img width="922" alt="Screenshot 2021-02-11 at 11 03 43" src="https://user-images.githubusercontent.com/5648645/107628626-d87e2680-6c58-11eb-904a-a5725ae712cb.png">

And the summary from R:

```
     coef exp(coef) se(coef)      z       p
x -1.8498    0.1573   0.6433 -2.876 0.00403

Likelihood ratio test=38.93  on 1 df, p=4.402e-10
n= 15, number of events= 15 
```

The coefficients are pretty much exactly the same. This indicates that there is something wrong with the prediction function in the Python implementation.

Versions:
* Python 3.6.9
    * lifelines: 0.25.8
    * numpy: 1.19.5
    * pandas: 1.1.5
    * scipy: 1.5.2
* R 4.0.3
    * survival 3.2.7

**Comment by CamDavidsonPilon** [comment]
Hey @joshlk, 

Thanks for the detailed issue. The difference comes from what the prediction function does in R vs Python. In lifelines, you've chosen the `predict_median` which is when the predicted survival function cross the y=0.5 line. For this dataset, the predicted survival curve for high "x" values is very high (shallow). Here's an example:

```
pred_surv = regr.predict_survival_function(data.iloc[T+1])
pred_surv.plot()
```
<img width="586" alt="Screen Shot 2021-02-11 at 9 07 13 AM" src="https://user-images.githubusercontent.com/884032/107647076-baa8c580-6c48-11eb-8252-9a7ad4cf4c70.png">


That survival function will not hit 0.5 in the "observed range" of time (we can't extrapolate the survival curve using a semi-parametric model). This is the correct inference, as the dataset is saying "as x goes up, time-to-event goes up too". 

So median = inf, is the correct inference. 

-----

What's up with R then? The default output of `pred` in R is "linear", that is, what I called "log-partial hazard" [here](https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#cox-s-proportional-hazard-model). In lifelines, you can replicate this with:

```
pred_line= regr.predict_log_partial_hazard(data.iloc[T:])
```

And you'll get similar values to what R is producing.

**Comment by joshlk** [comment]
Got yar. So am I right in thinking that `CoxPHFitter` can work for ranges outside side the training range but in this case it cant.

Odd that R is outputting the `predict_log_partial_hazard` and not the predicted median. Is there a way of getting that?

**Comment by CamDavidsonPilon** [comment]
> So am I right in thinking that CoxPHFitter can work for ranges outside side the training range but in this case it cant.

That's right - that's the tradeoff of using a semi-parametric model! 

>  Is there a way of getting that?

ah I'm not sure! You'll have to do some googling!
