### ISSUE TITLE
KaplanMeierFitter plot color argument

### ISSUE THREAD

**Issue by marc-vaisband** [CamDavidsonPilon/lifelines#1231]
Hi!

I've got a relatively trivial issue. When using the plot utility of a KaplanMeierFitter, the color currently has to be passed via the `color` keyword; using the matplotlib alias `c` results in `TypeError: Got both 'c' and 'color', which are aliases of one another`. I assume that this behaviour is similar for other classes inheriting the plot function.

**Comment by CamDavidsonPilon** [comment]
hi @marc-vaisband - right, I've noticed this too. 

For yourself or any others: I think the solution is to change [this LOC](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/plotting.py#L933) to something that looks for `color` or `c` (and pops it out of the `kwarg`)

**Comment by farhanreynaldo** [comment]
Hello, Does this issue have been solved? It seems like this particular [code](https://github.com/CamDavidsonPilon/lifelines/blob/f911bc594951505f0365798adac4e0429cf76d3e/lifelines/plotting.py#L741) covered the `c` argument. 

Otherwise, I would like to work on this issue.
