### ISSUE TITLE
Problems with plot_partial_effects_on_outcome

### ISSUE THREAD

**Issue by jonathan-taylor** [CamDavidsonPilon/lifelines#1241]
Trying to produce partial effects plots but having problems for both continuous and categorical variables:

Fitting model
--------------

import numpy as np, pandas as pd, lifelines
print('numpy:', np.__version__, 'pandas:', pd.__version__, 'lifelines:', lifelines.__version__)
from lifelines import CoxPHFitter

T = np.random.exponential(50)
X = np.random.standard_normal(50)
S = np.random.choice([0, 1], 50, replace=True)
C = pd.Categorical(np.random.choice([0, 1, 2], 50, replace=True))
D = pd.DataFrame({'X':X, 'S':S, 'C':C, 'T':T})
ff = CoxPHFitter().fit(D, 'T', 'S', formula='X+C')

Versions
----------
numpy: 1.19.2 pandas: 1.1.5 lifelines: 0.25.10

Trying to plot
--------------

ff.plot_partial_effects_on_outcome('C', values=[0,1,2])
ff.plot_partial_effects_on_outcome('X', values=[0,1])

Both a broadcasting raise ValueError in utils.__init__.normalize

**Comment by CamDavidsonPilon** [comment]
Hi @jonathan-taylor, sorry about the delay. I believe the problem is how lifelines handles numeric categorical variables (eg: 1, 2, 4 vs "A", "B", "D"). I'll fix this for the next release.

**Comment by jonathan-taylor** [comment]
Great, thanks!

Meantime I'll checkout master and see if my intended example works (i.e. different data than in the issue).
________________________________

**Comment by clancia** [comment]
Hi, I have run the example above with Python 3.9.5 and lifelines 0.26.0 and I am getting empty plots
In another example of mine, with covariates of dtype `pd.Categorical`, I get
`ValueError: operands could not be broadcast together with shapes`

**Comment by clancia** [comment]
[UPDATE] I double-checked my code, and I found I had one covariate that was a `pd.Categorical` and another that was just a column of strings. Changing both to categorical and adding `plot_baseline=False` fixed it.

**Comment by sapaca** [comment]
I am having the same issue (and this may be a dumb question). In a small test set - (anderson.sav data [here](http://web1.sph.emory.edu/dkleinb/surv3.htm#datal), after fitting the CPH, the only way I can get the plot_partial_effects_on_outcome to work is if I pass (in this example) both categorical values. If don't it just breaks with an ' operands could not be broadcast together' error. Am I missing something about passing in categoricals? Can you possibly provide some examples of clarification on how these work in Lifelines?

I have a much larger CPH project and am running into a lot of issues with this. Thank for the support!
