### ISSUE TITLE
Missing reference/description on kidney transplant data set

### ISSUE THREAD

**Issue by clarkedb** [CamDavidsonPilon/lifelines#1244]
The kidney transplant data set (`lifelines.datasets.load_kidney_transplant`) has no references or description. It would be great to include that there. I had to do a lot of searches to track down the original source.

It seems like this must be from the data set D.3 from Klein and Moeschberger _Statistics for Biology and Health_, 1997. I would be happy to submit a PR with the reference and a brief description so future users don't have to track it down like I did.

**Comment by CamDavidsonPilon** [comment]
Hi @clarkedb! Even given your hint, it was hard to track more information. I'll include the reference you provided in the next release - thanks for your help!
