### ISSUE TITLE
Revert numpy upperbound and replace with Pandas lowerbound

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#1247]
revert https://github.com/CamDavidsonPilon/lifelines/pull/1220

**Comment by edwardreed81** [comment]
This is pretty urgent (at least for me) because if anyone is using numpy features from 1.20 (like `numpy.typing`), this breaks the project.

**Comment by CamDavidsonPilon** [comment]
Hey, let's do this now :)
