### ISSUE TITLE
Incorrect elastic net penality in Cox Models

### ISSUE THREAD

**Issue by bnaras** [CamDavidsonPilon/lifelines#1251]
The elastic net penalty is incorrect for Cox models (lifelines version 0.25.11 and all others). The correct penalty term is
$$
\lambda\left(\alpha \sum_{j=1}^{p}\left|\beta_{j}\right|+\frac{1-\alpha}{2} \sum_{j=1}^{p} \beta_{j}^{2}\right)
$$
Luckily, this seems to affect only `cox_time_varying_fitter.py` and `coxph_fitter.py` and everywhere else it is correct. I will make a PR referring to this issue.

**Comment by CamDavidsonPilon** [comment]
Fixed in 0.25.11
