### ISSUE TITLE
CoxPHFitter baseline survival different from KaplanMeierFitter

### ISSUE THREAD

**Issue by agnesbao** [CamDavidsonPilon/lifelines#1254]
Hi, 
I found the docstring in `CoxPHFitter._compute_baseline_survival` that the baseline survival should agree with KaplanMeierFitter: https://github.com/CamDavidsonPilon/lifelines/blob/101922ca4991fcb662c5a907066ea4c10b744601/lifelines/fitters/coxph_fitter.py#L2530-L2551
However I tried the example code provided, although the plots look overlapping, the numeric values are different. Moreover, I tested it on my own dataset and the difference is much larger:
![image](https://user-images.githubusercontent.com/26316224/114445136-56957580-9b95-11eb-9761-47787abe3eae.png)
I wonder what would be the reason. Thanks!

**Comment by agnesbao** [comment]
In my own dataset my `var1` is not normally distributed (although it's normalized to have mean of 0 and std of 1). Seems normal distribution is what's required for the KMF and CPH to agree?

**Comment by CamDavidsonPilon** [comment]
Hi @agnesbao, that comment refers to the "shape", not necessarily equality (as you demonstrated). 

> In my own dataset my var1 is not normally distributed (although it's normalized to have mean of 0 and std of 1). Seems normal distribution is what's required for the KMF and CPH to agree?

Actually I think it's just that the distribution has a median value of 0 (which the Normal does). Anyways, in general, the baseline survival does not equal the Kaplan Meier. The baseline survival is also not normally interpretable as-is, but used as a reference.

**Comment by agnesbao** [comment]
Thanks for the explanation! I'll close the issue
