### ISSUE TITLE
ValueError in plot_interval_censored_lifetimes when passing entry dates

### ISSUE THREAD

**Issue by Cimbali** [CamDavidsonPilon/lifelines#1287]
The following lines in `plotting.plot_interval_censored_lifetimes(..., entry=None, ....)` triggers a 
`ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` when the argument `entry` is passed. Furthermore `lower_bound` is wrongly substituted for `entry`.

https://github.com/CamDavidsonPilon/lifelines/blob/71f4e4d659870058c33572e7e582654f96c1fcaa/lifelines/plotting.py#L620-L621

Instead it should be:

```python
        if entry is not None:
            entry = _iloc(entry, ix)
```

**Comment by CamDavidsonPilon** [comment]
Yup, looks like a bug - thanks for pointing this out!
