### ISSUE TITLE
LogRank statistic for normalized time

### ISSUE THREAD

**Issue by spacecowboy** [CamDavidsonPilon/lifelines#129]
Doing some logrank tests, I noticed that logrank methods fail for normalized times (where some are negative), which is clearly specified in the documentation:

    event_times_foo: a (nx1) array of event durations (birth to death,...) for the population.

Supporting negative times could be done in two lines (which I do myself before calling running the test atm):

    if np.any(event_times < 0):
        # Be careful not to change the array for the caller
        event_times = event_times - np.min(event_times)

Thoughts?

**Comment by CamDavidsonPilon** [comment]
lgtm! You can send a PR to master or 0.6.0 with this fix
