### ISSUE TITLE
name 'multivariate_logrank_test' is not defined

### ISSUE THREAD

**Issue by alexandre-sousa-git** [CamDavidsonPilon/lifelines#1303]
Hi, 

I import the library : "from lifelines.statistics import logrank_test" 
and if I use:
result = multivariate_logrank_test(df['survivalMonths'], df['smoker'], df['dead'])
result.print_summary()

It gives me error : name 'multivariate_logrank_test' is not defined

Anyone can help me?

**Comment by dbikiel** [comment]
you need to import the multivariate_logrank_test:

from lifelines.statistics import multivariate_logrank_test

you are importing the logrank_test which only compares two groups

**Comment by alexandre-sousa-git** [comment]
I'm sorry for this dumb question! Thank you a lot

**Comment by alexandre-sousa-git** [comment]
I'm sorry for this dumb question! Thank you a lot
