### ISSUE TITLE
Changing y axis range

### ISSUE THREAD

**Issue by hellorp1990** [CamDavidsonPilon/lifelines#1315]
Hi, Instead of plotting 1-0 range for y axis, is it possible to plot the y axis in 100-0 (percentage) range?

**Comment by CamDavidsonPilon** [comment]
Hi @hellorp1990 
This isn't available, and I don't think it will be available. This can achieved by modifying the y-axis in the resulting `ax` that a `plot(...)` method returns. Something like: https://www.kite.com/python/answers/how-to-change-the-axis-scales-of-a-plot-by-a-factor-in-matplotlib-in-python
