### ISSUE TITLE
Updates to Weibull

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#133]
1. Add a median_ property.
2. Better indexing on survival_function_ and others. Don't use linspace, use integers.

**Comment by CamDavidsonPilon** [comment]
Fixed in ce710bb6655e

**Comment by spacecowboy** [comment]
Isn't an integer timeline a significant limitation?

**Comment by CamDavidsonPilon** [comment]
@spacecowboy how so? 

The user can still change it by specifying the `timeline` in the call to `fit`.

**Comment by spacecowboy** [comment]
@CamDavidsonPilon Ah, if it can be specified then nevermind :)
