### ISSUE TITLE
Error in add_at_risk_counts when using 'entry' in KM

### ISSUE THREAD

**Issue by k-milligan** [CamDavidsonPilon/lifelines#1344]
I'm using a pandas column to indicate the entry time for subjects in a Kaplan-Meier model, but receive the following error when attempting to show the at-risk counts (using add_at_risk_counts). Everything works fine if I don't try to include the counts. Any ideas on what this might be? I suspect the way this is handled is that subjects who have not yet entered the at-risk group are labeled NaN until their entry time, but not sure how to fix this on my end. Thanks for any help or advice!
```
~\Anaconda3\lib\site-packages\lifelines\plotting.py in add_at_risk_counts(labels, rows_to_show, ypos, xticks, ax, *fitters, **kwargs)
    492                 .rename({"at_risk": "At risk", "censored": "Censored", "observed": "Events"})
    493             )
--> 494             counts.extend([int(c) for c in event_table_slice.loc[rows_to_show]])
    495 
    496         if n_rows > 1:

~\Anaconda3\lib\site-packages\lifelines\plotting.py in <listcomp>(.0)
    492                 .rename({"at_risk": "At risk", "censored": "Censored", "observed": "Events"})
    493             )
--> 494             counts.extend([int(c) for c in event_table_slice.loc[rows_to_show]])
    495 
    496         if n_rows > 1:

ValueError: cannot convert float NaN to integer
```

**Comment by CamDavidsonPilon** [comment]
Hi @k-milligan, 
hm, I'm not able to reproduce the error. Can you supply a sample dataset that gives this bug?
