### ISSUE TITLE
Weighted KM and NA survival estimators?

### ISSUE THREAD

**Issue by agartland** [CamDavidsonPilon/lifelines#136]
Hi @CamDavidsonPilon 

I need to adapt the KM and NA estimators to add weights to each subject. (I have a case-control design with all cases and matched controls, so I need to upweight each control by its IPW in the whole cohort.)

I noticed that you actually have a `weights` parameter in the `survival_table_from_events()` function, but I don't see `weights` any where else in the package.

Do you think it would work to simply pass `weights` through the `fit()` method, through `preprocess_inputs()` or did you have a different implementation in mind? I can try it myself, but I didn't want to mess it up if you already has an idea.

**Comment by CamDavidsonPilon** [comment]
Ah yes, I added `weights` there for this reason, but I haven't had a use case for it. Passing a `weight` param though `fit` is definitely the way to go, feel free to add it!

**Comment by ahaque12** [comment]
Hi @agartland ,

I actually ran into the same circumstance and did a quick implementation at (https://github.com/ahaque12/lifelines/tree/weighted-est) which addressed my needs. Feel free to use it until this feature is added. If you find the implementation useful I'll try cleaning it up and submitting a pull request :).
