### ISSUE TITLE
Add support for Random Survival Forest

### ISSUE THREAD

**Issue by wjyhumor** [CamDavidsonPilon/lifelines#1362]
Hi all，
Very nice project. Great work!
May you provide support for Random Survival Forest? Its a very useful tool for survival analysis.

Reference: 
Ishwaran, H., Kogalur, U. B., Blackstone, E. H., & Lauer, M. S. (2008). Random survival forests. The annals of applied statistics, 2(3), 841-860.

**Comment by wjyhumor** [comment]
A reference implementation：
https://github.com/julianspaeth/random-survival-forest

**Comment by wjyhumor** [comment]
Another implementation based on scikit :
https://scikit-survival.readthedocs.io/en/stable/user_guide/random-survival-forest.html

**Comment by CamDavidsonPilon** [comment]
Hi @wjyhumor thanks for the kind words,

I don't expect us to implement the RSF. Lifelines is based more on inference rather than prediction, and existing libraries, like scikit survival, have existing implementations that are probably better than anything we could implement.
