### ISSUE TITLE
Applying kmf.median_survival_time to subgroups

### ISSUE THREAD

**Issue by wangarikiarie** [CamDavidsonPilon/lifelines#1363]
I have a dataset with several subgroups and I want to run the `kmf.median_survival_time_` function on them in order to get the median for each individual group.

I previously got their survival functions by using code similar to below:

```
annual_filtered_types = df_filtrd_a.sort_values(by = [var_of_interest])[var_of_interest].unique()

t = df_filtrd_a['age']
e = df_filtrd_a['is_churned']


for i, annual_filtered_types in enumerate(annual_filtered_types):
  ax = plt.subplot(2, 2, i + 1)
  ix = df_filtrd_a[var_of_interest] == annual_filtered_types
  kmf.fit(t[ix], e[ix], label = annual_filtered_types)
  kmf.plot_survival_function(ax = ax, legend = False)
  plt.title(annual_filtered_types)
  plt.xlim(0, 100)
plt.tight_layout()
```

This gives me the survival function plots of the different subgroups. I now want to get the median survival time of each of those groups. I tried using the code below but it seems to be doing it incorrectly. Is there a better way to get the median of those subgroups? Or can median_survival_time_ take some arguments?

```
for i, annual_filtered_types in enumerate(annual_filtered_types):
    ix = df_filtrd_a[var_of_interest] == annual_filtered_types
    print("The median survival time for", annual_filtered_types, "is:", kmf_a.median_survival_time_)
```

**Comment by CamDavidsonPilon** [comment]
Hi @wangarikiarie, 

What was wrong with the code you posted?
```python
for i, annual_filtered_types in enumerate(annual_filtered_types):
    ix = df_filtrd_a[var_of_interest] == annual_filtered_types
    print("The median survival time for", annual_filtered_types, "is:", kmf.median_survival_time_)
``` 
(corrected `kmf_a` to `kmf`). That should work - were you seeing an error or output that didn't make sense?

**Comment by wangarikiarie** [comment]
@CamDavidsonPilon yes - the output repeated the same median for each of the subgroups for example:

```
The median survival time for group1 is: 35.0
The median survival time for group2 is: 35.0
The median survival time for group3 is: 35.0
The median survival time for group4 is: 35.0
The median survival time for group5 is: 35.0
```

It seems like it's not applying the median function to the subgroups. So I was wondering if there was a way to do this

**Comment by wangarikiarie** [comment]
Yes! That makes sense. And this worked. Thank you so much.
