### ISSUE TITLE
Can't install lifelines

### ISSUE THREAD

**Issue by jingjian** [CamDavidsonPilon/lifelines#137]
I used pip install and this is all i got:
$ pip install lifelines
Downloading/unpacking lifelines
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement lifelines
Cleaning up...
No distributions at all found for lifelines
Storing debug log for failure in /Users/jjian/.pip/pip.log

**Comment by CamDavidsonPilon** [comment]
What version of pip do you have?

`pip --version`

**Comment by jingjian** [comment]
pip 1.5.6 from //anaconda/lib/python2.7/site-packages (python 2.7)

**Comment by CamDavidsonPilon** [comment]
@jingjian, I don't think this is a lifelines issue. Can you try upgrade your version of `pip`? See http://stackoverflow.com/questions/21294997/pip-connection-failure-cannot-fetch-index-base-url-http-pypi-python-org-simpl

Let us know if that works.

**Comment by jingjian** [comment]
i can't seem to do easy_install pip==6.0.8
how does one install pip from the tar gz file?

MM208318-pc:~ jjian$ easy_install pip==6.0.8

Searching for pip==6.0.8

Reading https://pypi.python.org/simple/pip/

Download error on https://pypi.python.org/simple/pip/: [Errno 61]
Connection refused -- Some packages may not be found!

Couldn't retrieve index page for 'pip'

Scanning index of all packages (this may take a while)

Reading https://pypi.python.org/simple/

Download error on https://pypi.python.org/simple/: [Errno 61] Connection
refused -- Some packages may not be found!

No local packages or download links found for pip==6.0.8

error: Could not find suitable distribution for
Requirement.parse('pip==6.0.8')

**Comment by jingjian** [comment]
after i installed pip version 6.0.8

MM208318-pc:~ jjian$ pip install lifelines

Collecting lifelines

  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after
connection broken by 'ProtocolError('Connection aborted.', error(61,
'Connection refused'))': /simple/lifelines/

  Could not find any downloads that satisfy the requirement lifelines

  No distributions at all found for lifelines

MM208318-pc:~ jjian$

**Comment by jingjian** [comment]
is there a way for me to install lifelines without pip? can i also just
download the zip file from github and do python setup.py install?

**Comment by jingjian** [comment]
nvm, i think i got it by just downloading the zip. sorry if i've bothered
you, and thanks for a fantastic package! don't have to deal with R! or
matlab! i also loved your blog post

**Comment by CamDavidsonPilon** [comment]
So weird. Can you pip install other packages, or just not lifelines?

**Comment by spacecowboy** [comment]
Since you are using Anaconda, use conda to update pip:

    conda install pip

or to really force just pip to be updated and nothing else

    conda install pip --no-deps
