### ISSUE TITLE
One of Z-score in Log Normal Fitter is reported wrongly. 

### ISSUE THREAD

**Issue by shiling2007** [CamDavidsonPilon/lifelines#1374]
![image](https://user-images.githubusercontent.com/77811866/147006197-f1906cbe-daff-47df-b370-9112e10d4d4e.png)

The Z value of sigma -10.471 is inconsistent with  coef  / se(coef ),  which is around 40.  It also has a  negative sign, which is suspicious. All other numbers are the SAME with those from both SAS and Statsmodels python package.

Here is the notebook for more details.

https://github.com/shiling2007/Python-/blob/main/survival_model_likelihood_estimator.ipynb

**Comment by CamDavidsonPilon** [comment]
Weird! Thanks for reporting this!

**Comment by CamDavidsonPilon** [comment]
Coming back to this: this is actually correct, but not obvious to the end user. The z-score is calculated with a given null hypothesis in mind. In this case, the null is that sigma = 1.0. So, our internal calculation is (0.803 - 1)/0.019. This gives the desired result. 

However, no where is it mentioned (expect in our code) that the comparison is against 1.0 (most would assume 0.0).
