### ISSUE TITLE
Strange calibration plot 

### ISSUE THREAD

**Issue by MuradOmarov** [CamDavidsonPilon/lifelines#1377]
Hello! 
I'm trying to use your great package in my study. I want to calibrate Cox model (with 10 predictors) with `survival_probability_calibration`. 
There are about 2 000 cases and 130 000 controls in my dataset.  
Here my event table from KM for better understanding:
![Снимок экрана 2021-12-30 в 13 14 18](https://user-images.githubusercontent.com/65356761/147742663-8b0989ed-ba58-4d15-994c-5f4c1e3b9773.png)
And cumulative density: 
![Снимок экрана 2021-12-30 в 13 19 39](https://user-images.githubusercontent.com/65356761/147742948-e2b956d7-8b43-4230-a15a-0942caec5452.png)

I got C-index 0,77 after fitting. But Calibration curves look very strange:
![Снимок экрана 2021-12-30 в 13 18 08](https://user-images.githubusercontent.com/65356761/147742826-faee8df5-257e-429b-a7fe-e72c75594a4e.png)
![Снимок экрана 2021-12-30 в 13 18 42](https://user-images.githubusercontent.com/65356761/147742870-44f8dbca-e8c0-48cd-bf1f-07b129cd59ae.png)

Can you tell me what I'm doing wrong?
Thanks in advance

**Comment by juancq** [comment]
@MuradOmarov did you figure out the problem? I'm looking for an answer too.
