### ISSUE TITLE
add_at_risk_counts is showing at_risk counts not at time t, but at t+1

### ISSUE THREAD

**Issue by chrispoptic** [CamDavidsonPilon/lifelines#1383]
@CamDavidsonPilon  I suspect there may be an off-by-one error with the `xticks` parameter in the `add_at_risk_counts()` function.   The "at-risk" counts are still being calculated at end-of-time-period rather than at the start-of-time-period.
cc:  https://github.com/CamDavidsonPilon/lifelines/blob/9be26a9a8720e8536e9828e954bb91d559a3016f/lifelines/plotting.py#L475

This is probably related to the issue [Results of no. of pts at risk calculating by add_at_risk_counts different from SAS results #1316](https://github.com/CamDavidsonPilon/lifelines/issues/1316) and also related to [Discussion 1229](https://github.com/CamDavidsonPilon/lifelines/discussions/1229#discussioncomment-385803).

I have a KMF fitter fitted on my data and I've saved a survival table of the `Censored` & `At_Risk` counts at each year time.
I'm plotting the KM curve at 3 year increments.

The survival table is showing the correct counts but the table from `add_at_risk_counts()` is not.

Notice here that there are actually 27 patients at year 0, but the 'add_at_risk_counts' table below the KM plot shows the number of `At_risk` incorrectly as the number of patients at year 1 (i.e. year 0+1), which is 24.

Similarly, at year 3, the survival table shows the number `At_risk` is 19, but the `add_at_risk_counts` derived table shows 18, which is the count at year 4 (i.e. year 3+1).

Similarly, at year 12, the survival table shows the number `At_risk` is 10, but the `add_at_risk_counts` derived table shows 187 which is the count at year 13 (i.e. year 12+1).

Any idea why the `add_at_risk_counts` function appears to show the number of `At_risk` at the time one unit **after**  the `event_at` that is generated from the `survival_table_from_events`?

I.e. the `add_at_risk_counts` function is yielding a table whose `at_risk` value aligns with the row immediately AFTER the correct `event_at` value (e.g. `event_at` of 4.0 instead of 3.0)

Notice that the `Censored` and `Events` rows correctly match the cumulative count of `censored` and `observed` patients up to, and including, each given year (`event_at`) in the survival table.  But for some reason, the `At_risk` counts are shifted by 1 year.

Why is the `At_risk` count showing the time period one unit after what it should be showing?

```
    kmf = KaplanMeierFitter()
    kmf.fit(T, E, label=df.attrs["name"])
    ax = kmf.plot_survival_function(legend=show_legend, ci_show=True, ci_alpha=0.1, at_risk_counts=False, show_censors=False, ax=ax, color=color, label=df.attrs["name"])

    year_interval = 3
    x_tick_vals = np.arange(0, time_duration, year_interval).astype(int)  # set step size to every 3 years 
    xlabel_name = "Years to Event"

    ax.set_xticks(x_tick_vals)
    ax.set_xticklabels(x_tick_vals, rotation=0)
    ax.set_ylim(bottom=0, top=1)
    ax.set(
        xlabel=xlabel_name,
        ylabel="Event-Free Survival Probability",
    )

    # I am plotting a few KMF objects on the same chart so store each in a list
    list_of_fitters.append(kmf)

    # Plot each of the cohort KM curves overlaid with at-risk counts below the chart
    add_at_risk_counts(*list_of_fitters, ax=ax, rows_to_show=['At risk', 'Censored', 'Events'])
```

![Screen Shot 2022-01-14 at 11 00 04 AM](https://user-images.githubusercontent.com/76219685/149546029-636cf6ee-3189-455d-8eb5-747d16de2299.png)

![Screen Shot 2022-01-14 at 10 59 08 AM](https://user-images.githubusercontent.com/76219685/149545871-d0b09cc5-03a7-4edd-ab93-c8356ea37519.png)

**Comment by chrispoptic** [comment]
@CamDavidsonPilon

**Comment by CamDavidsonPilon** [comment]
Hi @chrispoptic 

I wonder if the trouble that I start the table metrics with the following [line](https://github.com/CamDavidsonPilon/lifelines/blob/eda404ebb869a26a746a7716d043f9a69f9df907/lifelines/plotting.py#L494)?

```
f.event_table.assign(at_risk=lambda x: x.at_risk - x.removed
```

I have a comment in there saying `to align with R (and intuition), we do a subtraction off the at_risk column`. And that comment was added when I aligned this table with [KMunicate](https://bmjopen.bmj.com/content/9/9/e030215).

Below I recreated lifelines and R's KMunicate package:

<img width="1266" alt="Screen Shot 2022-01-18 at 8 25 16 PM" src="https://user-images.githubusercontent.com/884032/150046226-d7000dc6-65d4-478c-b987-f649e8953694.png">

It looks like the default lifelines behaviour is the same as R's. 

Looking again at the KMunicate paper, they write:

>  In figure 1, after 10 years, there remain 71 and 99 participants at risk of an event in the control and research arms, respectively.

Which suggests, to me at least, that it should be end of period. What do you think?

**Comment by chrispoptic** [comment]
That's a good point about having the at-risk counts at the end of the period.
And yes I think the issue arises around [line](https://github.com/CamDavidsonPilon/lifelines/blob/eda404ebb869a26a746a7716d043f9a69f9df907/lifelines/plotting.py#L494)
`f.event_table.assign(at_risk=lambda` x: x.at_risk - x.removed`

How about adding a single parameter to the `add_at_risk_counts()` function called something like `counts_at_risk_at_start_vs_end_of_period`.

The default value would be `end_of` and would replicate the behavior of the KMunicate paper.  
But setting that parameter instead to `start_of` would construct the same such that the counts for "At risk", "Censored", and "Events" all match and align with each corresponding row of the survival event table.

So in my above example, the  "At risk", "Censored", and "Events" for that first column in the table under the KM curve would be `27, 2, 1` rather than the current "end_of" period count of `24, 2, 1`.

The rationale of this design is that for certain use cases we may be more interested in the `at_risk` counts of patients (or events) at _the beginning of_ each time period, rather than at the end of it.

**Comment by CamDavidsonPilon** [comment]
That's probably the way to go. Are you able to share more about why the beginning is more useful for your application?
