### ISSUE TITLE
At Risk from add_at_risk_counts Monotonically Decreasing with Left Truncation

### ISSUE THREAD

**Issue by joshkaps** [CamDavidsonPilon/lifelines#1385]
I'm trying to use `add_at_risk_counts` to plot `At Risk`, `Censored`, and `Events` counts with left truncated data.

I expect to see the `At Risk` counts both rise and fall, depending on how late entries balance out with samples being removed due to censorship and observation over time. However, I observe that the `At Risk` counts are monotonically decreasing. (As I understand it, this is expected only when not using left truncation).

Digging into the `KaplanMeierFitter.event_table`, it looks like the `at_risk` column is correct. So I think the issue is how those values are being manipulated at the time that `add_at_risk_counts` is called, likely here: https://github.com/CamDavidsonPilon/lifelines/blob/deb663838269067192f7ca990b7b4f3f908fdc4e/lifelines/plotting.py#L489 That comment suggests that the code likely assumes monotonically decreasing, which would explain the behavior I'm seeing.

I think the Censored and Event counts are correctly monotonically increasing, so the issue is only in the At Risk counts.

I'm using lifelines version 0.26.0. Let me know if my expectations for what I should be seeing are correct. Code snippet and screenshot are below:
```
import pandas as pd
import matplotlib.pyplot as plt
from lifelines import KaplanMeierFitter
from lifelines.plotting import add_at_risk_counts
from lifelines.datasets import load_dfcv


dfcv = load_dfcv()

# this is an arbitrary change to the example data to make the issue more obvious
dfcv.loc[(dfcv.index > 4) & (dfcv.start == 0), 'start'] = 3

kmf = KaplanMeierFitter()
kmf.fit(
    durations=dfcv.stop,
    event_observed=dfcv.event,
    entry=dfcv.start
)

display(kmf.event_table)

kmf.plot()
add_at_risk_counts(kmf)
plt.tight_layout()
plt.show()
```
<img width="440" alt="Screen Shot 2022-01-21 at 9 35 28 PM" src="https://user-images.githubusercontent.com/18150137/150623345-3bfeb2e9-90ca-4b55-8a5e-9758ab7f255a.png">

**Comment by CamDavidsonPilon** [comment]
Interesting, defs a bug. 

I'll make an effort to fix this, and the other at_risk_table problems in the next release

**Comment by CamDavidsonPilon** [comment]
Very helpful, ty!
