### ISSUE TITLE
add_at_risk_counts does not work properly with adjusted/weighted Kaplan Meier curves

### ISSUE THREAD

**Issue by Senejohnny** [CamDavidsonPilon/lifelines#1386]
When using Adjusted Kaplan Meier (AKM) with weights "add_at_risk_counts" demonstrate a different population than the original population. As seen, using AKM we notice a very minor difference in this use case; however, a large population difference. Is this the pseudo population? If so, is there a way we still get the original population/cohort?

Below you can see an AKM on **left** with a different population than the KM curves with the original population on **right**. 
I expect to always see the numbers below the right curve. 
 
![](https://user-images.githubusercontent.com/46810505/121411934-6f879080-c964-11eb-9e1b-107fea141191.png)

**Comment by CamDavidsonPilon** [comment]
This is the same issue as #1286?
