### ISSUE TITLE
How to include multiple categorical variables in CoxPhFitter? 

### ISSUE THREAD

**Issue by pzinz** [CamDavidsonPilon/lifelines#1407]
Hello,
I have multiple categorical variables (gender: 1, 2; copd: 0, 1; ethnicgroup: 1,2,3,4). How can I incorporate these categorical variables when fitting the cox model? I tried something like below but it does not work. 

cph.fit(survival_data[['fu_time', 'death', 'age', 'gender', 'copd', 'prior_dnas','ethnicgroup']], 'fu_time', 'death', formula="C(gender, copd, ethnicgroup)")

Any assistance is appreciated.

**Comment by CamDavidsonPilon** [comment]
Hi @pzinz, try something like:
```
 formula="C(gender) +  C(copd) + C(ethnicgroup)"
```

**Comment by pzinz** [comment]
Thank you very much!
