### ISSUE TITLE
doc error: 'penalizer' keyword does not exist in AalenAdditiveFitter.__init__()?

### ISSUE THREAD

**Issue by ApproximateIdentity** [CamDavidsonPilon/lifelines#141]
In the docs, I found this line:

```python
aaf = AalenAdditiveFitter(penalizer=1.0, fit_intercept=True)
```

But it seems like penalizer is not (presumably no longer) a keyword argument in the class' __init__:

https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/estimation.py#L591

I'm guessing that penalizer should be replaced by either coef_penalizer or smoothing_penalizer, but since I'm very new to this (and learning about Hazard models from this project), I'm not really sure which one is meant...

**Comment by CamDavidsonPilon** [comment]
Ah yes! Thank you for bringing that to my attention, @ApproximateIdentity. Here's how they work:

1. `coef_penalizer` is shrinkage on the absolute value of the hazard coefficients. Ex: it will shrink `c_{i,t}` towards 0.
2. `smoothing_penalizer` is shrinkage on the absolute value *between* adjacent coefficients (over time). Ex: it will shrink `c_{i,t} - c_{i, t+1}` towards 0.

**Comment by CamDavidsonPilon** [comment]
Added to core in https://github.com/CamDavidsonPilon/lifelines/commit/129fa56695dccd6c19ff01561c5bde9743c6bd6c
