### ISSUE TITLE
Fix stale docs for plot_lifetimes()

### ISSUE THREAD

**Issue by kyleabeauchamp** [CamDavidsonPilon/lifelines#1431]
As part of addressing #1385, A few behaviors were changed regarding the behaviors of functions when adding an entry variable.  However, I'm finding that these changes are not reflected in the current sphinx docs.  In particular, in https://lifelines.readthedocs.io/en/latest/Survival%20analysis%20with%20lifelines.html?highlight=entry#left-truncated-late-entry-data I find that trying to reproduce leads to "death events" occurring at the beginning, rather than end, of the observation interval.  

I have a complete working example (and possible fix) in the following colab notebook: https://colab.research.google.com/drive/13Wx9NCtKCNPGHJ7b97yf5CTspF2h-yLr#scrollTo=CEz754kBginm

**Comment by kyleabeauchamp** [comment]
For reference, this is what the "weird behavior" looks like:

![image](https://user-images.githubusercontent.com/1900459/175695586-34f73266-7b8b-4c9e-9f9d-9f547f355f75.png)

**Comment by CamDavidsonPilon** [comment]
Oh good catch, I'll fix now. Thanks @kyleabeauchamp!
