### ISSUE TITLE
hazard_at_times(times, label=None) Not working 

### ISSUE THREAD

**Issue by ryanr0401** [CamDavidsonPilon/lifelines#1434]
hazard_at_times does not seem to work when called on any model fitted. It is in the lifelines documentation but does not work

**Comment by CamDavidsonPilon** [comment]
Hi @ryanr0401, can you also provide a reproducible example / code snippet?

**Comment by ryanr0401** [comment]
I fit my data using the NelsonAalenFitter and then called hazard_at_times(times=timeline) where timeline is the timeline of the data. 

naf_fit = naf.fit(data["diff_months"], event_observed=data["death_1"], label="Field")
naf_fit.plot_hazard(bandwidth=1.0)
naf_fit.cumulative_hazard_at_times(times, label=None)
naf_fit.cumulative_hazard_at_times(times, label=None)


NotImplementedError                       Traceback (most recent call last)
/var/folders/_9/gmdlzf0929zg66zfv3sk99500000gn/T/ipykernel_5700/3333045759.py in <module>
----> 1 naffield.hazard_at_times(times, label=None)

~/opt/anaconda3/lib/python3.9/site-packages/lifelines/fitters/__init__.py in hazard_at_times(self, times, label)
    227 
    228     def hazard_at_times(self, times, label=None):
--> 229         raise NotImplementedError

**Comment by CamDavidsonPilon** [comment]
Try a method like [smoothed_hazard_](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/nelson_aalen_fitter.py#L198)

NAF doesn't have a nice hazard function, so a hazard_at_times is not well defined.

**Comment by ryanr0401** [comment]
I am just trying to figure out a way of finding the probability if an observation has made it to lets say for example 3 months what is the probability that observation will make it to 4,5 or 6 months. Do you have anything available to help with this kind of problem in lifelines

**Comment by CamDavidsonPilon** [comment]
For sure. Use KaplanMeierFitter, first:

```
kmf = KaplanMeierFitter().fit(T, E)
```
>  the probability if an observation has made it to lets say for example 3 months what is the probability that observation will make it to 4,5 or 6 months.

You simply divide the survival function by the survival function at three months:
```
kmf.survival_function_ / kmf.predict(3) 
```

The value at t=4 is the _conditional probability_ of living to 4 months, given you lived to 3 months.

**Comment by ryanr0401** [comment]
Thank you ! I found this extremely helpful. Can you do this using cox-ph in lifelines or any other models

**Comment by CamDavidsonPilon** [comment]
For regression models, it's built in as `predict_survival_function(..., conditional_after=...)`. See the docs for more: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction-on-censored-subjects
