### ISSUE TITLE
Error in Gompertz Fitter

### ISSUE THREAD

**Issue by tuliosarmento** [CamDavidsonPilon/lifelines#1443]
I`m facing the following error when running the Gompertz Survival Function?

> TypeError: loop of ufunc does not support argument 0 of type ArrayBox which has no callable expm1 method

Code:
```
class GompertzFitter(ParametricUnivariateFitter):
    _fitted_parameter_names = ['nu_', 'b_']
    def _cumulative_hazard(self, params, times):
        nu_, b_ = params
        return nu_ * (np.expm1(times * b_))
```

```
T, E = waltons['T'], waltons['E']
ggf = GompertzFitter()
ggf.fit(T, E)
```

**Comment by CamDavidsonPilon** [comment]
Hi @tuliosarmento, try adding `import autograd.numpy as np` before the class definition

**Comment by tuliosarmento** [comment]
> Hi @tuliosarmento, try adding `import autograd.numpy as np` before the class definition

Oh I see. I was using the "original" numpy library. 
Now it works. Thanks so much!
