### ISSUE TITLE
About the bonferroni correction in pairwise_logrank_test

### ISSUE THREAD

**Issue by lycantrope** [CamDavidsonPilon/lifelines#1451]
Lifelines provides `pairwise_logrank_test` in `lifelines.statistics` for multicomparison of logrank between various group pairs.
I found the [issue](https://github.com/CamDavidsonPilon/lifelines/issues/185#issuecomment-135221260_) mention about this function provide the bonferroni correction in default. 
However, I could not find the options or implementation in current version.
Is this function deprecated? Or some reason this method are removed from `pairwise_logrank_test`.

**Comment by CamDavidsonPilon** [comment]
Hi @lycantrope, looks like it was removed. It should be possible to do _outside_ lifelines using the results from `pairwise_logrank_test`.
