### ISSUE TITLE
Weibull fitter has different results for the same data and environment

### ISSUE THREAD

**Issue by GergelyMincsovicsPhilips** [CamDavidsonPilon/lifelines#1455]
Weibull fitter and Weibull AFT with no features have different results for the same data #750
 #750 is closed, while I am still observing the issue on 0.26.4, even when not changing anything in the environment.
 Was it fixed? If not, would you point me to the piece that calls the optimization for the Weibull fitter?

**Comment by CamDavidsonPilon** [comment]
Hi @GergelyMincsovicsPhilips, I don't think anything changed as a result of #750. Are you able to post the parameter estimates (using `.print_summary()` or something) for the two models. 

The optimization code for the Weibull Fitter is [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/__init__.py#L539-L557)

**Comment by GergelyMincsovicsPhilips** [comment]
it turned out that the differences I saw come from the order I called the Weibull, looping over the groups, i.e.

BEFORE (changes in the output observed)
Groups=df['G']
for group in set(Groups):

AFTER (stable output)
Groups=df['G']
for group in sorted(set(Groups)):

the issue can be closed
