### ISSUE TITLE
Can't use print_summary() in CoxPHFitter

### ISSUE THREAD

**Issue by JoCouweleers** [CamDavidsonPilon/lifelines#1465]
I'm running a CoxPHFitter model on my dataset and the model runs but I can't output the model summary. The plot and plot_partial_efects_ still work for me. Using a Synapse notebook if that helps.

![print_summary](https://user-images.githubusercontent.com/22525672/192349829-1514098f-237a-4ec8-b796-406c485bde91.png)

**Comment by JoCouweleers** [comment]
Looks like cph.summary works but lacks some of the details of print_summary

**Comment by CamDavidsonPilon** [comment]
uh oh, I may have broken something in the latest release. I'll investigate now

**Comment by CamDavidsonPilon** [comment]
Oh, actually, can you list your pandas version, and your lifelines version?
