### ISSUE TITLE
predict_median is sometimes a poor default for k_fold_cross_validation

### ISSUE THREAD

**Issue by benkuhn** [CamDavidsonPilon/lifelines#147]
Currently when one calls `k_fold_cross_validation` on a Cox model, the concordance is calculated using the `predict_median`. For problems where the majority of cases survive the entire study duration, this can be problematic, as many cases end up having median survival time of `inf`. (For a flavor of how severe this is, it knocked a full 0.10 off the concordance index for a problem I'm working on, which really threw me for a loop until I did my own split-sample testing.)

I guess it's hard to find a default here that works well, but using `predict_median` for a Cox model leads to some pretty strange behavior. Here are a couple of solutions I can think of (I'd be happy to implement one but want to run it by others first):

- Default to `predict_partial_hazard` (or rather, its negative) for the Cox model and `predict_median` otherwise
- Allow each model to implement a `predict_rank` function and use that by default
- Switch from `predict_median` to something less likely to generate `inf`s (perhaps `predict_expectation`? not sure how well this would work for non-Cox models)
- Have `k_fold_cross_validation` issue a warning if it seems like there are too many ties in the output of `predict_median`

Which one seems best?

**Comment by CamDavidsonPilon** [comment]
I've encountered this before, one thing to try is also 
```
p = 0.8  # some value larger than 0.5
k_fold_cross_validation(fitters, df, duration_col, event_col,
                            predictor="predict_percentile", predictor_kwargs={'p': p})
```

Though `predict_partial_hazard` is another good suggestion (which is really what these survival models are trying to predict).

**Comment by CamDavidsonPilon** [comment]
If we were to select a new one, I would choose `predict_partial_hazard`. But this lacks interpretability. I guess it's a decision between what performance metric one is using: hazard for concordance, and median/percentile for l1/l2 loss against the actual survival time. (This has it's own issues: it's not totally clear how to measure predictions against censored cases).

**Comment by benkuhn** [comment]
I think that for a Cox model, any prediction function that doesn't introduce extra ties will rank things identically to `predict_partial_hazard`, so there's not really an issue of interpretability there. On the other hand, as I understand it the Aalen additive model doesn't have any similar canonical univariate thing to rank stuff by. I don't think Harrell was really thinking of such non-parametric models when he proposed the concordance index for ranking.

The deeper obstruction to doing a concordance index for (e.g.) an Aalen additive model is that the survival functions of two cases could in principle be arbitrarily different (have different shapes, not just different statistics), so there are always cases where a univariate summary of ranking is too lossy. In that case it seems like you basically have to ask for an application-dependent "utility function" type thing to get a reasonably principled concordance index?

**Comment by emindeniz** [comment]
Hello,
I understand that this issue is closed but I have a related question. Could you please explain why `predict_partial_hazard` function give predicted survival times? I understand from the docs that exp(beta*X), but mathematically why is this predicted times?

thanks,

**Comment by CamDavidsonPilon** [comment]
> Could you please explain why predict_partial_hazard function gives predicted survival times?

it doesn't, it simply gives a scalar that (because of how it's used in the cox model) can be seen as an ordinal value (higher scalar == faster to die).

**Comment by emindeniz** [comment]
Ok, makes perfect sense. It is just a way to order subjects so that we can check the concordance between ordering by the model and ordering the data.
