### ISSUE TITLE
[BUG] Anaconder server badge not rendering in readme

### ISSUE THREAD

**Issue by darigovresearch** [CamDavidsonPilon/lifelines#1470]
See screenshot below

![image](https://user-images.githubusercontent.com/30328618/200117335-13edb14e-9d5b-4254-88d8-e72c25083587.png)

**Comment by CamDavidsonPilon** [comment]
Thanks!

**Comment by darigovresearch** [comment]
You're very welcome @CamDavidsonPilon!
