### ISSUE TITLE
Formulaic version requirement

### ISSUE THREAD

**Issue by kvsramarao** [CamDavidsonPilon/lifelines#1490]
Hi: when I try to install lifelines, I get:
ERROR: Could not find a version that satisfies the requirement formulaic<0.3,>=0.2.2 (from lifelines)

I see the same (not the error but the requirement) at https://www.databricks.com/notebooks/telco-accel/03_cox_proportional_hazards.html 

The documentation only says formulaic>=0.2.2 . Current formulaic is 0.5.2. Can you pls remove the formulaic<0.3 requirement? Thx

**Comment by CamDavidsonPilon** [comment]
Hi, I don't know where that upper bound is from. Are you installing over pip or conda?
