### ISSUE TITLE
Implement proportional test

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#150]
Same as cox.zph test. see http://escarela.com/archivo/anahuac/03o/coxdiag.pdf but maybe there is a more understandable paper.

**Comment by daturkel** [comment]
Sorry to comment on a very old, closed issue, but wondering what you decided on here. I'm trying to validate PH assumptions on a continuous variable (and even some categorical ones) and finding the graphical approach isn't working well. I'm debating temporarily moving the data into R just to use the `cox.zph` function to assess my covariates.

**Comment by CamDavidsonPilon** [comment]
I don’t think I ever did implement this :(

**Comment by daturkel** [comment]
Looks like it might overlap with this ticket https://github.com/CamDavidsonPilon/lifelines/issues/339

**Comment by CamDavidsonPilon** [comment]
Ah that’s why I closed this
