### ISSUE TITLE
Is there Hazard Function in lifelines ? 

### ISSUE THREAD

**Issue by DaniBre99** [CamDavidsonPilon/lifelines#1506]
Hi! Is possible to implement Hazard Function in python with lifelines like in R and SAS languages? 
Thanks

**Comment by CamDavidsonPilon** [comment]
Hi @DaniBre99, like you want to implement your own hazard function? Something like [this](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Piecewise%20Exponential%20Models%20and%20Creating%20Custom%20Models.html)?

**Comment by DaniBre99** [comment]
Hi @CamDavidsonPilon! Thanks a lot for the answer! I'm doing a survival analysis with KaplanMeierFitter (lifelines) and I'd like to add a graph like this:
https://bookdown.org/rwnahhas/RMPH/survival-hazard.html
Or like this:
https://stats.oarc.ucla.edu/sas/seminars/sas-survival/
![immagine](https://user-images.githubusercontent.com/127534560/224643662-5be77350-1fc3-439d-8414-4bc7d808e336.png)
(chapter: 1.2.4. Background: The hazard function)
In python I can manually calculate the hazard ratio like this: 
https://allendowney.github.io/SurvivalAnalysisPython/02_kaplan_meier.html
(chapter: Estimating the hazard function)
I was wondering if these calculations to find the hazard ratio were already included in the lifelines library or if it was possible to insert them and then create the graph. I saw the link you kindly sent me, maybe are they the same in the ThreeParamInverseTimeHazardFitter() function? I don't understand very well how this function works. 
Thank you very much!

**Comment by DaniBre99** [comment]
Thank you very much!!
