### ISSUE TITLE
How to label censored data on survival curves

### ISSUE THREAD

**Issue by realHongYuZhou** [CamDavidsonPilon/lifelines#1507]
lifelines is a great work that provides a lot of efficient features. But there is one thing I don't quite understand, how can I mark the censored data on the survival curve?
I'm a novice and don't understand if I'm expressing myself clearly. As shown in the figure below, there are many short vertical lines on the survival curve, which represent censored data. How can I use lifelines to achieve this function? I hope you can provide me with a simple demo code, thank you.
![image](https://user-images.githubusercontent.com/92027668/224521591-ad20f16b-89bf-49fd-a79d-931ae32e81f0.png)

**Comment by CamDavidsonPilon** [comment]
Hi there, try something like:
```
kmf.plot_survival_function(show_censors=True, censor_styles={'ms': 6, 'marker': 'vline'})
```

**Comment by realHongYuZhou** [comment]
Thank you very much, but "vline" no use, I use '|' to replace, it is possible. Thank you for your answer and have a good life.
