### ISSUE TITLE
`import lifelines` errors with `SyntaxError` in Python 3.7

### ISSUE THREAD

**Issue by DrShushen** [CamDavidsonPilon/lifelines#1517]
There appears to be a bug in *lifelines* `0.27.5` with Python 3.7.

To replicate:

1. Have an environment with Python 3.7, e.g. `conda create -n env_lifelines python=3.7`
2. Install *lifelines* `0.27.5`, e.g. `pip install "lifelines==0.27.5"`
3. In Python run `import lifelines`

You get `SyntaxError` as below - looks like an `fstring` issue:
```python
import lifelines
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/<...>/python3.7/site-packages/lifelines/__init__.py", line 5, in <module>
    from lifelines.fitters.weibull_fitter import WeibullFitter
  File "<fstring>", line 1
    (minimum_results=)
                    ^
SyntaxError: invalid syntax
```

**Note that:**
* This does not happen (import works fine) with Python 3.8+.
* This does not happen (import works fine) for *lifelines* `0.27.4` or earlier.

**Comment by CamDavidsonPilon** [comment]
Oh shoot, that feature is py3.8+ only. I'll update with a fix!

**Comment by CamDavidsonPilon** [comment]
0.27.6 is released now on PyPI

**Comment by TZTsai** [comment]
Yes this feature f"{minimum_results=}" is only supported by py3.8+.
