### ISSUE TITLE
numpy exp issue

### ISSUE THREAD

**Issue by genevievebo** [CamDavidsonPilon/lifelines#153]
When I try to use the CoxPHFitter, I get this error for line 1029: 

`phi_i = exp(np.dot(xi, beta))`
`AttributeError: exp`

I've notice that the dtype in xi is sometimes object.  If I do `X = X.astype(float)` at the beginning of the function --before the loop where xi is created--, I don't have this problem (but I get stuck at a further step).

I'm using lifelines 0.7 with numpy 1.9.2 and pandas 0.16.0

**Comment by CamDavidsonPilon** [comment]
Hey @genevievebo, can you check your input data and make sure they are all booleans/floats/ints, and not objects, strings, or Nones?

I've seen this issue when `exp` is called on a non-numeric data type.

**Comment by genevievebo** [comment]
It was indeed related to a column having a dtype object in my dataframe.  Thanks!
