### ISSUE TITLE
Possible to reduce CoxPHFitter pickled model size?

### ISSUE THREAD

**Issue by maoserr** [CamDavidsonPilon/lifelines#1544]
Hi,

I trained a model with 20+ million rows, and the final model size is 1.5GB pickled.

If I only want this model for inferencing, is there a way to reduce the size? specifically using predict_survival_function

**Comment by CamDavidsonPilon** [comment]
Wow that's surprisingly big. It's a file, so you could try compressing it with gzip or something else.

**Comment by maoserr** [comment]
Yea, that works also, but is the training data stored in the model somewhere? Can I clear some attributes that are not needed if it is or something similar?

**Comment by CamDavidsonPilon** [comment]
durations col, weights col, and censoring col (and associated index) are stored on the model: https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/coxph_fitter.py#L1231-L1234

**Comment by maoserr** [comment]
thanks, compression and removing extra data reduced my model from 1.5GB to 98MB
