### ISSUE TITLE
[Question] In _additive_f, why use log instead of directly use division?

### ISSUE THREAD

**Issue by yichuan1118** [CamDavidsonPilon/lifelines#155]
`_additive_f` returns `np.log(population - deaths) - np.log(population)` and `_additive_estimate` `cumsum` in used to get the total. Since numpy do have `cumprod` function, why everything is calculated in log? to avoid overflow?

**Comment by CamDavidsonPilon** [comment]
Yea, underflow can be a big problem in Kaplan Meier. For most datasets, it wouldn't happen, but one could create an artificial dataset that would underflow.
