### ISSUE TITLE
Overlapping 'at risk' counts in Kaplan-Meier plot for multiple dataframes

### ISSUE THREAD

**Issue by Aniket99coder** [CamDavidsonPilon/lifelines#1556]
When plotting Kaplan-Meier survival estimates for multiple dataframes using lifelines, the "at risk" counts are overlaid on top of each other, making them unreadable.

**Expected Behavior:**
The "at risk" counts for each dataframe should be clearly visible and not overlap with counts from other dataframes.

**Actual Behavior:**
The "at risk" counts for different dataframes are printed on top of each other, making them unreadable.

```python
import pandas as pd
import numpy as np
from lifelines import CoxPHFitter, KaplanMeierFitter

# Generate random data for three hypothetical dataframes
np.random.seed(42)

def generate_data(size):
    return pd.DataFrame({
        'duration': np.random.exponential(10, size),
        'event': np.random.binomial(1, 0.5, size),
        'age': np.random.normal(50, 10, size)
    })

df1 = generate_data(100)
df2 = generate_data(100)
df3 = generate_data(100)

dataframes = [df1, df2, df3]

# Kaplan-Meier Estimation
kmf = KaplanMeierFitter()

for idx, df in enumerate(dataframes, 1):
    kmf.fit(df['duration'], event_observed=df['event'], label=f'DataFrame {idx}')
    kmf.plot(at_risk_counts=True)
``` 

<img width="548" alt="image" src="https://github.com/CamDavidsonPilon/lifelines/assets/34135246/1cdc7c70-f5b3-43f3-aaf4-54dc02f32155">

**Comment by badge** [comment]
You can do this today if you store the fitted models and use `add_at_risk_counts`:

```python
from lifelines.plotting import add_at_risk_counts

fitters = [
    KaplanMeierFitter().fit(
        df['duration'],
        event_observed=df['event'],
        label=f'DataFrame {idx}'
    )
    for idx, df in enumerate(dataframes, 1)
]

for fitter in fitters:
    ax = fitter.plot()

add_at_risk_counts(*fitters, ax=ax)
```

**Comment by CamDavidsonPilon** [comment]
Thanks @badge, yes, this is the correct way to inject multiple at-risk rows.

**Comment by Aniket99coder** [comment]
Wow . That was fast! Thanks for your help @badge  and @CamDavidsonPilon !
