### ISSUE TITLE
In lifelines 0.27.8, CoxPHFitter().fit() --> AttributeError: module 'formulaic' has no attribute 'ModelSpec'

### ISSUE THREAD

**Issue by RSHum23** [CamDavidsonPilon/lifelines#1565]
I get an attribute error when running this code:

`cph = CoxPHFitter()`
`cph.fit(df, duration_col='time', event_col='evento')`

If I add a formula, I get the same error (and the formula can even be wrong, e.g. it can contain invalid column names - the error raised is the same).

How can I fix it?

Thank you!

**Error:**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [40], in <cell line: 2>()
      1 cph = CoxPHFitter()
----> 2 cph.fit(df, duration_col='time', event_col='evento')

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\utils\__init__.py:56, in CensoringType.right_censoring.<locals>.f(model, *args, **kwargs)
     53 @wraps(function)
     54 def f(model, *args, **kwargs):
     55     cls.set_censoring_type(model, cls.RIGHT)
---> 56     return function(model, *args, **kwargs)

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\fitters\coxph_fitter.py:290, in CoxPHFitter.fit(self, df, duration_col, event_col, show_progress, initial_point, strata, weights_col, cluster_col, robust, batch_mode, timeline, formula, entry_col, fit_options)
    184 """
    185 Fit the Cox proportional hazard model to a right-censored dataset. Alias of `fit_right_censoring`.
    186 
   (...)
    287 
    288 """
    289 self.strata = utils._to_list_or_singleton(utils.coalesce(strata, self.strata))
--> 290 self._model = self._fit_model(
    291     df,
    292     duration_col,
    293     event_col=event_col,
    294     show_progress=show_progress,
    295     initial_point=initial_point,
    296     strata=self.strata,
    297     weights_col=weights_col,
    298     cluster_col=cluster_col,
    299     robust=robust,
    300     batch_mode=batch_mode,
    301     timeline=timeline,
    302     formula=formula,
    303     entry_col=entry_col,
    304     fit_options=fit_options,
    305 )
    306 return self

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\fitters\coxph_fitter.py:610, in CoxPHFitter._fit_model(self, *args, **kwargs)
    608 def _fit_model(self, *args, **kwargs):
    609     if self.baseline_estimation_method == "breslow":
--> 610         return self._fit_model_breslow(*args, **kwargs)
    611     elif self.baseline_estimation_method == "spline":
    612         return self._fit_model_spline(*args, **kwargs)

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\fitters\coxph_fitter.py:623, in CoxPHFitter._fit_model_breslow(self, *args, **kwargs)
    619 model = SemiParametricPHFitter(
    620     penalizer=self.penalizer, l1_ratio=self.l1_ratio, strata=self.strata, alpha=self.alpha, label=self._label
    621 )
    622 if utils.CensoringType.is_right_censoring(self):
--> 623     model.fit(*args, **kwargs)
    624     return model
    625 else:

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\utils\__init__.py:56, in CensoringType.right_censoring.<locals>.f(model, *args, **kwargs)
     53 @wraps(function)
     54 def f(model, *args, **kwargs):
     55     cls.set_censoring_type(model, cls.RIGHT)
---> 56     return function(model, *args, **kwargs)

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\fitters\coxph_fitter.py:1229, in SemiParametricPHFitter.fit(self, df, duration_col, event_col, show_progress, initial_point, strata, weights_col, cluster_col, robust, batch_mode, timeline, formula, entry_col, fit_options)
   1226 self.formula = formula
   1227 self.entry_col = entry_col
-> 1229 X, T, E, weights, entries, original_index, self._clusters = self._preprocess_dataframe(df)
   1231 self.durations = T.copy()
   1232 self.event_observed = E.copy()

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\fitters\coxph_fitter.py:1326, in SemiParametricPHFitter._preprocess_dataframe(self, df)
   1323 _clusters = df.pop(self.cluster_col).values if self.cluster_col else None
   1325 self.regressors = utils.CovariateParameterMappings({"beta_": self.formula}, df, force_no_intercept=True)
-> 1326 X = self.regressors.transform_df(df)["beta_"]
   1328 T = T.astype(float)
   1330 # we check nans here because converting to bools maps NaNs to True..

File C:\ProgramData\Anaconda3\lib\site-packages\lifelines\utils\__init__.py:1911, in CovariateParameterMappings.transform_df(self, df)
   1909 Xs = {}
   1910 for param_name, transform in self.mappings.items():
-> 1911     if isinstance(transform, formulaic.ModelSpec):
   1912         X = transform.get_model_matrix(df)
   1913     elif isinstance(transform, list):

AttributeError: module 'formulaic' has no attribute 'ModelSpec'

**Comment by RSHum23** [comment]
lifelines 0.27.8
formulaic 0.2.4

**Comment by CamDavidsonPilon** [comment]
You want to upgrade formulaic
