### ISSUE TITLE
Incompatibility of v0.27.8 with Python <3.9 due to `importlib.resources.files`

### ISSUE THREAD

**Issue by TonyYanOnFire** [CamDavidsonPilon/lifelines#1568]
Hi there, 
The latest version of lifelines, v0.27.8, has started using `importlib.resources.files` for data loading. [This feature was introduced in Python 3.9. ](https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files) Therefore, lifelines v0.27.8 is not compatible with Python 3.8 and earlier versions. I noticed that this was not reflected in the changelog. I suggest mentioning this in the documentation or changelog for clarity.

**Comment by CamDavidsonPilon** [comment]
Hi @TonyYanOnFire, 

You're correct, this should be made explicit in the setup.py, too. The error appears when trying to load data only, is that correct?

**Comment by TonyYanOnFire** [comment]
Yes, that is correct.
