### ISSUE TITLE
Overflow with large numbers in Nelson Aalen fitter

### ISSUE THREAD

**Issue by shilet** [CamDavidsonPilon/lifelines#1585]
When determining the confidence interval for the Nelson Aalen Fitter, the following formula is used:
 def _variance_f_discrete(self, population, deaths):
        return (population - deaths) * deaths / population ** 3

The problem is that population (population = events["at_risk"] - entrances) is an integer, this should be changed to float to prevent overflow. Otherwise the resulting confidence interval is NaN.

**Comment by CamDavidsonPilon** [comment]
Hi @shilet, are you able to provide an example of this failing? AFAIK, integers in Python shouldn't overflow.

**Comment by shilet** [comment]
Hi Cameron,

I was just using the NelsonAalenFitter(nelson_aalen_smoothing=False), and
got the following error:

<lifelines.NelsonAalenFitter:"NA_estimate", fitted with 5.77905e+06 total
observations, 0 right-censored observations>
\lib\site-packages\lifelines\fitters\nelson_aalen_fitter.py:176:
RuntimeWarning: invalid value encountered in sqrt
  df[ci_labels[0]] = cum_hazard_ * np.exp(-z * np.sqrt(cumulative_sq_) /
np.where(cum_hazard_ == 0, 1, cum_hazard_))

The confidence interval for the cumulative hazard contains weird (way too
large) numbers, and also NaN/Inf.
When using a smaller dataset I didn't have this problem.

The error disappears after I changed this: in utils/__init__.py:
   population = events["at_risk"] - entrances
  population = population.astype(float)

So that's why I guess it is some sort of overflow issue (but my python
knowledge is limited...)

Hopefully this helps

Best regards,

Sheila

**Comment by CamDavidsonPilon** [comment]
hm, I'm not able to reproduce it. Can you share the dataset (unlikely)? Can you tell me more about your dataset (any negative values, any late entry being used)?

**Comment by shilet** [comment]
Hi,

I can reproduce with the following:

 y = np.random.randint(1, 1000, 100000000)
    naf = NelsonAalenFitter(nelson_aalen_smoothing=False)
    naf.fit(y ,event_observed=None, timeline=range(0, int(y.max())))

**Comment by CamDavidsonPilon** [comment]
Thanks, I was able to reproduce it with your example. I believe the problem _is_ integer overflow, as you predicted. It's correct that _Python_ integers don't overflow, but when they are inside a Pandas series, they are `int64`, which can overflow. The `population**3` term in the calculation was creating a negative value where there shouldn't have been. I've fixed it by avoiding that large exponent: 

```python
    def _variance_f_discrete(self, population, deaths):
        return (population - deaths) * deaths / population ** 3

```

to 

```
    def _variance_f_discrete(self, population, deaths):
        return (1 - deaths / population) * (deaths / population) * (1. / population)
```

**Comment by shilet** [comment]
Hi,

Happily you could reproduce it.
Is there a reason you didn't repair it by converting population to float
(population = population.astype(float))?

**Comment by CamDavidsonPilon** [comment]
floats (or float64, in pandas) have the same problem: they'll overflow eventually. However, they'll overflow at a higher number. So why not use float64? While the upperbound of a float64 is higher than a int64, a float64s precision is severely reduced for larger numbers, so your final values aren't precise and could look quite silly. The implemented solution avoids computing these large numbers, so we can keep the precision of int64s while avoiding overflows.
