### ISSUE TITLE
"fill_date" in datetimes_to_durations

### ISSUE THREAD

**Issue by AlexandreDecan** [CamDavidsonPilon/lifelines#159]
Hello,

According to the documentation, `fill_date` in utils.datetimes_to_durations can also be used to censor `end_dates` that are above `fill_date`:
> fill_date: the date to use if end_times is a None or empty string. This corresponds to last date
                  of observation. Anything above this date is also censored. Default: datetime.today()

It is currently not implemented. Here's the current computation of `C` (L613)
`C = ~(pd.isnull(end_times).values | (end_times == "") | (end_times == na_values))`

Also, the warning at L624 should be modified. At the moment, it prints *Warning: some values of start_times are __before__ end_times* in case where `(T < 0).sum()`. As `T` contains the result of `end_dates - start_dates`, *before* should be replaced by *after*.

**Comment by CamDavidsonPilon** [comment]
Thanks for bringing this up, @AlexandreDecan! There's a fix going in, and I'll cut a release of 0.7.1 soon =)
