### ISSUE TITLE
max_unique_durations in AalenAdditiveFitter fit method not implemented

### ISSUE THREAD

**Issue by cavaunpeu** [CamDavidsonPilon/lifelines#160]
There is a `max_unique_durations` parameter enumerated in the docstring of this method, however it does not appear to be implemented in the method itself. When fitting this model to a dataset with ~1000+ unique durations, I experience significant slowdown.

**Comment by CamDavidsonPilon** [comment]
The `max_unique_durations` is out of date, and should be removed / reimplemented. I wonder why I removed it now, investigating...

**Comment by CamDavidsonPilon** [comment]
Hmm, [so the initial commit in this PR](https://github.com/CamDavidsonPilon/lifelines/pull/45) added functionality for that keyword, but a latter commit in the same PR removed it. 

I'll go into adding something like that back in, but for now, you can manually bin the unique durations into bins of modest cardinality. Let me know how that goes!

**Comment by cavaunpeu** [comment]
Thanks Cam. Will give it a shot this week and report back!
