### ISSUE TITLE
Compatibility with numpy 2.0

### ISSUE THREAD

**Issue by Zethson** [CamDavidsonPilon/lifelines#1619]
Numpy 2.0 is out and lifelines currently does not support it (base requirements restrict to < 2.0). I would like to politely request an unpin if possible.

**Comment by CamDavidsonPilon** [comment]
For sure, we can do this and fix #1618. Let me attempt this tonight.

**Comment by CamDavidsonPilon** [comment]
mmmm this may be more complicated due to autograd not being updated, and #1615

**Comment by CamDavidsonPilon** [comment]
So things are happening with autograd, and some new maintainers have stepped up. I will keep any eye on thier progress.

**Comment by motin** [comment]
Apparently a user has confirmed that lifelines works with numpy 2.0 with the latest autograd https://github.com/CamDavidsonPilon/lifelines/issues/1615#issuecomment-2376290569 - any hopes for a 0.30.0 release with numpy support soon? :)

**Comment by pawel-biernacki-roche** [comment]
Is there any timeline for this? Can we help by opening a PR?

**Comment by CamDavidsonPilon** [comment]
Sorry for the delay! 0.30.0 is out and has numpy2 suppory
