### ISSUE TITLE
Censored Chemistry Data Functionality

### ISSUE THREAD

**Issue by inkenbrandt** [CamDavidsonPilon/lifelines#168]
I am too much of an amateur to provide a meaningful, constructive issue.  However, I prefer python for analysis, and the functionality of your package is pretty nice. I am using survival analysis to accommodate for nondetects in water chemistry data. I would like to see more functions like the ones provided in the R package <a href=http://cran.r-project.org/web/packages/NADA/index.html>NADA</a>, specifically the `cenfit` and `cendiff` functions, where there is greater flexibility for left-censored data.  Maximum Likelihood Estimation techniques would be awesome, as well as Bayesian estimates.  The NADA scripts are based mostly off of work by a former U.S. Geological Survey employee named <a href=http://www.practicalstats.com/resources/Helsel-Publications.pdf>Dennis Helsel</a>.  I apologize for being so vague, and for using your script issues as a comment board.  Thank you for your work!

**Comment by CamDavidsonPilon** [comment]
Hey @inkenbrandt, 

We do support the kaplan-meier based inference for left-censored data, but I'm not sure we'll extend it to MLE or Bayesian approaches. 

```
from lifelines import KaplanMeierFitter
D = [4,2,1,4,5,2,1,2]
C = [0,1,0,1,1,1,0,1]
kmf =
kmf = KaplanMeierFitter()
kmf.fit(D, C, left_censorship=True)
kmf.cumulative_density_
```

**Comment by inkenbrandt** [comment]
Thanks CamDavidsonPilon!
