### ISSUE TITLE
implement power and sample size analysis

### ISSUE THREAD

**Issue by jamesdj** [CamDavidsonPilon/lifelines#174]
This could be useful for several reasons. In my use case, I have a large number of possible group assignments I could test with pairwise log-rank tests. However, I prefer to not test them all since I expect that a significant fraction of them stands no chance of being significant, because of insufficient sample sizes or numbers of deaths. Performing such tests would have no benefit but would dilute the results by increasing the amount of multiple-hypothesis correction. If instead I can rule many of these hopeless cases out a priori based on power/sample size analysis, I can avoid that problem. 

I'm new to survival statistics, so I hesitate to try my hand at helping code this, but I imagine that for an expert, implementing this for the log-rank test would not be very difficult. I have searched a bit and found proprietary statistical packages (Stata, SAS, etc) offering this feature. There are R packages, academic references and a few forum posts that seemed related but perhaps not exactly what I'm looking for.

Power and sample size analysis for survival regression would also be useful.

**Comment by CamDavidsonPilon** [comment]
:+1: yea I can put this with the 0.8.0 release. Thanks for the suggestion. Can you suggest some literature on the subject?

**Comment by jamesdj** [comment]
Sure. I will need to search a bit but I'll try to get back to you soon.

**Comment by jamesdj** [comment]
The references mentioned at [this site](http://www.stata.com/stata10/poweranalysis.html) should be useful. They are listed at the bottom of the page. The [manual](https://cran.r-project.org/web/packages/powerSurvEpi/powerSurvEpi.pdf) for the R package powerSurvEpi has newer references, including the most apparently relevant that I found myself with Google Scholar.

This may not cover everything you'll need, but hopefully it covers most of it and can give you leads to find other relevant references.

**Comment by CamDavidsonPilon** [comment]
This has been implemented in v0.8.0.

**Comment by jamesdj** [comment]
Excellent! Good work. I've got the latest version and am looking for it--where is it? How is it accessed? Sorry, I shouldn't be impatient, the documentation will catch up.

**Comment by CamDavidsonPilon** [comment]
Yea, I skipped docs on it :disappointed: 

In the CHANGLOG, you'll see:

> added sample size and power calculations for statistical tests. See lifeline.statistics. sample_size_necessary_under_cph and lifelines.statistics. power_under_cph.

**Comment by jamesdj** [comment]
Great, I'm using them now. Nice work on the quick turnaround for these.

For both functions, I'd like to estimate p_exp and p_con from data. I
understand these are the probability of an event in the experimental and
control groups, respectively, over the maximum time of the study. How do I
estimate them given that some observations are truncated? This is probably
a very basic survival analysis question; I apologize for my inexperience. I
thought I could use CoxPHFitter, fit a model to each group's data, and
retrieve the probability as some attribute of the fitted model, although it
wasn't clear to me which attribute was relevant. Am I headed in the right
direction?


James Jensen
PhD student, Bioinformatics and Systems Biology
Trey Ideker lab
University of California, San Diego
