### ISSUE TITLE
Survival regression Documentation

### ISSUE THREAD

**Issue by Aloiris** [CamDavidsonPilon/lifelines#176]
Hello,

First of all, congratulations for this extremely nice package: it is straightforward to use and I love the plots. I am having difficulties using the survival regression however. Would it be possible to add a short section (or post here) an example for the Cox PH model? For example, if I want to generate the survival curve for the baseline, and for a 30 years old individual, which commands would allow me to do so?

What if I want survival the curve for a specific age + another parameter?
Many thanks!

**Comment by CamDavidsonPilon** [comment]
Cool yea, thanks for telling me about this missing documentation. I'll add some this weekend =)
