### ISSUE TITLE
reimplement bounds for weibull

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#182]
http://stats.stackexchange.com/questions/135749/confidence-intervals-of-fitted-weibull-survival-function

**Comment by CamDavidsonPilon** [comment]
hmm this is for the survival function, whereas lifelines implements CI bounds for the hazard

**Comment by bayesfactor** [comment]
Can you please implement a version of CI bounds for Weibull survival function?
