### ISSUE TITLE
Problems installing with conda

### ISSUE THREAD

**Issue by ewancarr** [CamDavidsonPilon/lifelines#184]
I'm new to IPython/Pandas, so apologies for the basic question.

I'm trying to install `lifelines` with [Anaconda](https://store.continuum.io/cshop/anaconda/). However, I run into the following problem:

```
conda install lifelines
Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: lifelines
```

Installation works fine when using `pip install`, but packages installed with `pip` aren't available in IPython (so far as I can tell).

Any suggestions on how to solve this?

**Comment by spacecowboy** [comment]
lifelines is not currently available as a conda package. However, as it is a pure python package, installing it with pip works fine.

The issue with pip packages not being available to your ipython suggests you are calling "the wrong pip", or "the wrong ipython".

Make sure to install pip in conda first:

    conda install pip

Now, to verify that you are using the correct pip/ipython, do the following:

    which pip

and

    which ipython

On my computer, I get the following paths:

    /home/jonas/anaconda3/bin/pip
    /home/jonas/anaconda3/bin/ipython

Note that they are both in the same directory, under anaconda/miniconda. If either one reports something like `/usr/bin/pip` or `/usr/bin/ipython`, your PATH variable needs fixing. Print the output of above commands here and I can help if you need additional instructions.

**Comment by ewancarr** [comment]
Thank you!

That worked. I'm sure there's a cleaner way to do it, but I just

```shell
cd /usr/local/bin
rm pip
pip install lifelines
```

and lifelines is now working in IPython as expected. 

(I had previously installed `pip`, with `easy_install`, and then installed `conda` as well. So `pip` was picking up the `/usr/local/bin` copy, not the copy in `/Users/ewancarr/anaconda/bin/pip`).

**Comment by CamDavidsonPilon** [comment]
:+1: thanks @spacecowboy

**Comment by LarryKuehn** [comment]
Hi.
I would like to use lifelines 0.13 in Anaconda. Unfortunately, conda-forge only has version 0.11.2. What can I do?
I did 'conda install -c conda-forge lifelines' and also 'pip install lifelines'. But that does not work.
Thanks.
