### ISSUE TITLE
Nelson Aalen hazard off by a factor of 1/2

### ISSUE THREAD

**Issue by bradhackinen** [CamDavidsonPilon/lifelines#186]
I've been experimenting with Lifelines for hazard rate estimation, and I'm pretty sure there is a problem with the output of the Nelson Aalen fitter's hazard rate function. It looks like the function is scaled by 1/2 relative to the correct value.

Here is a quick test script. The data is exponentially distributed, so it should have a constant hazard of 1. But the output (at least on my computer) shows the hazard at 0.5. 

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import lifelines
import random


n = 1000

testData = pd.DataFrame(index=range(n))
testData['duration'] = np.random.exponential(1,(n,))


b = 1
naf = lifelines.NelsonAalenFitter()
naf.fit(testData['duration'])
ax = naf.plot_hazard(bandwidth=b)

plt.show()
```

![nelsonaalenhazardtest](https://cloud.githubusercontent.com/assets/14437616/9983026/067d26ec-5fa5-11e5-8a4a-918f02e4ed72.png)

It would also be nice if the smoothed curve didn't average in some zeros at the start. That initial short increase is not coming from the data (it changes with the bandwidth).

**Comment by CamDavidsonPilon** [comment]
Thanks for the great write up, @bradhackinen. This is pretty serious, so I'll investigate it this week.

**Comment by CamDavidsonPilon** [comment]
I have good news and bad news. The good news is I found an errant `2` floating around. That fixes the 1/2 error. The bad news is I tried to implement an asymmetric smoothing function, and it went terribley haha.

So I'll change the 2, and open a new issue for the smoothing.

**Comment by bradhackinen** [comment]
Awesome. I really like the module, so it's nice to have this fixed so fast.
