### ISSUE TITLE
Can't pickle univariate models properly 

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#188]
```
pickle.dump(kmf, open(file, 'wb' ) )

PicklingError: Can't pickle <function plot at 0x000000004D491278>: it's not found as lifelines.plotting.plot
```

**Comment by IvanBarrientos** [comment]
One of the relevant parts of aaf to pickle for predictions and analysis is cumulative_hazards_, e.g.

pickle.dump(aaf.cumulative_hazards_, open('train_chazards.p', 'wb' ) )

**Comment by CamDavidsonPilon** [comment]
Though the PR aboves solves this for regression models, univariate models are still no pickle-able.

**Comment by AbdealiJK** [comment]
I'd like to understand if this is closed and all models in lifelines is expected to be picklable now ?
Or should I expect pickling of UnivariateFitter models to fail ?

**Comment by CamDavidsonPilon** [comment]
Hm, thanks for bringing this up! I thought I had a test for all models, but maybe I missed something. I’ll try to get this fixed ASAP

**Comment by AbdealiJK** [comment]
@CamDavidsonPilon I did a quick test for the fitters based on the docstring examples in the API docs:

```python

import pickle
import pandas as pd

df = pd.DataFrame({
    'T': [5, 3, 9, 8, 7, 4, 4, 3, 2, 5, 6, 7],
    'E': [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0],
    'var': [0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2],
    'age': [4, 3, 9, 8, 7, 4, 4, 3, 2, 5, 6, 7],
})

from lifelines.fitters import UnivariateFitter
from lifelines import (
    KaplanMeierFitter, LogLogisticFitter, WeibullFitter,
    GeneralizedGammaFitter, AalenAdditiveFitter, CoxPHFitter, WeibullAFTFitter,
    LogNormalAFTFitter, LogLogisticAFTFitter)

for cls in (
        KaplanMeierFitter, LogLogisticFitter, WeibullFitter,
        GeneralizedGammaFitter, AalenAdditiveFitter, CoxPHFitter, WeibullAFTFitter,
        LogNormalAFTFitter, LogLogisticAFTFitter):
    try:
        clf = cls()
        if cls in (KaplanMeierFitter, LogLogisticFitter, WeibullFitter, GeneralizedGammaFitter):
            clf.fit(df['T'], df['E'])
        else:
            clf.fit(df, 'T', 'E')
        _ = pickle.dumps(clf)
        print('TEST -- {}: PASS'.format(cls.__name__))
    except Exception as err:
        print('TEST -- {}: {}'.format(cls.__name__, err))


TEST -- KaplanMeierFitter: Can't pickle local object 'KaplanMeierFitter._fit.<locals>.<lambda>'
TEST -- LogLogisticFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
TEST -- WeibullFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
TEST -- GeneralizedGammaFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
TEST -- AalenAdditiveFitter: PASS
TEST -- CoxPHFitter: PASS
TEST -- WeibullAFTFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
TEST -- LogNormalAFTFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
TEST -- LogLogisticAFTFitter: Can't pickle local object 'unary_to_nary.<locals>.nary_operator.<locals>.nary_f'
```
And most of them were failing, although most from the same function

**Comment by CamDavidsonPilon** [comment]
Wait - I think I knew this and had a failing test for this. Instead of pickle package, try the dill package: https://lifelines.readthedocs.io/en/latest/Examples.html#serialize-a-lifelines-model-to-disk

**Comment by CamDavidsonPilon** [comment]
I don’t except pickle to ever work (unless pickle changes drastically) since we rely a lot on anonymous functions.

**Comment by AbdealiJK** [comment]
Nods, I saw the note on dill
But was hoping to use pickle as we standardize on pickle and pmml in our systems and not able to use dill =(

Thought this issue was to track pickle support so pinged here. 

I had a follow up question, which may not be related to this issue then - is there a way to convert the models to PMML? 
When I use sklearn2pmml, it throws an error related to pickling too.

**Comment by CamDavidsonPilon** [comment]
Ah sorry, atm pickle won't be supported unless I get a serialization expert too look at it. 

w.r.t. sklearn2pmml, that lib uses `joblib`, which has a better chance of working with lifelines than pickle. However, it's currently not working with lifelines.

**Comment by AbdealiJK** [comment]
Could you elaborate on the need for autograd in lifelines? 
So we could understand the need and constraint a bit better? 

My understand is that it helps to be able to take any function written with pure numpy functions and generate a function which is the derivative for that function.
But it could be avoided if the derivative is a close form expression and can be defined as a separate function.

Note: I had created a issue in jax, which hasn't gotten a reply yet. https://github.com/google/jax/issues/1362

**Comment by CamDavidsonPilon** [comment]
> But it could be avoided if the derivative is a close form expression and can be defined as a separate function.

Totally, but is why I migrated to autograd :) Very often, the closed form expression is very complicated (and even worse for second-derivatives). Also, autograd allows for custom models, which can be arbitrarily complicated. 

An approach might be to find a way to serialize these functions.

**Comment by AbdealiJK** [comment]
I did take a look at autograd, and it looked like making it support pickle would require a lot of core changes. And considering it doesn’t have an active maintainer - it would be tough to make changes there.
