### ISSUE TITLE
CoxPHFitter.predict() gives many 'inf' values

### ISSUE THREAD

**Issue by ibarrien** [CamDavidsonPilon/lifelines#189]
The Cox proportional hazards method "predict" returns 'inf' the majority of the time, on average, for several data sets. For example:

```
from lifelines.datasets import load_rossi
from lifelines import CoxPHFitter
rossi_dataset = load_rossi()
df_train = rossi_dataset.head(300)
cf = CoxPHFitter()
cf.fit(df_train, 'week', 'arrest')
df_test = rossi_dataset.tail(100)
df_test['pred'] = cf.predict(df_test)
df_test['pred'].describe()
count    100.000000
mean            inf
std             NaN
min       50.000000
25%             inf
50%             inf
75%             inf
max             inf
Name: pred, dtype: float64
```

On several other data sets I also get 'inf' values at least at the 50% level, which seems to suggest numerical instability. 

A related stability/accumulation point issue is also seen with the Aalen additive fitter returning repeated values via its predict() method. In general, I get a single repeated predicted value on over 80% of entries in test sets with num_rows between 1k and 10k.
**Question: could someone compare lifelines results with results from R or SAS?**

**Comment by CamDavidsonPilon** [comment]
hm, so we dealt with inf values a while back - the trouble is in prediction when we do the exponentiation. I'll look into it again. 

We've compared the parameters fitted against R, but I don't think the prediction

**Comment by CamDavidsonPilon** [comment]
Oh, one problem with your example: internally to deal with numerical instability, we normalize everything by removing the mean and dividing by the std. dev. This is turned on by default with the `normalize=True` param: https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/coxph_fitter.py#L35

When you call `predict`, you have not normalized your data, so the values are all very extreme compared to what the model has seen. You can normalize like this:

```
from lifelines.utils import normalize
data_to_predict = normalize(df_test, mean=cf._norm_mean, cd._norm_std)
cf.predict(data_to_predict)
```

Does that make sense?

**Comment by IvanBarrientos** [comment]
It would be nice to see prediction comparisons with R (I admit I don't have R expertise!). 

I wonder if a workaround may be a low order Taylor expansion in the predict_survival(). For example, replacing exp(-self.predict_cumulative_hazard(X))

with exp_n(-self.predict_cumulative_hazard(X), order=n)

where exp_n is a method that returns 1 + x + x**2/2 + ... + x**n /n!

**Comment by IvanBarrientos** [comment]
Thanks for the normalization tip. I tried it but still get lots of inf values:
dx = normalize(df_test, mean=cf._norm_mean, std=cf._norm_std)
dx['pred'] = cf.predict(dx)
dx['pred'].describe()
count    100.000000
mean            inf
std             NaN
min       28.000000
25%       46.000000
50%             inf
75%             inf
max             inf
Name: pred, dtype: float64

Note:
 cf._norm_mean
fin      0.503333
age     24.836667
race     0.890000
wexp     0.553333
mar      0.106667
paro     0.623333
prio     3.180000
dtype: float64


cf._norm_std
fin     0.500824
age     6.203623
race    0.313413
wexp    0.497978
mar     0.309205
paro    0.485360
prio    3.025134
dtype: float64

**Comment by IvanBarrientos** [comment]
No luck so far...even truncating the Taylor expansion in the predict_survival_method at degree 2 or 100 still gives predict() results mostly 'inf'. 

While the predict() method seems unstable, the predict_expectation() method seems preferable at the moment.

**Comment by CamDavidsonPilon** [comment]
This is a PR with some of our discussion around coxph prediction methods: https://github.com/CamDavidsonPilon/lifelines/pull/89
