### ISSUE TITLE
"color_cycle" does not exist in matplotlib 1.5

### ISSUE THREAD

**Issue by thomas-haslwanter** [CamDavidsonPilon/lifelines#191]
The matplotlib upgrade from 1.4.3 to 1.5.0 breaks lifelines:
In "plotting.py", lines 317/8:
```
        kwargs['color'] = coalesce(kwargs.get('c'), kwargs.get('color'),                                  next(kwargs["ax"]._get_lines.color_cycle))
```
has to be replaced by
```
  import matplotlib as mpl
  if int(mpl.__version__.split('.')[1]) > 4:
        kwargs['color'] = coalesce(kwargs.get('c'), kwargs.get('color'), next(kwargs["ax"]._get_lines.prop_cycler))
```

**Comment by CamDavidsonPilon** [comment]
Nice, thanks for reporting this. I'll get a fix in asap

**Comment by CamDavidsonPilon** [comment]
Uh, maybe you can help - how do I install the latest development version of matplotlib?

**Comment by thomas-haslwanter** [comment]
If you work on Windows, copy the appropriate file
   matplotlib‑1.5.0rc2‑cp35‑none‑win32.whl
or
   matplotlib‑1.5.0rc2‑cp35‑none‑win_amd64.whl
from
   http://www.lfd.uci.edu/~gohlke/pythonlibs/#matplotlib
to your computer, and install it with 
  pip install [filename].

If you are on a Mac, I assume that 
   pip install --pre -f http://wheels.scipy.org matplotlib 
would work (taken from http://matplotlib.1069221.n5.nabble.com/Matplotlib-devel-v1-5-0rc2-td46266.html)

And if you are on Linux, then I don't really know off-hand ....

**Comment by CamDavidsonPilon** [comment]
Closed in ce7e54713bcb01877bd609ca554c5445dfb15c16

**Comment by thomas-haslwanter** [comment]
Cam, could you please update lifelines on pypi?
The currently installed version does not contain the fix that you implemented for this issue.
Thanks, thomas

**Comment by CamDavidsonPilon** [comment]
@thomas-haslwanter, thanks for the notice! Done now: https://pypi.python.org/pypi/lifelines

**Comment by cleemesser** [comment]
I think this fix does not work for matplotlib 2.0, I'm guessing that you are conditioning on the minor version only in your test.

**Comment by CamDavidsonPilon** [comment]
@cleemesser I locally updated to matplotlib 2.0 and ran the plotting tests - I didn't receive any errors. Can you post your lifelines + matplotlib versions, the code you are running and the error displayed?

**Comment by cleemesser** [comment]
I think this does not concern the latest lifelines (at least what I see in github master) as I see you have just decided not to support matplotlib < 1.5. I have lifelines 0.9.2 with matplotlib 2.0.0 using my updated version of anaconda. Sorry to waste time.

**Comment by CamDavidsonPilon** [comment]
Okay, thanks for following up =)
