### ISSUE TITLE
Kaplan–Meier plotting Documentation

### ISSUE THREAD

**Issue by kramaswamyxu** [CamDavidsonPilon/lifelines#193]
Hello,

* `kmf.plot()` according to the docs give a smooth graph(of the survival function) , while in reality, calling this produces a step graph.  The docs need to be updated accordingly with the right plots.
* `kmf.survival_function_.plot()` actually produces the smooth graph - it will be useful to enable a way to have these graphs also have the confidence intervals and show censor points. 
* This issue was originally asked at http://stats.stackexchange.com/questions/175342/difference-between-kaplanmeierfitter-plots-in-lifelines/

**Comment by CamDavidsonPilon** [comment]
Thanks @kramaswamyxu!

**Comment by CamDavidsonPilon** [comment]
This is fixed with the recent changes to the docs.

**Comment by kramaswamyxu** [comment]
Yes - thanks @CamDavidsonPilon!
