### ISSUE TITLE
CoxPHFitter.predict() gives just inf values

### ISSUE THREAD

**Issue by sanazb** [CamDavidsonPilon/lifelines#197]
CoxPH method returns all inf for predict method.
This is my code.
 
```python
df_train = df.head(1000)
df_test = df.tail(200)
cf = CoxPHFitter()
cf.fit(df_train, 'd', event_col = 'o')
df_test_norm = normalize(df_test, mean=cf._norm_mean, std=cf._norm_std)
print cf.predict(df_test_norm)
```

**Comment by IvanBarrientos** [comment]
I've encountered very similar issues and would *love* to solve this problem. One question: have you tried other prediction methods, such as 'expectation' in the Lifelines which uses trapz() or a simple dot product of the form <self.timeline, self.survival_function()>?

Would also be nice if you could link to some of your data set when presenting these examples.

**Comment by sanazb** [comment]
Here is my data:
```
https://dl.dropboxusercontent.com/u/19770326/features2.txt
```

The last two features are duration and observed status.

I used predict_expectation(test_set) and I got '26712' for all events.

**Comment by sanazb** [comment]
I also used predict_median, but got inf for almost  all predictions.

**Comment by IvanBarrientos** [comment]
If you might be interested in the Aalen additive model, checkout 
https://github.com/IvanBarrientos/Survival-Analysis

Using your data set and aalen_additive_oop.py, the total_expectation method seems to give reasonable answers (none of which are 'inf'). Note that for my train set I used df.head(1000) and for the test df.tail(100).

If you'd like to chat about my Aalen additve model implementation, feel free to email me at corps.des.nombres@gmail.com

It would still be interesting to get Lifelines predict() methods to work...

**Comment by CamDavidsonPilon** [comment]
@IvanBarrientos, you seem to be very confident in your Aalen Additive version, why not submit it to lifelines?

**Comment by IvanBarrientos** [comment]
@CamDavidsonPilon  Hi! Sure, happy to submit; what is the appropriate way to do so in this case?  

I highly benefited from your own code layout on Aalen additive in my own implementation. Just as fyi: I simply followed a basic implementation. While it seems to work for basic data sets, I make no claim that it works for large/complex datasets, nor on its computational efficiency. 

If I can, happy to help! You've initiated a much sought after library.

**Comment by CamDavidsonPilon** [comment]
@IvanBarrientos Have you submitted a pull request before to another library? https://help.github.com/articles/using-pull-requests/ can help. 

Ideally, the api is identical to the existing implementation, thus only swapping the internals is necessary. Also, some tests would be appreciated!

**Comment by IvanBarrientos** [comment]
Thank you - I haven't submitted PR's before. I will start by adding unit tests this week and will try to work on mimicking your api (e.g. vectorizing my predict() method so it may accept a dataframe rather than single rows)

**Comment by CamDavidsonPilon** [comment]
closed for being a duplicate

**Comment by joshlk** [comment]
Duplicate link #189
