### ISSUE TITLE
alpha is flipped with confidence level

### ISSUE THREAD

**Issue by JonathanRBates** [CamDavidsonPilon/lifelines#198]
Just a minor comment, but the alpha parameter is 1-\alpha for what \alpha usually means in a confidence interval.  Nice package, btw!

**Comment by CamDavidsonPilon** [comment]
@JonathanRBates, thanks for the heads up. Can you tell me what objects you are using?

**Comment by JonathanRBates** [comment]
NelsonAalenFitter

**Comment by Silvernine0S** [comment]
I'm on the newest version 0.18.6. I'm curious as to why your alpha IS the confidence level when plotting the graphs. Alpha should be  1-confidence_interval so if you want a confidence interval of 95%, alpha would be 1 - 0.95 = 0.05. For example, manually specifying alpha = 0.05 (confidence level of 95%) results in plots with small confidence interval. Specifying alpha = 0.95 (confidence level of 5%) results in plots with larger confidence interval. It should be the opposite.

This is seen in most of the fitters I used. Particularly Kaplan-Meiler, Nelson-Aalen, and Weibull. Even your most recent documentation is confusing. You listed alpha's default value of 0.95, which would mean your default confidence interval is 5%. Obviously you meant 95% confidence interval which mean alpha should be 0.05.

alpha (float, option (default=0.95)) – The alpha value associated with the confidence intervals.

**Comment by CamDavidsonPilon** [comment]
Yea, this has been a silly bug for a while. If this is confusing users (via the documentation), then I need to change. Let me put add it to the next release. Thanks for the ping!
