### ISSUE TITLE
coxph: different results vs R

### ISSUE THREAD

**Issue by IvanBarrientos** [CamDavidsonPilon/lifelines#200]
It would be neat to see comparisons with R's coxph(). For example, R's coxph() produces quite different coefficient results on the rossi data set. **E.g. Lifeline's coefficient for age is over 6x larger than that of R's.**

Perhaps I've overlooked something simple? I haven't tried altering default params in Lifelines for fit() such as alpha or penalizer. I'd appreciate comments on this one! Details of results below.

Results from R:
Code:
> library(survival)
> fit <-coxph(Surv(dat$week, dat$arrest) ~ dat$fin + dat$age + dat$race + dat$wexp + dat$mar + dat$paro + dat$prio, data=dat)
> summary(fit)
Results:
>n= 432, number of events= 114 

 >var  coef   

>dat$fin -0.37942
>dat$age  -0.05744 
>dat$race  0.31390
>dat$wexp -0.14980
>dat$mar  -0.43370
>dat$paro -0.08487 
>dat$prio  0.09150 

Results from Lifelines, via:
http://lifelines.readthedocs.org/en/latest/Survival%20Regression.html#cox-s-proportional-hazard-model)

> n=432, number of events=114

> var coef

> fin  -1.897e-01
> age  -3.500e-01 
> race  1.032e-01  
> wexp -7.486e-02 
> mar  -1.421e-01 
> paro -4.134e-02 
> prio  2.620e-01

The coefficients look quite different to me. For example the age coefficients vary significantly.  R: coef(age) = -0.057 and coef(age)/coef(race) = -0.183 whereas in Lifelines, coef(age) = -0.344 and coef(age)/coef(race) = -3.378. Similar discrepancies for other vars such as mar.

On the other hand, some statistics seem to agree better such as 'z' (not displayed above).

**Comment by CamDavidsonPilon** [comment]
Lifelines by default normalizes its input data. That's likely the reason it differs at first glance. We do test against R here: https://github.com/CamDavidsonPilon/lifelines/blob/master/tests/test_estimation.py#L828

**Comment by IvanBarrientos** [comment]
Oh, great - thank you! I set normalize=False and got more consistent results against R:

fin -3.790e-01 
age -5.725e-02
race  3.141e-01
wexp -1.511e-01 
mar  -4.328e-01 
paro -8.498e-02 
prio  9.111e-02 

The only question I have is whether normalizing should be default (as in Lifelines) or not (as R seems to do). Thanks again for pointing this out, I'll close this issue now.

**Comment by CamDavidsonPilon** [comment]
The estimation is more stable if we normalize in lifelines - that's why we do it
