### ISSUE TITLE
Issue in CoxPHFitter._newton_rhaphson

### ISSUE THREAD

**Issue by HombreDeGatos** [CamDavidsonPilon/lifelines#204]
I am trying to use the CoxPH Fitter and I have been having a lot of troubles running the regression.
When running the code

    cf = CoxPHFitter()
    cf.fit(hidden_clinical_data, duration_col = 'duration', event_col = 'observed',
             include_likelihood=True, show_progress = True
            )

hidden_clinical_data is a Panda Dataframe of shape 260 x 502 (of all non-null numbers)
When I run the `cf.fit` line, I get the error:

    //anaconda/lib/python2.7/site-packages/lifelines/fitters/coxph_fitter.pyc in _newton_rhaphson(self, X, T,    E, initial_beta, step_size, precision, show_progress, include_likelihood)
    240             i += 1
    241 
    --> 242         self._hessian_ = hessian
    243         self._score_ = gradient
    244         if include_likelihood:
    UnboundLocalError: local variable 'hessian' referenced before assignment

I ran through the code with the python debugger to try and get to the bottom of it. What I discerned is that the reason why this error is raised is because of the control structure at line 229.
Before the point of failure, the norm of the delta is still > 10 (line 227)
It then executes line 228 and the step_size was finally reduced to be < 0.001
It then continues and exits the while loop.

In this control, the program never reaches line 233 to actually set the variable `hessian`
And so when it breaks from the while loop, it reaches an error when executing line 242. 

Is this the intended behavior of the program? Is there something inherently wrong with the data for the assumptions of norm(delta) > 10 while step size < 0.001?

What could solve this solution?

**Comment by CamDavidsonPilon** [comment]
Hey @HombreDeGatos, thanks for the detailed issue. I think I have a solution. Are you able to send me the dataset you are using? I'd like to try my solution on your data.

**Comment by CamDavidsonPilon** [comment]
So in the commit above, I've fixed the issue. However, your data is quite imbalanced: the numerical stability is not guaranteed when you have 500 covariates and only ~250 observations. For this reason, the output is pretty much nonsensical. 

I tried adding a small penalizer, `CoxPHFitter(penalizer=1.0)`, and my results were much more sensible. I suggest doing this as well =)
