### ISSUE TITLE
Robust fitting for colinear and near-colinear inputs

### ISSUE THREAD

**Issue by smallnamespace** [CamDavidsonPilon/lifelines#207]
A very nice to have would be robustness in the face of colinear and ill-conditioned inputs, much like [the R survival package](https://cran.r-project.org/web/packages/survival/survival.pdf) does.

I immediately ran into this issue when trying to try the CoxPH fitter for the first time on real data.

There seem to be a few issues that one runs into with ill-conditioned inputs:

1) The gradient fails to compute with the error that there are NaNs in the delta
2) After computation, the Hessian fails to invert because there are singular values
3) Even if these succeed, the returned estimates come back as Infs

Of course, I could improve the input conditioning myself first (e.g. by dropping columns), it would certainly be a nice to have.

**Comment by CamDavidsonPilon** [comment]
Hey @smallnamespace, any idea what R's package does to correct this? 

Also, have you tried adding a positive penalizer into the `fit` method? That should certainly help with colinear data.

**Comment by smallnamespace** [comment]
@CamDavidsonPilon 
I don't know enough R to answer your question, but the code in question is here: https://github.com/cran/survival/blob/master/R/coxph.R

It might be the case that I'm misreading what the robust parameter actually does here. I'll try the L2 penalizer and report back.

**Comment by smallnamespace** [comment]
Adding in the ridge penalty didn't seem to help in my case.

So one particular issue is that I have categorical data and some of the categories are very rare. It's easy to do the initial regression by using patsy and then dropping the intercept term, but when I use `lifelines.utils.k_fold_cross_validation` the input _or_ training set will often randomly have all 0s for at least one of the categories, in which case the fitting fails.

**Comment by CamDavidsonPilon** [comment]
Oh interesting, that seems like a common problem k-fold I imagine, independent of the regression one is using. Let me think about it a bit!

**Comment by smallnamespace** [comment]
One option might be to do elastic net penalization, since the L1 penalty should drop the collinear terms.
