### ISSUE TITLE
Hazard function in weibull_fitter.py documentation is incorrect

### ISSUE THREAD

**Issue by benrifkind** [CamDavidsonPilon/lifelines#208]
Small typo.  
In the documentation on line 47 should be,
"""
and the hazard rate is:
      h(t) = rho\*lambda(lambda\*t)\*\*(**rho-1**)
"""

**Comment by CamDavidsonPilon** [comment]
:ok_hand: mind if you open up a pull request to fix it?

**Comment by benrifkind** [comment]
Yup. I'll do that.
