### ISSUE TITLE
CoxPH and strata base survival functions

### ISSUE THREAD

**Issue by IvanBarrientos** [CamDavidsonPilon/lifelines#210]
Perhaps I've missed something, but it seems that when using the strata option in CoxPHFitter's fit() method, we don't get different base hazards output for each strata.

Using R's survival library, if we apply 'strata' in coxph() to train a model and call the result "fit",  then the results of basehaz(fit) have n-many baseline hazard sets where n is the number of values in the strata. On the other hand, 'base_cum_hazard' in Lifelines seems to output only one strata.

For example, if a timeline has 365 points and the strata variable has 3 values, then basehaz(fit) will have 3*365 points whereas 'base_cum_hazard' will only have 365 points.

The feature coefficients (and their stats, e.g. se and concordance) are the same in R and Lifelines - assuming that normalize=False in the latter. It's just the baseline hazards I'm curious about.

**Comment by CamDavidsonPilon** [comment]
@IvanBarrientos this open PR is probably want you want, right? https://github.com/CamDavidsonPilon/lifelines/pull/196

Can you confirm that gives the correct functionality?

**Comment by IvanBarrientos** [comment]
Ah yes, the original PR is what I'm seeking - apologies I didn't do more
due diligence here. I'll try to compare jstoxrocky's code with some of R's
results in order to see if functionality is looking good.
