### ISSUE TITLE
Weibull fit should have summary function like Cox fit

### ISSUE THREAD

**Issue by dugusanfeng** [CamDavidsonPilon/lifelines#224]

**Comment by CamDavidsonPilon** [comment]
Hey @dugusanfeng, can you provide an example of what you would like to see in a summary function?

**Comment by dugusanfeng** [comment]
![201620122709647616](https://cloud.githubusercontent.com/assets/12732760/12601407/c3cdb2d4-c4db-11e5-8046-a00c6dac7f86.png)

I got some results in R  using weibull fit,but some important results not in weibull fit model in lifelines

**Comment by CamDavidsonPilon** [comment]
@dugusanfeng what do you think of https://github.com/CamDavidsonPilon/lifelines/pull/231?
