### ISSUE TITLE
Interest in forecasting for specific timepoints?

### ISSUE THREAD

**Issue by raderaj** [CamDavidsonPilon/lifelines#226]
@CamDavidsonPilon I really enjoy your work on this package and have been using it since version 0.3. In one of my particular use cases, I found that it is desirable to return the survival prediction at one (or many) specific future time point(s). For example forecasting 1 year into the future. Is this something that is of general interest and should be added into this code base? So far I've been applying this within the context of the CoxPH fitter but imagine it could be generalized to other fitters too.

**Comment by CamDavidsonPilon** [comment]
Hey @raderaj, yea that's definitely something desireable. It's something that is not easy (perhaps not even _correct_) to do with a model like Kaplan-Meier or Nelson Aalen. For regression fitters, yea this can be added easily. Thanks for the suggestion!

**Comment by labreu** [comment]
I don't know if my questions fits this Issue. But here it goes:

I am predicting the lifecicle in minutes of a machine before it needs maintenance (preventive repair). My data has many cicles (birth is when it receives maintenance and death is when it breaks or needs maintenance) and I'm using the CoxPHFitter to train and I'm leaving one cicle out for testing. The results of the predictions are amazing! Very accurate.
But now I'm testing for production environment and it always predicts the end of the input cicle as death. Is this the way the algorithm tells me that the lifecicle goes beyond that point? Does the CoxPH algorithm supports long time predictions after the end of my input?

Thank you,
Lucas

**Comment by CamDavidsonPilon** [comment]
> But now I'm testing for production environment and it always predicts the end of the input cicle as death. 

this is strange behaviour. Can you show me 1) what version of lifelines you are using and 2) the code/functions you are using the make the prediction?

**Comment by labreu** [comment]
The version in the version.py file is '0.9.0.0'.

I'm using:
cf.predict_median(test)     
cf.predict_expectation(test)

**Comment by CamDavidsonPilon** [comment]
Predicting future times points was added in master https://github.com/CamDavidsonPilon/lifelines/pull/333
