### ISSUE TITLE
Predicting only one row

### ISSUE THREAD

**Issue by labreu** [CamDavidsonPilon/lifelines#227]
Hello,
firstly I'd like to congratulate you and tell you that you have done a really good work in this package.

I'm trying to test on a dataset that looks like this:
![capture](https://cloud.githubusercontent.com/assets/10853158/13222363/70293ecc-d95e-11e5-95d1-41a4f7dcc349.PNG)
The last columns are 'category', 'lifetimes'(T) and 'observed'(E). 
- My code is as follows and works fine:
  cf = CoxPHFitter()
  cf.fit( auxDF, 'T', event_col='E', strata = ['category'])
  r = cf.predict_median(coxDF.ix[ 0: 1, :8 ])   #two lines of testing (indices 0 and 1) until the 8th column
- But when I try to predict only one line:
  r = cf.predict_median(coxDF.ix[ 1, :8])   #one line of testing (index 1)
- I get the error:
  ValueError: Shape of passed values is (1, 1), indices imply (1, 8)

Any idea what am I doing wrong? I've tried creating another DF, np.array(in the right order), nothing works.

Thank you!

**Comment by CamDavidsonPilon** [comment]
interesting, thanks for the bug report. 

I think the difference is that `.ix[ 0: 1, :8 ]` returns a Dataframe (of size (2, 8)), and `.ix[1, :8]` returns a Series of size (8,). Kinda lame that lifelines will fail on this. 

For now, you can do `.ix[[1], :8]` (note the [] included)

**Comment by labreu** [comment]
Thank you!

- This line worked:
cf.predict_median(coxDF.ix[ [0], :8])

- This didn't work
cf.predict_median(coxDF.ix[ [1], :8])

- This works and returns me the result 4 times:
cf.predict_median(coxDF.ix[ [1,1], :8])

**Comment by CamDavidsonPilon** [comment]
Very stange that `cf.predict_median(coxDF.ix[ [1], :8])` didn't work - what is the error message? Also, what is the index of your dataframe?

**Comment by IvanBarrientos** [comment]
I'm wondering if basic questions like this may be better-suited for
stackoverflow. For example, code snippets, data snapshots, and error
messages could be provided so that the community may suggest solutions.

**Comment by CamDavidsonPilon** [comment]
It's a lifelines problem, so I think it's appropriate to put here as well

**Comment by IvanBarrientos** [comment]
ah cool, sounds good.

**Comment by labreu** [comment]
Problem solved with:

testDF = pd.DataFrame(columns = [..my8columns..])
testdf.loc[0] = np.array( OriginalDF.ix [n, :8] )
result = cf.predict_median(testdf)

**Comment by gpras** [comment]
What function do I need to call to know the predicted median time and its corresponding probability? I would like to know when does my predicted survival function crosses 0.5 first time.

**Comment by CamDavidsonPilon** [comment]
@gpras I don't think that question is valid, in a frequentist framework at least. 

The predicted survival curve does or does not cross 0.5, there is not way to attack a probability to it. 

> I would like to know when does my predicted survival function crosses 0.5 first time.

This is exactly the median, which is finite if the curve crosses 0.5, and infinite if the curve never crosses.

**Comment by gpras** [comment]
@CamDavidsonPilon - Is there a way I can input specific event_at (specific time) while using the function predict_survival_function in Cox's regression
