### ISSUE TITLE
Plot() issues

### ISSUE THREAD

**Issue by seungwonyang** [CamDavidsonPilon/lifelines#228]
Thank you for creating this nice package.   I'm following the very first code example in the quick start guide, but kmf.plot() does not show any plots, even though kmf.survival_function_ generates KM_estimates.  It did not generate any error messages, either.  I'll appreciate any hint regarding this issue,

**Comment by CamDavidsonPilon** [comment]
are you using this from ipython shell? Do other plots work?
```
plt.plot(range(10))
```

Does that show anything?

**Comment by seungwonyang** [comment]
Thanks for the prompt reply.   I'm using Python 2.7.10 on Mac OSX 10.11.   If I also do plt.show() following plt.plot(range(10)), I see a plot:
-----------------
>>> from matplotlib import pyplot as plt
>>> plt.plot(range(10))
[<matplotlib.lines.Line2D object at 0x1138d8f50>]
>>>plt.show()
-----------------

**Comment by CamDavidsonPilon** [comment]
Did you try:
```
kmf.plot()
plt.show()
```

?

**Comment by seungwonyang** [comment]
Now it shows the plot
`from lifelines.datasets import load_waltons
from lifelines import KaplanMeierFitter
from matplotlib import pyplot as plt

df = load_waltons()
T = df['T']
E = df['E']
kmf = KaplanMeierFitter()
kmf.fit(T, event_observed=E)
s = kmf.survival_function_
kmf.median_
kmf.plot()
plt.show()`
Thank you!

**Comment by ToadTWP666** [comment]
Us there a way to use the fitted model to determine the survival probability for a new data point that was not used to fit the model? For example if I want to determine the probability of survival for a duration of 55 but not use the plot to determine the probability of survival value. Is there a function to do this that is part of lifelines?

**Comment by CamDavidsonPilon** [comment]
There is a `predict` method on the `KaplanMeierFitter` that can be used.

**Comment by liulumiere** [comment]
thank you very much！
