### ISSUE TITLE
logrank_test.print_summary to file?

### ISSUE THREAD

**Issue by pjadzinsky** [CamDavidsonPilon/lifelines#230]
Hi,

I'm new to lifelines, thanks for an awesome package!. I'm interested in sharing the results of logrank_test and can't find how to export to a file. Assuming I'm not missing anything obvious, would a PR accepting optional parameters for a file be welcome?

Thanks

**Comment by CamDavidsonPilon** [comment]
Hey there, an interesting idea, however what do you think of using `fitter.summary`, returning a df, and saving that to a file?

**Comment by pjadzinsky** [comment]
That works for me, 

Thanks for the advice.
