### ISSUE TITLE
Classes and methods description

### ISSUE THREAD

**Issue by superciccio14** [CamDavidsonPilon/lifelines#235]
Hi, on the official doc the link to module index is broken http://lifelines.readthedocs.io/en/latest/py-modindex.html

Where can I find a full description of classes and their methods?

**Comment by CamDavidsonPilon** [comment]
Hey there, hm I wasn't aware that link existed. For now, the only place to see a full list is in the code base. Is there something I can help you find?

**Comment by superciccio14** [comment]
Hi @CamDavidsonPilon. Not really, I was just looking for a human readable overview of lifelines. Thank you anyway : )
