### ISSUE TITLE
No print_summary for aaf?

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [CamDavidsonPilon/lifelines#251]
Why is there is no `print_summary` function for `AalenAdditiveFitter` like there is for `CoxPHFitter`? Wouldn't it make the API of `lifelines` more consistent if they both had print_summary's?

**Comment by CamDavidsonPilon** [comment]
Hey there, yes however I'm not sure what it would print out! The CoxPH summary is clear (scalar parameter's + their statistics), but the AAF, we don't have scalar parameters, but a time series of parameters. 

What would you like to see in the print_summary?

**Comment by CamDavidsonPilon** [comment]
Hey there, yes however I'm not sure what it would print out! The CoxPH summary is clear (scalar parameter's + their statistics), but the AAF, we don't have scalar parameters, but a time series of parameters. 

What would you like to see in the print_summary?

**Comment by absolutelyNoWarranty** [comment]
I'm new to survival analysis so I don't really know what a print_summary of AAF should look like. 

The R package `timereg` has documentation which states

> summary.aalen Prints summary statistics
> Description
> Computes p-values for test of significance for nonparametric terms of model, p-values for test of
> constant effects based on both supremum and integrated squared difference.
> Returns parameter estimates and their standard errors.

Maybe that kind of summary would work for `lifelines` as well?

**Comment by springcoil** [comment]
https://github.com/CamDavidsonPilon/lifelines/issues/234 related
