### ISSUE TITLE
What is frailty?

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [CamDavidsonPilon/lifelines#253]
Currently the introduction reads 

> So why did the combination of both regimes have a decreasing hazard? This is the effect of frailty, a topic we will discuss later.

except frailty is never again discussed.

**Comment by CamDavidsonPilon** [comment]
Oh neat, thanks for bringing this up. I'll leave this issue open for myself (or others) to update the docs.

**Comment by liujimj** [comment]
Are there any plans to implement frailty models?
