### ISSUE TITLE
KaplanMeierFitter.plot() ignores `flat` argument

### ISSUE THREAD

**Issue by TCAllen07** [CamDavidsonPilon/lifelines#255]
I ran into this accidentally while trying to recreate the stepped-style plot elsewhere and found that the value passed for `flat` seemed to be ignored, and the resulting plot is always stepped/flat.

In case it was related to the data I was using, I recreated it with the political regimes dataset from `lifelines.datasets.load_dd()`. Below are snippets of the plot command used for each resulting graph in the image.

``` python
data = lifelines.datasets.load_dd()
kmf = lifelines.KaplanMeierFitter()
kmf.fit(data['duration'], data['observed'])
kmf.plot(ci_show=False, show_censors=True, flat=False, title='Flat False')  # title lengthened later
kmf.plot(ci_show=False, show_censors=True, flat=True, title='Flat True')  # title lengthened later
```

I dug into it a bit myself, but don't see that `plt.step()` is even ever called; in fact `matplotlib.pyplot.step()` defaults its `where` parameter to `'pre'` and I had to explicitly call `step(..., where='post')` to get it to match the default results from `kmf.plot()`. My only guess is whether it's related to calling `fill_between()` like an unintended side effect or something. 

![screen shot 2016-09-23 at 6 09 37 pm](https://cloud.githubusercontent.com/assets/1156198/18802923/eb88cc6e-81b9-11e6-8357-c9e647935b00.png)

**Comment by CamDavidsonPilon** [comment]
👌 I'll take a look at this problem this weekend, thanks for bringing it up!

**Comment by CamDavidsonPilon** [comment]
> while trying to recreate the stepped-style plot elsewhere 

lifelines by default will create a step-styled plot (thinking about it, "flat" is then a very misleading name).

Looking at what `flat` flag does:
 1. `ci_force_lines = True`, but you have `ci_show=False` so this does nothing.
 2. `show_censors = True`, but you specify `show_censors=True` anyways.

So what is the value in `flat`? I'm not sure anymore, it sounds like it just caused confusion. I'm thinking now to drop support for that (redundant) flag. 

Does that help?
