### ISSUE TITLE
time-dependent cox regression model

### ISSUE THREAD

**Issue by zerchow** [CamDavidsonPilon/lifelines#258]
will you implement time-dependent cox regression model? This is more meaningful than pure cox regression model.

**Comment by CamDavidsonPilon** [comment]
This is planned for the next release, and I'll likely start late next week. 

 - [ ] https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf
 - [ ] http://www.math.ucsd.edu/~rxu/math284/slect7.pdf
 - [ ] http://www.annualreviews.org/doi/pdf/10.1146/annurev.publhealth.20.1.145
 - [ ] https://socialsciences.mcmaster.ca/jfox/Books/Companion/appendix/Appendix-Cox-Regression.pdf
