### ISSUE TITLE
Mortality.Org Data

### ISSUE THREAD

**Issue by ncdingari** [CamDavidsonPilon/lifelines#266]
Is there a way to plot mortality.org data. It is in the form of 

http://www.mortality.org/hmd/GBR_NP/STATS/Deaths_1x1.txt

Year     Age        Female             Male              Total
1922      0          31303.00         42762.19         74065.19
1922      1          11301.00         12646.07         23947.07
1922      2           5192.00          5699.03         10891.03
1922      3           2182.00          2325.01          4507.01
1922      4           1443.00          1427.01          2870.01
1922      5           1349.59          1342.82          2692.41
1922      6           1123.56          1215.78          2339.34
1922      7            980.75          1028.37          2009.12
1922      8            816.20           908.59          1724.79
1922      9            763.90           790.46          1554.36
1922     10            748.21           734.19          1482.40
1922     11            686.67           727.76          1414.43
1922     12            769.67           697.35          1467.02
1922     13            829.19           740.01          1569.20
1922     14            910.26           854.71          1764.97
1922     15            979.69           875.51          1855.20
1922     16           1073.96          1042.72          2116.68
1922     17           1092.91          1168.36          2261.27
1922     18           1160.55          1240.44          2400.99
1922     19           1235.89          1346.99          2582.88
1922     20           1321.07          1387.05          2708.12
1922     21           1327.81          1308.97          2636.78
1922     22           1333.27          1376.86          2710.13
1922     23           1317.47          1281.69          2599.16
1922     24           1392.39          1350.45          2742.84
1922     25           1390.25          1224.14          2614.39
1922     26           1379.01          1261.68          2640.69

**Comment by CamDavidsonPilon** [comment]
mm this is population per year? Without thinking about it too much, I can't see a way to convert population tables to survival curves. Is there any other data (like births/deaths) that we can use?

**Comment by ncdingari** [comment]
This is Deaths by year

**Comment by CamDavidsonPilon** [comment]
I don't think lifelines is the correct lib to use for this. You can take the `q(x)` in your table an construct the survival curve from that: S(x) = product(q(i), i<x) (I think that's correct)
