### ISSUE TITLE
ci_force_lines=True ci_legend=False is buggy

### ISSUE THREAD

**Issue by erichu8** [CamDavidsonPilon/lifelines#267]
When you try to plot the 95% CI without their legend, the library behaviour is buggy and does not produce the required results -- basically the labels are always plotted...

kmf.plot(ax=ax, ci_force_lines=True, ci_legend=False) 

ax.legend_=None works but it destroys all legends, including the main one...

![screen shot 2016-12-26 at 6 19 04 pm](https://cloud.githubusercontent.com/assets/21008168/21487484/db320e70-cb97-11e6-83a5-6d72b7b44d83.png)
![screen shot 2016-12-26 at 6 19 21 pm](https://cloud.githubusercontent.com/assets/21008168/21487485/e12b84b4-cb97-11e6-977f-2ba76cb24d5f.png)

**Comment by CamDavidsonPilon** [comment]
Thanks for the report. I've fixed this in a recent commit. Here are is the output:


```
from lifelines import KaplanMeierFitter

kmf = KaplanMeierFitter()

kmf.fit(arange(100))
kmf.plot(ci_force_lines=True, ci_legend=False)
```

<img width="936" alt="screen shot 2016-12-28 at 17 43 38" src="https://cloud.githubusercontent.com/assets/884032/21533129/5e5501a2-cd25-11e6-9a25-e1faffa330a4.png">
