### ISSUE TITLE
Ties in Aalen Additive Fitter?

### ISSUE THREAD

**Issue by IvanBarrientos** [CamDavidsonPilon/lifelines#276]
Does the current AalenAdditiveFitter handle tied observations? I don't see an explicit mention of this, but am curious (not urgent!). Note that in R ties are handled by a randomized scheme:
From http://finzi.psych.upenn.edu/library/timereg/html/aalen.html:
"The program assumes that there are no ties, and if such are present random noise is added to break the ties."

**Comment by CamDavidsonPilon** [comment]
Hey, it looks like I let Python handle this (which is a bit too implicit): https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/aalen_additive_fitter.py#L146

Python will do whatever it feels like with ties. It's probably not too hard to add some custom logic here though.

**Comment by IvanBarrientos** [comment]
Thanks! argsort's indexing method seems like a sensible default to ties.
