### ISSUE TITLE
patsy with Aalen Additive Fitter

### ISSUE THREAD

**Issue by ncdingari** [CamDavidsonPilon/lifelines#282]
When I run
`Xtest = patsy.dmatrix('Variable1 + Variable2 -1', data = testData, return_type='dataframe')`

Number of rows are being dropped, number of rows in Xtest is less than testData. When we do one-hot-encoding, this won't happen. If I do one-hot-encoding and try to input to 
`testPred = aaf.predict_survival_function(Xtest.ix[1:10])`
 is not working

**Comment by CamDavidsonPilon** [comment]
Hey @ncdingari 
> Number of rows are being dropped, number of rows in Xtest is less than testData.
is this a problem with lifelines, or Patsy?

Can you produce a script with a reproducible error?
