### ISSUE TITLE
Interval Censored Survival Analysis

### ISSUE THREAD

**Issue by ncdingari** [CamDavidsonPilon/lifelines#283]
Are you planning to implement "interval" censored Survival analysis in future?

**Comment by CamDavidsonPilon** [comment]
Hey there, no immediate plans no

**Comment by CamDavidsonPilon** [comment]
Dropping this here for future research: https://www.r-project.org/conferences/useR-2010/tutorials/Fay_1.pdf

**Comment by abossenbroek** [comment]
Do you need support to start embedding this?

**Comment by CamDavidsonPilon** [comment]
That would be great! My focus has been on Cox Models recently, so I haven't thought much about this yet

**Comment by CamDavidsonPilon** [comment]
So version 0.21.0 (just released) has initial support for _parametric_ models of interval censoring. Here's an example: https://dataorigami.net/blogs/napkin-folding/counting-and-interval-censoring

Next is to do non and semi parametric models, but that's for the medium-term future.
