### ISSUE TITLE
Survival function constant

### ISSUE THREAD

**Issue by elenina5** [CamDavidsonPilon/lifelines#287]
Hi! Thank you very much for this amazing package! 

Is it normal that I get constant survival function with this hazard function?
![surv](https://cloud.githubusercontent.com/assets/26309516/25506281/c07703cc-2b9d-11e7-9a02-9b82ec3c7a74.png)

This is my code: `
```
cfTransplant = CoxPHFitter(normalize = False)
cfTransplant.fit(df = pdTransp.iloc[2:len(pdTransp)-1], duration_col = 'Survival_Time', event_col='NotCensored', show_progress=True, include_likelihood=True)
cfTransplant.print_summary()
fig, axes = plt.subplots(nrows=1, ncols=2, squeeze=False, sharex=True)

cfTransplant.baseline_cumulative_hazard_.plot(ax=axes[0,0], legend=False
                ,title='Baseline cumulative hazard rate')
cfTransplant.baseline_survival_.plot(ax=axes[0,1], legend=False
                ,title='Baseline survival rate')

```

**Comment by CamDavidsonPilon** [comment]
Hey there, 


hm, strange. Are you able to provide the data set just prior to the call to `.fit`? That would really help debugging.

**Comment by elenina5** [comment]
Sorry, unfortunately I  cannot share the data. 
But the weird thing is that if I do  normalize, thus I write: 
`cfTransplant = CoxPHFitter(normalize = False)`

I get the following: 
![surv](https://cloud.githubusercontent.com/assets/26309516/25508162/1eac2f4e-2ba8-11e7-9222-8030e4c698f9.png)

**Comment by CamDavidsonPilon** [comment]
Likely fixed in https://github.com/CamDavidsonPilon/lifelines/pull/293
