### ISSUE TITLE
comparing AAF and Cox

### ISSUE THREAD

**Issue by disimone** [CamDavidsonPilon/lifelines#289]
Hi,

first of all, thanks for this library. I am fitting both an AAF and a Cox model on my data, and I wanted to compare the results.

I noticed that the Cox predictions are always very different from the AAF ones. Once I translate everything into survival probabilities, I also compare to a plain KM measurement, and AAF agrees with KM, Cox does not.

My first explanation was that my data does not obey the multiplicative assumption and I was ready to let it go, but then I plotted the Cox baseline prediction and the "total" prediction, and they are just identical, which seem to point to the partial hazards not being properly taken into account. Is this a known bug/issue?

Any hints on how I could debug this further?

Thanks for your help,

Andrea.

**Comment by disimone** [comment]
Hi all,

for the record, I just wanted to report that I found the error. It is related to the fitter de-meaning features, which by definition set them to 0 on the average dataset.

If I properly use the normalize=False option, everything runs smoothly.

This means, however, that there is no way to plot a lifetime curve for the average dataset with the default normalization procedure. Or am I missing anything?

Thanks for your help,

Andrea.

**Comment by CamDavidsonPilon** [comment]
Ah yes, `normalize=True` is something that most users don't notice (it is set to True to help with stability). Thanks for following up. 

> This means, however, that there is no way to plot a lifetime curve for the average dataset with the default normalization procedure. Or am I missing anything?

We do retain the mean and std. values as we normalize and use them in future `predict_` functions, so it should just work™ - but maybe I am missing you usecase.

**Comment by aclutes** [comment]
I noticed a similar issue to disimone and I think I've discovered the root cause. In the COXPHFitter class, the baseline hazards are being computed within the fit function. This passes in a version of the data set which has already been normalized. This is an issue because with the compute_baseline_hazard function, the first step is to calculate partial hazards, which normalizes the data again.

I think the solution is just to add an unnormalize step in the fit function, making line 321 something like:

        self.baseline_hazard_ = self._compute_baseline_hazards(unnormalize(df,self._norm_mean,self._norm_std), T, E)

**Comment by CamDavidsonPilon** [comment]
Interesting, let me experiment with this this weekend!

**Comment by CamDavidsonPilon** [comment]
Looks like this was the issue. I've taken steps to completely remove `normalize`, so this shouldn't happen again. 

Fixes in https://github.com/CamDavidsonPilon/lifelines/pull/293

**Comment by disimone** [comment]
Hi,

can I ask what did you acttually do to "remove normalize"? I am running with 0.10.0, and the Cox prediction on the mean dataset is now *very* off from the KM measurement.

Just to be clear, here are my steps:

1) prepare the data, scaling the continuous variables with sklearn's minmaxscaler
2) pass the data through patsy and prepare the input to lifelines
3) fit a cox model
4) perform a KM mesurement
5) obtain the mean matrix (myPatsyMatrix.mean()) and ust it to predict the Cox lifetime
6) plot the cox prediction on the KM measurement

With the previous version of lifelines, things were ok as long as I specified "normalize=False". Now the cox prediction and the KM measurement are significantly off.

Am I doing anything wrong?

Thanks for your help,

Andrea.

**Comment by disimone** [comment]
Hi,

I had a look at the changes in 0.10.0, and I am not sure I understand what is being done.

What I see in the code is:

1) you apply some transformation to the inputs (using `utils.normalize(fitData, fitDataMean, fitDataStd)`) and fit the model
2) at prediction time, the user gives you a set of values for the features of the model. What should happen now is that you use the same transformation you used before fitting, e.g. `utils.normalize(newData, fitDataMean, fitDataStd)`, then feed the result to the calculation.

If I follow the execution flow starting e.g. from CoxPHFitter::predict_survival_function, I can't really see where you apply the transformation to the inputs X. Or am I misunderstanding the code?

Andrea.

**Comment by CamDavidsonPilon** [comment]
hm, I tried to make it so the dataset doesn't need to be normalized at all except during fitting (but then I unnormalize the coefficients back) - okay I think I need to rethink the `predict_` parts. Thanks for bringing this up!

**Comment by disimone** [comment]
Just to mention that I opened also #294, with basically the same information. The only consideration missing in this issue, which I think would be important for me to understand, it that, assuming all transformations are done correctly, when predicting on a point that is exactly the mean of the fitted dataset, all partial hazards do not contribute anymore, and the only relevant term is the baseline. Doesn't this mean that the baseline survival from cox should be fairly similar to KM's measurement?

sorry for the duplicate issue, feel free to close one of the two :)
