### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity - when looping over KaplanMeierFitter()

### ISSUE THREAD

**Issue by AnaCnGarcia** [CamDavidsonPilon/lifelines#290]
#Hi!

I'm doing some Survival Analysis and it works fine when I don't put things on a loop, but, when I do, it simply shoes this ValueError I can't solve.

Code is bellow. Thank yo so much!

```python
for city in city:
    kmf = KaplanMeierFitter()
    city=city
    ix = (City == city)
    T = dat_final["lifetime_completed_trips"]
    E = dat_final["Churn_28d"]
    kmf.fit(T[ix], E[ix])
    ax=kmf.median_
    df2=pd.DataFrame(kmf.survival_function_)
    df2['city']=city  
```

**Comment by CamDavidsonPilon** [comment]
@AnaCnGarcia  (I cleaned up your code snippet btw)

Can you post the ValueError you receive?

**Comment by AnaCnGarcia** [comment]
Hey, @CamDavidsonPilon , thanks for the quick heads-up=D

The error I got is bellow:


/home/udocker/phoenix-worker/environments/python2/local/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by CamDavidsonPilon** [comment]
Can you post more of the stacktrace? I want to see where in lifelines the problem starts.

**Comment by AnaCnGarcia** [comment]
Cure! This is all that came out:

ValueErrorTraceback (most recent call last)
<ipython-input-457-8b213ced9260> in <module>()
     10         T = city_data["lifetime_completed_trips"]
     11         E = city_data["Churn_56d"]
---> 12         kmf.fit(T, E)
     13         ax=kmf.median_
     14         df5=pd.DataFrame(kmf.survival_function_)

/home/udocker/phoenix-worker/environments/python2/local/lib/python2.7/site-packages/lifelines/fitters/kaplan_meier_fitter.pyc in fit(self, durations, event_observed, timeline, entry, label, alpha, left_censorship, ci_labels)
     45         # if the user is interested in left-censorship, we return the cumulative_density_, no survival_function_,
     46         estimate_name = 'survival_function_' if not left_censorship else 'cumulative_density_'
---> 47         v = _preprocess_inputs(durations, event_observed, timeline, entry)
     48         self.durations, self.event_observed, self.timeline, self.entry, self.event_table = v
     49         self._label = label

/home/udocker/phoenix-worker/environments/python2/local/lib/python2.7/site-packages/lifelines/utils/__init__.pyc in _preprocess_inputs(durations, event_observed, timeline, entry)
    624         entry = np.asarray(entry).reshape((n,))
    625 
--> 626     event_table = survival_table_from_events(durations, event_observed, entry)
    627     if timeline is None:
    628         timeline = event_table.index.values

/home/udocker/phoenix-worker/environments/python2/local/lib/python2.7/site-packages/lifelines/utils/__init__.pyc in survival_table_from_events(death_times, event_observed, birth_times, columns, weights)
    179     death_times = np.asarray(death_times)
    180     if birth_times is None:
--> 181         birth_times = min(0, death_times.min()) * np.ones(death_times.shape[0])
    182     else:
    183         birth_times = np.asarray(birth_times)

/home/udocker/phoenix-worker/environments/python2/local/lib/python2.7/site-packages/numpy/core/_methods.pyc in _amin(a, axis, out, keepdims)
     27 
     28 def _amin(a, axis=None, out=None, keepdims=False):
---> 29     return umr_minimum(a, axis, None, out, keepdims)
     30 
     31 def _sum(a, axis=None, dtype=None, out=None, keepdims=False):

ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by CamDavidsonPilon** [comment]
It looks like for some `city`, there are no rows in the dataframe `dat_final` that link to it.

**Comment by AnaCnGarcia** [comment]
Got it!!! I corrected that and now it works =D than you so much!
