### ISSUE TITLE
any reason why kmg.median_ would be inf?

### ISSUE THREAD

**Issue by JonathanJHull** [CamDavidsonPilon/lifelines#296]
Hi,
I've used lifelines before and never had a problem like this.  After fitting to a set of data, the survival function is fine and the plot looks correct, but the median_ value is inf.

Is there any simple explanation for why this might be the case?

Thanks,
Jonathan Hull

**Comment by CamDavidsonPilon** [comment]
Hey, 

It's likely that the survival curve never dips below the 0.5 probability mark, hence there is no finite time where the half population has died. Does that make sense? You should observe this too on the `kmf.plot()`

**Comment by JonathanJHull** [comment]
That's it.  Thanks for the clarification.

**Comment by tsando** [comment]
Thanks for asking and answering this question. However, what does this actually mean then in practical terms?  - if there is not finite time by which half of the population has died. How can one interpret this result or under which circumstances does this tend to happen? Thanks!

**Comment by CamDavidsonPilon** [comment]
Maybe an example would help: most marriages don't end in divorce, hence the median time to divorce doesn't exist.

**Comment by redravioli** [comment]
Hi there, I also have a dataset where the survival curve never reaches the .5 mark - it goes down to about 0.7  So the conditional_time_to_event_ dataset returns inf for every value.  However, given that, is it possible to predict the expected lifetime in any way?  ie given that most marriages don't end in divorce,  if say you get to 1 year, what then is the probability that you will get to 5 years? and if you get to 1 year, is it possible to work out the expected length of the marriage?  
Apologies if this is a stupid question, I am new to survival analysis.

**Comment by CamDavidsonPilon** [comment]
> , if say you get to 1 year, what then is the probability that you will get to 5 years? and if you get to 1 year, is it possible to work out the expected length of the marriage?

This can be done be conditioning on the survival curve. Take a look at the math here: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction
