### ISSUE TITLE
Suggestion for citing

### ISSUE THREAD

**Issue by clerian** [CamDavidsonPilon/lifelines#297]
Hello,

I saw that your citing section doesn't have a DOI included, some journals make it difficult to cite web resources without a DOI. I don't know if you are interested, but you could get one by using the [Zenodo](https://zenodo.org/) service. They automatically update the DOI with each release from the github repository and therefore allow citing specific versions of your package.

Cheers!

**Comment by CamDavidsonPilon** [comment]
Is it possible for you to help me understand why the DOI badge in the readme links to a 404?

**Comment by clerian** [comment]
That's quite strange, clicking the badge works for me. I directly land on the Zenodo page, citing a version from today: Version 2 10.5281/zenodo.815658 	Jun 22, 2017

**Comment by CamDavidsonPilon** [comment]
Oh it works now! nvm =)
