### ISSUE TITLE
concordance index stalls 

### ISSUE THREAD

**Issue by alvarouc** [CamDavidsonPilon/lifelines#303]
For 10,000 samples and no censored data the concordance index never escapes this "While True" loop in `lifelines/utils/__init__.py` line 844

`https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/utils/__init__.py#L844`

**Comment by CamDavidsonPilon** [comment]
Hey @alvarouc, are you able to provide either 
1) the data (actual times, predicted times, and observed) 
2) the call to concordance_index you are making

Either of these would help - I'm unable to reproduce the bug locally.
