### ISSUE TITLE
how to interpret kmf.event_table numbers

### ISSUE THREAD

**Issue by yunkekeke** [CamDavidsonPilon/lifelines#309]
Hi All, 

I was looking at the kmf event table. 
In my data, I have a total of 308 death, however when reading the "total removed" column from the kmf event table, there show a number of 474. 
Does anyone know how to interpret this number?

Thanks.

**Comment by CamDavidsonPilon** [comment]
That is strange... can you provide the dataset you are using? Even emailing it to me? That would help me understand what you are seeing.

**Comment by yunkekeke** [comment]
Sure. How do I send it ?

**Comment by yunkekeke** [comment]
Just sent . Thanks!

**Comment by CamDavidsonPilon** [comment]
"Removed" does not imply death, simply the individual is removed from the population (could be death, or censorship). In some datasets where the current time censor individuals (ex: people alive today), there can be a bunching of removals (censorships) at the latest time. This is the case here. 

So, nothing to worry about. The event_table is used more for internal calculations of the estimate.

**Comment by yunkekeke** [comment]
Hi Cam, there shouldn't be any censorship happening during the observation period in my data. 
In this package, how do we "tag" which row is censored?

**Comment by CamDavidsonPilon** [comment]
> In this package, how do we "tag" which row is censored?

using the second argument in the `fit` command. Ex: `kmf.fit(durations, observed_death)` where `observed_death` is a boolean array the same size as `durations`
