### ISSUE TITLE
KMF curve didn't give the correct survival rate for the last period

### ISSUE THREAD

**Issue by yunkekeke** [CamDavidsonPilon/lifelines#310]
Hi Cam, 
I am comparing the KMF curve from lifeline with the calculation I did in excel and using the R survival package for KMF curve.
The survival rate of the last period is lower than the r result and the excel result. 
I am inspecting the data and I wonder if this could be caused by some missing values in the explanatory variables in my data. 

Could you comment on this?
Thanks.

**Comment by CamDavidsonPilon** [comment]
Can you provide the excel sheet or dataset set? That would help debug.
