### ISSUE TITLE
AttributeError: '_process_plot_var_args' object has no attribute 'color_cycle'

### ISSUE THREAD

**Issue by mjiansun** [CamDavidsonPilon/lifelines#312]
**When i run a official example,** 
from lifelines.datasets import load_waltons
df = load_waltons() # returns a Pandas DataFrame
print df.head()
T = df['T']
E = df['E']
from lifelines import KaplanMeierFitter
kmf = KaplanMeierFitter()
kmf.fit(T, event_observed=E) # more succiently, kmf.fit(T,E)
kmf.survival_function_
kmf.median_
kmf.plot()

**Happened a problem(my matplotlib version 2.0.0):**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-943b97c78566> in <module>()
----> 1 kmf.plot()

/usr/local/lib/python2.7/dist-packages/lifelines/plotting.pyc in plot(ix, iloc, flat, show_censors, censor_styles, ci_legend, ci_force_lines, ci_alpha, ci_show, at_risk_counts, bandwidth, **kwargs)
    289 
    290         set_kwargs_ax(kwargs)
--> 291         set_kwargs_color(kwargs)
    292         set_kwargs_drawstyle(kwargs)
    293 

/usr/local/lib/python2.7/dist-packages/lifelines/plotting.pyc in set_kwargs_color(kwargs)
    226     else:
    227         kwargs['color'] = coalesce(kwargs.get('c'), kwargs.get('color'),
--> 228                                    next(kwargs["ax"]._get_lines.color_cycle))
    229 
    230 

AttributeError: '_process_plot_var_args' object has no attribute 'color_cycle'

**Comment by CamDavidsonPilon** [comment]
Hey @mjiansun, was this not a problem anymore?
