### ISSUE TITLE
Is there another way to caculate p-value just like the way in R?

### ISSUE THREAD

**Issue by YanceyWang** [CamDavidsonPilon/lifelines#314]
In R we get p value 

a=rt[,"expression"]<median(rt[,"expression"])
diff=survdiff(Surv(futime, fustat) ~a,data = rt)
pValue=1-pchisq(diff$chisq,df=1)
pValue=round(pValue,5)

In lifelines I can get p value same as in R using logrank_test. Can provide the same function in lifeline?

**Comment by CamDavidsonPilon** [comment]
Hey @YanceyWang, I'm not sure I understand your question. 

> In lifelines I can get p value same as in R using logrank_test

yes should should be able to use `logrank_test`

> Can provide the same function in lifeline?

I'm not sure what function you are requesting..

**Comment by YanceyWang** [comment]
@CamDavidsonPilon Thanks for your response and sorry for my English 
I open this issue because I get the different p calue in python way and R way.
yes, In python I use logrank_test in lifeline.
and In R, the code is as follows:

a=rt[,"expression"]<median(rt[,"expression"])
diff=survdiff(Surv(futime, fustat) ~a,data = rt)
pValue=1-pchisq(diff$chisq,df=1)
pValue=round(pValue,5)


I am not farmilliar with R, and I just want lifeline can provide a method that return same p value as R which uses the above code.
So the key point is R code above ....Hope I make it clear.

**Comment by CamDavidsonPilon** [comment]
To help debug, can you provide the dataset either here, or by email?

**Comment by YanceyWang** [comment]
@CamDavidsonPilon Sorry for late reply. I have pushed my demo to  [Github](https://github.com/YanceyWang/survival_curve/tree/master), the data and pics in python and R also are there. you can check it. Thanks

**Comment by CamDavidsonPilon** [comment]
This is great - is it possible to add the R script too?

**Comment by CamDavidsonPilon** [comment]
I am pretty confident the issue it because in the R script you are using `median` (value of 324.1), whereas in the Python script you are using `mean` (value of 570.5).
