### ISSUE TITLE
Versions 0.10.1+ not backwards compatible for scoring if originally trained with normalize=False

### ISSUE THREAD

**Issue by dashaw** [CamDavidsonPilon/lifelines#315]
When using a version >= 0.10.1 of Lifelines for prediction of a CoxPHFitter object, it is assumed the object has a value for self._norm_mean. When that object was originally trained using a prior version of Lifelines with normalize=False, it will not have this attribute and therefore will fail. The function predict_log_partial_hazard should contain a logic check to resolve this issue.

For what it is worth, I'm more than happy to add the logic in myself and create a pull request. Let me know.

**Comment by CamDavidsonPilon** [comment]
Hey @dashaw, interesting issue. Is it not possible to retrain the model? I'm not a fan of supporting previous serialised versions, and especially in this case: the rabbit hole could go deep.

**Comment by dashaw** [comment]
Thanks for the response @CamDavidsonPilon. Unfortunately, it would take some serious effort to retrain the set of models I'm continuing to use from 0.9.4. I understand your hesitation. I'm a pretty frequent user of the package, specifically making use of CoxPHFitter. I'm wondering if there's anything to be done such that I could maintain a single version of Lifelines in my environment, leverage the great additions in 0.10.1+, but also be able to score my models from versions past. This also seems like a possible scenario for other users that wish to upgrade.

**Comment by CamDavidsonPilon** [comment]
> I'm wondering if there's anything to be done such that I could maintain a single version of Lifelines in my environment, 

One solution would be to fork the current master and make the changes in your forked repo. Pip can target specific branches on a github repo. I would suggest this.

**Comment by dashaw** [comment]
Absolutely, I was hoping to avoid a custom fork :) as I thought it bad to diverge from the project.
