### ISSUE TITLE
Can Aalen's handle multiple observations for the same 'person' 

### ISSUE THREAD

**Issue by cliffordgreen** [CamDavidsonPilon/lifelines#326]
ie can we use time dependent covariates with Aalen's Additive in this implementation?

**Comment by CamDavidsonPilon** [comment]
I don't quite understand the question, can you provide an example of what you mean please?

**Comment by cliffordgreen** [comment]
Sorry let me clarify, can you run time depending convariates with
lifelines? For example if person A stops taking meds halfway through the
trial, normally you'd represent that as two oberservations with the same
'ID' each with there own time segment, one for the period when A was on
meds and one for the period when they stop taking them

**Comment by CamDavidsonPilon** [comment]
@cliffordgreen getting back to this: it's possible to do this with Aalen's Additive model with time varying covariates. The format for the dataset should be different than normal though. Example: https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/aalen_additive_fitter.py#L64-L88. Keep in mind this part of the library is experimental. 

I don't suggest turning that individual into _two_ unique people, if that's what you are suggesting.
