### ISSUE TITLE
Tick marks for censored patients

### ISSUE THREAD

**Issue by BloodChiefStromberg** [CamDavidsonPilon/lifelines#346]
It would be awesome if the KMF supported adding tick marks out of the box. Can't seem to find a way to add them now.

**Comment by CamDavidsonPilon** [comment]
Hey, you can using `show_censors=True` in the call to `plot`: https://lifelines.readthedocs.io/en/latest/Examples.html#show-censorships

**Comment by BloodChiefStromberg** [comment]
Killer, thank you. I was surprised when I couldn't seem to find the option. The vocabulary that I seem to see other sites use for this are "tick marks" or "censors". I saw you opened another issue which might intended to increase the discoverability of this as well. Thanks for the sweet package!
