### ISSUE TITLE
AalenAdditiveFitter fit is extremy slow for large matrices

### ISSUE THREAD

**Issue by aparij** [CamDavidsonPilon/lifelines#35]
if X is large like (500k,4) , the fit method will loop over all of them ... despite the fact 99% of them the are censored.
in estimation.py the loop that I'm talking about starts on line 320 
        for i, time in enumerate(sorted_event_times):

The algebra is way beyond my understanding :) maybe I missing something but why sorted_event_times is so large ?

**Comment by CamDavidsonPilon** [comment]
This is improved in v0.15
