### ISSUE TITLE
Accessing the covariance-variance matrix of the Cox PH fitter 

### ISSUE THREAD

**Issue by springcoil** [CamDavidsonPilon/lifelines#353]
I've been attempting to get the Schoenfeld residuals implementation from here https://github.com/MustafaOguz/Survival_Analysis/blob/master/3_Semi-Parametric_Models.ipynb (around line 16) to work. I've even put it in my forked version of lifelines.

However a blocker I have is that I'm unable to access the `cf.covar()` part. Was this ever in the code, I can't find references? 

Do you have an alternative implementation in mind?

**Comment by CamDavidsonPilon** [comment]
You can access the hessian at the argmin of the negative log-likelihood with `cf. _hessian_ ` - the inverse of this is an estimator of the asymptotic covariance matrix.
