### ISSUE TITLE
Can COXPH or KaplanMeierFitter predict the probability of the death?

### ISSUE THREAD

**Issue by MilletPu** [CamDavidsonPilon/lifelines#356]
I'm not familiar with the medical and biological science.
Anybody knows how to predict the probability of the survival? I have the survival data including OS_MONTHS and OS_STATUS data.

**Comment by CamDavidsonPilon** [comment]
Yes, both models could do this, but you need to add a condition to your query: 

> predict the probability of the survival _before time T_?

Survival analysis gives us a tool to answer that question. Using the survival curves produced by KaplanMeierFitter or `predict_survival_curve` in a fitted `CoxPHFitter` would work.

**Comment by MilletPu** [comment]
Thank you very much Cameron.
But I didn't find the `predict_survival_curve()` in `CoxPHFitter` in  0.12.0 lifelines packages.
By the way, many appreciations for this gorgeous package which really help me out of R. :>

**Comment by CamDavidsonPilon** [comment]
Whoops, I mean `predict_survival_function`
