### ISSUE TITLE
checking for complete separation should only fire if a column really does separate the event values

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#367]

**Comment by MassMadankumar** [comment]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
A server is already running. Check /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid.
Exiting
