### ISSUE TITLE
Is Cox regression usable without patsy?

### ISSUE THREAD

**Issue by KOLANICH** [CamDavidsonPilon/lifelines#372]
I have tried Cox regression without patsy, it doesn't work. It's a pain to deal with patsy since it transforms the names of columns and adds some unneeded text there. I wonder if it is possible to use it without patsy. What are the exact requirements the DataFrame passed to the fitter in order to make it work?

**Comment by CamDavidsonPilon** [comment]
Hey, yes it is possible (and more commonly used without). Ex:
```python
X = pd.DataFrame(np.random.randn(100, 4))
X['T'] = np.arange(100)
X['E'] = 1

from lifelines import CoxPHFitter
cp = CoxPHFitter()
cp.fit(X, 'T', 'E')
cp.summary
```

All you need is to give it a Dataframe

**Comment by KOLANICH** [comment]
Could you please document the requirements and add a some fuction checking these requirements? Since I have dropped patsy (because of its unpredictability, unresolved bugs and dropped development) and replaced it with a just pandas built-in one-hot encoder, I started getting ```delta contains nan value(s). Convergence halted.```. 

So what are the requirements? Can it deal with lineary dependent columns? Can it deal with missing values?
