### ISSUE TITLE
Implement Schoenfeld residuals

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#373]
http://www.math.ucsd.edu/~rxu/math284/slect9.pdf

**Comment by CamDavidsonPilon** [comment]
http://r.789695.n4.nabble.com/Schoenfeld-Residuals-with-tied-data-td895396.html

**Comment by pzivich** [comment]
Personally, I like the keep-it-in-the-family option. Like you said, it cuts down on computation time. Also it allows something like ``cph.compute_residuals`` which I think would be a great feature to have. Especially with all the different residuals (I remember there being at least 4)

As for users not dealing directly with the residuals, maybe you could have it generate plots instead. You could have something like ``cph.check_assumptions()`` For example, if you implemented martingale residuals, it would generate a plot with a LOESS line. From this, users would easily be able to diagnose functional form issues. Similarly the Schoenfeld residuals would generate a plot with a LOESS curve to see if the points are randomly scatter around zero.

You could also print to the console for helping users to interpret the plots. Maybe something like ``help=True``

The main disadvantage would be the need for creation of LOESS/linear regression fitters for these diagnostic plots

**Comment by CamDavidsonPilon** [comment]
`help=True` is a great idea - I'll definitely add that. So I think I need:

`cph.compute_residuals(df, type='xx')`

and 

`cph.check_assumptions(..., help=True)`

**Comment by ybagdasa** [comment]
@CamDavidsonPilon I'm trying to use compute_residuals on a dataframe with 5M observations and after tens of minutes it is unclear whether it will ever finish computing. I suspect the dataframe is probably too large to do the computation as is in a reasonable amount of time. I'd like to avoid significantly scaling down as events constitute a small fraction of the observations and I need the statistics. Is there an existing solution for this?

**Comment by CamDavidsonPilon** [comment]
@ybagdasa let's start a new issue.
