### ISSUE TITLE
Use iterator/generator to report progress by Cox fitter

### ISSUE THREAD

**Issue by KOLANICH** [CamDavidsonPilon/lifelines#384]

**Comment by CamDavidsonPilon** [comment]
This

**Comment by KOLANICH** [comment]
It `print`s progress, does not report it. Do you feel the difference?  When the progress is reported, it can be processed in own way, not prijting stdout. Currently to process in own wau one has to replace `print` globally (a drastic side effect), then parse the message generated by your library, and in the end restore the original `print`. An extremily ugly way.
