### ISSUE TITLE
KeyError: .... not in index

### ISSUE THREAD

**Issue by KOLANICH** [CamDavidsonPilon/lifelines#385]
[The trace](https://pastebin.com/raw/At8Ahvpi)

**Comment by CamDavidsonPilon** [comment]
Are you able to provide the code snippet or the dataset that caused this?

**Comment by CamDavidsonPilon** [comment]
`self.predict_survival_function(X)[index]`

that should probably be `self.predict_survival_function(X).loc[index]`

**Comment by KOLANICH** [comment]
maybe, but I've found a fatal flaw in my program (I've replaced patsy with get_dummy, everything stopped working, I dug into the code and have found it cannot work with incomplete data, so now I have to create imputting model), so for now there is no sense to publish the script and the dataset.

**Comment by CamDavidsonPilon** [comment]
Curious if you can recall, was `a.cf` trained on `dmat`?

**Comment by KOLANICH** [comment]
What do you mean? Have it been previously trained on dmat? Yes and no - the result of crossvalidation (the exception in process) had no dependence on it, and I guess shouldn't have.

**Comment by CamDavidsonPilon** [comment]
Ah right! I know exactly what happened then. The unique strata groups may not be be the same across the split datasets during k-fold, so the prediction will break. I know exactly how to reproduce this, but not sure on a fix yet.

**Comment by KOLANICH** [comment]
I noticed that such Exception also occurs on prediction of survival curve when predicted hazard is NaN. And the predicted hazards were nans even for the instances belonging to the stratas which the model was trained on.
