### ISSUE TITLE
WeibullFitter Summary Interpretation

### ISSUE THREAD

**Issue by Sandy2904** [CamDavidsonPilon/lifelines#389]
Hi Cam,

I have  fitted WeibullFitter Model from lifelines package for my data based on duration(T) and Event(E), and obtained the summary using wf.print_summary(), I got lambda and rho in the output summary. Can you please let me know  what does lambda and rho represent in the summary. Does lambda and rho represent scale and shape parameters ?If not then wanted to know what are  the  scale and shape parameters for the obtained weibull distribution and how to find it  or else if there is any default parameter for scale and shape..Also it would be very helpful if you can share any resource or link to understand the weibull parameters and summary obtained , because in the lifelines documentation I could not find the same.

Thanks.

**Comment by CamDavidsonPilon** [comment]
Hey @Sandy2904, right this is a problem I've heard before. For now, this is the model: 

```
      S(t) = exp(-(lambda*t)^rho),   lambda > 0, rho > 0,

    which implies the cumulative hazard rate is

      H(t) = (lambda*t)^rho,

    and the hazard rate is:

      h(t) = rho*lambda(lambda*t)^(rho-1)

```

I have an open issue to make this more clear in the documentation: https://github.com/CamDavidsonPilon/lifelines/issues/375. 

There is a nice interpretation of `rho` (here)[https://en.wikipedia.org/wiki/Weibull_distribution#Definition] (though they call it `k`)

**Comment by Sandy2904** [comment]
Thanks cam, so that means lambda is scale parameter and rho is shape parameter right?

Regards,
Sandeep.

**Comment by CamDavidsonPilon** [comment]
that's right

**Comment by Sandy2904** [comment]
Thanks cam..for the update

**Comment by anselmlau** [comment]
Hi Cam, you mentioned that the lambda is one over the scale parameter. Do you mean that when the lambda_ output is 0.05, we should interpret the scale parameter as 1.05? For context, I was expecting lambda_ to be ~1 but the `fit` method outputs ~0.05.

**Comment by CamDavidsonPilon** [comment]
hmm, can you share some code @anselmlau? That doesn't sound correct

**Comment by anselmlau** [comment]
My mistake, the results are correct as described. Thanks!
