### ISSUE TITLE
Weibull 3 parameter

### ISSUE THREAD

**Issue by Sandy2904** [CamDavidsonPilon/lifelines#391]
Hi Cam,

Do we have 3 parameter Weibull distribution a in the lifelines package.

Regards,
Sandeep.

**Comment by CamDavidsonPilon** [comment]
Not atm. Can you provide a reference for it?

**Comment by Sandy2904** [comment]
No am not sure but heard there is a 3 parameter weibull as well...I dont
have any reference....

Regards
Sandeep.

On 12 Jan 2018 7:09 pm, "Cameron Davidson-Pilon" <notifications@github.com>
wrote:

Not atm. Can you provide a reference for it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/CamDavidsonPilon/lifelines/issues/391#issuecomment-357240564>,
or mute the thread

**Comment by murakotaro4** [comment]
Hello
The 3-parameter model is described in the link below.
(shape, scale, **location**)
[https://en.wikipedia.org/wiki/Weibull_distribution](url)
![image](https://user-images.githubusercontent.com/7923699/58305425-03946700-7e33-11e9-8705-f90c305820ee.png)

As an example, when there is a model that does not break below a certain time, the tilt of the Weibull plot becomes a straight line by introducing the location parameter.

It would be very nice if we could guess the location parameter using the maximum likelihood estimation. Commercial software called Minitab has this feature.

2-Parameters
![image](https://user-images.githubusercontent.com/7923699/58305756-39861b00-7e34-11e9-9cdd-1317c870d289.png)

parameters(shape, scale, AD*, failure, right-censored)
AD* is unkown....
![image](https://user-images.githubusercontent.com/7923699/58305810-64706f00-7e34-11e9-8ec2-12328410402e.png)

3-Parameters
![image](https://user-images.githubusercontent.com/7923699/58305735-22dfc400-7e34-11e9-9c62-6a4aecf28e3f.png)

parameters(shape, scale, **location**, AD*, failure, right-censored)
![image](https://user-images.githubusercontent.com/7923699/58305913-aac5ce00-7e34-11e9-92cd-01a1e547f9d8.png)

Regards

**Comment by CamDavidsonPilon** [comment]
That's cool @murakotaro4, let me think about how an API might look like.

**Comment by murakotaro4** [comment]
Thank you for your positive consideration. @CamDavidsonPilon 
I will put a link to help in the calculation.
I'm glad if you can use this as a reference.

[http://www.real-statistics.com/distribution-fitting/distribution-fitting-via-maximum-likelihood/fitting-weibull-parameters-mle/](url)
[http://www.real-statistics.com/distribution-fitting/distribution-fitting-via-maximum-likelihood/weibull-censored-data/](url)

**Comment by CamDavidsonPilon** [comment]
Actually, I've decided not to implement this in lifelines. This is a perfect example of creating a _custom_ model in lifelines, see the new example implementation [here](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Piecewise%20Exponential%20Models%20and%20Creating%20Custom%20Models.html#3-parameter-Weibull-distribution), but maybe better to read the entire page as well.

**Comment by murakotaro4** [comment]
It is a very easy-to-understand commentary.
You are a genius!
Thank you for the very useful library.
