### ISSUE TITLE
_conditional_time_to_event_ not working

### ISSUE THREAD

**Issue by courtneymonk** [CamDavidsonPilon/lifelines#393]
Hi, I am trying to generate some conditional survival times but having issues.

After running the model:
kmf.fit(durations = df_survival.tenure, event_observed = df_survival.observed, timeline=range(0,335))
kmf.survival_function_
kmf._conditional_time_to_event_()

I get an error message "Shape of passed values is (1, 318), indices imply (1, 335)".  I thought adding the "timeline" argument would help because it has something to do with passing 0 values.  How do I correct this?

**Comment by CamDavidsonPilon** [comment]
Hey @courtneymonk, there are some problems with that function (even without using `timeline`). It's being fixed in v0.14, see #395

**Comment by CamDavidsonPilon** [comment]
Nothing planned - you could pip install that branch however if you need it immediately (or just copy-paste the new code). See here: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by courtneymonk** [comment]
Hi, I tried running the new code for the conditional time to event function (from here: https://github.com/CamDavidsonPilon/lifelines/blob/v0.14/lifelines/fitters/__init__.py).
 I also tried installing the branch (I wasn't sure which link to use so tried a few):
!pip install git+https://github.com/CamDavidsonPilon/lifelines/tree/v0.14
!pip install git+https://github.com/CamDavidsonPilon/lifelines/pull/395
!pip install git+https://github.com/CamDavidsonPilon/lifelines/pull/395/commits/509ab6672d5c36948a0a69952f209af092ca76b7
!pip install git+https://github.com/CamDavidsonPilon/lifelines/blob/v0.14/lifelines/fitters/__init__.py  
But none of that worked.  Should I be doing something differently?
Thanks!

**Comment by CamDavidsonPilon** [comment]
Try this:
```
pip uninstall lifelines && pip install git+https://github.com/camdavidsonpilon/lifelines@v0.14

```

**Comment by courtneymonk** [comment]
Thanks, that seems to have worked.  
Do you have any tips on the best way to calculate the probability of failure between time t1 and t2, conditional on survival up until t1 (where the (t2-t1) is longer than 1 unit)?  Is that possible using the KM estimator and survival function table?  This is basically a hazard rate but not at time t but rather over some longer interval.  an example is, say, given that you have lived until age 30, what's the probability that you'll die in the next n years?

**Comment by CamDavidsonPilon** [comment]
This is a common problem. Let's work it up mathematically. 

Define S(t) := P(T > t), i.e. the survival function at time t

What you want is P(T > t | T > 30).

P(T > t | T > 30) = P(T > t and T > 30) / P(T > 30) = P(T > t) / P(T > 30) = S(t) / S(30)

So all you need to do is rescale the survival function by it's value at time 30.
