### ISSUE TITLE
Survival Regression Stephen Harper Example

### ISSUE THREAD

**Issue by alexminnaar** [CamDavidsonPilon/lifelines#394]
I am reading the survival regression documentation specifically the Stephen Harper example.  It looks like Stephen Harper is a right-censored example (started in 2006 and was still in office as of 2008).  Looking at the plot of the survival function though it looks like there is a non-zero probability that he could be out of office within 2 years.  How is it possible given that we know from the data that he was in office for the first two years? Or does this prediction not assume that we have that prior knowledge i.e. we are pretending we are making the prediction when we are in 2006?

**Comment by CamDavidsonPilon** [comment]
>  we are pretending we are making the prediction when we are in 2006?

this. You could include the fact that we know he was in office for two years by conditioning on that probability. Suppose P(T > t) = S(t) is his survival curve. Then P(T > t | T > 2) = S(t)/S(2) (you can do the math to make sure that's correct).

**Comment by alexminnaar** [comment]
Great, thanks!
