### ISSUE TITLE
Add weights to Kaplan Meier

### ISSUE THREAD

**Issue by pzivich** [CamDavidsonPilon/lifelines#396]
Is there a way to add weights to individual observation in KaplanMeierFitter().fit()? This is useful for inverse probability censor weights. 
For IPCW, logistic regression is used to generate probabilities of individuals being censored by a set of dependent variables (where the independent variable is censor=1). The inverse of the predicted probability is then used to weight observations.
I am currently looking up how SAS generates the weighted Kaplan Meier

**Comment by CamDavidsonPilon** [comment]
No, not atm, but there should be. All the pieces are in place for it. I'll add it to v0.14 release.

**Comment by pzivich** [comment]
One item I wanted to add to this, the SE estimates from a weighed Kaplan-Meier are invalid. If confidence_intervals_ are requested on a weighted KM, an error or warning should be given to users. 

Currently , the only option I am aware of for CI for a weighted KM is non-parametric bootstrapping

**Comment by CamDavidsonPilon** [comment]
Huh, interesting, can you explain why they are invalid? Any docs you recommend I read?

**Comment by pzivich** [comment]
This might be my bad. It depends on the way the weights are generated. I am using inverse probability weights. Variances are invalid in this specific situations, since there is some residual correlations in the weights since they are generated via regression models. When using inverse probability weighted data, you need to use a robust variance estimator to account for these dependencies. As far as I know, there is not a version for Greenwood's variance for KM. 

If you would like a source that discusses this specific issue somewhat: http://onlinelibrary.wiley.com/doi/10.1002/sim.7084/full
However, this discussion predominately focuses on Cox proportional hazards SE being invalid in IPW data. However, the same concern applies to KM
