### ISSUE TITLE
check for NaNs in T and E

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#398]

**Comment by courtneymonk** [comment]
Hi, the CPHfitter is now throwing a bunch of errors related to nan values : 
"ValueError: delta contains nan value(s). Convergence halted."  This is totally new today and my model and data haven't changed so it's very odd (and there are 0 nan values in the df).  I'm using v0.14 from git -- is this issue related or perhaps causing the problem?  I know there's some risk to using the most current version, so please let me know if this is a known bug or something you're tinkering with or if I need to debug more on my side. Thanks!

**Comment by CamDavidsonPilon** [comment]
huh, one thing that did change was some step_size things: https://github.com/CamDavidsonPilon/lifelines/commit/b6635ca0f7f9f22e48bd4c2a358790577cae849c

Can you post the shape of your dataframe going into the model, and if you have change the `step_size` param at all? Also, can you please post the output if you add `show_progress=True` to `fit(...)`?

**Comment by courtneymonk** [comment]
![image](https://user-images.githubusercontent.com/11510487/35465602-01f46db2-02b2-11e8-8ca5-b678d09ba153.png)
(hope this image loads)
I was trying to trim out variables to home in on the issue, so in this instance the model is only trying to use 1 explanatory variable.  Shape is (1233318 rows, 3 column)

**Comment by CamDavidsonPilon** [comment]
Very useful, thanks. 

Try:
```
cp.fit(df, .. ..., step_size=0.1)
```

or even lower step sizes. Please report back if that works or not.

**Comment by CamDavidsonPilon** [comment]
That's a lot of rows, and something lifelines is not optimised for yet. The problem, as I understand, is that the log-likelihood is very tight around a single point (the maximum likelihood estimator in fact), so the iterative search is getting confused.

**Comment by courtneymonk** [comment]
Yep, I know it's a lot of rows.  Makes sense that the MLE was having issues converging when the LL isn't hitting a max.  That fix seemed to work.  I can run it again next week and see if the error crops up again.  Thank you!!
