### ISSUE TITLE
Conda

### ISSUE THREAD

**Issue by LarryKuehn** [CamDavidsonPilon/lifelines#400]
Hi.
I would like to use lifelines 0.13 in Anaconda. Unfortunately, conda-forge only has version 0.11.2. What can I do?
I did 'conda install -c conda-forge lifelines' and also 'pip install lifelines'. But that does not work.
Thanks.

**Comment by CamDavidsonPilon** [comment]
Hey @LarryKuehn, I am new to conda, but I did manage to update lifelines on conda: https://anaconda.org/conda-forge/lifelines

Please try again
