### ISSUE TITLE
What happens if the covariate plots go below zero

### ISSUE THREAD

**Issue by springcoil** [CamDavidsonPilon/lifelines#406]
I've some covariate plots for Aalen Additive that the plots go below zero, on the cumulative plot of coefficients. 

Does this make sense? Is it reasonable, does anyone have literature on this?

**Comment by CamDavidsonPilon** [comment]
It does not make "sense", however it is reasonable. There is not constraint in the AAF model for this.  A resource that adds more about this is "Survival and Event History Analysis: A Process Point of View".

**Comment by springcoil** [comment]
Thanks. Maybe worth clarifying this in the docs.
