### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ZzDizzyBearzZ** [CamDavidsonPilon/lifelines#415]
Hi! I am new to Python and are currently having [Errno 2] No such file or directory error.
(Using Mac Sierra OS High)

python: can't open file '27NovTest.py': [Errno 2] No such file or directory

The code is shown below:

```
from lifelines.datasets import load_dataset
from lifelines import KaplanMeierFitter

def load_smrtData(**kwargs):

    
    return load_dataset('C:\\Users\\admin\\Desktop\\XXXX\\xxxxUpdatedDatasetData.csv', **kwargs)

df = load_smrtData() # returns a Pandas DataFrame

print ("df.head()")


T = df['T']
E = df['E']

kmf = KaplanMeierFitter()
kmf.fit(T, E)

kmf.survival_function_
kmf.median_
kmf.plot()

print (kmf.survival_function_)
print (kmf.median_)


import pandas as pd
d = pd.DataFrame(data=kmf.survival_function_)
d.to_csv('testdata.csv', index=False)
```

**Comment by CamDavidsonPilon** [comment]
hm, I'm not sure to be honest. I don't see `27NovTest.py` in your example code above.

**Comment by ZzDizzyBearzZ** [comment]
I used Terminal and what I typed is below:


Admins-MacBook-Pro-2:~ admin$ python 27NovTest.py
python: can't open file '27NovTest.py': [Errno 2] No such file or directory

**Comment by CamDavidsonPilon** [comment]
Oh, this is some problem local to your computer. Are you sure `27NovTest.py` is in the directory you are in? try `ls` in the Terminal

**Comment by ZzDizzyBearzZ** [comment]
Hi, I forgot to use command "cd desktop" just now.
Solved the problem with python /Users/admin/Desktop/27NovTest.py
Sorry for the trouble :D thanks for helping out!
Currently have another problem 

File "27NovTest.py", line 1, in <module>
from lifelines.datasets import load_dataset 
ImportError: No module named lifelines.datasets

I will open another trend about it. Sorry for the trouble!

**Comment by Chakaravarthi** [comment]
I'm also having same issue while I'm running chatbot program in CMD.

[](url)
![image](https://user-images.githubusercontent.com/15834682/48692561-77dc1c80-ebfc-11e8-8007-de5daae74f6c.png)
![import error](https://user-images.githubusercontent.com/15834682/48692594-92ae9100-ebfc-11e8-92aa-f6792e3f4bf1.JPG)

**Comment by Chakaravarthi** [comment]
Please help me @ZzDizzyBearzZ

**Comment by CamDavidsonPilon** [comment]
@Chakaravarthi does your problem have anything to do with the lifelines library?

**Comment by Chakaravarthi** [comment]
I'm sorry, I don't understand your question and I'm new to python.

Here's my code,

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot = ChatBot('bot')
bot.set_trainer(ListTrainer)

for files in os.listdir('C:/Python31/chatterbot-corpus-master/chatterbot_corpus/data/english/'):
    data = open('C:/Python31/chatterbot-corpus-master/chatterbot_corpus/data/english/' + files, 'r').readline()
    bot.train(data)

while True:
        message = input('You:')
        if message.strip()!='Bye':
            reply = bot.get_reponse(message)
            print('ChatBot:',reply)
        if message.strip()=='Bye':
            print('ChatBot: Bye')
            break

**Comment by Chakaravarthi** [comment]
I download the chatterbot_corpus from github and placed in C drive

**Comment by CamDavidsonPilon** [comment]
Unfortunately, your problem is unique to your set up, and I (nor ZzDizzyBearzZ) can assist you. I would recommend asking a knowledgable individual around you, or trying an online course to learn Python like on [Coursera](https://www.coursera.org/specializations/python)
