### ISSUE TITLE
Kaplan-Meier estimator confidence intervals

### ISSUE THREAD

**Issue by javadnoorb** [CamDavidsonPilon/lifelines#419]
The KM confidence interval in __bounds_ method of _KaplanMeierFitter_ class seems to be exponential Greenwood CI. Unfortunately the link commented in that method seems to be dead:

http://courses.nus.edu.sg/course/stacar/internet/st3242/handouts/notes2.pdf

Here's some notes that I looked through to make sense of the math behind the code:

https://www.math.wustl.edu/~sawyer/handouts/greenwood.pdf

But going through the code takes a lot of time. Is it possible to mention 'exponential Greenwood CI' in the documents? For example here:

http://lifelines.readthedocs.io/en/latest/Survival%20analysis%20with%20lifelines.html

By the way, the link in that document also seems to be dead.

**Comment by springcoil** [comment]
Why don't you add this to the docs? :)

**Comment by javadnoorb** [comment]
I created a pull request:
https://github.com/CamDavidsonPilon/lifelines/pull/422

**Comment by javadnoorb** [comment]
Never done this before, so wasn't sure how the logistics of it work.
