### ISSUE TITLE
Speeding up Aalen Additive Regression

### ISSUE THREAD

**Issue by springcoil** [CamDavidsonPilon/lifelines#421]
Hi, I've been working on a project for a few months now and one problem I have is that it can take about 4 days to run on 340k rows, with about 6 features. 

I know lifelines isn't necessarily designed for this and I've discovered that the ridge regression solve step is the biggest bottleneck - 60% of the compute time happens there. 

Are there alternative algorithms I can use like mini-batch say? Rather than the ridge regression?

**Comment by CamDavidsonPilon** [comment]
Four days!? That is beyond inappropriate. I’ll look into this for the next release

**Comment by springcoil** [comment]
https://stats.stackexchange.com/questions/83272/fastest-way-to-run-ridge-regression-on-large-datasets-where-np makes me think that this is a problem with my BLAS/LAPACK. Do you want me to check what they are.

**Comment by springcoil** [comment]
What sort of debugging information would you need from me? How can I help you?

**Comment by springcoil** [comment]
The server I was running this on - I took the spec from it. Let me know if that helps :) 


```Numexpr version:   2.6.1
NumPy version:     1.11.3
Python version:    2.7.12 | packaged by conda-forge | (default, Sep  8 2016, 14:22:31) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Platform:          linux2-x86_64
AMD/Intel CPU?     True
VML available?     False
Number of threads used by default: 8 (out of 24 detected cores)

>>> np.__config__.show() 

lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/net/DataScience_public/jupyter_virtual_envs/python2/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/net/DataScience_public/jupyter_virtual_envs/python2/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/net/DataScience_public/jupyter_virtual_envs/python2/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/net/DataScience_public/jupyter_virtual_envs/python2/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_mkl_info:
  NOT AVAILABLE
```
```

**Comment by springcoil** [comment]
In https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/aalen_additive_fitter.py#L188 is this correct. It seems to me it's predicting per row in table not per time event.

**Comment by CamDavidsonPilon** [comment]
> It seems to me it's predicting per row in table not per time event.

the `for` loop iterates over the times https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/aalen_additive_fitter.py#L170

**Comment by springcoil** [comment]
Ok I'll close that bugfix. Any idea how to speed this up Cameron? 4 days isn't adequate.

**Comment by CamDavidsonPilon** [comment]
For now, just sample down to a smaller number of observations

**Comment by springcoil** [comment]
I've tried that but not really suitable for my problem. But thanks :)

**Comment by CamDavidsonPilon** [comment]
Looking at the profile of the code, most of the time is spent in solving the least-squares problem. I've found some modest performance increases there (~10%)

**Comment by springcoil** [comment]
Ahh cool. Could you use gradient boosting?

**Comment by CamDavidsonPilon** [comment]
I don't know what gradient boosting would solve. The LR step is part of the inference algorithm

**Comment by springcoil** [comment]
Just so I understand, are you saying that gradient boosting wouldn't work for the inference step?

**Comment by CamDavidsonPilon** [comment]
That's correct

**Comment by springcoil** [comment]
Ahh that makes sense. It looks like your solving step change is the right approach. I suspect there's other performance improvements. Looking forward to the new release :)
