### ISSUE TITLE
Command Prompt not showing all Excel rows

### ISSUE THREAD

**Issue by ZzDizzyBearzZ** [CamDavidsonPilon/lifelines#431]
Hi! May I ask if anyone know how do I do a quick fix on this problem?
The excel have 131 rows and the Command Prompt only show some of the line with ... ... in between.
Is there any way to show all 131 rows? Thanks in Advance!

C:\Users\jasmi\OneDrive\Desktop>python 27NovTest.py
     T  E    group
0  427  1  miR-137
1  575  1  miR-137
2  650  1  miR-137
3  792  1  miR-137
4  836  1  miR-137
          KM_estimate
timeline
0.0          1.000000
427.0        0.998410
575.0        0.996820
650.0        0.995231
792.0        0.993641
836.0        0.992051
854.0        0.990461
999.0        0.988871
1089.0       0.987281
1112.0       0.985692
1201.0       0.982512
1210.0       0.980922
1218.0       0.979332
1246.0       0.977742
1247.0       0.976153
1288.0       0.974563
1336.0       0.972973
1341.0       0.971383
1348.0       0.969793
1377.0       0.968203
1407.0       0.966614
1414.0       0.965024
1418.0       0.963434
1420.0       0.961844
1422.0       0.960254
1435.0       0.958665
1437.0       0.957075
1438.0       0.953895
1442.0       0.952305
1449.0       0.950715
...               ...
2350.0       0.826709
2353.0       0.825119
2354.0       0.823529
2366.0       0.821940
2384.0       0.820350
2385.0       0.818760
2431.0       0.817170
2438.0       0.812401
2439.0       0.807631
2465.0       0.806041
2466.0       0.802862
2468.0       0.799682
2482.0       0.798092
2486.0       0.796502
2493.0       0.794913
2497.0       0.793323
2527.0       0.791733
2592.0       0.790143
2645.0       0.788553
2699.0       0.786963
2711.0       0.785374
2712.0       0.783784
2713.0       0.782194
2743.0       0.780604
2810.0       0.779014
2853.0       0.777424
2912.0       0.775835
2949.0       0.774245
2975.0       0.772655
3121.0       0.772655

[131 rows x 1 columns]
inf

**Comment by CamDavidsonPilon** [comment]
@ZzDizzyBearzZ, I can help you, but this is a general Pandas issue, not related to lifelines. The solution is present here: https://stackoverflow.com/a/16433953/1895939
