### ISSUE TITLE
check_low_var does not work if some columns are non-numeric

### ISSUE THREAD

**Issue by bayesfactor** [CamDavidsonPilon/lifelines#435]
It appears as though lifelines expects all columns to be numeric.  When fitting a coxPH model, a first step is to call check_low_var. Line 974 in __init__.py
cols = str(list(df.columns[low_var]))

throws an error, since low_var has len = number of numeric columns, whereas df.columns has len = total number of columns. I think this can be fixed by changing line 974 to:
cols = str(list(df.select_dtypes(include=np.number).columns[low_var]))

**Comment by CamDavidsonPilon** [comment]
Hm, but why are you passing in non numeric data? CoxPH will just break somewhere else, no?

**Comment by bayesfactor** [comment]
Perhaps. I was trying to pass in categorical data (e.g. a column containing ['A','B','C']). This could be one-hot-encoded -- is that what is required?

**Comment by CamDavidsonPilon** [comment]
> This could be one-hot-encoded -- is that what is required?

Yes, that's right. I expect the user to encode variables as they want, and pass me the final dataframe. For one-hot-encoding, Pandas (`get_dummies`), Patsy and Scikit-learn can do this. (I prefer the former two to the latter, as they work better on pandas dataframes)
