### ISSUE TITLE
WeibullFitter object doesn't have an event_table attribute

### ISSUE THREAD

**Issue by bayesfactor** [CamDavidsonPilon/lifelines#440]
plotting a weibull fit results in an error if show_censors = True due to line 350 of plotting.py.  
WeibullFitter object doesn't have an event_table, it has an event_observed. If this is the same, we could copy event_observed into event_table? 

The WeibullFitter class probably needs something like the KaplanMeierFitter class:
`
v = _preprocess_inputs(durations, event_observed, timeline, entry, weights)
`
`
self.durations, self.event_observed, self.timeline, self.entry, self.event_table = v
`
        

Example to reproduce:

`
from lifelines import WeibullFitter
`
`
wf = WeibullFitter()
`
`
wf.fit(durations = [3,4,5,6], event_observed = [1,1,1,0])
`
`
wf.plot(show_censors=True, ci_alpha=0.05, ax=ax)
`
`
AttributeError: 'WeibullFitter' object has no attribute 'event_table'
`

**Comment by CamDavidsonPilon** [comment]
Thanks for the reproducible example and issue. I don't think this is a bug, but a problem with the KaplanMeierFitter (and other classes') API. Here's my reasoning:

1. The `KaplanMeierFitter` needs the `event_table` to do it's product estimation. 
2. Early on, this table was so useful that I exposed it in the fitted class. 
3. However, most other fitters (like Weibull) don't need this event table to do the calculation, hence didn't have it as part of their API _and_ probably don't need it either. Users interested can use `lifelines.utils.survival_table_from_events`
4. Really, I should _remove_ the table from the `KaplanMeierFitter` API, and force everyone to use `survival_table_from_events` instead.
