### ISSUE TITLE
delta contains nan value(s)

### ISSUE THREAD

**Issue by codeisbeauty** [CamDavidsonPilon/lifelines#441]
I m using the regression part and I came across the top 1 problem:
delta contains nan value(s)

First I careless identify the problem cause by the nan value in the dataframe , I have checked lf_df.isnull().any().any() which return False.

what is the difference between data contain... and delta contain...

**Comment by CamDavidsonPilon** [comment]
Hey there, can you post 1) the version of lifelines you are using and 2) the output if you set show_progress=True in the call to fit?

**Comment by CamDavidsonPilon** [comment]
Any update on this?

**Comment by codeisbeauty** [comment]
Yes, I have update the version to 0.14.1, however the value error is still there:

raw data:
 ```
var1,var2,var3,var4,var5,var6,var7,var8,var9,var10,var11,var12,var13,var14,var15,var16,var17,time_span,observed
1,867,3000,10313,3437.6667,5.666666667,6,0,0,0,4,24,21,13,3,6,21,883,1
0,0,3000,8000,4000,6.5,7,0,0,0,4,24,21,11,3,18,8,532,1
4,651,3000,37630,5375.7143,8.142857143,7,0,0,0,4,25,1,28,3,18,8,686,1
0,0,3000,9455,4727.5,11.5,12,0,0,0,4,24,21,18,3,6,21,716,1
0,0,3000,6455,3227.5,12,12,0,0,0,4,24,21,24,3,6,21,745,1
0,0,3000,17824,4456,8.25,7,0,0,0,4,24,21,32,3,6,21,843,1
0,0,1500,1500,1500,9,9,0,0,0,3,9,3,9,3,9,3,419,1
0,0,3000,3000,3000,7,7,0,0,0,3,6,21,7,3,6,21,632,1
0,0,3000,3000,3000,7,7,0,0,0,3,18,8,7,3,18,8,842,1
0,0,3000,3000,3000,7,7,0,0,0,3,6,21,7,3,6,21,1222,1
0,0,3000,3000,3000,7,7,0,0,0,3,18,8,7,3,18,8,1222,1
0,0,3000,3000,3000,12,12,95,1,3,3,6,21,12,3,6,21,742,1
0,0,3000,9797,3265.6667,6,12,0,0,0,4,24,21,18,3,6,21,778,1
1,584,500,500,500,12,12,0,0,0,1,1,4,3,1,1,4,715,1
0,0,3000,3000,3000,7,7,0,0,0,3,6,21,7,3,6,21,1001,1
0,0,3500,6500,3250,4.5,6,0,0,0,4,24,21,9,3,7,1,412,1
0,0,3000,13000,6500,6.5,7,0,0,0,4,24,21,12,3,6,21,816,1
0,0,3000,11109,3703,7,12,0,0,0,4,24,21,10,3,6,21,852,1
1,1023,3000,3000,3000,12,12,0,0,0,3,6,21,5,3,6,21,1222,1
3,442,3000,12927,2585.4,12,12,0,0,0,2,2,4,32,1,1,4,480,1
0,0,3500,6588,3294,9.5,12,0,0,0,4,25,1,19,3,18,8,563,1
```
code:

cphdata1=pd.read_csv('./delta_contain_nan_20.csv',sep=',')
cph = CoxPHFitter()
cph.fit(cphdata1, duration_col='time_span', event_col='observed',show_progress=True)
cph.print_summary()  

---------------------------------------------------------------------------
log:
Iteration 1: norm_delta = 10.91807, step_size = 0.98000, ll = -45.38014
Iteration 2: norm_delta = 2.91857, step_size = 0.48755, ll = -25.61972
Iteration 3: norm_delta = 2.58188, step_size = 0.48511, ll = -23.73123
Iteration 4: norm_delta = 5.23090, step_size = 0.48269, ll = -22.83778
Iteration 5: norm_delta = 2.07538, step_size = 0.48027, ll = -22.41483

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-100-357976d31879> in <module>()
      3 from lifelines import CoxPHFitter
      4 cph = CoxPHFitter()
----> 5 cph.fit(cphdata1, duration_col='time_span', event_col='observed',show_progress=True)
      6 cph.print_summary()  # access the results using cph.summary

/opt/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py in fit(self, df, duration_col, event_col, show_progress, initial_beta, strata, step_size, weights_col)
    136                                          initial_beta=initial_beta,
    137                                          show_progress=show_progress,
--> 138                                          step_size=step_size)
    139 
    140         self.hazards_ = pd.DataFrame(hazards_.T, columns=df.columns, index=['coef']) / self._norm_std

/opt/anaconda3/lib/python3.6/site-packages/lifelines/fitters/coxph_fitter.py in _newton_rhaphson(self, X, T, E, weights, initial_beta, step_size, precision, show_progress, max_steps)
    225                 raise ValueError("""delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:
    226 https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model
--> 227 """)
    228 
    229             # Save these as pending result

ValueError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:
https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

**Comment by CamDavidsonPilon** [comment]
Inspecting the data, the problem is with (at least) cols var8, var9 and var10: they are linear combinations of each other. This creates problems in the fitting. One remedy is to drop two of the columns. However, even after doing this, I still get convergence problems. So I do suspect there is less obvious linear combinations (multicollinearity) in the dataset. Have you looked into something like Variance Inflation Factor (VIF)?

**Comment by codeisbeauty** [comment]
Yes,if the input dataset with much more observations, the error chance would decrease while the correlation decline.Variable collection always with high cost from different source, and the correlation detection delayed after the modeling.So in lifelines correlation detection  would put forward before the fit process. 
Even so, as you mentioned the  'less obvious linear combinations' would lead to error, how much the less? this is the problem still here.
