### ISSUE TITLE
Pair Wise Log Rank Test

### ISSUE THREAD

**Issue by venkra** [CamDavidsonPilon/lifelines#444]
I sliced overall duration data into 3 slices, resulting in arrays of unequal length.

When I try running pairwise_logrank_test (with events, groups, durations all with shape (3, )), the following error happens:

operands could not be broadcast together with shapes (221411,) (161265,) 

I tried padding the arrays to max length, but then I get the error

P.S: Really neat package for python! Thanks!

**Comment by venkra** [comment]
incomplete comment from above:

I get the error: cannot reshape array of size 3 into shape (221411,)

**Comment by CamDavidsonPilon** [comment]
oops sorry I meant to get back to you. The following works fine for me: 
```python
pairwise_logrank_test(np.array([1,2,3]), np.array([1,2,3]), np.array([1,2,3]))
```

Does your data look similar to that?

**Comment by venkra** [comment]
Hi sorry, it was my misunderstanding on how the function works. Turns out I was slicing the events and durations into a (3,) array and passing group labels as a list of unique group names.

I changed the code to pass (1,) arrays and group labels for *each individual* element and it works beautifully.
