### ISSUE TITLE
CoxPH "general" model fit p-value

### ISSUE THREAD

**Issue by TCAllen07** [CamDavidsonPilon/lifelines#448]
Sort of a question and suggestion combined -- comparing to output from R's `coxph`, the latter includes in its output the p-value of the fit as a whole, or more specifically `likelihood ratio test=X  on Y df, p=Z` (or the Wald test or logrank score, all of which testing the null case where all coefficients are zero); example below.

Does lifelines CoxPH fitter have a similar estimate attached to it? I couldn't find one, and can work out how to calculate it if not, but I thought it prudent to ask before assuming.

```
> require(survival)
> data(lung)
> res.cox <- coxph(Surv(time, status) ~ sex, data = lung)
> summary(res.cox)
Call:
coxph(formula = Surv(time, status) ~ sex, data = lung)

  n= 228, number of events= 165

       coef exp(coef) se(coef)      z Pr(>|z|)
sex -0.5310    0.5880   0.1672 -3.176  0.00149 **
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

    exp(coef) exp(-coef) lower .95 upper .95
sex     0.588      1.701    0.4237     0.816

Concordance= 0.579  (se = 0.022 )
Rsquare= 0.046   (max possible= 0.999 )
Likelihood ratio test= 10.63  on 1 df,   p=0.001111
Wald test            = 10.09  on 1 df,   p=0.001491
Score (logrank) test = 10.33  on 1 df,   p=0.001312
```

**Comment by CamDavidsonPilon** [comment]
To be clear: is the `Score (logrank) test` the test that all coefficients are 0? 

So lifelines doesn't have this, but it's not too hard to add in the next release.

**Comment by TCAllen07** [comment]
Yes. In fact all three of the last lines in the summary are different score tests of just that, at least according to my understanding of [John Fox's 2008 Cox PH paper](https://socialsciences.mcmaster.ca/jfox/Books/Companion-1E/appendix-cox-regression.pdf):
> "The likelihood-ratio, Wald, and score chi-square statistics at the bottom of the output are asymptotically equivalent tests of the omnibus null hypothesis that all of the β’s are zero."

I don't have the knowledge to say which of them would be preferable to implement in lifelines, though I can say that for my purposes the `logrank` is test is probably what I would use.

(Side note: my original description was misleading, as I mentioned the wrong output. I'll edit it for clarity in the future.)

**Comment by pzivich** [comment]
The three tests are only comparable when the n is large. Wald performs poorly in situations of a low sample size. One other issue is that Wald is not invariant under reparameterization. Likelihood ratio and score statistics are

Ideally, all three would be implemented. Likelihood ratio or score would be better though

**Comment by CamDavidsonPilon** [comment]
I added `Likelihood ratio test` to the most recent version of lifelines (0.14.4). I'm not sure if I want to add the other two statistics: Wald seems out of fashion.
