### ISSUE TITLE
StatisticalResult significance can be misleading

### ISSUE THREAD

**Issue by yanirs** [CamDavidsonPilon/lifelines#465]
I'm not sure what the rationale behind dropping `StatisticalResult.is_significant` was, but now things are bit confusing:

* `is_significant` is still referenced in [docs/Examples.rst](https://github.com/CamDavidsonPilon/lifelines/blob/12128c0de156583b7e092eeebdbf4904a6d37468/docs/Examples.rst#L55).
* `utils.significance_code()` doesn't take the `alpha` into account, so results that are starred by `StatisticalResult.print_summary()` don't account for multiple comparisons when the Bonferroni correction is used.

**Comment by CamDavidsonPilon** [comment]
Hm, you make some good points. Let me investigate this further. I may want to cut a new release to fix this.

**Comment by CamDavidsonPilon** [comment]
I'm curious: how would you expect the stars to work, given a Bonferroni correction?

**Comment by yanirs** [comment]
Good question. I wonder if stars make sense when the `alpha` isn't 0.95. A quick search yielded these results &ndash; seems like people just use words:
* https://depts.washington.edu/psych/files/writing_center/stats.pdf
* https://stats.stackexchange.com/questions/325847/bonferroni-correction-vs-asterisks-signifying-significance-levels

By the way, having `StatisticalResults.is_significant` would be useful in any case. For example, I use the following code to summarise the results of a `pairwise_logrank_test` call as the percentage of significant pairs. Being able to write `res.is_significant` rather than `res.p_value < 1 - res.alpha` would be nice. :slightly_smiling_face: 
```python
results = pairwise_logrank_test(event_durations, groups, event_observed).applymap(
    lambda res: 1.0 if res and res.p_value < 1 - res.alpha else 0.0
)
num_pairs = len(results) * (len(results) - 1) // 2
return len(results), num_pairs, results.sum().sum() / 2 / num_pairs
```
