### ISSUE TITLE
Martingale Residuals

### ISSUE THREAD

**Issue by mzhao94** [CamDavidsonPilon/lifelines#479]
Are there any plans to implement calculation of Martingale Residuals?

**Comment by CamDavidsonPilon** [comment]
Hey, is this the same as schoenfeld residuals?

**Comment by mzhao94** [comment]
They're a little bit different according to this post. 
https://stats.stackexchange.com/questions/297740/what-is-the-difference-between-the-different-residuals-in-survival-analysis-cox

**Comment by mzhao94** [comment]
My understanding is the Schoenfeld residuals are used to test the proportional hazards assumption and Martingale residuals are used to test goodness-of-fit.

**Comment by CamDavidsonPilon** [comment]
Great , thanks. Yup I’ll try to include this in v15

**Comment by CamDavidsonPilon** [comment]
This is available now
