### ISSUE TITLE
Lower limit of lambda is negative

### ISSUE THREAD

**Issue by amod99** [CamDavidsonPilon/lifelines#488]
Hi Cam,

I am getting lower 0.95 limit of lambda_ parameter as negative. Hence my cumulative hazard calculations are failing. Basically I am trying to generate cumulative hazard rate upper and lower bounds using respective bounds of parameters. Let me know if there is any work around for negative value lambda.

**Comment by CamDavidsonPilon** [comment]
Hey, sorry I missed this. Can you post some code / data? Are you using the ExpontentialFitter?
