### ISSUE TITLE
step_size in k_fold_cross_validation

### ISSUE THREAD

**Issue by gjogonzalezc** [CamDavidsonPilon/lifelines#495]
Hi There

I'm dealing with a dataset with convergence issues (i'm using a step_size=0.2) but now I want to perform a cross_validation thru the dataset but i dont know how to incorporate the step size into the code line. 

i.e:
print(np.mean(k_fold_cross_validation(cph, df, duration_col='T', event_col='E')))

please your help

**Comment by CamDavidsonPilon** [comment]
Hey @gjogonzalezc 

hmmm, can you give me an example of a convergence issue you are seeing? Also, what is the size of your `df`?

**Comment by gjogonzalezc** [comment]
regression.shape  => (272, 7)

ValueError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:
https://lifelines.readthedocs.io/en/latest/Examples.html#problems-with-convergence-in-the-cox-proportional-hazard-model

you mean that?

**Comment by CamDavidsonPilon** [comment]
So you can pass step_size in using:
```
print(np.mean(k_fold_cross_validation(cph, df, duration_col='T', event_col='E', fitter_kwargs={'step_size': 0.3})))
```

However, if you do, can you print the output of:
```
print(np.mean(k_fold_cross_validation(cph, df, duration_col='T', event_col='E', fitter_kwargs={'step_size': 0.3, 'show_progress': True})))
```

**Comment by gjogonzalezc** [comment]
Thanks!
