### ISSUE TITLE
investigate CI for this project

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#498]
https://hypothesis.works/articles/continuous-releases/

**Comment by Kilo59** [comment]
Is this something you are still interested in? I'll create a fork with a simple TravisCI pipeline.

**Comment by CamDavidsonPilon** [comment]
The idea was continuous releases for every push to master. 
 
Hard to implement, but interesting idra

**Comment by Kilo59** [comment]
I just started working on adding some additional steps to the CI and I can add a "deploy" step as well.

**Comment by Kilo59** [comment]
I just opened a small PR for moving to a more up-to-date version of python 3.7 in the CI #558.
I'll be creating 2 additional PR's in the following order
 1. Additional static analysis to protect against bad deployments of broken/bad code.
 2. Automatic deployment to Pypi travis build stage
