### ISSUE TITLE
Singular Matrix error 

### ISSUE THREAD

**Issue by aaronbroderickpiano** [CamDavidsonPilon/lifelines#501]
I'm currently getting a Singular Matrix error  while trying to run a CoxPHFitter on some data trying to predict future donations for a non profit.  

duration variable = week (1-52)
event variable = 0/1 (not donor/donor)

15 other variables about the people.  All numeric.  Some are 1<x<0.  Some are int.  Not sure what other helpful info I can provide, but let me know and I'll post it as soon as I can.

**Comment by CamDavidsonPilon** [comment]
How many rows? Might there be colinearity in the columns?

**Comment by aaronbroderickpiano** [comment]
Thanks for your response.  Shape is (6706, 17).  Collinearity could be an issue.  Just wondering, why would that cause a matrix issue?

**Comment by aaronbroderickpiano** [comment]
<img width="1016" alt="screen shot 2018-07-19 at 7 50 11 pm" src="https://user-images.githubusercontent.com/30608282/42975937-febf725e-8b8c-11e8-89f5-c043c4ba469f.png">

This is a heat map of my variables

**Comment by aaronbroderickpiano** [comment]
Ok, removing correlated variables made the model run.  Thanks for your help.

**Comment by CamDavidsonPilon** [comment]
Colinearity is always a problem in linear models without a strong penalizer (due to a matrix inversion step, technically).

Terrific!
