### ISSUE TITLE
Predictions using the Cox time varying fitter.

### ISSUE THREAD

**Issue by pinouche** [CamDavidsonPilon/lifelines#506]
Hello @CamDavidsonPilon,

First of all, thanks a lot for providing us with the library!

My question is regarding making predictions using the Cox Time varying fitter. There is very little documentation about the issue. 

My problem is that in CoxPH, we do not need to specify the time at which the covariates were measured as they are assumed to be constant over the whole observation period, for each individual. However, for the time varying method, it does make a difference to know at which point in time our covariates were measured.

Do we thus have to provide the start and stop time in our dataset in the .predict() method?

Thanks a lot,
Tom

**Comment by CamDavidsonPilon** [comment]
Hey @pinouche, so prediction with time varying covariates has an internal paradox: if I know the covariates of a subject at each, surely I know if they are alive or not! See more here: https://cran.r-project.org/web/packages/survival/vignettes/timedep.pdf

**Comment by ganzheng85** [comment]
Can we pre-assume covariates for each subject for a period of future time and check their survival probability for that time range? Different covariates will surely lead to different survival probability at different future times.  I don't need to know if they are alive or not. I need to get each individual's survival decay curve. Thanks.

**Comment by SimplyOm** [comment]
Hi @CamDavidsonPilon, really appreciate the effort in bringing the lifelines library to life.

As discussed in https://github.com/CamDavidsonPilon/lifelines/issues/530, this can be legitimate use case in running future what-if scenarios -- not necessarily hitting the internal paradox you mentioned above. So, wanted to check if this can be included as a future enhancement, as it seems like the underlying components are available and we need to expose the survival function on top of the same.
