### ISSUE TITLE
Mismatch in proportional hazards between R and Mathematica with Lifelines

### ISSUE THREAD

**Issue by MattB27** [CamDavidsonPilon/lifelines#508]
I'm working with a dataset with one covariate that is categorical and has three levels. In R and Mathematica I get a proportional hazard of 1.5 (coefficient of 0.41649) but in Lifelines I get a hazard of 0.8899 (coefficient of -0.1166). My workflow is as follows:

- Import original data set
-Create an event array (1's for failure and 0's for right censorship)
-Create a duration array
-Use pandas pd.factorize to create a number dummy array to represent the three covariates
-Combine the event, duration and dummy array into a new pandas dataframe
---At this point the dataframe has:
----event array 479 non-null float64
----duration array 479 non-null float64
----dummy array 479 non-null int
-Calculate the proportional hazard using the new dataframe:
cph.fit(df, duration_col='time', event_col='event', show_progress=True)

The output shows that convergence is completed after 5 iterations, and shows the correct number of events and n but is reporting a different coef than R. If I take the same dataframe and export it to csv and then run it in R then I get a proportional hazard of 1.5. This is also the case with Mathematica.

Anyone have any suggestions for troubleshooting this? Thanks!

**Comment by MattB27** [comment]
Here's the output:

Python Lifelines implementation

n=479, number of events=239

            coef  exp(coef)  se(coef)       z      p  lower 0.95  upper 0.95   
grouping -0.1166     0.8900    0.0847 -1.3757 0.1689     -0.2827      0.0495   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 

Concordance = 0.524
Likelihood ratio test = 1.917 on 1 df, p=0.16623

R Survival Package

Call:
coxph(formula = Surv(time, event) ~ grouping, data = df)

 n= 479, number of events= 239 

                 coef         exp(coef) se(coef)      z Pr(>|z|)
grouping -0.11658   0.88996  0.08474 -1.376    0.169

               exp(coef) exp(-coef) lower .95 upper .95
grouping      0.89      1.124    0.7538     1.051

Concordance= 0.524  (se = 0.02 )
Rsquare= 0.004   (max possible= 0.994 )
Likelihood ratio test= 1.92  on 1 df,   p=0.1662
Wald test            = 1.89  on 1 df,   p=0.1689
Score (logrank) test = 1.9  on 1 df,   p=0.1685

Thanks for your response

**Comment by pzivich** [comment]
Based on your output, the answers are equivalent between lifelines and R. Following the lifelines output, you have log(HR) = -0.1166. The R output gives log(HR) = -0.11658.  I'm not sure where the 0.41649 coeffecient in the R output

One other thing I want to mention, unrelated to the discrepancies, I would be careful with how your model is set up. How your categories are coded in your model assume a linear relationship of the HR between categories. Here is a simple example, image your categorical variable is education level; primary only (0), secondary (1), and graduate (2). With how you have the model implemented, the model assumes that the HR between primary and secondary is the same as the HR between secondary and graduate. This may not be true. It would be better practice to allow for non-linearity by coding the categorical variable as a dummy variable (two binary variables, with one indicating a value of 1, and one indicating a value of 2). You can use ```pd.get_dummies``` to do this.

**Comment by MattB27** [comment]
@pzivich thanks for your explanation. I apologize that I didn't catch that the R output was the same as lifelines. I was in-between the train where I had internet and a bus where I would not have internet so I was a little rushed. The 0.4169 output comes, as I discovered, when the grouping variable type is a double and the analysis assumes that it is a continuous covariate. In earlier analysis I had accidentally defined the grouping column as being a double, and I double check my data types in R.

Thanks again for your explanation, I'm fairly new to survival analysis and it's nice to have a practical example to help me keep things straight.

**Comment by pzivich** [comment]
@MattB27  No problem! Glad I could help

**Comment by CamDavidsonPilon** [comment]
Thanks @pzivich for the quick solution (Matt and I corresponded over email, but I was on vacation). Glad everything is 👌!
