### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by nairvinitha** [CamDavidsonPilon/lifelines#514]
Hey, 

There is an error I've been facing while coding in Python 3.6, despite adding the file path to environment variables on the control panel.
This was a part of the code, trying to plot an image:
`for j, img_name in enumerate(ids):
...     q = j+1
...     img = load_img(r"""C:/Users/VinithaNair/Desktop/VINI/Kaggle Projects/Salt Identification Challenge/train.zip/images/""" + img_name + '.png')
...     img_mask = load_img(r"""C:/Users/VinithaNair/Desktop/VINI/Kaggle Projects/Salt Identification Challenge/train.zip/masks/""" + img_name + '.png')
...     plt.subplot(1,2*(1+len(ids)),q*2-1)
...     plt.imshow(img)
...     plt.subplot(1,2*(1+len(ids)),q*2)
...     plt.imshow(img_mask)
`
Here's the error I've been getting:

**img = pil_image.open(path)
  File "C:\Users\VinithaNair\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/VinithaNair/Desktop/VINI/Kaggle Projects/Salt Identification Challenge/train.zip/images/1f1cc6b3a4.png'**

Can somebody please help me out with what I've been doing wrong here? I've imported all the necessary libraries needed too.
[https://www.kaggle.com/jesperdramsch/intro-to-seismic-salt-and-how-to-geophysics/notebook](url)

OS: Windows
Python version : 3.6

**Comment by CamDavidsonPilon** [comment]
This doesn’t have anything to do with lifelines, right?

**Comment by nairvinitha** [comment]
No this has nothing to with lifelines. I'm guessing, it's some basic file directory code statement I'm missing out on, just not sure what. 
If I code the following:
`os.path.exists(r'C:\Users\VinithaNair\Desktop\VINI\Kaggle Projects\Salt Identification Challenge\train\images/')
True`

The above file exists. But if I pick out an image to be plotted:

`os.path.exists(r'C:\Users\VinithaNair\Desktop\VINI\Kaggle Projects\Salt Identification Challenge\train\images/1f1cc6b3a4.png/')
False`

The False statement tells me the file doesn't exist, while it actually does when I searched for the image in the same file path.

Could you please tell me, how do I fix this issue?

**Comment by nairvinitha** [comment]
Thank You so much!!! That actually worked :D I can't believe I struggled with the slash for nearly 2 hours :P . 

This is what I did:

`>> for j, img_name in enumerate(ids):
...     q = j+1
...     img = load_img(r"""C:\Users\VinithaNair\Desktop\VINI\Kaggle Projects\Salt Identification Challenge\train\images/""" + img_name + '.png')
...     img_mask = load_img(r"""C:\Users\VinithaNair\Desktop\VINI\Kaggle Projects\Salt Identification Challenge\train\masks/""" + img_name + '.png')
...     plt.subplot(1,2*(1+len(ids)),q*2-1)
...     plt.imshow(img)
...     plt.subplot(1,2*(1+len(ids)),q*2)
...     plt.imshow(img_mask)`

and the following was my output along with the images displayed:

`**matplotlib.axes._subplots.AxesSubplot object at 0x000002593A9500B8>
<matplotlib.image.AxesImage object at 0x000002593A976198>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593A9694E0>
<matplotlib.image.AxesImage object at 0x000002593A9EC588>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593A227B00>
<matplotlib.image.AxesImage object at 0x000002593AA21FD0>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593AA2C2B0>
<matplotlib.image.AxesImage object at 0x000002593AA64828>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593A9ECD30>
<matplotlib.image.AxesImage object at 0x000002593AA7B828>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593AA75F60>
<matplotlib.image.AxesImage object at 0x000002593AAC7C50>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593A9EC908>
<matplotlib.image.AxesImage object at 0x000002593B2DC160>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593B2DC400>
<matplotlib.image.AxesImage object at 0x000002593B316400>
<matplotlib.axes._subplots.AxesSubplot object at 0x000002593AA64B38>
<matplotlib.image.AxesImage object at 0x000002593B34CA20>**`
![image](https://user-images.githubusercontent.com/16742842/45386387-ebb9e180-b61b-11e8-9f6c-4393b186e9de.png)

**Comment by CamDavidsonPilon** [comment]
lovely!
