### ISSUE TITLE
cph.predict_expectation? 

### ISSUE THREAD

**Issue by gjogonzalezc** [CamDavidsonPilon/lifelines#515]
Hi There! 

I know this is not a "tech" issue, but can you explain me how this predict_expectation works? 
how it's calculated?

Thanks!

**Comment by CamDavidsonPilon** [comment]
Hey @gjogonzalezc, it's estimates the expectation using a finite approximation formula:

![codecogseqn 8](https://user-images.githubusercontent.com/884032/46261938-a9701b80-c4c8-11e8-835f-68a750f5528c.gif)

The first equality is from the definition of expected value: https://en.wikipedia.org/wiki/Expected_value#Formula_for_non-negative_random_variables

the second approximation is just the trapezoidal rule. https://en.wikipedia.org/wiki/Trapezoidal_rule

**Comment by gjogonzalezc** [comment]
Ok I see, I really appreciate it. 
Cheers

**Comment by KOLANICH** [comment]
@CamDavidsonPilon , why doesn't it use an analytical formula instead of numerical integration of survival function?
