### ISSUE TITLE
Switch source code to `src`

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#522]
https://blog.ionelmc.ro/2014/05/25/python-packaging/

**Comment by Kilo59** [comment]
I think the way the package is structured now is actually a better approach.

https://docs.python-guide.org/writing/structure/#the-actual-module

The editable install problem (and various other problems) can be solved by moving to a [`pipenv`](https://pipenv.readthedocs.io/en/latest/) workflow, [like I've done here](https://github.com/Kilo59/lifelines/blob/ddf26484130476017fabbbf433f99343a162854b/Pipfile#L13).

**Comment by CamDavidsonPilon** [comment]
Cool. I do like the current structure more, and am happy to see that its recommended.
