### ISSUE TITLE
[CTV] Hazard Point Estimate

### ISSUE THREAD

**Issue by marcosantoni** [CamDavidsonPilon/lifelines#523]
The `CoxTimeVaryingFitter` class provides the following methods/variables:

- `ctv.predict_partial_hazard(df)`
-  `ctv.baseline_cumulative_hazard_`

Given the model, I would like to predict a point estimate of the hazard given `t` and `x(t)`

![image](https://user-images.githubusercontent.com/30628424/47215747-d4041480-d3a2-11e8-946d-a15d779bda25.png)

After fitting, we have the partial hazard in the `CoxTimeVaryingFitter` class. However, we don't have the __baseline hazard__ (we have just the cumulative). I inspected the code, and modified the `_compute_cumulative_baseline_hazard` method below:

```python
def _compute_cumulative_baseline_hazard(self, tv_data, stop_times_events):
        events = stop_times_events.copy()
        events['hazard'] = self.predict_partial_hazard(tv_data).values

        unique_death_times = np.unique(events['stop'].loc[events['event']])
        baseline_hazard_ = pd.DataFrame(np.zeros_like(unique_death_times),
                                        index=unique_death_times,
                                        columns=['baseline hazard'])

        for t in unique_death_times:
            ix = (events['start'] < t) & (t <= events['stop'])
            events_at_t = events.loc[ix]

            deaths = events_at_t['event'] & (events_at_t['stop'] == t)
            death_counts = deaths.sum()  # should always be atleast 1.
            baseline_hazard_.loc[t] = death_counts / events_at_t['hazard'].sum()

        #### --> new command here
        self.my_baseline_hazard_ = baseline_hazard_

        return baseline_hazard_.cumsum()
```

By doing so, I have access to the hazard values at every `t`. I could then:

```python
# pseudocode
def hazard(self, t, x_t):
    return self.my_baseline_hazard_.loc[t] * self.predict_partial_hazard(df)
```

I tried to implement the above method, and it works from the code point of view. Is it a valid method?

**Comment by CamDavidsonPilon** [comment]
Hey @marcosantoni,

Is it a valid method? Yes, (alternatively, `ctv.baseline_cumulative_hazard_.diff()` is equivalent), however the catch is the standard errors on the baseline hazard are quite large and typically you want to do some smoothing of the hazard, ex `ctv.baseline_cumulative_hazard_.diff().rolling(3).mean()`

**Comment by marcosantoni** [comment]
Clear, thanks!
