### ISSUE TITLE
Model serialization?

### ISSUE THREAD

**Issue by dwilson1988** [CamDavidsonPilon/lifelines#524]
First off - AWESOME library. I've been using it for a few of my projects and it's been a lifesaver. 

However, I'm looking to save models. I can't seem to find any documentation on how. My specific use case is just wanting to save the Kaplan-Meier estimator and use it to make predictions later. I can of course save off the data frame of the survival function, but I'd like to pickle (or otherwise) the model and reload in a different module as I'm performing analysis/fitting and then using the model later. Is there another way besides exporting the survival function (I'd like use the predict method...) 

Thanks!

**Comment by CamDavidsonPilon** [comment]
Hey @dwilson1988, thanks for the kind words. So there's been an open issue in lifelines for a while around that point: https://github.com/CamDavidsonPilon/lifelines/issues/188

(pickle is a library to serialize python objects)

There's not a good solution atm, unfortunately. However, in a later release, I will come back to fix this.

**Comment by dwilson1988** [comment]
I've written custom __reduce__ methods for metaclasses before, would you be interested in a PR if I can break off some time to work on this?

**Comment by CamDavidsonPilon** [comment]
yesss so interested!

**Comment by CamDavidsonPilon** [comment]
I'd prefer 2. - I don't like the additional dependency to clean up bad software architecture (I can say that because I wrote it heh)

**Comment by dwilson1988** [comment]
:)

In progress, I'll send you a PR when I have it complete.

**Comment by CamDavidsonPilon** [comment]
If you can, feel free to work off my v0.15 branch (or point your contributions to branch `v0.15.0`), so I can add your contributions in the next release

**Comment by dwilson1988** [comment]
Awesome, working on v0.15.0

**Comment by dwilson1988** [comment]
Aha, I get it. You were trying to avoid rewriting docstrings because they are the same for the most part. A lot of docstrings are writable, but method docstrings aren't. You also can't modify the class `__dict__` in 3.6+, so I'm working on workarounds.

**Comment by CamDavidsonPilon** [comment]
>  You were trying to avoid rewriting docstrings because they are the same for the most part. 

I think a bit of over-engineering on my part, I feel

**Comment by CamDavidsonPilon** [comment]
I'd be just as happy with a "no-nonsense under-engineered" solution too

**Comment by dwilson1988** [comment]
I like clever code that saves lines of code, but perhaps "Explicit is better than implicit" is a good call here. I'm almost done either way, should have the PR in soon. Thanks!
