### ISSUE TITLE
Univariate and multivariable Cox regression analysis

### ISSUE THREAD

**Issue by norbertstrzelecki** [CamDavidsonPilon/lifelines#536]
Hi @CamDavidsonPilon,

I'm pretty new to survival analysis so have a question, how can one make a univariate Cox regression analysis using lifelines? Is it just by using dataframe with that one particular variable (column), and then loop through the rest variables to check them all? Because as I understand default results from CoxPHFitter using whole df with many variables is multivariable analysis, right?

Thank you for any help, best regards

**Comment by CamDavidsonPilon** [comment]
Hey! Emailed you with a reply, but I'll add the examples here for future users:

univariate: https://gist.github.com/CamDavidsonPilon/2e52966b72e62491935a38c7a20d91ca

**Comment by norbertstrzelecki** [comment]
Cameron, thanks for the email and those examples, that's what I was looking for :)
