### ISSUE TITLE
Cox PH Regression Baseline Hazard

### ISSUE THREAD

**Issue by andremurillocorrea** [CamDavidsonPilon/lifelines#543]
Hello,

I'm quite new to survival analysis and I'm probably asking something very stupid, but I'll ask anyway.

In Cox PH Regression model, the baseline hazard function is the hazard function when all covariates are set to zero, right?

So, when I plot covariate groups like it's done in the doc, why the baseline curve isn't equal to the prio=0 curve. I'm dropping all other covariates to get only the influence of prio in the death process

```from lifelines.datasets import load_rossi
from lifelines import CoxPHFitter

rossi_dataset = load_rossi()
a = rossi_dataset.drop(["fin","race","wexp","mar","paro","age"],axis = 1)
cph = CoxPHFitter()
cph.fit(a, duration_col='week', event_col='arrest')

cph.plot_covariate_groups('prio', [0, 5, 10, 15])
```

![image](https://user-images.githubusercontent.com/27099418/48807741-9974fb00-ed05-11e8-83dd-2b233f76fa2a.png)

Most of the time when fitting data to this model, I get a baseline survival curve that is equal to the survival curve of the whole dataset, and not equal to the survival curve of the elements having covariates = 0.

Is it right? I'm probably missing something in the explanation.

**Comment by CamDavidsonPilon** [comment]
I think... there may be a bug.. 

I think I am de-meaning too aggressively. Let me get back to you about this after some investigations.

**Comment by CamDavidsonPilon** [comment]
> In Cox PH Regression model, the baseline hazard function is the hazard function when all covariates are set to zero, right?

So, no. In lifelines, the baseline hazard is the hazard function when all covariates are set _to the mean of the covariate_. 

So that "baseline survival" in the graph is the "average" subject (which often has no real world meaning tbh, you can't be 0.5 male). Thus, it makes sense to have prio=0 above the baseline survival. 

Does that make sense?

**Comment by CamDavidsonPilon** [comment]
Good points:

- Yea docs need to be updated to reflect this

> Is there a way to calculate the baseline function considering covariates equal zero and not the mean values? 

- hm, I think if you scale the lifelines baseline hazard by the factor `exp(-x_mean * hazards)`, that equals what you want. 

- w.r.t. to the goodness of fit test suggested in the docs: the way I see it is how much "variance" is provided by the baseline hazard vs the partial hazard. The baseline hazard is approx. equal to the Kaplan-Meier curve if _none_ of the variance is explained by the covariates / partial hazard. Deviations from this provide a visual measure of variance explained. I don't any of this logic has to do with the mean _expect_ that "The baseline hazard is approx. equal to the Kaplan-Meier curve" is correct.

**Comment by justkrismanohar** [comment]
> > In Cox PH Regression model, the baseline hazard function is the hazard function when all covariates are set to zero, right?
> 
> So, no. In lifelines, the baseline hazard is the hazard function when all covariates are set _to the mean of the covariate_.
> 
> So that "baseline survival" in the graph is the "average" subject (which often has no real world meaning tbh, you can't be 0.5 male). Thus, it makes sense to have prio=0 above the baseline survival.
> 
> Does that make sense?

Hi @CamDavidsonPilon  can you explain this a little more, what is confusing me is that base line should also be a function of time? An example would be appreciated :)
