### ISSUE TITLE
better docs on left-truncation

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#557]
It confused me at first

**Comment by hcarlens** [comment]
Is this the part of the docs you're referring to? https://github.com/CamDavidsonPilon/lifelines/blob/master/docs/Survival%20analysis%20with%20lifelines.rst#left-truncated-data

I'm just looking at using this now, so I'd be happy to try improving the docs while I'm figuring out how it works.

**Comment by CamDavidsonPilon** [comment]
👋 hi @hcarlens 
Yes, this and the doc string on the `KaplanMeierFitter.fit`. Specifically, one thing that confused me was if `entry` included in the duration or not. For example, given a subject with duration=11, and entry=5, does that mean either:
1) the individual entered at time 5, and then lasted 11 units?
2) the individual entered at time 5, and then lasted an additional 6 = 11-5 units?

I believe it's the former, but it's not clear from the docs you linked nor the docstring in `.fit`

**Comment by CamDavidsonPilon** [comment]
Oh great test, nice investigation. So if you would like to update the docs, feel free to create a new branch and PR to master.

> Oddly, both ExponentialFitter and WeibullFitter also accept entry though they don't actually do anything with it.

Ah, I recently removed that in #567.
