### ISSUE TITLE
Consider dropping support for Python 3.4

### ISSUE THREAD

**Issue by Kilo59** [CamDavidsonPilon/lifelines#559]
The more versions of Python that are supported the harder it is to maintain and extend `lifelines`.

Forcing users to switch from Python2 to Python3 can be deal-breaking for some people despite Python2 nearing its [death](https://pythonclock.org/). However, moving from `Python3.4` to `3.5` or `3.6` is trivial.

Python3.4 is incredibly slow compared to 2.7 and later versions of 3

![image](https://user-images.githubusercontent.com/13108583/49341603-c38bbe80-f61d-11e8-9434-117d530add38.png)

**Comment by Kilo59** [comment]
Another alternative would be to configure Travis so that build failures on `3.4` do not cause the whole build to fail.
This wouldn't really help with the build time but it would be less burdensome for developers going forward.

**Comment by CamDavidsonPilon** [comment]
I’m down with stopping support, but let’s make that change part of a larger release 👍

**Comment by Kilo59** [comment]
I can add a warning to users with Python3.4 recommending they change to python`3.6`/`3.7`.

**Comment by CamDavidsonPilon** [comment]
mm, I don't think it's necessary to add a warning. I'm sure _all_ the other packages will give the user a warning too.

**Comment by CamDavidsonPilon** [comment]
Let's drop it in 0.16.0. Here's a graph of lifelines installs for 3.4:

![screen shot 2018-12-21 at 8 21 45 am](https://user-images.githubusercontent.com/884032/50344556-85393f00-04f9-11e9-9481-04f77d9a2f16.png)

From here: https://pypistats.org/packages/lifelines
