### ISSUE TITLE
Consider refactoring high complexity methods

### ISSUE THREAD

**Issue by Kilo59** [CamDavidsonPilon/lifelines#560]
The following methods/functions receive a mccabe [complexity score](https://en.wikipedia.org/wiki/Cyclomatic_complexity) `> 10`. This is basically a measure of loops and conditionals.

This, of course, doesn't mean that all of these methods need to be refactored, just that they are worth taking a look at.

----------------------------------------------------------------------------------------------

- [ ] mccabe: MC0001 / CoxPHFitter._newton_rhaphson is too complex (20)
- [ ] mccabe: MC0001 / CoxTimeVaryingFitter._newton_rhaphson is too complex (16)
- [ ] mccabe: MC0001 / add_covariate_to_timeline is too complex (16)
- [ ] mccabe: MC0001 / _naive_concordance_index is too complex (13)
- [ ] mccabe: MC0001 / plot_estimate is too complex (12)
- [ ] mccabe: MC0001 / AalenAdditiveFitter._fit_static is too complex (11)

-----------------------------------------------------------------------------------------------

The most important thing should be readability, maintainability and testability...not making a complexity checking tool happy 😄.

**Comment by CamDavidsonPilon** [comment]
❤️❤️ this is great advice!

**Comment by usmanatron** [comment]
More refactoring?!  I'm in :-)

**Comment by usmanatron** [comment]
Had a stab at plot_estimate, see #581 .  @CamDavidsonPilon - I'll wait to hear your thoughts before attempting any more (to make sure you agree with my approach)
