### ISSUE TITLE
Rounding in print summary

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#578]
Two decimals places please

**Comment by usmanatron** [comment]
Any specific summaries or all of them?

**Comment by CamDavidsonPilon** [comment]
Specifically the way we present them in `print_summary` methods, this is the rule I'd like to implement: https://twitter.com/jaimiegradus/status/1075000614499901440

**Comment by usmanatron** [comment]
Ok thanks, I'll have a stab
