### ISSUE TITLE
v0.20.0 will not have Python2 support

### ISSUE THREAD

**Issue by Kilo59** [CamDavidsonPilon/lifelines#582]
Many of the tools in the Scientific Python stack have already moved to a BugFix only model for Python2, as such it's going to make the continued development of Lifelines for Python2 more difficult.

Examples:
https://docs.scipy.org/doc/numpy-1.14.1/neps/dropping-python2.7-proposal.html

There is a website for making a public commitment to requiring python3 as well as resources and tips for making the "switch".
https://python3statement.org/
https://python3statement.org/practicalities/

## First steps

I think these might be some good action items.

- [x] Announce/Commit to requiring Python3 in the future
  * Add section to README explaining the decision and encourage users to adopt python3, provide resources to do so.

- [ ] Pick a date/release to move to Bugfix only mode for Python2. Stop making new features Python2 compatible.
     
- [ ] Add deprecation warning to lifelines for python2 users. 

Eventually we can add a install requires Python3 to `setup.py` and remove all the Python2 compatibility code.

**Comment by CamDavidsonPilon** [comment]
Yesss! I opened this same issue in a browser tab but I had no idea what the “next steps” were - thank you for assisting here.

**Comment by CamDavidsonPilon** [comment]
0.20.0 will not have Python2 support
