### ISSUE TITLE
Add MACS data from Cole Hudgens 2010

### ISSUE THREAD

**Issue by pzivich** [CamDavidsonPilon/lifelines#601]
If you are looking for additional data sets to add to lifelines, you might consider adding the data set within Table 2 of [this paper (Cole & Hudgens 2010)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2954271/)

The interesting item of this data set is that late-entry occurs (indicated by W_i). Also might be useful for ``plot_lifetimes`` example with the ``entry`` option

**Comment by CamDavidsonPilon** [comment]
Figure 1 in that paper looks so nice.

This is a great paper to reconcile lifelines against, thanks for sharing!

**Comment by CamDavidsonPilon** [comment]
Using the latest 0.17.0 branch:

```python
from lifelines.datasets import multicenter_aids_cohort_study
from lifelines.plotting import plot_lifetimes
df = multicenter_aids_cohort_study().reset_index()

plot_lifetimes(df['Ti']-df['Wi'], event_observed=df['Di'], entry=df['Wi'], event_observed_color='#383838', event_censored_color='#383838')
plt.ylabel("Patient Number")
plt.xlabel("Years from AIDS diagnosis")
```

![screen shot 2019-01-10 at 5 09 19 pm](https://user-images.githubusercontent.com/884032/51000256-907cfa80-14fa-11e9-9ab0-8f2f8e93f4ba.png)
