### ISSUE TITLE
Error in check assumptions

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#614]
https://github.com/LeoGrin/PSC/blob/master/xena_scraping.ipynb

cc @leogrin, can you detail the error your saw in "check the assumptions" section?

**Comment by LeoGrin** [comment]
hi @CamDavidsonPilon 
I've updated the notebook to show the error. Tell me if you need other info.

**Comment by CamDavidsonPilon** [comment]
Great, thanks. This was recently fixed (yesterday?) in v0.17.3 - you can `pip install lifelines==0.17.3` to get it.

**Comment by LeoGrin** [comment]
Oh cool, thank you ! 
Also I'm curious : how did you tumble on my notebook ?

**Comment by CamDavidsonPilon** [comment]
That's a fair question: 

I sometimes go a global github search for `lifelines` to see how people are using the API. It's like a passive way to get user feedback.

**Comment by LeoGrin** [comment]
Haha that's a good idea
