### ISSUE TITLE
Aalen-Johansen Variance

### ISSUE THREAD

**Issue by pzivich** [CamDavidsonPilon/lifelines#630]
For large sample sizes, the `AalenJohansenFitter` has some trouble estimating the variances. While working on a tutorial for competing risks, I noticed some unexpected behavior for confidence intervals of the Aalen-Johansen estimator. 

This does not have to do with the formula, but rather it becomes a problem for large samples. Somewhere in the variance formulation (in `_bounds`), one element gets close to zero (or something similar). This near-zero value is causing the variance calculations to blow up. Everything works exactly as expected when n ~ 1000, but when I increase the sample size closer to n ~ 10,000 is when problems start occurring. 

Below is where the variance calculation takes place
```
            sf["part1"] = ((F_t - sf["Ft"]) ** 2) * (
                sf["observed"] / (sf["at_risk"] * (sf["at_risk"] - sf["observed"]))
            )
            sf["part2"] = (
                ((sf["lagS"]) ** 2)
                * sf[self.label_cmprisk]
                * ((sf["at_risk"] - sf[self.label_cmprisk]))
                / (sf["at_risk"] ** 3)
            )
            sf["part3"] = (F_t - sf["Ft"]) * sf["lagS"] * (sf[self.label_cmprisk] / (sf["at_risk"] ** 2))
            variance = (np.sum(sf["part1"])) + (np.sum(sf["part2"])) - 2 * (np.sum(sf["part3"]))
```
My guess is that something is going wrong with `(sf["observed"] / (sf["at_risk"] * (sf["at_risk"] - sf["observed"]))` or ` (sf[self.label_cmprisk] / (sf["at_risk"] ** 2))`, but I haven't tracked down this problem yet. The reason I target these two parts as responsible is because they will get close to zero for large sample sizes, especially the second option

When writing the original, I missed this because I tested it on sample sizes below 2,000

For replication, you can use the following data generator
```
def simulate_competing_risk(large_n):
    if large_n:
        n_idu = 1143
        n_non = 6039
    else:
        n_idu = 114
        n_non = 603

    df_idu = pd.DataFrame()
    df_idu['t_death'] = np.random.weibull(0.8, size=n_idu) * 10
    df_idu['t_aids'] = np.random.weibull(1, size=n_idu) * 10
    df_idu['idu'] = 1

    df_non = pd.DataFrame()
    df_non['t_death'] = np.random.weibull(1.1, size=n_non) * 10
    df_non['t_aids'] = np.random.weibull(1.1, size=n_non) * 10
    df_non['idu'] = 0

    df = pd.concat([df_idu, df_non], ignore_index=True)
    df['t_censor'] = np.random.weibull(1.3, size=n_idu + n_non) * 3
    df['t_censor'] = np.where(df['t_censor'] > 5, 5, df['t_censor'])  # Admin censoring at t=5

    df['t'] = np.min(df[['t_death', 't_aids', 't_censor']], axis=1)
    df['event'] = np.where(df['t'] == df['t_censor'], 0, np.nan)
    df['event'] = np.where(df['t'] == df['t_aids'], 1, df['event'])
    df['event'] = np.where(df['t'] == df['t_death'], 2, df['event'])
    df['t'] = np.round(df['t'], 5)
    df['id'] = df.index
    return df[['id', 'event', 't']]
```
When `large_n=True` the variance explodes. Also, I know that it is somewhere before the SE transformation, since `AalenJohansenFitter.variance` is blown up. It has to be in the part 1 / part 2 / part 3 calculations somewhere

**Comment by CamDavidsonPilon** [comment]
Thanks for the detailed bug report 👍 

Just thinking quickly, it may be an overflow/under problem. A solution might be to "flatten" the divisions and multiplications. Ex:

```python
            sf["part2"] = (
                ((sf["lagS"]) ** 2)
                * sf[self.label_cmprisk]
                * ((sf["at_risk"] - sf[self.label_cmprisk]))
                / (sf["at_risk"] ** 3)
```

to 
```python
sf["part2"] = (
    sf["lagS"] ** 2 / sf["at_risk"] 
    * sf[self.label_cmprisk] / sf["at_risk"] 
    * (sf["at_risk"] - sf[self.label_cmprisk]) * sf["at_risk"]
)
```

**Comment by pzivich** [comment]
Good call! Spacing out the terms seems to work when I tested it. I will create a PR with the two issues I raised today

@CamDavidsonPilon One more item since I am working on this: Aalen-Johansen variance is slow since it needs to go over every event time. When I use IPW, I have to use non-parametric bootstrapping to get the confidence intervals. Since `AalenJohansenFitter` calculates the variance for each individual resample, it takes more computation time than necessary (since these variances play no role in the bootstrap). Would you mind if I add something like `calculate_variance` to init? The default would be `True` and calculate the variance. If set to `False` it would skip over these calculations to save computation time during bootstrapping

**Comment by CamDavidsonPilon** [comment]
right right, that makes sense. Yea, I think that additional kwarg is fine 👍 

Thanks for being a good code owner!
