### ISSUE TITLE
What are the penalty functions of lifelines in survival analysis regression?

### ISSUE THREAD

**Issue by Abraxas2071** [CamDavidsonPilon/lifelines#637]
Such as the lasso？I searched the document and it's still not very clear

**Comment by CamDavidsonPilon** [comment]
The two regression models, `AalenAdditiveFitter` and `CoxPHFitter`, have some docs on using an L2 penalizer. For example, see `coef_penalizer` and `smoothing_penalizer` here: https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.aalen_additive_fitter.AalenAdditiveFitter

I don't have plans to implement a lasso penalizer in those models, however, I think I can implement lasso in the new AFT models coming out.

**Comment by CamDavidsonPilon** [comment]
But I am also interested: _why_ do you want a lasso penalizer?

**Comment by Abraxas2071** [comment]
> But I am also interested: _why_ do you want a lasso penalizer?

@CamDavidsonPilon Our Dear Cameron。Because lasso can select variables

**Comment by CamDavidsonPilon** [comment]
Yes, but why do you want to select variables?

**Comment by Abraxas2071** [comment]
@CamDavidsonPilon Our Dear Cameron
So far as I understand
1) variable selection can avoid tedious and controversial statistical significance test (for example, in a 2016 paper on threshold regression that I implemented, the author used SCAD penalty function to avoid tedious threshold effect statistical test, which was very clever and greatly improved the calculation efficiency).
2】 in the process of solving can achieve the purpose of dimensionality reduction, but also more conducive to the selection of explanatory variables, to help business understanding

Haha, my own understanding, don't laugh at me

**Comment by ioannis12** [comment]
Hello, 

I have used the penalizer options for the Aalen and Cox models, in a dataset with correlated covariates, but I don't see how to select variables. In the lasso method the penalized coefficients are shrunk to zero, but it doesn't happen in those models. Any ideas?

**Comment by CamDavidsonPilon** [comment]
Hm, is your penalizer term just not large enough? Try doubling it, at least. You also want to make sure that `l1_ratio=1` in the `CoxPHFitter` initalization.

**Comment by ioannis12** [comment]
yes, this seems to work. Thank you!
