### ISSUE TITLE
ValueError in KaplanMeierFitter

### ISSUE THREAD

**Issue by alinakhay** [CamDavidsonPilon/lifelines#639]
Hi!
Thanks for your examle. I am having a trouble implementing it with my data though.
When I am trying to fit the
`km = KaplanMeierFitter() km.fit(durations, event_observed,label='Kaplan Meier Estimate')`
I get the `ValueError: Length of values does not match length of index`.
Do you know what could be the error?
Thank you!

**Comment by CamDavidsonPilon** [comment]
Can you post what your durations and event_observed variables look like?

**Comment by CamDavidsonPilon** [comment]
I think this has to do with your pandas version. I think this would be fixed if using pandas 0.23 and 0.24. (That's not a proper solution however, and I'll see what else I can do)
