### ISSUE TITLE
Cure models with proportional hazards

### ISSUE THREAD

**Issue by rcalsaverini** [CamDavidsonPilon/lifelines#641]
Is there an easy way to extend the CoxPH class and add a cure proportion to the model?

I saw in the [tutorial](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Modelling%20time-lagged%20conversion%20rates.html) that it's very easy to code your own log-likelihood for estimating the unconditional survival rate. 

Is there a similarly easy implementation for extending the Cox regression models with custom likelihoods? I'd like to add a cure rate to the CoxPH likelihood.

**Comment by CamDavidsonPilon** [comment]
Probably not for the Cox model, but the next release (0.19.0) will set a foundation for doing conditional cure models for parametric models (ex: Weibull).

**Comment by CamDavidsonPilon** [comment]
It's now possible to do custom parametric cure models: https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Custom%20Regression%20Models.html#Cure-models
