### ISSUE TITLE
Support for categorical features in `plot_covariate_groups`

### ISSUE THREAD

**Issue by erykml** [CamDavidsonPilon/lifelines#644]
Afaik, it is currently not possible to use `plot_covariate_groups` to plot survival curves when a categorical variable has been one hot encoded (and one category is used as baseline). Might be useful to add this feature for interpretation of the results :)

**Comment by CamDavidsonPilon** [comment]
Agree! I love that idea. I'll think about an API for it

**Comment by CamDavidsonPilon** [comment]
So this is now possible, example:
```python
cph.plot_covariate_groups(
    covariates=df.filter(like='col1_').columns.tolist(), # or just write it out: ['col1_A', 'col1_B', ....]
    values=np.eye(6)  # equal to the number of covariates
)
```

Some more docs here: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#plotting-the-effect-of-varying-a-covariate

**Comment by erykml** [comment]
Great work!
