### ISSUE TITLE
lifelines forces a downgrade of matplotlib

### ISSUE THREAD

**Issue by jgbustos** [CamDavidsonPilon/lifelines#646]
The setup.py file states that one of the dependencies is "matplotlib>=2.0,<3.0", which forces a downgrade of matplotlib. While this might be understandable for Python 2 users, it's a hassle for thouse using Python 3.

Ideally, this could be changed to use platform specific dependencies (see https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies and https://www.python.org/dev/peps/pep-0508/) so the downgrade is only forced for Python 2.

Maybe state 'matplotlib>=2.0,<3.0;python_version<"3.0"' as the dependency line?

**Comment by sisiphos2018** [comment]
I was facing the same issue. Also affecting numba and several other packages.

**Comment by CamDavidsonPilon** [comment]
Ah nice, I like that solution. I didn't know I could do that. Let me rip a new release with that this morning.

**Comment by CamDavidsonPilon** [comment]
(Aside: I'm nearing the point of dropping py2)

**Comment by CamDavidsonPilon** [comment]
Okay, 0.19.1 with the conditional matplotlib 2.x install is on PyPI

**Comment by jgbustos** [comment]
> 
> 
> Okay, 0.19.1 with the conditional matplotlib 2.x install is on PyPI

And it worked like a treat on my Python 3 environment. Thanks so much!
