### ISSUE TITLE
ImportError: LogNormalFitter, LogLogisticFitter, PiecewiseExponentialFitter

### ISSUE THREAD

**Issue by cerenaaa** [CamDavidsonPilon/lifelines#660]
I am having issues importing the following subpackages:
```
from lifelines import LogNormalFitter
from lifelines import LogLogisticFitter
from lifelines import PiecewiseExponentialFitter
```
The error message is:
```
ImportError: cannot import name 'LogNormalFitter' from 'lifelines' (C:\Users\AppData\Local\Continuum\anaconda3\lib\site-packages\lifelines\__init__.py)
```

Any ideas what the problem might be?

Thank you,
c.

**Comment by CamDavidsonPilon** [comment]
Can you reply here with the version of lifelines that `conda list` says?

**Comment by cerenaaa** [comment]
It says 17.1.

I hope this helps,
Ceren

**Comment by CamDavidsonPilon** [comment]
It does! You need atleast 0.18.1 for those models, but I encourage you to get the latest for best results. Try:
```
conda update lifelines
```
and then `conda list` again. Let me know how it does.

**Comment by cerenaaa** [comment]
Hi Cameron,

I tried the above and got the following errors:

[image: image.png]

Any idea why this might be happening?

I truly appreciate your help,
Ceren

**Comment by CamDavidsonPilon** [comment]
Your image isn't displaying properly ^

**Comment by cerenaaa** [comment]
Hi Cameron,
When I do conda update pipelines where my Python is installed, I get the
error:

solving environment: failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url

I hope this clarifies things.

Ceren

**Comment by cerenaaa** [comment]
haha yes I did mean lifelines, it's a typo.

Yes, I'm having Anaconda problems. I really don't know how to fix these but
I'll follow your suggestions.

Thank you for your help,
Ceren

**Comment by cerenaaa** [comment]
Hi Cameron,
Just a quick update: i uninstalled/reinstalled anaconda and now everything
works :)

Hope this helps with others going through the same issue.

Ceren

**Comment by CamDavidsonPilon** [comment]
Great to hear @cerenaaa! 

I'm going to close this, but I keep a list of installation issues on the [projects README](https://github.com/CamDavidsonPilon/lifelines#installation-issues) for others :)

**Comment by cerenaaa** [comment]
Perfect, thank you!

**Comment by WellJoea** [comment]
I have the same problem.
pip install lifelines
pip listPackage         Version
--------------- -------
autograd        1.2Bottleneck      1.2.1
cycler          0.10.0
entrypoints     0.3
flake8          3.7.7
future          0.17.1
joblib          0.13.2
kiwisolver      1.1.0
lifelines       0.22.0
matplotlib      3.1.1
mccabe          0.6.1
numpy           1.16.4
pandas          0.24.2
pip             19.0.3
pycodestyle     2.5.0
pyflakes        2.1.1
pyparsing       2.4.0
python-dateutil 2.8.0
pytz            2019.1
scikit-learn    0.21.2
scipy           1.2.1
setuptools      40.8.0
six             1.12.0

python lifelines.pyTraceback (most recent call last):
  File "lifelines.py", line 3, in <module>
    from lifelines.fitters import ParametricRegressionFitter
  File "C:\Users\lenovo\Desktop\MLSurvival\test\lifelines.py", line 3, in <module>
    from lifelines.fitters import ParametricRegressionFitter
ModuleNotFoundError: No module named 'lifelines.fitters'; 'lifelines' is not a package
ModuleNotFoundError: No module named 'lifelines.fitters'; 'lifelines' is not a package
