### ISSUE TITLE
Provide Initial Guess to Regression Fitters

### ISSUE THREAD

**Issue by bacalfa** [CamDavidsonPilon/lifelines#661]
It would be great to be able to provide an initial guess point (warm-start) to the regression fitters, such as `WeibullAFTFitter`. I'm referring to this line:

https://github.com/CamDavidsonPilon/lifelines/blob/d9d3f9f9acb832d03166e39556770c3374c868a4/lifelines/fitters/__init__.py#L1018

I've been comparing this particular fitter to R's `survreg`, and for some datasets, their solutions don't agree at all. I'd like to provide the same initial values to both codes and hopefully get the same solution.

**Comment by CamDavidsonPilon** [comment]
Yikes, I'm not pleased that surveg and lifelines give different results. Are you able to share an example dataset here (or privately over email)? 

It's easy enough to let users provide initial values, I can add that to the next release shortly.

**Comment by bacalfa** [comment]
Thanks for the quick response! Unfortunately, I can't share the data publicly nor privately. But I'll be happy to report the status after when I'm able to use initial points. :) By the way, I had convergence issues with `survreg` before if I don't provide any initial point. So achieving convergence can be sensitive to initial points.

**Comment by CamDavidsonPilon** [comment]
Can you describe your dataset more? 

1. What are the dimensions of it?

Some information about the fit, too:

1. Does lifelines provide a _smaller_ log-likelihood than R survreg? (you can see the log-likelihood using `.print_summary()` in lifelines)
2. Are any warnings displayed when `.fit` is called?

**Comment by CamDavidsonPilon** [comment]
flexsurvreg does some smarter initializations using summary statistics. From their docs:  

> If not specified, default initial values are chosen from a simple summary of the
survival or censoring times, for example the mean is often used to initialize scale
parameters. See the object flexsurv.dists for the exact methods used. If the
likelihood surface may be uneven, it is advised to run the optimisation starting
from various different initial values to ensure convergence to the true global
maximum.

**Comment by bacalfa** [comment]
Thanks! There were some problems with the code I was using. Will report after the experiments are finished. But it's an intercept-only model (no covariates) with datasets that range from fewer than 10 to nearly 100 points (most are suspensions).

**Comment by CamDavidsonPilon** [comment]
What about using the simpler `WeibullFitter`, which naturally takes no covariates? It will probably be faster too.

**Comment by bacalfa** [comment]
That could be done. It's just that I wanted to compare the AFT fitter with survreg. :) I have other tests with covariates as well.

**Comment by CamDavidsonPilon** [comment]
@bacalfa, if you update to 0.20.0, please try out the new defaults (i.e don't provide `initial_point`) to compare against R. 

(0.20.0 is python3 only, and has some updated dependencies too FYI)

**Comment by bacalfa** [comment]
I'm using Anaconda, and the latest version seems to be 0.19.5.

On a related note, [`survreg`](https://stat.ethz.ch/R-manual/R-devel/library/survival/html/survreg.html) offers the option to fix the scale parameter (e.g., `scale=1`) and to pass parameters to the optimizer via `survreg.control`. Those are interesting features as well.... :)

**Comment by CamDavidsonPilon** [comment]
I just updated conda

**Comment by bacalfa** [comment]
By the way, `WeibullAFTFitter` was more robust than `survreg` on my test cases. :) Even without any special initialization. But having the ability to initialize the decision variables is important.

**Comment by CamDavidsonPilon** [comment]
woohoo! Thanks for reporting back!
