### ISSUE TITLE
plot_lifetimes plots in inverted order

### ISSUE THREAD

**Issue by vpolimenov** [CamDavidsonPilon/lifelines#666]
I was playing around with this function and wanted to plot the actual death times of individuals together with their predicted lifetimes.

However, I've realised the `plot_lifetimes` is actually plotting in an [inverted order](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/plotting.py#L234). This piece of code actually makes it do so: `N - 1 - i`

Is this intended? or Is there something that I am missing?

**Comment by CamDavidsonPilon** [comment]
> I was playing around with this function and wanted to plot the actual death times of individuals together with their predicted lifetimes.

that's an interesting idea.

TBH I don't know why it's `N - 1 - i` - does this produce the wrong visualization?

**Comment by vpolimenov** [comment]
Kind of. It plots from top to bottom - in a way individual 0 is plotted as row 25. And as I was plotting my predictions from bottom to top it took me some time to realise why those look horribly wrong.

Anyway at the end I used the same inverse logic to plot the predictions.

_Just wanted to raise awareness_ 😃 

BTW, I will be happy to look into it and submit a PR if this behaviour is not intended in general. 💯

**Comment by CamDavidsonPilon** [comment]
Yea, give it a shot! Maybe you'll figure out why it's inverted in first place haha (because I don't know)

**Comment by vpolimenov** [comment]
Implemented here https://github.com/CamDavidsonPilon/lifelines/pull/673
