### ISSUE TITLE
Time-Invariant Cox Proportional Hazard Model

### ISSUE THREAD

**Issue by tom-hao** [CamDavidsonPilon/lifelines#675]
If none of my variables are time varying and I don't have a duration variable, will the CoxPHFitter still work? Do I need a duration column in my dataset?

**Comment by CamDavidsonPilon** [comment]
Well, survival analysis and specifically the cox model is a time-to-event analysis, so a duration variable is necessary. Is there a reason you want to use the cox model? Maybe describing your problem more would help me understand.

**Comment by tom-hao** [comment]
Ok, nevermind. It looks like I do have a time variable I can use. It's because my variables don't have a lot of time-dependence, I was wondering if time is that necessary. I'd like to use the CoxPH model to look at how much each of my supply chain steps contribute to a product rejection.
