### ISSUE TITLE
Cannot add count_at _risk for aalen_johansen_fitter

### ISSUE THREAD

**Issue by acmilannesta** [CamDavidsonPilon/lifelines#688]
Hi,

I tried to apply add_count_at_risk to a aalen_johansen_fitter object, but it returns an error message:

'AalenJohansenFitter' object has no attribute 'durations'.

Is there a way to customize and bypass this issue?

Thank you,
Jason

**Comment by acmilannesta** [comment]
> Ah, hm, this is something I'll have to fix with a release. For now, you could do:
> 
> ```python
> ajf = AalenJohansenFitter().fit(T, E)
> ajf.durations = T
> add_count_at_risk(ajf)
> ```

Thank you! I've just another issue.
If I set "calculate_variance" in AalenJoansenFitter to false, the plot function seems not to work even if I set "ci_show" to false. It seems to ask for confidence interval information from AalenJoansenFitter regardlessly.

**Comment by CamDavidsonPilon** [comment]
Try this:
```python
from lifelines.plotting import _plot_estimate
_plot_estimate(ajf, estimate='cumulative_density_', confidence_intervals=None, ci_show=False, <other keyword args>
```

**Comment by acmilannesta** [comment]
> Try this:
> 
> ```python
> from lifelines.plotting import _plot_estimate
> _plot_estimate(ajf, estimate='cumulative_density_', confidence_intervals=None, ci_show=False, <other keyword args>
> ```

Got it. Thx so much!

**Comment by CamDavidsonPilon** [comment]
We'll fix this in a future release, thanks for letting us know!

**Comment by acmilannesta** [comment]
sounds good!
