### ISSUE TITLE
Goodness of fit for AFT models and CoxPH fitter extrapolation

### ISSUE THREAD

**Issue by priyadarsanshankar** [CamDavidsonPilon/lifelines#690]
The martingale and deviance residuals calculations don't work for the WeibullAFTFitter, is there any other way to assess the goodness of fit for these models?

Is there any inbuilt way to plot the concentration curve to identify the lift against the random prediction, similar to an ROC curve?

Also, the predictions beyond the cut off date on a CoxPH fitter is the exact same as the one on the cut off date tenure, is this expected that this fit model cannot extrapolate?

**Comment by CamDavidsonPilon** [comment]
Residuals on those models are to-do. For now, you can do a qqplot of the univariate model like in https://lifelines.readthedocs.io/en/latest/Examples.html#selecting-a-parametric-model-using-qq-plots

> Is there any inbuilt way to plot the concentration curve to identify the lift against the random prediction, similar to an ROC curve?

The concordance-index, reported at the bottom of the `print_summary` and under `score_`, is a generalized AUC measure. 

CoxPH can't extrapolate beyond the last time, that's correct. It probably should return inf though - what prediction method are you using?

**Comment by priyadarsanshankar** [comment]
Thanks for the reply! 

I used the predict_survival_function and get the same value for all "times" >= my cut off date. 

Stupid question but, if I would like to perform extrapolation using other features in my data also, which model would you suggest I use? Is there a way to determine this?

**Comment by CamDavidsonPilon** [comment]
1. Can you provide an example? I'm not sure what you mean. 

2. Tenure values = 0 are a sign of some mismeasurement since technically a weibull random variable will never give the value 0. Try adding a small positive constant (could be 1 - it depends on the scale of your data)

3. I'm not sure I understand - are you looking for an exponential AFT model?

**Comment by priyadarsanshankar** [comment]
Thank you very much for the explanation, regarding Q1, I think it was an issue with my data preparation, which I had corrected. For Q3, yes, based on my data the exponential distribution fits best, is there any method for an exponential AFT fit, which an take into account other features of the data apart from tenure and event, like the WeibullAFT model?

**Comment by CamDavidsonPilon** [comment]
Sorry I didn't get back to this. An exponentialAFT model looks something like: https://github.com/CamDavidsonPilon/lifelines/issues/812
