### ISSUE TITLE
Interval events

### ISSUE THREAD

**Issue by amirhosseindavoody** [CamDavidsonPilon/lifelines#693]
Thanks for the awesome work.

I am trying to do some survival analysis where the observations are done on fixed intervals.
Is there anyway to handle these types of information?

The following is an example of such data

```
    Start   Stop  Censored
0    4640    NaN      True
1    4640    NaN      True
2    4640    NaN      True
3    4640    NaN      True
4    4640    NaN      True
..    ...    ...       ...
15    215  464.0     False
16      0    1.0     False
17   4640    NaN      True
18   4640    NaN      True
19   4640    NaN      True
```

Here, if the `Stop` column is `NaN` then the data is censored, but if the `Stop` has a number then the event happened between `Start` time and `Stop` time.

Thanks for the help

**Comment by CamDavidsonPilon** [comment]
Hi @amirhosseindavoody,

No support for something like that yet, unfortunately!

**Comment by CamDavidsonPilon** [comment]
It's not hard to write down the likelihood for this data (assuming a parametric model). It would be a combination of eq (2) and (3) in this paper: https://cran.r-project.org/web/packages/flexsurv/vignettes/flexsurv.pdf

**Comment by amirhosseindavoody** [comment]
Okay thanks for the reference. It seems easy enough. If I get them time I will add it to the package and send a pull request

**Comment by CamDavidsonPilon** [comment]
So version 0.21.0 (just released) has initial support for _parametric_ models of interval censoring. Here's an example: https://dataorigami.net/blogs/napkin-folding/counting-and-interval-censoring

Next is to do non and semi parametric models, but that's for the medium-term future. 

Your example can be modelled something like:
```python
from lifelines import LogLogisticFitter

df['stop'] = df['stop'].fillna(np.inf)

llf = LogLogisticFitter().fit(df['start'], df['stop'])
llf.plot_survival_function()
```

I believe that's it! I'm treating your right censored as interval censored (with an endpoint at infinity).

**Comment by amirhosseindavoody** [comment]
Thank you so much.
This is exactly what I have been looking for.
