### ISSUE TITLE
PiecewiseExponentialFitter is busted

### ISSUE THREAD

**Issue by snoodleboot** [CamDavidsonPilon/lifelines#694]
This bitt me.
```
def __init__(self, breakpoints, *args, **kwargs):
    breakpoints = np.sort(breakpoints)
    if breakpoints and not (breakpoints[-1] < np.inf):
        raise ValueError("Do not add inf to the breakpoints.")
```
in your cotr the condition "breakpoints and (breakpoints[-1] < np.inf) should be "not (breakpoints and (breakpoints[-1] < np.inf))" since you are wanting to make sure that if breakpoints, then the endpoint cannot be inf. This is an issue if breakpoints is None. Better to have chained conditional statements. I will write a change and PR it.

Better code would be 
```
def __init__(self, breakpoints, *args, **kwargs):
    breakpoints = np.sort(breakpoints)

    # Make sure that breakpoints is not an empty list or None 
    if not breakpoints or breakpoints == []:
       raise ValueError("breakpoints cannot be None or an empty list.")

    # Make sure that breakpoints does not contain any entries equivalent to np.inf
    if any([breakpoint==np.inf for breakpoint in breakpoints]):
        raise ValueError("Do not add inf to the breakpoints.")

```

**Comment by CamDavidsonPilon** [comment]
Hm, if `breakpoints` is `None` than doesn't `np.sort(breakpoints)` fail first?

**Comment by snoodleboot** [comment]
Good point

Validation should occur before any relevant manipulation.
