### ISSUE TITLE
How to plot univariate Cox regression analysis?

### ISSUE THREAD

**Issue by ElmoLee822** [CamDavidsonPilon/lifelines#704]
Hi, 
I was using univariate Cox regression analysis and loop through all variables.
How to draw the forest plot with combined the variables in the same plot?

Here is my code:
```
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi
import matplotlib.pyplot as plt
import pandas as pd

rossi = load_rossi()

cph = CoxPHFitter()
for col in rossi.columns[2:]:
    cph.fit(rossi[[col, 'week', 'arrest']], 'week', 'arrest')
    cph.print_summary()
    print(col)
    cph.plot()
    plt.show()
```

Thanks a lot.

**Comment by CamDavidsonPilon** [comment]
Hi @ElmoLee822 
You'll need to do this by hand, using matplotlib. Internally, cph.plot uses `ax.errorbar` from matplotlib to do the plotting. You'll need to loop over the variables, and manually plot the hazards + errors using `ax.errorbar`

**Comment by ElmoLee822** [comment]
Hi Cam,
Thanks for your help. 
I have done the univariate plot using `ax.errobar`.

Here is my code:
`fig, ax = plt.subplots()
x = cph_summary_df['coef']
y = np.arange(0, 7)
xerr = abs(cph_summary_df['upper 0.95']-cph_summary_df['lower 0.95'])/2
yticks_label=list(cph_summary_df.index)
ax.errorbar(x, y, xerr=xerr, fmt ='s', mfc='white', color='black', capsize=3, markeredgewidth=0.8)
plt.xlim(-1.5,1.5)
plt.yticks(range(0,7),yticks_label)
plt.vlines(0, 0, 6, linestyles = "dashed", linewidth=1, transform=ax.get_xaxis_transform(), color='black')
plt.show()`
