### ISSUE TITLE
`KaplanMeierFitter` by default uses interpolation to calculate survival probabilities 

### ISSUE THREAD

**Issue by leihuang** [CamDavidsonPilon/lifelines#713]
When the provided time is not one of the times used to define the step function returned by Kaplan-Meier estimator, `KaplanMeierFitter` uses linear interpolation to calculate the survival probabilities. But this produces probabilities different from the analytical solution (ie, the step function), and hence should not be the default behavior. It is better to make this behavior an (non-default) option by providing a parameter to `KaplanMeierFitter.predict`.

**Comment by CamDavidsonPilon** [comment]
Hi @leihuang 
Hm, I think I agree with you that your suggestion is a better API. I'll change the default, and add an interpolation flag, in a future release. Thanks for bringing this up!
