### ISSUE TITLE
Cox regression bugs?

### ISSUE THREAD

**Issue by tongtong1993** [CamDavidsonPilon/lifelines#717]
[survival_log.zip](https://github.com/CamDavidsonPilon/lifelines/files/3162128/survival_log.zip)
Hi, I have encountered a problem with cox model using this data set. It showed that a error msg :  "ValueError: array must not contain infs or NaNs", which was not seemingly the issue after re-checking the dataset. I then used the same data in R's cox package which ran the analysis correctly without any problem.  Please help.

**Comment by CamDavidsonPilon** [comment]
Hello, I noticed you closed this - did you still want assistance? If so, can you tell me what your code looked like, and how you treated the `Array` column?

**Comment by tongtong1993** [comment]
Thank you very much for your response. I finally solve the problem by adding step_size=0.1 when fitting the model.
