### ISSUE TITLE
Right way of creating a custom AFT model

### ISSUE THREAD

**Issue by cristobaltapia** [CamDavidsonPilon/lifelines#720]
I have been playing around with this very nice library (thanks a lot for writing it!) and for what I have read, it should be pretty easy to implement custom fitters, as it is shown in one of the [Examples](https://github.com/CamDavidsonPilon/lifelines/blob/master/examples/Piecewise%20Exponential%20Models%20and%20Creating%20Custom%20Models.ipynb). So I tried to implement a custom AFT fitter, which seems straightforward. However, I have one question:

1. If my new fitter is `CustomAFTFitter` then I need to define the `CustomFitter` class too, since this is looked for in the method `_create_initial_point()` of the parent class `ParametericAFTRegressionFitter`. However, this fitter will not be found unless one includes it in the `lifelines` package, as it will be called as:
```python
name = self.__class__.__name__.replace("AFT", "")
uni_model = getattr(lifelines, name)()
```

So, if I don't do anything I will get the following error message:
```
File "/home/tapiac/.virtualenvs/py36/lib/python3.6/site-packages/lifelines/fitters/__init__.py", line 1688, in _create_initial_point
    uni_model = getattr(lifelines, name)()
AttributeError: module 'lifelines' has no attribute 'CustomFitter'
```

I can rewrite this method in the new `CustomAFTFitter` pointing to the correct `CustomFitter`. Then the AFT model works. Is this the intended way to do this? (rewriting the `_create_initial_point()` method?) Or is there another way to do this?

**Comment by CamDavidsonPilon** [comment]
Hi @cristobaltapia, interesting, I never planned on users to write their own AFT models, but I can think about how to make this easier in the future. 

One quick workaround is to just explicitly set the initial points in the call to `fit`: 
```python
my_aft.fit(df, 'T', 'E', initial_point=np.zeros(...))
```

That's not a very "nice" solution however.  You could rewrite/overwrite `_create_initial_point` to return something like a vector of zeros, too, however.

**Comment by cristobaltapia** [comment]
Hi @CamDavidsonPilon , it is not like I know exactly what I am doing with the custom AFT model though... just experimenting a bit :sweat_smile: . 

Both solutions seem OK for me, as it is not so much extra code. I just thought you might have thought about it already, since there was this example about making the custom model. :P 

By the way, is there any literature you would recommend regarding the implemented AFT models?

**Comment by CamDavidsonPilon** [comment]
Here's a resource for AFT models and Cox models I like: https://harvest.usask.ca/bitstream/handle/10388/etd-03302009-140638/JiezhiQiThesis.pdf

But they may use different parameterizations

**Comment by cristobaltapia** [comment]
Thanks for that reference! ;)
