### ISSUE TITLE
Pretty Table Results

### ISSUE THREAD

**Issue by lordflaron** [CamDavidsonPilon/lifelines#721]
Is there any support for having the regression tables output in latex or html?

**Comment by CamDavidsonPilon** [comment]
Not currently, but that would be a terrific idea!

**Comment by CamDavidsonPilon** [comment]
Currently, you can do `model.summary.to_latex()` however, and similarly `to_html`

**Comment by AlephNotation** [comment]
I can take this

**Comment by CamDavidsonPilon** [comment]
@AlephNotation, I feel a prerequisite step of generalizing the `print_summary` function to a class is necessary, first. This would enable easier changes to _all_ `print_summary` functions, and allow for some other neat extensions. Later today, I can post some example ideas on how this could be implemented, and we can proceed from there?

**Comment by lordflaron** [comment]
Wow, this is awesome! Do you think it would also be possible to choose the variables you want in the table, as well as set names for them?

**Comment by CamDavidsonPilon** [comment]
So almost all the classes in lifelines have a `print_summary` method that, if you squint, looks identical. (This is a good pattern for finding abstractions). The general structure looks like:
```python
   def print_summary(self, decimals=2, **kwargs):

        << print self >>
        << print a sequence of possible optional settings >>
        << print **kwargs >>
        print("---")

        << print summary dataframe, with some custom float formatting >> 
        
        << only the regression models have below >>
        print("---")
        << print concordance index score >>
       << print log-likelihood rate test summary >>
```

Within each lifelines fitter class, we can replace the `print_summary` method with something like:

```python
def print_summary(self, decimals=2, **kwargs):
     # existing doc string
     settings_kwargs = {
          # optional settings in here
     }
     SummaryPrinter(self,
        **settings_kwargs, 
        ).print(decimals, **kwargs) # maybe these are moved into the class args
```

For example, the `CoxPHFitter` might be [reimplemented](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/coxph_fitter.py#L1222-L1287)
```python
def print_summary(self, decimals=2, **kwargs):
     # existing doc string
     fit_settings = {
        "duration col": self.duration_col,
        "event col": self.event_col, 
        "weights col": self.weights_col if self.weights_col else None, # don't print if None
        "cluster col": self.cluster_col if self.cluster_col else None, 
        "robust variance": True if self.robust or self.cluster_col else None, 
         ...
     }
     SummaryPrinter(self,
       decimals=decimals,
        **{**fit_settings **kwargs}, # this "merges" the two dictionaries of things to print
        ).print()

```

Most of the formatting and logic is pushed into the `SummaryPrinter` class (see below)

Again, squinting all these _slimmer_ `print_summary` functions, they look the same except for the `fit_settings`. Maybe it can be generalized further, but I'm indifferent. 

So what might the `SummaryPrinter` look like? It should go in `lifelines.utils`. 

```python
class SummaryPrinter():

   def __init__(self, model, decimals=2, **fit_settings):
       self.model = model                    
       self.fit_settings = fit_settings
       self.decimals = decimals

   def print(self):
         # here we can do interesting things. 
         if in jupyter environment:  
              self.display_as_html()
         else:
              self.display_as_text()

   def display_as_text(self):
        # this function looks like the old print_summary

   def display_as_html(self):
       # this uses IPython tools like `from IPython.display import HTML, display`

```
That wraps up my idea. Let me know if you think of a better idea or an extension, or if anything is confusing. Apologies for dumping code with little comments!
