### ISSUE TITLE
AttributeError: module 'scipy.misc' has no attribute 'logsumexp'

### ISSUE THREAD

**Issue by pezAmaury** [CamDavidsonPilon/lifelines#722]
Hi,

I just installed lifelines to change from my regular survival analysis tool to something more automatic, and I'm running into the following issue:

> Traceback (most recent call last):
>   File "Regressions.py", line 31, in <module>
>     from lifelines import KaplanMeierFitter
>   File "/home/pezam/.local/lib/python3.6/site-packages/lifelines/__init__.py", line 13, in <module>
>     from lifelines.fitters.log_normal_fitter import LogNormalFitter
>   File "/home/pezam/.local/lib/python3.6/site-packages/lifelines/fitters/log_normal_fitter.py", line 5, in <module>
>     from autograd.scipy.stats import norm
>   File "/home/pezam/.local/lib/python3.6/site-packages/autograd/scipy/__init__.py", line 7, in <module>
>     from . import misc
>   File "/home/pezam/.local/lib/python3.6/site-packages/autograd/scipy/misc.py", line 7, in <module>
>     logsumexp = primitive(scipy.misc.logsumexp)
> AttributeError: module 'scipy.misc' has no attribute 'logsumexp'

It seems there is a conflict with Scipy, who has been recently upgraded to v.1.3.0. The documentation doesn't provide any page for `scipy.misy.logsumexp`, but suggests it is now in `scipy.special.logsumexp`. I suspect there will be other similar problems with the new scipy.

PS: Sorry this is a problem with autograd, I did not see it before.

**Comment by louden** [comment]
The issue is described [here](https://github.com/HIPS/autograd/issues/501) with a temporary solution until autograd is fixed.
