### ISSUE TITLE
More than two parameters in an AFT model

### ISSUE THREAD

**Issue by cristobaltapia** [CamDavidsonPilon/lifelines#724]
Hi,
I am trying to use a "Maximal Weibull" distribution for an AFT model. This distribution has three parameters (`lambda`, `beta` and `delta`). I have successfully implemented the corresponding parametric univariate fitter with these three parameters. However, I am puzzled about how to proceed with the AFT model, as all the implemented models have two parameters only (a primary and an ancillary one). I suppose that this should be in theory possible, right? Would it require major changes to the package code to do it?

PS: I know you didn't plan on people implementing their own AFT models, but well, your package is so well implemented that it invites you to do it ;)

**Comment by CamDavidsonPilon** [comment]
This really motivates me to think about making custom AFT models as [easy as custom univariate models](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Piecewise%20Exponential%20Models%20and%20Creating%20Custom%20Models.html). It's something I would really really love to add. I remember thinking about custom models when I was writing the classes, so it's not too far off. Let me describe the hard part, but you've already mention it:

Given N parameters, there needs to be an API to regress potentially different dataframes against different parameters. The API of `ancillary_df` doesn't work when we have more than 2 parameters. Maybe it's a dictionary? But what might the keys be? Just thinking out loud. 
 
Let me noodle on this a but longer.

**Comment by cristobaltapia** [comment]
Nice to hear that you are considering this :) I suppose that if a dictionary is used, then the keys should be the corresponding parameters. Of course, that would make it model-specific and one would have to change them manually when trying out different models.
