### ISSUE TITLE
scipy >= 1.3.0 incompatible with lifelines

### ISSUE THREAD

**Issue by Sikerdebaard** [CamDavidsonPilon/lifelines#725]
In scipy >= 1.3.0 some functions that lifelines uses are moved to a different namespace. Due to this change lifelines currently will not work when installed trough a package manager like pypi.

**Comment by CamDavidsonPilon** [comment]
Ah, this is important. I'll prepare a new release asap

**Comment by CamDavidsonPilon** [comment]
The problem is internal to autograd, and there is a PR to fix it: https://github.com/HIPS/autograd/pull/490

For now, unless you need scipy==1.3, I would suggest forcing `scipy <= 1.2.1` (lame, I know).

**Comment by Sikerdebaard** [comment]
Yup, that's what we ended up doing internally. I've added this fix to PR #726. Since autograd seems to move not too quickly it might be nice to release this 'fix' on the lifelines side as current installations trough a package manager like pip kind of fail.

**Comment by CamDavidsonPilon** [comment]
It's happening! https://pypi.org/project/autograd/

![gif](https://i.imgur.com/7drHiqr.gif)
