### ISSUE TITLE
Plot HR(exp(coefficients)) for CoxPHFitter

### ISSUE THREAD

**Issue by ThunderBearCN** [CamDavidsonPilon/lifelines#727]
I am using lifelines to run a Cox’s proportional hazard model.

And now I have a little confusing about the plot function of model’s coefficients, I read the Docs and find that the packages **could only plot log(HR)** (in fact they are model’s coefficients)directly, but in medical research, **reporting HR(also means exp(coefficients)) in plot and result are more acceptable**.

So, I wonder if they are some ways to get the HR plot directly? I have search in google but couldn’t find any solution about my idea. 

If the packages have  built-in way to plot HR will make the packages more useful for medical researcher.

Here is an example about HR plotting. We campare HR with 1 to find whether they are any effection about the factors.

![image](https://user-images.githubusercontent.com/47938656/58531362-9b6bc980-8214-11e9-94c9-1254d50036a6.png)

Thank you for your attention!

**Comment by CamDavidsonPilon** [comment]
👍 seems easy enough to add as a kwarg to `plot` in the next release.

**Comment by CamDavidsonPilon** [comment]
This is now possible in v0.21.3. Try `cph.plot(..., hazard_ratios=True)`
