### ISSUE TITLE
joblib serialization fails to work with autograd

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#741]
Some resources: 
https://github.com/HIPS/autograd/issues/38
https://joblib.readthedocs.io/en/latest/auto_examples/serialization_and_wrappers.html

**Comment by AbdealiJK** [comment]
I wonder if using autograd is much useful considering that the README suggests using JAX now:

https://github.com/HIPS/autograd

> Note: Autograd is still being maintained but is no longer actively developed. The main developers (Dougal Maclaurin, David Duvenaud, Matt Johnson, and Jamie Townsend) are now working on JAX, with Dougal and Matt working on it full-time. JAX combines a new version of Autograd with extra features such as jit compilation.

**Comment by AbdealiJK** [comment]
@CamDavidsonPilon This is solved now as part of https://github.com/CamDavidsonPilon/lifelines/pull/845
