### ISSUE TITLE
Weibull fitter and Weibull AFT with no features have different results for the same data

### ISSUE THREAD

**Issue by TianyuWu89** [CamDavidsonPilon/lifelines#750]
Hi,

I was using Weibull AFT model in my project. I noticed that, when using the Weibull fitter and Weibull AFT fitter with no features on the same data, they produce different results. The resulted parameters are different (exponential transform accounted for) and the survival curves differ. Is this due to the fact they have different likeli-hood function, and numerical instability? 
I noticed that the initial value of the Weibull AFT model is even generated by the Weibull fitter, which makes this difference more surprising.

Best,
Tianyu

**Comment by CamDavidsonPilon** [comment]
This is very surprising to me. 
From my local tests on some data, they do appear the same. Can you screenshot the output of the `print_summary` on both models? (Feel free to hide the variable names as well).

**Comment by TianyuWu89** [comment]
> This is very surprising to me.
> From my local tests on some data, they do appear the same. Can you screenshot the output of the `print_summary` on both models? (Feel free to hide the variable names as well).

Thank you for your response. This behavior does change from data to data. My data has a lot of censoring. 
I am currently behind a company firewall. I will try to replicate this issue using public data on my own computer and post when it's done.

**Comment by TianyuWu89** [comment]
> This is very surprising to me.
> From my local tests on some data, they do appear the same. Can you screenshot the output of the `print_summary` on both models? (Feel free to hide the variable names as well).

I am curious about your thought of this follow-up question: if we add one feature with 0 mean, and zero covariance with the all-1 vector, would the intercept of the Weibull AFT model be the same as the parameters of the Weibull model?

**Comment by CamDavidsonPilon** [comment]
That's a hard question to answer. It depends on whether the model is "collapsible" or not. Linear regression is collapsible; logistic regression and the Cox model [are not](http://jakewestfall.org/blog/index.php/2018/03/12/logistic-regression-is-not-fucked/). I suspect the AFT model is collapsible, so then I would answer your question in the affirmative.

**Comment by CamDavidsonPilon** [comment]
Hi @TianyuWu89, did you manage to find a reproducible example?

**Comment by TianyuWu89** [comment]
Hi @CamDavidsonPilon ,

Sorry for the late reply. Yes I indeed come up with a reproducible example. Before I give you the example, I have to say that the example is highly artificial and may not have any practical usefulness. I observed this odd behavior in my work because of a data processing error in my code. After I corrected the error the behavior disappeared. However, I did get a feeling what datasets produce this behavior: those having many censored samples with censoring time much longer than the observed event time.

Here is the code:
```import pandas as pd
import lifelines
from lifelines.datasets import load_dd
from lifelines import WeibullAFTFitter, WeibullFitter

df = load_dd()

df_simple = df[['duration', 'observed']].copy()

df_simple.loc[df_simple.duration >=4, 'observed'] = 0
df_simple.loc[df_simple['observed'] == 0, 'duration'] = 90

df_0 = df_simple.query('observed == 0').copy()

df_simple = pd.concat([df_simple] + [df_0 for _ in range(10)])
print("Event counts: ")
print(df_simple.observed.value_counts())

wb = WeibullFitter()
wb.fit(df_simple.duration, df_simple.observed)

wb.print_summary()

wbaft = WeibullAFTFitter()

wbaft.fit(df_simple, duration_col='duration', event_col='observed')
wbaft.print_summary()```

**Comment by CamDavidsonPilon** [comment]
Thanks for the detailed response! So I ran this locally, and also observed the behaviour. I see a small relative difference in the fitters, ex: 2.2452e+06 vs 2162472 and 0.2487 vs 0.2495. 

Can you confirm you see something similar? 

I initially thought it was a difference in how the minimization was done. I tested both models with the _same_ minimization routine, but observed the same behaviour. 

I think the problem is some slight rounding errors in the AFT model. Instead of fitting `lambda_` like in the non-AFT model, it's fitting `exp(1 * _intercept)`, and the `exp` (plus the additional operations) is causing some rounding / computer precision differences. 

Note that the log-likelihoods are almost identical: -5436.5294 vs -5436.5347, so we can be confident that both minimizations are reasonable solutions.

**Comment by TianyuWu89** [comment]
> Thanks for the detailed response! So I ran this locally, and also observed the behaviour. I see a small relative difference in the fitters, ex: 2.2452e+06 vs 2162472 and 0.2487 vs 0.2495.
> 
> Can you confirm you see something similar?
> 
> I initially thought it was a difference in how the minimization was done. I tested both models with the _same_ minimization routine, but observed the same behaviour.
> 
> I think the problem is some slight rounding errors in the AFT model. Instead of fitting `lambda_` like in the non-AFT model, it's fitting `exp(1 * _intercept)`, and the `exp` (plus the additional operations) is causing some rounding / computer precision differences.
> 
> Note that the log-likelihoods are almost identical: -5436.5294 vs -5436.5347, so we can be confident that both minimizations are reasonable solutions.

Yeah I think they are just rounding errors. I got slightly different values than yours. It probably is OS dependent.

**Comment by TianyuWu89** [comment]
In addition to the second question I ask you. I think our initial guess may be wrong. Adding one uncorrelated feature will change the value of the intercept. It is due to the special form of the underlying optimization problem. (Sorry a bit off-topic)
Speaking of optimization, it seems to me the underlying optimization problem for Weibull models are non-convex, which means they may be multiple local minimums. Not likely it is a contributor to the behavior in question tho, since it seems more like a numerical (rounding) issue.

**Comment by CamDavidsonPilon** [comment]
> Speaking of optimization, it seems to me the underlying optimization problem for Weibull models are non-convex, which means there may be multiple local minimums. 

for highly colinear inputs, I think it's more possible to have a multiple solutions. I think the weibull MLE problem should be pretty reliable though, and one doesn't need to worry much about multiple minimima.
