### ISSUE TITLE
Generalizing Parametric Regression models

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#751]
### Design goals:

1) Easy to add custom regression models, similar to how one can create custom univariate models.

2) Arbitrary number of parameters to fit to. Example: an exponential AFT model has a single parameter, whereas Weibull AFT model has two, and a custom one could have N. 

3) Fixing parameters. I should be able to fix n < N parameters to set parameters.

4) custom penalizers (this enables point 5 below) for users to allow some interesting parameter/information sharing. 

5) Stretch goal: make PiecewiseExponentialRegressionFitter less of a snowflake. 

Point 2. and 3. allow the Exponential AFT fitter to be a special case of the the Weibull AFT fitter. 

### Prior workarounds or issues

See also #720 and [this answer](https://stackoverflow.com/questions/56787015/is-it-possible-to-run-a-cox-proportional-hazards-model-with-an-exponential-distr/56794328#56794328)

### Some thoughts:

- I think I need to expel the idea of "primary" and "ancillary" for the general case, and make `Known` models reimplement those
- `PiecewiseExponentialRegressionFitter` is currently a snowflake. One of the reasons was because it has an arbitrary number of parameters and a customer penalizer function. I might be able to fold that into this class. 

### Custom AFT API

```python

class ShiftedWeibull(ParametericRegressionFitter):

    _fitted_parameter_names = ['lambda_', 'rho_', 'delta_']
    # no point in _bounds: assume they range over all floats, the user can change to positive only 
    # using the cumulative hazard and exp()

    def _cumulative_hazard(self, params, T, Xs):
        lambda_ = np.exp(np.dot(Xs["lambda_"], params["lambda_"])) # > 0
        rho_    = np.exp(np.dot(Xs["rho"],     params["rho_"]))    # > 0
        delta_  =        np.dot(Xs["delta_"],  params["delta_"])

        return ((T - delta_) / lambda_) ** rho_


    def _add_penalty(self, neg_ll, params):
        """ 
        only penalize the delta parameter, for whatever reason
        """
        penalty = params['delta_'] ** 2
        return neg_ll + self.penalizer * penalty



swf = ShiftedWeibull(penalizer=1.0)

covariates = {
  'lambda_': [variable names], # need a shortcut for all columns?
  'rho_':    [variable names], 
  'delta_':  [variable names] # (or fixed constant),
}

swf.fit_right_censoring(df, "T", "E", regressors=covariates) # TODO: name 
```

**Comment by CamDavidsonPilon** [comment]
WIP here: https://github.com/CamDavidsonPilon/lifelines/pull/752

**Comment by CamDavidsonPilon** [comment]
Need tools to help debug and visualize customer cumulative hazards

**Comment by cristobaltapia** [comment]
Wow, you have been doing some work in this! Looks very good :D 

I like the concept of "AFT fitter" to be replaced by the more general "parametric regression fitter", as we don't always want to have the exponential function applied to the parameters. I was actually going to suggest this :)

Also, would it make sense to define "bounds" for the parameters as it is done in the normal parametric fitters? Or is this no problem if the initial values are approximated by means of the corresponding parametric fitter? It might sound absurd, as we are fitting a function, which means that in the end, it can take any value, depending on the variables given. However, what happens when a parameter need to be e.g. larger than zero (at least for the given variables)? Just want to know your opinion about this, since your certainly understand this better :)

**Comment by CamDavidsonPilon** [comment]
I did think about "bounds", but didn't give it more than a few minutes thought. Let me think it a bit more now. 

For a parameter, `p`, it can be represented by a function of linear terms¹:

```
p = f( beta * x^T )
```

Remember, it's the `beta`s that we are trying so solve for. 

- If `p` should be positive, `f` can be `exp` - cool
- if `p` is bounded between 0 and 1, then `expit`/`tanh` can be used

The alternative route is to define bounds on `beta` - but because it's a linear combination, it's impossible (I think) to guarantee bounds on `p`. 

So my thinking is: unlike the univariate models, the user needs to define their bounds (implicitly) in the cumulative hazard. Here's an example of a cure model with bounds: 

```python
class CureModel(ParametricRegressionFitter):

    _fitted_parameter_names = ["lambda_", "beta_", "rho_"]

    def _cumulative_hazard(self, params, T, Xs):
        c = expit(np.dot(Xs["beta_"], params["beta_"]))
        lambda_ = np.exp(np.dot(Xs["lambda_"], params["lambda_"]))
        rho_ = np.exp(np.dot(Xs["rho_"], params["rho_"]))
        cdf = 1 - np.exp(-(T / lambda_) ** rho_)

        return -np.log((1 - c) + c * (1 - cdf))
```


¹ actually, it doesn't need to be a linear relationship. I could do something like `p = f( beta[0]  *  x[0] / (beta[1] * x[1]) )`

**Comment by cristobaltapia** [comment]
Thanks for sharing your thoughts about this. It makes sense to me. (I must confess though that I didn't even know about the `expit` function :P .) But sure, it is a nice way to implicitly limit the parameters of the distributions.

**Comment by helloannietran** [comment]
In the cumulative hazard func for CureModel, should it return -np.log(c + (1 - c) * sf) instead of -np.log((1 - c) + c * sf) if c is the cure rate? I'm new to survival analysis and currently experimenting with lifelines. Let me know if I should post this somewhere else...

**Comment by CamDavidsonPilon** [comment]
@helloannietran yes, you're correct, that makes more sense for a parameter called "cure" - the interpretation is all relative though!
