### ISSUE TITLE
KaplanMeierFitter median is giving Infinity issue

### ISSUE THREAD

**Issue by skagrawal10** [CamDavidsonPilon/lifelines#755]
KaplanMeierFitter median is giving Infinity issue. 

Any way to resolve this?

**Comment by CamDavidsonPilon** [comment]
That's expected if the Kaplan Meier curve doesn't intersect y=0.5.

**Comment by skagrawal10** [comment]
In this case, I am getting survival probability for all objects greater than .5. 
So, is there any way to check which data points are causing this issue?

**Comment by CamDavidsonPilon** [comment]
I doubt it's caused by individual data points. More likely, your dataset has lots of censoring (ie not many deaths observed)
