### ISSUE TITLE
Survival Curve stops at 0.98 probability.  

### ISSUE THREAD

**Issue by mancunian1792** [CamDavidsonPilon/lifelines#759]
**Disclaimer**: Not sure if its a data issue or a code issue. Need some help in figuring out why the following happens.

**Version**:0.21.5

**Issue**:  My data set contains 31705 observations where 31426 are censored. There are only 2 columns. Duration and failed(where TRUE indicates the event has failed and FALSE indicates otherwise).  Dataframe name df_full_1.

`df_full_1.describe()` returns the following.

Statistics | duration
--| --
Count | 31705.000000
mean | 2553.014509
std | 1299.844065
min | 93.000000
25% | 1416.000000
50% | 2462.000000
75% | 3668.000000
max | 4998.000000

The unit of duration is in days. The quantiles for the failed cases dont differ that much from my censored data 
`df_full[df_full["failed"]==True]["duration"].quantile([0,0.25,0.5,0.75,1])`  returns the following.

Quantiles | value
--|--
0.00   |   93.0
0.25    | 786.5
0.50  |  1359.0
0.75  |  1960.5
1.00  |  4815.0

I fit the model using the following code.
```
from lifelines import WeibullFitter    
wb2 = WeibullFitter().fit(df_full_1["duration"], df_full_1["failed"])
```
I used a normal weibull fitter since i wanted a baseline model without using any co-variates.
The summary looks like below.
```
<lifelines.WeibullFitter: fitted with 31705 observations, 31426 censored>
number of subjects = 31705
  number of events = 279
    log-likelihood = -3790.46
        hypothesis = lambda_ != 1, rho_ != 1

---
            coef  se(coef)  lower 0.95  upper 0.95      p  -log2(p)
lambda_ 91318.66  11953.64    67889.97   114747.36 <0.005     45.38
rho_        1.33      0.05        1.23        1.43 <0.005     32.76
```
I plot the survival function using the code
``` wb2.plot_survival_function() ```
![survival_function](https://user-images.githubusercontent.com/9761766/60519839-5a9f1e80-9cb2-11e9-95a2-878a59ae309a.png)

If you can see, the survival curve ends at 0.98 for the whole duration of 5000 hours. If i try to get the conditional time to event, since the curve doesn't go less than 0.5 probability it returns Infinity for all cases. I can't seem to understand where i have went wrong ? Is this because of the imbalance in the number of failed and censored cases ? 

Looking for some help.
Thanks,
Harish

**Comment by CamDavidsonPilon** [comment]
Hi @mancunian1792, you're doing everything right (and well-detailed issue, too). I think what you are looking to do is extend the survival curve to future times. This can be done with 

```python
from lifelines import WeibullFitter    
timeline = np.arange(0, 20000) # or whatever you'd like
wb2 = WeibullFitter().fit(df_full_1["duration"], df_full_1["failed"], timeline=timeline)
```

This will compute the survival curve at each value in `timeline`. After that, you should see the curve drop below 0.98, and `conditiona_time_to_event_` should produce more reasonable values. That being said, I think we can do better for parametric models: see issue #760

If you are curious, the reason why you see 0.98 is because you have such a high number of censored cases (non-failures).

**Comment by CamDavidsonPilon** [comment]
In the latest version, 0.22.0, you should see improved results in `conditional_time_to_event_`. Unless you have more questions (I'm open to more!), I'm going to close this issue.
