### ISSUE TITLE
Implementing a Log-Gamma fitter

### ISSUE THREAD

**Issue by cristobaltapia** [CamDavidsonPilon/lifelines#762]
Hi,

I am trying to implement a Log-Gamma fitter. According to [1], the CDF of this distribution is

![loggamma_cdf](https://user-images.githubusercontent.com/7276493/60666481-6aac2f00-9e67-11e9-84fe-4f9dbc02f78c.png)

with 

![loggamma_gamma](https://user-images.githubusercontent.com/7276493/60667565-1b1b3280-9e6a-11e9-8e69-acd819a525ca.png)

the incomplete Gamma ratio.

According to this definition, the cumulative hazard is given as

![loggamma_cum_haz](https://user-images.githubusercontent.com/7276493/60667219-4bae9c80-9e69-11e9-82de-988086202de5.png)

So I implemented this as a fitter:

```python
from lifelines.utils.gamma import gammainc

class LogGammaFitter(KnownModelParametericUnivariateFitter):

    _fitted_parameter_names = ["lambda_", "delta_", "kappa_"]

    _bounds = [(0, 14), (0, 10), (0, 10)]

    def _cumulative_hazard(self, params, times):
        lambda_, delta_, kappa_ = params
        z = np.exp((-lambda_ + times) / delta_)

        return -np.log1p(-gammainc(beta_, z))
```
Notice that I have imported the `gammainc` function from lifelines, as there were errors otherwise. But I cannot get this to converge. Even if I choose initial values that somewhat should describe this data well. Is this because of the problem with the `gammainc` function, or is just that the data is not good for the distribution? (Is the implementation good?)

[1] Castillo, E., A. S. Hadi, N. Balakrishnan, and J. M. Sarabia (2005). Extreme Value and Related Models with Applications in Engineering and Science. John Wiley & Sons, Inc. isbn: 0-471-67172-X.

**Comment by CamDavidsonPilon** [comment]
Ah! You've found the one function that is a problem. I haven't been able to make gammainc "work", but I have an open issue to reimplement this: https://github.com/CamDavidsonPilon/lifelines/issues/753

The problem is the derivative of the inc. gamma function is hard to write down. One option is to just use finite diff methods (like the current implementation), but this simply doesn't work (not sure why not). The other option is to try to approx. the derivative using some series representation (ala the linked issue).

**Comment by CamDavidsonPilon** [comment]
Evaluating the derivative of gammainc is a common problem, but I haven't been able to find a good reference implementation. Some R packages, like flexsurv, should have a stable implementation

**Comment by cristobaltapia** [comment]
Thanks @CamDavidsonPilon for taking care of this. I will close this issue, as it has been addressed in 9c3a62cb41be3a432444b7ab4138d314b5ef3cb4 . The `gammainc` works now as expected.

**Comment by CamDavidsonPilon** [comment]
Check out the new autograd-gamma library on pypi too

**Comment by cristobaltapia** [comment]
Already did. Works perfectly ;)
