### ISSUE TITLE
Confused about how to graph the effect of 'strata' variables 

### ISSUE THREAD

**Issue by NataliaVConnolly** [CamDavidsonPilon/lifelines#763]
Hi,

   Suppose we have a variable that's been binned and used in the 'stata' argument of fit, as in the documentation's example with variable "age" in the "rossi" dataset (https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html?highlight=strata).  It's not clear to me how one would assess the effect of this variable on survival after stratification.   In the example, neither the summary print out nor the plot contain any information about 'age'  after the model has converged.  

    Could you please help?

**Comment by CamDavidsonPilon** [comment]
Sorry I didn't get to this, Natalia. I think this is a more general survival analysis problem, and you will get better answers on a forum like https://stats.stackexchange.com/
