### ISSUE TITLE
NameError: name 'log_hazards' is not defined

### ISSUE THREAD

**Issue by nataliaconnolly** [CamDavidsonPilon/lifelines#767]
Hi,
 
   I am trying to run the time-varying fitter like so:

     from lifelines.utils import to_episodic_format

     cph_train1 = cph_train1.sort_values(by=['tenure'],ascending=False)
     cph_train1 = cph_train1[cph_train1.tenure>0]

     # the time_gaps parameter specifies how large or small you want the periods to be.
     cph_train1_long = to_episodic_format(cph_train1, duration_col='tenure',    
               event_col='churn', time_gaps=1)

     from lifelines import CoxTimeVaryingFitter
     ctv = CoxTimeVaryingFitter()

     ctv.fit(cph_train1_long,
            id_col='id',
            event_col='churn',
            start_col='start',
            stop_col='stop')

     ctv.print_summary(3, model="including time interaction")
     ctv.plot()

It runs through print_summary but then dies at the plot call like so:

       ---> 11 ctv.plot()

        <PATH>/cox_time_varying_fitter.py in plot(self, columns, **errorbar_kwargs)
         753         hazards = self.hazards_[columns].values.copy()
         754 
      --> 755         order = list(range(len(columns) - 1, -1, -1)) if user_supplied_columns else np.argsort(log_hazards)
         756 
         757         ax.errorbar(hazards[order], yaxis_locations, xerr=symmetric_errors[order], **errorbar_kwargs)

       NameError: name 'log_hazards' is not defined

I am using python3.7 and lifelines v. 0.21.5.   

Is there a way to fix this?  Thanks.

**Comment by CamDavidsonPilon** [comment]
Thanks for the bug report. Looks like I fixed this in this line: https://github.com/CamDavidsonPilon/lifelines/pull/757/files#diff-39c097e72b92a5aa30771ed9ab8fb451L755

Can you try upgrading to lifelines 0.22.0? `pip install lifelines==0.22.0`
