### ISSUE TITLE
Censoring ticks don't adjust when plotting cumulative density

### ISSUE THREAD

**Issue by NickCEBM** [CamDavidsonPilon/lifelines#769]
When plotting the cumulative density function for a `kmf.fit` and setting `show_censors` to `True`, the censor ticks do not adjust to fit the inverted curve.

`ax =  kmf_overall.plot(ci_show=False, show_censors=True, censor_styles={'ms':10, 'marker':'|'}, yticks=yticks, figsize=(15, 10), grid=True, legend=False, ax=ax, lw=2.5)`

![image](https://user-images.githubusercontent.com/25153969/60894496-b2adc600-a25a-11e9-83a1-2de04c99df90.png)

`ax = kmf_overall.plot_cumulative_density(ci_show=False, show_censors=True, censor_styles={'ms':10, 'marker':'|'}, yticks=yticks, figsize=(15, 10), grid=True, legend=False, ax=ax, lw=2.5)`

![image](https://user-images.githubusercontent.com/25153969/60894538-d07b2b00-a25a-11e9-8a58-dee7f7817005.png)

**Comment by CamDavidsonPilon** [comment]
wowow embarrassing. Thanks for the bug report, I'll fix for the next release.
