### ISSUE TITLE
Better alignment and sizing of at_risk_counts

### ISSUE THREAD

**Issue by NickCEBM** [CamDavidsonPilon/lifelines#770]
By setting `ha = "center"` you get nicer alignment with the x ticks.

`ha = "right"`

![image](https://user-images.githubusercontent.com/25153969/60897079-56997080-a25f-11e9-9cd3-32237aa7411b.png)

`ha = "center"`

![image](https://user-images.githubusercontent.com/25153969/60897148-7af54d00-a25f-11e9-8113-4eae1b6f19b9.png)

I also hacked together a way to adjust the font size by adding it as a parameter to the function that accepts an integer `x` then adding:

`ax2.set_xlabel("At risk", fontsize = x)`

Probably a nicer way to incorporate that into the arguments though.

edit:
Or very possible that there was already a way to adjust the font size and I just couldn't figure it out!

**Comment by NickCEBM** [comment]
This might help with #562

**Comment by CamDavidsonPilon** [comment]
Hi @NickCEBM! 
There were some changes to `at_risk_counts` in a recent version, so can you confirm that you are on a least 0.21.5, preferably v0.22.0? 

Let me play around with the "center" param a bit 👍

**Comment by NickCEBM** [comment]
Looks like the most recent on Conda Forge is 0.21.0 so that's what I'm on since I'm working within Anaconda.

https://anaconda.org/conda-forge/lifelines

I edited the function myself based on what's here in the repo though and imported to my code and got it to work the way I wanted. Perhaps it was already fixed up in the newer version though.

Not sure if I can force `conda update` to 0.22.0.

**Comment by CamDavidsonPilon** [comment]
> Looks like the most recent on Conda Forge is 0.21.0 so that's what I'm on since I'm working within Anaconda.

Looking into this now

**Comment by NickCEBM** [comment]
Any word on getting the updated versions to pushed to conda forge?

**Comment by CamDavidsonPilon** [comment]
Ooh sorry to leave you hanging. I need to work on the Conda workflow more. That’ll be my next task

**Comment by NickCEBM** [comment]
Just checking in again on updates for Conda Forge. Thanks!

**Comment by CamDavidsonPilon** [comment]
🤞 I think I just uploaded a new conda package

**Comment by NickCEBM** [comment]
Great! seeing it there too. Isn't showing up in my updates on conda yet though. Not sure why that would be.

**Comment by CamDavidsonPilon** [comment]
hm, not sure either. How do you usually update packages with conda?

**Comment by NickCEBM** [comment]
Probably not worth your time to sort if this is just a problem for me but as of now a `conda update --all` or trying to update the package individually or even install it again doesn't get it up past 0.21.0

**Comment by NickCEBM** [comment]
So at a bit of tinkering I can get it to install with 

`conda install -c conda-forge lifelines=0.22.8=py_0`

I imagine the reason it isn't updating with a standard `conda update --all` is because it downgrades scipy from 1.3.1 to 1.2.1 and this conflicts with the most up to date version of the standard conda library. I believe that causes `conda update -all` to bypass updates that conflict.

**Comment by CamDavidsonPilon** [comment]
hm, does lifelines force scipy 1.2.1? It shouldn't AFAIK.

**Comment by CamDavidsonPilon** [comment]
Also, ❤️for looking in this!

**Comment by NickCEBM** [comment]
That’s what it did when I installed. It was the only package it downgraded.

**Comment by NickCEBM** [comment]
So that install was on my windows machine, just to confirm for you, I'm updating it on my Mac. Here is what Terminal is showing me:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/25153969/68208703-aa2b8900-ffc9-11e9-9ef5-3d66039bd26a.png">

**Comment by NickCEBM** [comment]
Also, back to the original point of this pull request, my fixes still, I think let you customise and align 'at_risk_counts' better, even in the new version.

Without Fix:
<img width="842" alt="image" src="https://user-images.githubusercontent.com/25153969/68209790-11e2d380-ffcc-11e9-9ead-c7a04bd6ee39.png">

My fix:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/25153969/68209649-be708580-ffcb-11e9-821c-9a8e7fa76ac9.png">

They can probably be implemented in a better way, or there may be inbuilt ways to do this but being able to control font size and centering the at risk counts with the axis values is much nicer in my opinion.

**Comment by CamDavidsonPilon** [comment]
I have an idea what’s happening - I’ll confirm later today

**Comment by CamDavidsonPilon** [comment]
This is why https://github.com/conda-forge/lifelines-feedstock/blob/0a6ec2ef5b6dc02f4db9dbb92ed99caa91409b57/recipe/meta.yaml#L32

:( it's annoying that I have to maintain two separate requirements.

**Comment by NickCEBM** [comment]
Yea I hear ya. I'm slowly trying to move away from Conda to my own environments but I imagine some not insignificant portion of your userbase is going to come via Conda given who uses it.

**Comment by CamDavidsonPilon** [comment]
Okay, try conda install now - I think the requirements should be corrected.

**Comment by NickCEBM** [comment]
Maybe it's not automatic as it's still not working. I'll try again later and see if it works:

![image](https://user-images.githubusercontent.com/25153969/68490432-db61be80-0240-11ea-99a5-64eb238d3a66.png)

**Comment by CamDavidsonPilon** [comment]
Okay it's live! https://anaconda.org/conda-forge/lifelines/files

**Comment by NickCEBM** [comment]
Great. So, it still doesn't update with a `condo update --all` but at least I can force it up to the most recent and scipy is now where it is supposed to be.

Seems like on install it still clashes with the  versions of some of the other stuff in the standard conda packages (like `ca-certificates` per my Mac screenshot above) which may cause it to be overlooked.

But I can live with this on my end. Not sure how much that matters to others.
