### ISSUE TITLE
Method to predict survival for censored data knowing that it has survived some time t.

### ISSUE THREAD

**Issue by mancunian1792** [CamDavidsonPilon/lifelines#771]
**Question**:

When lifelines is plotting or predicting survival for a range of times , does it take into account that an observation has survived till time T ? If i am not wrong, we need to update our survival curve as we know that it has survived till time T when predicting for T+u. If its already existing , which method should i use ?

**Example**

The following is my survival function .
![wb2_survival](https://user-images.githubusercontent.com/9761766/60981436-57d0a900-a304-11e9-8c31-888f09820e9a.png)

So, when i do 
```
wb2 = WeibullFitter().fit(df_full_1["duration"], df_full_1["failed"])
wb2.predict(7000)
```
i get the result as 0.5334356185336173. It seems like its just its interpreting from the curve. But if i know that this observation has survived till time T (say 100 days) my survival should be 1 from time 0 to 100.

**Comment by CamDavidsonPilon** [comment]
Good question - lifelines does not take into account the observed duration thus far (i.e., the survival curve returned is _not_ conditional). You can condition on living past time _s_ by dividing the unconditional survival curve by _S(s)_.  (and doing some appropriate clipping)

(Also see [conditional_time_to_event_](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.aalen_johansen_fitter.AalenJohansenFitter.conditional_time_to_event_) attribute)

**Comment by mancunian1792** [comment]
Yes, i tried to use conditional_time_to_event_ . But the problem with that is i cannot use that for an observation that i haven't used in my model. Or can it be ? 

Is there a plan to do the conditional survival curve in upcoming releases ? 

> You can condition on living past time s by dividing the unconditional survival curve by S(s). (and doing some appropriate clipping)

Divide by ? . Also, would it change if i use some other model other than weibull. This needs to be implemented at each base class , i believe ?

**Comment by CamDavidsonPilon** [comment]
> But the problem with that is i cannot use that for an observation that i haven't used in my model. Or can it be ?

With parametric models, you can extend as far as you want, so this isn't a problem. (You can use the `timeline` argument in `fit` to specify unseen times.)

> Divide by ? 

Sorry, I thought you knew the "trick". Take a look at the docs here: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction

> Also, would it change if i use some other model other than weibull. This needs to be implemented at each base class , i believe ?

Nope, as you can see from that doc link above, the math is the same regardless of the model.

**Comment by mancunian1792** [comment]
Oh, that makes a lot of sense. Should have paid more attention to the docs. Thanks a lot. 
Closing the issue.
