### ISSUE TITLE
Overflow on Kaplan-Meier variance estimate

### ISSUE THREAD

**Issue by lkieliger** [CamDavidsonPilon/lifelines#772]
Hello,

I'm working with heavily censored data and I encountered an issue when plotting the confidence band of my KM estimate. Some values in the additive_var vector were negative and resulted in NaNs after computation of the confidence band. I've been able to track the issue to an overflow in this function:

```
def _additive_var(self, population, deaths):
        np.seterr(divide="ignore")
        return (deaths / (population * (population - deaths))).replace([np.inf], 0)
```

More specifically, since population and deaths are passed as `int32`, large population values will result in an overflow in the denominator. I would suggest adding a cast to `int64` either here or directly in the survival table. Issuing a warning on overflows would be nice as well.

Kind regards

**Comment by CamDavidsonPilon** [comment]
Interesting. Is it correct that your `population` or `deaths` counts exceeded the int32 upper bound?

**Comment by lkieliger** [comment]
The population itself is not higher than the int32 upper bound. However, when the number of deaths is much smaller than the population, the denominator essentially becomes the population squared. This means that population values above 50k will already result in overflows since 50'000 squared is larger than  2^31.

**Comment by CamDavidsonPilon** [comment]
ho! Nice catch. Yea this is a pretty serious bug. I'll fix asap.
