### ISSUE TITLE
SLSQP vs L-BFGS-B

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#773]
Generalized Gamma seems to be much more stable with SLSQP. 

1. What are the perf gains / losses?
2. Do other models converge better, worse?

**Comment by cristobaltapia** [comment]
I have observed this with my data, too. Maybe it would be a good idea to have the possibility to define the method to be used in `minimize`? Maybe as a private variable of each fitter? Something like:

```python
class LogGammaParametricFitter(ParametricRegressionFitter):
    _fitted_parameter_names = ["lambda_", "delta_"]
    _minimize_method = "SLSQP" # <--- like this?

    def _cumulative_hazard(self, params, T, Xs):
        lambda_ = np.dot(Xs["lambda_"], params["lambda_"])
        delta_ = exp(np.dot(Xs["delta_"], params["delta_"]))

        beta_ = 0.437

        z = exp((-lambda_ + T) / delta_)

        return -np.log1p(-gammainc(beta_, z))

```

**Comment by cristobaltapia** [comment]
Just realized that you do have this implemented (`_sscipy_fit_method`), but it is not implemented in the `ParametricRegressionFitter` class. Why?

**Comment by CamDavidsonPilon** [comment]
Yup, something to add for a next release
