### ISSUE TITLE
Parallel curves in CoxPH

### ISSUE THREAD

**Issue by subratac353** [CamDavidsonPilon/lifelines#783]
Are the shapes of the curves generated using plot_covariates always show a certain shape (almost parallel trend) due to the proportional hazards assumption?

**Comment by CamDavidsonPilon** [comment]
That's right. After fitting the model, any output is _forced_ to obey the PH assumption. Note that this means it can't be used as a PH test for your training data.

**Comment by subratac353** [comment]
thanks very much Cameron. 
Sub
