### ISSUE TITLE
Force rho >0 for WeibullAFT model when model_ancillary=False

### ISSUE THREAD

**Issue by TianyuWu89** [CamDavidsonPilon/lifelines#794]
Hi,

Are we forcing rho>0 in the univariate model? Could we force it in the Weibull AFT model when model_ancillary=False?

Best,
Tianyu

**Comment by CamDavidsonPilon** [comment]
Hi @TianyuWu89, 

In the univariate model, rho is forced to be greater than 0. You can see more information [in the docs here](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#module-lifelines.fitters.weibull_fitter)


In the AFT model, we do still force the rho parameter to be greater than 0 (you can see the `exp` part [here](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#module-lifelines.fitters.weibull_aft_fitter)). However, when `model_ancillary`, we are trivially solving the problem: `rho = exp(alpha_0)`, so the `alpha_0` might be less than zero, but rho is still always positive. 

Does that make sense? If not I can try explaining again.

**Comment by TianyuWu89** [comment]
Oh! I missed the exponential part. Thank you! We should close this issue
