### ISSUE TITLE
fix docs for new conditional after

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#804]

**Comment by mohyneenm** [comment]
What happened to conditional_after? Can't find the param in the v0.22 of lifelines package.

**Comment by CamDavidsonPilon** [comment]
Hi @mohyneenm, it's only present in v0.22.3 and above. Can you confirm you are on a suitable version?

**Comment by mohyneenm** [comment]
Hey, thanks for the quick response. When I do "pip show lifelines" it says "Version: 0.22.4". However, the shft+tab doc of predict_survival_function only shows two params, and if I pass the conditional_after param it complains about not finding it.

**Comment by CamDavidsonPilon** [comment]
hmmm - what class are you trying it on? Like `CoxPHFitter`, `WeibullAFTFitter`?

**Comment by mohyneenm** [comment]
CoxPHFitter. I am on Mac btw, if that makes any difference.

**Comment by mohyneenm** [comment]
To be precise, this is the error message I am getting: 
"NotImplementedError: Sorry, conditional_after for Cox is tricky to do. It's not implemented yet."

**Comment by CamDavidsonPilon** [comment]
Ah yea. Sorry about that, that's because I haven't figured it out yet (in code). 

You can mimic the behaviour (which is what I may end up implementing) using logic like in the docs [here](https://github.com/CamDavidsonPilon/lifelines/blob/a4d76aabb244dded2aedfe0790f44a3cbe1b0d26/docs/Survival%20Regression.rst#prediction) - specifically the paragraphs on predicting censored subjects. 

(those are old docs, but still relevant)

**Comment by mohyneenm** [comment]
Yes, that's what I have been doing, thanks for confirming. Great package btw.

**Comment by clayh5** [comment]
> Ah yea. Sorry about that, that's because I haven't figured it out yet (in code).

Thanks for the explanation here, though I did want to say the docs are a little confusing since [here](https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction) you include conditional_after in your example that uses Cox. The code as you have it in the example won't run. I'll try the approach you linked for now. Love the package.

**Comment by CamDavidsonPilon** [comment]
Thanks @clayh5 and @mohyneenm for bringing this up - I'll spend time tomorrow working on this. Expect something soon!

**Comment by CamDavidsonPilon** [comment]
@clayh5 and @mohyneenm - just released was version 0.22.6, which has a functional `conditional_after`

**Comment by mohyneenm** [comment]
Can't wait to test it out! Thanks.

**Comment by clayh5** [comment]
> @clayh5 and @mohyneenm - just released was version 0.22.6, which has a functional `conditional_after`

Thanks a bunch, it's working like a charm for the most part! One little thing I noticed though, when conditional_after = t, the Cox PH  predict_survival_function only returns values for t+2 onward, skipping t+1. I'm checking against values I obtained using the method you used above. I'm not completely sure it's not a problem with the way I'm implementing it yet though.

**Comment by CamDavidsonPilon** [comment]
Hm, you maybe need to provide the `times` argument. By default, the time index used with `conditional_after` will be the same as the default for without `conditional_after`.  For example, can you try:

```
cph.predict_survival_function(X, conditional_after=..., times=np.arange(0, 10))
```

**Comment by clayh5** [comment]
That worked, thank you!

**Comment by CamDavidsonPilon** [comment]
I'll reopen this to add more examples/better description for future users.

**Comment by mohyneenm** [comment]
Hey Cameron, 
Really loving the Lifelines package. Will soon start using Lifetimes as well. 
Quick question about Lifelines... is it possible to get individual hazard ratio from the Cox fitter? For eg, when we do cph.print_summary() we get all the exp(coef) values for all the features. Is it possible to get them at the individual user level?
I am looking into cph.predict_survival_function(...), but it's not clear if it can give me each user's hazard ratio.
Thanks a lot,
Mehdi

    On Thursday, September 26, 2019, 02:49:40 p.m. EDT, Cameron Davidson-Pilon <notifications@github.com> wrote:  
 
 
I'll reopen this to add more examples/better description for future users.

**Comment by mohyneenm** [comment]
Will predict_partial_hazard(...) give me the individual hazard ratios? 
testing now....
    On Tuesday, November 12, 2019, 03:36:48 p.m. EST, Mohyneen Mehdi <mohyneenm@yahoo.com> wrote:  
 
  Hey Cameron, 
Really loving the Lifelines package. Will soon start using Lifetimes as well. 
Quick question about Lifelines... is it possible to get individual hazard ratio from the Cox fitter? For eg, when we do cph.print_summary() we get all the exp(coef) values for all the features. Is it possible to get them at the individual user level?
I am looking into cph.predict_survival_function(...), but it's not clear if it can give me each user's hazard ratio.
Thanks a lot,
Mehdi

    On Thursday, September 26, 2019, 02:49:40 p.m. EDT, Cameron Davidson-Pilon <notifications@github.com> wrote:  
 
 
I'll reopen this to add more examples/better description for future users.
