### ISSUE TITLE
DOC: Baseline hazard rate

### ISSUE THREAD

**Issue by sursu** [CamDavidsonPilon/lifelines#808]
**1**. Related to https://github.com/CamDavidsonPilon/lifelines/issues/543

For `CoxTimeVaryingFitter`, is it also true that: "baseline hazard is the hazard function when all covariates are set to the mean of the covariate"?

Their descriptions vary a bit:

[CoxPHFitter](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#module-lifelines.fitters.coxph_fitter):
![image](https://user-images.githubusercontent.com/12001304/63640130-fdfe2580-c69c-11e9-8e4a-2131f7a0cef8.png)

[CoxTimeVaryingFitter](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#module-lifelines.fitters.cox_time_varying_fitter):
![image](https://user-images.githubusercontent.com/12001304/63640111-db6c0c80-c69c-11e9-991e-df81d6a5e72e.png)

**2**. **The baseline hazard rate**, it is not clear to me how is it being computed.

Is it computed as suggested in:
- Breslow, N. (1974). Covariance analysis of censored survival data. Biometrics, 89-99.
?

Here is the fragment from the paper which tells the story:
![image](https://user-images.githubusercontent.com/12001304/63640310-d60fc180-c69e-11e9-80c9-06f6e4de91c4.png)

**Comment by CamDavidsonPilon** [comment]
👋 the docs the `CoxTimeVaryingFitter` need to be updated to look like 1. 

For 2., that is the formula we use, yes. I'll make it more clear in the docs.
