### ISSUE TITLE
Missing attribute

### ISSUE THREAD

**Issue by WyattSuling** [CamDavidsonPilon/lifelines#815]
I am largely new to Python and survival analysis, so apologies if this is a simple problem. I am trying to use the CoxPHFitter function, but it is throwing the error "'CoxPHFitter' object does not have the attribute 'duration_col.'" Possibly related is that I have a convergence issue I am trying to resolve using penalizer troubleshooting. Line of code is below, please let me know if more information is needed. Lifelines was installed recently, so my assumption is it is the latest release.

CoxPHFitter(penalizer = 0.1).fit(table_name, duration_col = 'duration', event_col = 'event', cluster_col = 'individual', show_progress = True)

'duration' is an integer, 'event' is an integer with values of 0 and 1, and 'individual' clusters on individuals as individuals can have multiple observations in the data. I'm not sure if it is relevant, but the table is roughly 190,000 rows, with only around 105,000 unique individuals.

**Comment by lordflaron** [comment]
Hi,

I'm not a developer but I've used lifelines before. What if you write your
duration and event column names without specifying that they are
`duation_col` and `event_col`? So:

```
CoxPHFitter(penalizer = 0.1).fit(table_name, 'duration', 'event',
cluster_col = 'individual', show_progress = True)
```

**Comment by WyattSuling** [comment]
I tried doing that and it still threw the same error. It doesn’t seem like an input issue, it strikes me as though the error is being encountered when the output is being generated. To add another tidbit, the iterations (6 usually) of the model get printed and finish before the error gets thrown.

**Comment by CamDavidsonPilon** [comment]
Hi, what version of lifelines do you have? Try ‘pip freeze’ to display

**Comment by WyattSuling** [comment]
Apologies for the delay and thank you for providing the necessary code, very helpful. I am running lifelines 0.22.3.

**Comment by CamDavidsonPilon** [comment]
Hm, very strange. Can you post the entire stack trace here please?

**Comment by WyattSuling** [comment]
I am sorry, but I do not know how to do that. Also, the environment I am working in does not allow copying information in or out, so that may impact my ability to post large amounts of information, but I can try provided no sensitive information from my data is contained within the stack trace.

**Comment by WyattSuling** [comment]
As an update, after playing with the code today, a coworker figured out the issue is in the print_summary function. I am simultaneously trying to do a time-varying version of the model and it encountered nearly identical errors. Both the print_summary and plot functions wanted me to define self and when I added "self = ctv", they both had missing attributes. Just like in the documentation, ctv is the CoxTimeVaryingFitter

When I made the code ignore those functions, both models ran successfully, albeit with 0.01 penalizers on each. So the models will run, I simply can't see what they say :)

**Comment by CamDavidsonPilon** [comment]
Can I ask what your code looks like? I'm not sure how `self=ctv` would work.

**Comment by WyattSuling** [comment]
Here is what it looks like:
____________________________________________________
start_time = time.time()

from lifelines import CoxTimeVaryingFitter
ctv = CoxTimeVaryingFitter

ctv(penalizer = 0.1).fit(table_name, id_col = 'identifier', event_col = 'event', start_col = 'start_qtr', stop_col = 'stop_qtr', show_progress = True)
ctv.print_summary(self = ctv)
ctv.plot(self = ctv)

print('CTV Regression completed in {:.2f} seconds'.format(time.time()-start_time))
___________________________________________________________________
When I did not have the 'self = ctv', the ctv.print_summary and ctv.plot functions had missing attribute errors for 'self'. I also think the missing attribute 'event_col' attribute was related to the ctv.print_summary().

**Comment by CamDavidsonPilon** [comment]
Thanks for sharing!
So this is an untraditional way to use lifelines. I would refactor the code to look like this:
```python

start_time = time.time()

from lifelines import CoxTimeVaryingFitter
ctv = CoxTimeVaryingFitter(penalizer=0.1)

ctv.fit(table_name, id_col = 'identifier', event_col = 'event', start_col = 'start_qtr', stop_col = 'stop_qtr', show_progress = True)
ctv.print_summary()
ctv.plot()

print('CTV Regression completed in {:.2f} seconds'.format(time.time()-start_time))

```

That should work as is

**Comment by WyattSuling** [comment]
Hello Cam,

Altering the code in line with what you wrote allowed both the time-varying and the normal proportional hazards models to run successfully with a penalizer. Thank you very much for the assistance, it is greatly appreciated!
