### ISSUE TITLE
'CoxPHFitter' object has no attribute 'params_'

### ISSUE THREAD

**Issue by Ghunzanfur** [CamDavidsonPilon/lifelines#826]
When trying to predict_median, I am being shown the above error message.

**Comment by CamDavidsonPilon** [comment]
Hi @Ghunzanfur, can you tell me which version of lifelines you have?
Try:
```python
import lifelines
print(lifelines.__version__)
```

**Comment by Ghunzanfur** [comment]
Hi @CamDavidsonPilon, I have version 0.22.4.

**Comment by CamDavidsonPilon** [comment]
hrm, not good. Let me investigate a bit.

**Comment by CamDavidsonPilon** [comment]
I am not able to reproduce locally. Can you try running the following on your computer?
```python
from lifelines.datasets import load_rossi
from lifelines import CoxPHFitter

rossi = load_rossi()
cph = CoxPHFitter().fit(rossi, 'week', 'arrest')
cph.predict_median(rossi)
```

Does that run successfully?

**Comment by Ghunzanfur** [comment]
Hey @CamDavidsonPilon,

Yes that is working, I am no longer getting the error either. Thank you!
