### ISSUE TITLE
Invalid API docs Example for AalenJohansenFitter

### ISSUE THREAD

**Issue by AbdealiJK** [CamDavidsonPilon/lifelines#830]
In the [API docs for AalenJohansenFitter](
https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.aalen_johansen_fitter.AalenJohansenFitter):

```
from lifelines.datasets import load_waltons
T, E = load_waltons()['T'], load_waltons()['E']
ajf = AalenJohansenFitter(calculate_variance=True)
ajf.fit(T, E)
```

The import: `from lifelines import AalenJohansenFitter` is missing

Also, the [fit() function](https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.aalen_johansen_fitter.AalenJohansenFitter.fit) says:
`fit(durations, event_observed, event_of_interest, ...`
 -- There are 2 required args, but in the example only 2 are provided.

**Comment by CamDavidsonPilon** [comment]
Thanks for letting us know! We'll fix this asap
