### ISSUE TITLE
Plot Hazard Ratio (rate) 

### ISSUE THREAD

**Issue by IvoryLu** [CamDavidsonPilon/lifelines#831]
Hi, 

This is a question instead of a real issue. 
I'm using the lifelines module to perform the Cox regression analysis. The cph.plot() function can plot log(HR) which is the coefficient. I'm just writing to ask whether there is a function can be used to plot the hazard ratio. 

Thank you

**Comment by CamDavidsonPilon** [comment]
Maybe you found the solution, but in recent releases there is a kwarg in the plot function to do just this.

**Comment by CamDavidsonPilon** [comment]
https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.coxph_fitter.CoxPHFitter.plot see `hazard_ratios` kwarg
