### ISSUE TITLE
Error in survival_difference_at_fixed_point_in_time_test

### ISSUE THREAD

**Issue by jakubruszkowski** [CamDavidsonPilon/lifelines#841]
Hi. I'm a new user of the lifelines package. After some successful application, I have a problem with using lifelines.statistics.survival_difference_at_fixed_point_in_time_test. When I paste an example from https://lifelines.readthedocs.io/en/latest/lifelines.statistics.html into Jupiter notebook in Anaconda, I receive "AttributeError: 'Series' object has no attribute 'columns'":

>   4 E2 = [1, 1, 1, 1,  1,  1,  1, 1]
>   5 from lifelines.statistics import survival_difference_at_fixed_point_in_time_test
> ----> 6 results = survival_difference_at_fixed_point_in_time_test(12, T1, T2, 
> event_observed_A=E1, event_observed_B=E2)
>   7 results.print_summary()
>
>  
> ~\Anaconda3\lib\site-packages\lifelines\statistics.py in 
> survival_difference_at_fixed_point_in_time_test(point_in_time, durations_A, durations_B, event_observed_A, event_observed_B, **kwargs)
>  230 
>  231     # **this is doing a prediction/interpolation between the kmf's index.**
> --> 232     sigma_sqA = interpolate_at_times_and_return_pandas(kmfA._cumulative_sq_, point_in_time)
>  233     sigma_sqB = interpolate_at_times_and_return_pandas(kmfB._cumulative_sq_, point_in_time)
> 
> 
> ~\Anaconda3\lib\site-packages\lifelines\utils\__init__.py in interpolate_at_times_and_return_pandas(df_or_series, new_times)
>  1563     new_times = _to_1d_array(new_times)
>  1564     return pd.DataFrame(
> -> 1565         interpolate_at_times(df_or_series, new_times), index=new_times, columns=df_or_series.columns
 >  1566     ).squeeze()
>   1567 
>
> 
> ~\Anaconda3\lib\site-packages\pandas\core\generic.py in __getattr__(self, name)
>   5174             or name in self._accessors
>   5175         ):
> -> 5176             return object.__getattribute__(self, name)
>   5177         else:
>   5178             if self._info_axis._can_hold_identifiers_and_holds_name(name):
> **AttributeError: 'Series' object has no attribute `'columns'**

How can I fix it?

**Comment by CamDavidsonPilon** [comment]
Whoops! I get the same error - let me fix this for the next release. For now, you can convert your data to a DataFrame, ex: 
```
data = pd.Series([1,2,3])
new_data =  pd.DataFrame(data, cols='data')
```

**Comment by CamDavidsonPilon** [comment]
No, wait my solution above won't work. You'll have to wait for the next release, sorry =(

I'll get it out very shortly though

**Comment by jakubruszkowski** [comment]
Thanks a lot!

**Comment by CamDavidsonPilon** [comment]
0.22.7 is now on PyPI with a fix
