### ISSUE TITLE
how to generate predicted time to event using coxph?

### ISSUE THREAD

**Issue by msnir009** [CamDavidsonPilon/lifelines#844]
I am quite new to survival analysis and I am trying to understand how to generate predictions in terms of time to event for each subject in my dataset. I have a dataset of machines that are tested for a limited duration. Some machines failed while others were still in working condition when the test ended. Therefore I have right censored data.  I am not confident to use a parametric model as the end of life distribution may not necessarily have a normal or Weibull like shape. So I am trying to use a semi parametric model through applying Cox regression. However, I realised that the cox regression function produces a hazard rate that gives an estimate of hazard at each timepoint. 

How do I then compute the estimated time to event for each subject? Is this possible or not? 

I would appreciate and guidance or advice on this. Thank you.

**Comment by CamDavidsonPilon** [comment]
Hi @msnir009, this is very possible. After fitting, the `CoxPHFitter` has methods like `predict_survival_function` that can predict the survival function of your machines. If you want a point estimate, you can use `predict_percentile`. 


I imagine you want _remaining life_, that is, you want to know how much life is left _given it's lived t time already_. There is the `conditional_after` argument in the `predict_` methods that can handle this. 

See more from our docs, [here](https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction)

**Comment by msnir009** [comment]
Hi @CamDavidsonPilon, thank you for your prompt reply. Yes I am looking to generate the duration that the machine survived until failure so that I can then compare it against the recorded duration to evaluate the error rate in predictions at least for those that did experience failure during the observation period.  I hope this makes sense as I imagine that I can generate the predicted time to event as how a linear regression method would predict the number of days until failure but I am using survival analysis due to having censored observations which I do not want to extrapolate to fit a linear curve instead. Thanks.

**Comment by CamDavidsonPilon** [comment]
@msnir009, is my comment above sufficient or do you require more information? You may also be interested in the `sklearn_adaptor`: https://lifelines.readthedocs.io/en/latest/Compatibility%20with%20scikit-learn.html

**Comment by msnir009** [comment]
thank you. I will try again and I think what you have provided is sufficient for now.
