### ISSUE TITLE
Predict funtion not recognising 'conditional_after' argument

### ISSUE THREAD

**Issue by msnir009** [CamDavidsonPilon/lifelines#849]
After fitting the cox model, I am trying to make prediction for censored subjects and I got the error below. I followed the example in the document but I am not sure why this error seems to not recognise the argument. Thanks. 

cph.predict_median(censored_subjects, conditional_after=censored_subjects_last_obs)

TypeError: predict_median() got an unexpected keyword argument 'conditional_after'

**Comment by CamDavidsonPilon** [comment]
Hi there, can you upgrade to version 0.22.8?

**Comment by msnir009** [comment]
thanks, it works now but I noticed that it is not able to produce a prediction value for all subjects where some shows 'inf'. I have tried to change the p rate in the cph.predict_percentile range and it changes the days for the same subjects that had a value before and the rest still remains 'inf'

**Comment by CamDavidsonPilon** [comment]
Does that make sense given your dataset? That is, might you have subjects (some subset of your data) that should never experience the event?

**Comment by msnir009** [comment]
Hi Cam, it doesn't make sense for the dataset I have because the subjects which were right censored are still expected to experience death at some point out of the observation period.

**Comment by CamDavidsonPilon** [comment]
Hm, my other idea is that the timeline is too short. The Cox model won't extrapolate past the longest observed death, hence if that value is too small, you'll get infs. 

You can try a parametric model: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#accelerated-failure-time-models

**Comment by msnir009** [comment]
Yes, I believe that is the issue so I will try using parametric models instead. Thank you very much.

**Comment by Evetricia** [comment]
Hello Cameron, I have encounter the same issue 'TypeError: predict_partial_hazard() got an unexpected keyword argument 'conditional_after' ', i have also downgrade the lifelines version to 0.22.8 from 0.22.9, it doesnt work. Also tried 0.23.0 but same result. Just wondering is there any other check that I can perform?

**Comment by Evetricia** [comment]
I also try out on cph.predict_survival_function() and cph.predict_median(), these two functions are working, only the predict_partial_hazard() doesnt work.

**Comment by CamDavidsonPilon** [comment]
Right, thats because partial_hazard doesn't change with time: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#cox-s-proportional-hazard-model

**Comment by Evetricia** [comment]
Thank you for clarify, it would be good also update the session on prediction for less confusion.
[https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction](url)
