### ISSUE TITLE
req/base-requirements.txt missing

### ISSUE THREAD

**Issue by omdgit** [CamDavidsonPilon/lifelines#852]
I tried to install lifelines-0.22.8.tar.gz and got the following error message: File "C:\Users\xxxxx\AppData\Local\Temp\pip-req-build-x6mtzyvm\setup.py", line 11, in <module>
        with open("reqs/base-requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'reqs/base-requirements.txt'

**Comment by CamDavidsonPilon** [comment]
Hi sorry about missing this! 

How did you try to install lifelines? Using `pip`? Or forking and running `setup.py`?

**Comment by omdgit** [comment]
I tried to install lifelines using pip.

**Comment by omdgit** [comment]
I'm using Windows 10

**Comment by matt-Andruff** [comment]
I ran into the same issue on centos.  Just increment the version and the error goes away.  (well technically i installed lifelines 0.9.4 instead)

**Comment by CamDavidsonPilon** [comment]
uh oh, seems like a bigger problem than I thought. Let me investigate more. 

> Just increment the version and the error goes away

what do you mean by that @matt-Andruff?

**Comment by CamDavidsonPilon** [comment]
I believe this problem is now fixed, see #900. New version on PyPI should fix this.

**Comment by omdgit** [comment]
Thank you!!
