### ISSUE TITLE
How can I save model after training 

### ISSUE THREAD

**Issue by hpham04** [CamDavidsonPilon/lifelines#857]
after training, how can I save the model so that I can use it right away without re-training the model each time i want to do prediction
Thanks

**Comment by hpham04** [comment]
Is it the one to do it?
https://github.com/CamDavidsonPilon/lifelines/blob/0c4781c14368e8a3064a7a0292dba1523317e897/docs/Examples.rst#serialize-a-lifelines-model-to-disk

**Comment by CamDavidsonPilon** [comment]
That's right, happy to help on gitter
