### ISSUE TITLE
Lower limit of Median Survival CI is 0 and Disagrees with R's Survival Package

### ISSUE THREAD

**Issue by windfreedom** [CamDavidsonPilon/lifelines#861]
I have a dataset that I'm trying to perform basic K-M survival analysis on. I initially used  lifelines to perform the analysis. To double check my results, I also then used the Survival package in R. However, I surprisingly received completely different results for the confidence interval of the median survival time.

The dataset is very small: 

[![enter image description here][1]][1]

As you can see it consists of 10 durations and 10 logical variables that indicate whether the event occurred or not (1 indicates that the event - death - was observed). 

In lifelines, I get the following results.

[![enter image description here][2]][2]

With the following survival curve.

[![enter image description here][3]][3]

I was extremely confused because the lower confidence interval was 0 in the output despite not being so in the graph itself. This is my first question: **how can the 95% CI lower bound be 0 in a calculation but not be so in the graph**? 

To add to my confusion, I then re-did the analysis in R. Firstly, I looked into different ways of calculating confidence intervals for point estimates in KM analysis, and it appears that Lifelines uses the Greenwood formula, while the R Survival package doesn't. So I switched the R survival package to use the Greenwood intervals. 

```r 
os_fit = survfit(km_os ~ 1, data = data, conf.type = 'plain')
ggsurvplot(os_fit, data = data, conf.int = TRUE, risk.table = TRUE, xlab = "Months", ggtheme = theme_light()) + ggtitle('Overall Survival') 
```

This resulted in:

[![enter image description here][5]][5]

The good news is that the upper bound matches between Lifelines and Survival. But the Lower Bound is still 28.9 for R's Survival, while the LB for lifelines is 0. **Is there a reason for this?**

Thanks so much in advance!

  [1]: https://i.stack.imgur.com/HkJSi.png
  [2]: https://i.stack.imgur.com/Qu5Zs.png
  [3]: https://i.stack.imgur.com/qXR6p.png
  [4]: https://i.stack.imgur.com/FC7IX.png
  [5]: https://i.stack.imgur.com/2adKX.png

**Comment by CamDavidsonPilon** [comment]
Hi @windfreedom, thanks for posting this here. Can you post the code you used to generate the lifeline's median confidence intervals? Also, can you post which version of lifelines you are using? (You can use: import lifelines; lifelines.__version__)

**Comment by windfreedom** [comment]
Using Lifelines version: '0.22.3'. 

```python

import lifelines
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from lifelines.utils import median_survival_times

df = pd.read_csv('filename.csv')
T_OS = list(df['OS'])
E_OS = list(df['OS Censor'])
T_PFS = list(df['PFS'])
E_PFS = list(df['rPFS Censor'])

#PFS is the same type of duration + observed data, but for a different #survival metric

fig1  = plt.figure(figsize=(15,10))
ax = fig1.add_subplot(111)

kmf = lifelines.KaplanMeierFitter()
kmf.fit(T_OS, event_observed=E_OS)
kmf.plot(ax = ax, color='b', ls='solid', ci_show=True, linewidth=4)
plt.title('Overall Survival', fontsize = 22)
plt.xlabel("Months", fontsize = 18)
plt.ylabel("Percent Survival", fontsize = 18)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.grid()
fig1.savefig('mOS.png')

## I was using a jupyter notebook, so what follows is a different cell. 


print("Median OS", kmf.median_)
print(median_survival_times(kmf.confidence_interval_))
print(kmf.event_table)
print(kmf.survival_function_)

```


Also here is the object types for the dataframe columns: 

[![enter image description here][7]][7]


  [1]: https://i.stack.imgur.com/HkJSi.png
  [2]: https://i.stack.imgur.com/Qu5Zs.png
  [3]: https://i.stack.imgur.com/qXR6p.png
  [4]: https://i.stack.imgur.com/FC7IX.png
  [5]: https://i.stack.imgur.com/2adKX.png
  [6]: https://i.stack.imgur.com/72Mxx.png
  [7]: https://i.stack.imgur.com/MIruI.png

**Comment by CamDavidsonPilon** [comment]
This helps thanks. I agree there is a problem here in the code, and it looks like a missed edge-case. I'll think about how to address this. Sorry about the inconvenience!

**Comment by CamDavidsonPilon** [comment]
Looking into this more,

1.  the correct R setting to match lifelines is `conf.type = 'log-log'`. However, that doesn't fix the problem. 
2. I think I have a fix, but it will require some more testing to make sure I'm not breaking other things.
