### ISSUE TITLE
Plotting with ci_show=True, CI area is dependent on the label text

### ISSUE THREAD

**Issue by Stakaitis** [CamDavidsonPilon/lifelines#862]
Thank You for an easy to use tool!

The bug is somehow associated with the word "**lower**" when using in _.fit(data1, data2, **label='something lower something'**)_. "lower" can be anywhere in the label= part, it doesn't matter. And the CI is plotting normally when I change "**lower**" to "**lowe**".

`kmf1= KaplanMeierFitter()
wbf= WeibullFitter()
hue1= IDH1_1_m181d_T2
hue2= IDH1_2_m181d_T2
x= 'Survived_Months'
event= 'Death'
c1= '#800000'
c2= '#808000'

kmf1.fit(hue1[x], hue1[event], labe= 'miR181d lower')
wbf.fit(hue1[x], hue1[event], label= 'miR181d lowe')
ax= kmf1.plot(ci_show= True, c= c1)
ax1= wbf.plot_survival_function(ci_show= True, c= c1)
ax2= wbf.plot(ci_show=True , c= c1)

kmf1.fit(hue2[x], hue2[event], label= 'MGMT methylated')
wbf.fit(hue2[x], hue2[event], label= 'MGMT methylated')
ax= kmf1.plot(ci_show= True, ax= ax, ls= '-.', c= c2)
ax1= wbf.plot_survival_function(ci_show= True, ax= ax1, ls='-.', c= c2)
ax2= wbf.plot(ci_show= True, ax= ax2, ls= '-.', c= c2)`
![185_Kaplan_m181d_IDH1_T2](https://user-images.githubusercontent.com/46847401/68303177-9fddbd80-00a3-11ea-8527-a87874494e02.png)
![186_Weibull_m181d_IDH1_T2](https://user-images.githubusercontent.com/46847401/68303181-9fddbd80-00a3-11ea-8f3a-d3247fa5b1d6.png)
![187_Weibull_hazard_m181d_IDH1_T2](https://user-images.githubusercontent.com/46847401/68303183-9fddbd80-00a3-11ea-9222-84908e2e66ad.png)

**Comment by CamDavidsonPilon** [comment]
ack! Yes, I see the bug. Thanks for the report, I'll fix very shortly and release to pypi.

**Comment by CamDavidsonPilon** [comment]
Try the latest, 0.22.10 available on pypi and conda
