### ISSUE TITLE
Getting Typeerror: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'

### ISSUE THREAD

**Issue by pdatascientist** [CamDavidsonPilon/lifelines#864]
I am using lifelines package for Cox regression. 

I am using below link which compatible with scikit-learn.

https://lifelines.readthedocs.io/en/latest/Compatibility%20with%20scikit-learn.html

The package is working fine with rossi dataset and I have attached the code to this email but when I am trying to used my dataset like clinical and gene then I am getting error TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe' for both dataset.

Previosuly, I am getting error like the particular column variance is very low to the target variable and delete the particular column from dataset. So, I have delete the low variance column but now I am getting TypeError: Cannot cast array data from dtype('O') to dtype('float64') according to the rule 'safe'.

I have attached clinical and gene dataset and code to this email. 
[Cox Data.zip](https://github.com/CamDavidsonPilon/lifelines/files/3816070/Cox.Data.zip)

Could you please suggest on this??

**Comment by pdatascientist** [comment]
when I am trying to used lifelines packages in Flux dataset, I am getting below error; ConvergenceError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:

I have checked the flux dataset but it do not have any nan values present. Can you please look into it?? I have attached the code and file;
[FLUX Data.zip](https://github.com/CamDavidsonPilon/lifelines/files/3827278/FLUX.Data.zip)

**Comment by CamDavidsonPilon** [comment]
In the Flux dataset, there are many more columns than rows, so I suspect that problem is caused by that. I downloaded the dataset and added `CoxPHFitter(penalizer=100.0)`, and this converged (but to useless results). Is there obvious redundancy or high-correlation between variables in your dataset?

**Comment by pdatascientist** [comment]
> In the Flux dataset, there are many more columns than rows, so I suspect that problem is caused by that. I downloaded the dataset and added CoxPHFitter(penalizer=100.0), and this converged (but to useless results). Is there obvious redundancy or high-correlation between variables in your dataset?

Hi Cameron, When I am trying to used complete flux dataset with sk_cph = CoxRegression(penalizer=100.0), I am getting TypeError: Cannot cast array data from dtype(‘O’) to dytpe(‘float64’) according to the rule ‘safe’ .

I will try to used minimum flux features and  get back to you. Could you please let me know about the Clinical and Gene dataset error??

**Comment by CamDavidsonPilon** [comment]
Please try this:
```
df = pd.read_excel("/Users/camerondavidson-pilon/Downloads/FLUX Data/FLUX - Copy.xlsx")

dc="Overall Survival (Months)"; 
ec = "Patient's Vital Status"
base_class = sklearn_adapter(CoxPHFitter, event_col=ec)
cph = base_class(penalizer=100.)

df_ = df.drop('HUG0_SYMBOL', axis=1)

Y = df_.pop(dc).values
X = df_
cph.fit(X, Y)


r = cph.predict(df_)
```

This works for me - I suspect the problem is dropping the string column.

**Comment by pdatascientist** [comment]
> Please try this:
> 
> ```
> df = pd.read_excel("/Users/camerondavidson-pilon/Downloads/FLUX Data/FLUX - Copy.xlsx")
> 
> dc = "Overall Survival (Months)"; 
> ec = "Patient's Vital Status"
> base_class = sklearn_adapter(CoxPHFitter, event_col=ec)
> cph = base_class(penalizer=100.)
> 
> df_ = df.drop('HUG0_SYMBOL', axis=1)
> 
> Y = df_.pop(dc).values
> X = df_
> cph.fit(X, Y)
> 
> 
> r = cph.predict(df_)
> ```
> 
> This works for me - I suspect the problem is dropping the string column.

Hi Cameron,

This is working fine. But I am trying to calculate the concordance index by using cph.print.summary() and I am getting an error and also, I am trying to used randomized optimisation and getting error.

**Comment by CamDavidsonPilon** [comment]
Hm, this works for me:
```
cph.lifelines_model.print_summary()
```

Can you post what code you are seeing the error with?

**Comment by pdatascientist** [comment]
> Hm, this works for me:
> 
> ```
> cph.lifelines_model.print_summary()
> ```
> 
> Can you post what code you are seeing the error with?

Hi Cameron,

I am using below randomizedsearch code for optimisation;

from sklearn.model_selection import RandomizedSearchCV

clf = RandomizedSearchCV(cph, {'alpha':[0.01, 0.02, 0.03, 0.04, 0.05, 0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0],
    'penalizer':[10,20,30,40,50,60,70,80,90,100]
}, cv=3)
clf.fit(X_train, y_train)

print(clf.best_estimator, clf.best_params)

and I am getting error ConvergenceError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:

**Comment by pdatascientist** [comment]
> > Hm, this works for me:
> > ```
> > cph.lifelines_model.print_summary()
> > ```
> > 
> > 
> > Can you post what code you are seeing the error with?
> 
> Hi Cameron,
> 
> I am using below randomizedsearch code for optimisation;
> 
> from sklearn.model_selection import RandomizedSearchCV
> 
> clf = RandomizedSearchCV(cph, {'alpha':[0.01, 0.02, 0.03, 0.04, 0.05, 0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0],
> 'penalizer':[10,20,30,40,50,60,70,80,90,100]
> }, cv=3)
> clf.fit(X_train, y_train)
> 
> print(clf.best_estimator, clf.best_params)
> 
> and I am getting error ConvergenceError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:

Hi Cameron,
I am trying to used cross validation and randomized search optimization but getting below error;
ConvergenceError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:

I have attached files to this. Please check the same.
[Clinical.zip](https://github.com/CamDavidsonPilon/lifelines/files/3883632/Clinical.zip)

**Comment by CamDavidsonPilon** [comment]
The problem is that your dataset is too sparse. For example, the columns `Form completion date_XXX` are sparse one-hot encoded cat. variables, but because the cross validation will split the dataset into smaller chunks, there will be many columns with all zeros in a chunk. This causes problems because there is no correct value to what the corresponding coefficient should be. 

My proposal is to find a better way to encode this categorical variable.

**Comment by pdatascientist** [comment]
> The problem is that your dataset is too sparse. For example, the columns `Form completion date_XXX` are sparse one-hot encoded cat. variables, but because the cross validation will split the dataset into smaller chunks, there will be many columns with all zeros in a chunk. This causes problems because there is no correct value to what the corresponding coefficient should be.
> 
> My proposal is to find a better way to encode this categorical variable.

Hi Cameron,
The same error I am getting when I am executing randomized search optimization on flux dataset i.e.ConvergenceError: delta contains nan value(s). Convergence halted. Please see the following tips in the lifelines documentation:

The dataset is not sparse and do not have categorical variable. The file is attached 
[Flux.zip](https://github.com/CamDavidsonPilon/lifelines/files/3884189/Flux.zip)

**Comment by pdatascientist** [comment]
> > The problem is that your dataset is too sparse. For example, the columns `Form completion date_XXX` are sparse one-hot encoded cat. variables, but because the cross validation will split the dataset into smaller chunks, there will be many columns with all zeros in a chunk. This causes problems because there is no correct value to what the corresponding coefficient should be.
> > My proposal is to find a better way to encode this categorical variable.

Hi Cameron,

can we calculate the variance score for each column in cox regression before cross validation in clinical dataset?? If yes, then could you please let me know the variance script please.
Thanks
