### ISSUE TITLE
setup.py installs data files in site-packages

### ISSUE THREAD

**Issue by Adsun701** [CamDavidsonPilon/lifelines#865]
The `setup.py` file installs files `README.md,` `LICENSE`, and `MANIFEST.in` in the `site-packages` root directory instead of a package specific directory.

Would it be possible to install these files in a more package-friendly directory such as `sys.prefix + "/share/doc/python-lifelines"` using `data_files` instead of `package_data`?

**Comment by CamDavidsonPilon** [comment]
I'll be honest, I know very little about packaging and `setup.py`. I'm happy to help with this, but can you show me some other setup.py examples of what you would like?

**Comment by Adsun701** [comment]
[Here is an example setup.py](https://github.com/pypa/sampleproject/blob/master/setup.py).

The reason why `README.md`, `LICENSE`, and `MANIFEST.in` get installed in the `site-packages` root folder is because in the `setup.py` `package_data` references them as outside of the `lifelines` folder (because they are inside the root folder in the source repository) so it ends up getting installed there.

Alternatively instead of putting these files in data_files, these files could be moved to inside the `lifelines` folder or in a `lifelines/doc` subdirectory, and modify `package_data` accordingly.
