### ISSUE TITLE
kmf.plot survival curves error

### ISSUE THREAD

**Issue by heavycello** [CamDavidsonPilon/lifelines#870]
I have a dataset that which contains about 1.2% of samples that have an event. However, when I run the kmf.fit and plot the survival, it shows around 4.5% do not survive over time.

I've looked at the dataframe and the data is correct going in. Is there any reason that I would be getting a significantly different plot for the survival curves? 

currently installed lifelines version 0.21.0

**Comment by CamDavidsonPilon** [comment]
Hi @heavycello, this is a common question that I should have an FAQ for. Let me first ask: do you have censoring in your dataset?

**Comment by heavycello** [comment]
Yes, there is a significant amount of censoring.

**Comment by heavycello** [comment]
So I'm now thinking the censoring is reducing the overall amount of samples
at each time interval right? If the were no censoring the total amount of
events over time would be 1.2% but at each interval there are fewer total
samples so the fraction of events grows?

Yes I'd say a FAQ description of this behavior would be very helpful.

**Comment by CamDavidsonPilon** [comment]
> So I'm now thinking the censoring is reducing the overall amount of samples
at each time interval right? If the were no censoring the total amount of
events over time would be 1.2% but at each interval there are fewer total
samples so the fraction of events grows?

Yup, you've pretty much got it. Those that are censored haven't died (obviously), so the KM curve takes that into account, hence with its terminal point is a larger value than 1.2%.

**Comment by heavycello** [comment]
Awesome, thank you for clarifying that, and for the quick response!
