### ISSUE TITLE
Shape mismatch when using conditional_after with strata in CoxPHFitter

### ISSUE THREAD

**Issue by VJarasse** [CamDavidsonPilon/lifelines#880]
When trying to use `conditional_after` parameter in CoxPHFitter prediction, I face a broadcast issue because the shapes of `np.tile(times_, (n_, 1))` and `conditional_after` don't match:
`times_to_evaluate_at = np.tile(times_, (n_, 1)) + conditional_after
ValueError: operands could not be broadcast together with shapes (25141,182) (77251,1)`

I am using stratas which make my `X_stratified` have `n_` all different from the size of X (`n`). My understanding from the `conditional_after` parameter is that I should give an iterator of size `n`. However, we never slice this iterator to make it match the samples from `X_stratified`, thus yielding the error.

Is that a bug or am I missing something?

**Comment by CamDavidsonPilon** [comment]
hm, probably a bug. I'll look into this.

**Comment by VJarasse** [comment]
Here is a little code snippet to reproduce the error, I hope it helps.
[cox_conditional_after.py.zip](https://github.com/CamDavidsonPilon/lifelines/files/3934534/cox_conditional_after.py.zip)

**Comment by CamDavidsonPilon** [comment]
fixed in latest, v0.23.2! 
This fix was greatly expedited by your example, so thank you!
