### ISSUE TITLE
Remove inverted axis example from docs

### ISSUE THREAD

**Issue by ian-whitestone** [CamDavidsonPilon/lifelines#884]
The current docs [here](https://lifelines.readthedocs.io/en/latest/Examples.html#invert-axis) include example code for plotting an inverted axis with kmf.

As per [changelog](https://github.com/CamDavidsonPilon/lifelines/blob/8f64de9d16425b232532977de43519bfbfdbb34a/CHANGELOG.md#0210---2019-04-12) this functionality was removed.

**Comment by CamDavidsonPilon** [comment]
nice catch! Thanks @ian-whitestone
