### ISSUE TITLE
CoxPHFitter alpha parameter 

### ISSUE THREAD

**Issue by ahlusar1989** [CamDavidsonPilon/lifelines#891]
Good Morning,

I am attempting to run the lifelines's examples and followed the steps for installing the development repository. I received the following and wanted to ensure that this [line](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/coxph_fitter.py#L148) indeed was the error. 

Thank you, in advance, for your time.

<img width="1083" alt="Screen Shot 2019-12-04 at 11 08 35 AM" src="https://user-images.githubusercontent.com/7760225/70159162-773aea80-1686-11ea-950e-7707bbe9b550.png">

**Comment by CamDavidsonPilon** [comment]
Yup! I noticed that too. I'll push a fix to master now so you can get unblocked.
