### ISSUE TITLE
Why is the median survival time infinite

### ISSUE THREAD

**Issue by woshigemi** [CamDavidsonPilon/lifelines#902]
![6800+故障及全部数据1](https://user-images.githubusercontent.com/49752900/70862108-cb8d7680-1f72-11ea-8c8f-23a48b671fe4.png)

**Comment by CamDavidsonPilon** [comment]
Hi @woshigemi, because the survival curve never passes y=0.5.

**Comment by woshigemi** [comment]
ok,Thank you very much
