### ISSUE TITLE
Error predict_survival_function(): unexpected keyword argument 'conditional_after'

### ISSUE THREAD

**Issue by ivandenende** [CamDavidsonPilon/lifelines#903]
I want to run the following code:
conditioned_sf = cph.predict_survival_function(censored_subjects, times=None, conditional_after=censored_subjects['Duration'])

But this results in an error:
TypeError: predict_survival_function() got an unexpected keyword argument 'conditional_after'

Does anyone know how to solve this error? In the documentation the same keywords are used: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html

**Comment by CamDavidsonPilon** [comment]
Hm, this might be a regression. I’ll look into it this morning.

**Comment by CamDavidsonPilon** [comment]
Can you post your version of lifelines (`import lifelines;lifelines.__version__`)?

**Comment by ivandenende** [comment]
My version of lifelines is 0.17.5.

**Comment by CamDavidsonPilon** [comment]
Can you upgrade to latest?

**Comment by anuttamasm** [comment]
I'm getting the same 

TypeError: predict_partial_hazard() got an unexpected keyword argument 'conditional_after'

when I try to use predict_partial_hazard - my code is:
censored_subjects = coxdata[~coxdata['Inforce'].astype(bool)]
censored_subjects_last_obs = censored_subjects['Total_Months']
cph.predict_partial_hazard(censored_subjects, conditional_after=censored_subjects_last_obs)

I'm using the latest version of lifelines (0.23.4)

**Comment by CamDavidsonPilon** [comment]
Oh, `predict_partial_hazard` doesn't have `conditional_after` since it the partial hazard is time-independent.

**Comment by anuttamasm** [comment]
I was only trying to follow the sample code given here: https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html#prediction

This is your own sample code below: 
# filter down to just censored subjects to predict remaining survival
censored_subjects = X.loc[~X['arrest'].astype(bool)]
censored_subjects_last_obs = censored_subjects['week']

cph.predict_partial_hazard(censored_subjects, conditional_after=censored_subjects_last_obs)
cph.predict_survival_function(censored_subjects, times=[5., 25., 50.], conditional_after=censored_subjects_last_obs)
cph.predict_median(censored_subjects, conditional_after=censored_subjects_last_obs)

**Comment by anuttamasm** [comment]
Though I see what you mean about it being time-independent. But perhaps the sample code should be changed to reflect that?

**Comment by CamDavidsonPilon** [comment]
Yup! Looks like an error in the docs. Thanks for flagging this.

**Comment by ivandenende** [comment]
> Can you upgrade to latest?

Thanks! It works.

**Comment by CamDavidsonPilon** [comment]
T
