### ISSUE TITLE
TimeVaryingCoxModel

### ISSUE THREAD

**Issue by ganzheng85** [CamDavidsonPilon/lifelines#907]
Can it provide Concordance Rate for the fitting result?

Thanks.

**Comment by CamDavidsonPilon** [comment]
No, as that involves some prediction, which can't be done with a Cox model. If you want some sort of model score, you can use AIC or BIC.

**Comment by ganzheng85** [comment]
Thanks. But, for time independent Cox model, in the print_summary(), it actually shows Concordance Rate. Just wonder why time varying Cox model cannot do that?
