### ISSUE TITLE
lognormal AFT fitter comment

### ISSUE THREAD

**Issue by zxp567** [CamDavidsonPilon/lifelines#908]
In the LogNormalAFTFitter code, the comment is as follows:
"This class implements a Log-Normal AFT model. The model has parameterized
    form, with :math:`\mu(x) = \exp\left(a_0 + a_1x_1 + ... + a_n x_n \right)`,
    and optionally, :math:`\sigma(y) = \exp\left(b_0 + b_1 y_1 + ... + b_m y_m \right)`,
    The cumulative hazard rate is
    .. math:: H(t; x, y) = -\log\left(1 - \Phi\left(\frac{\log(T) - \mu(x)}{\sigma(y)}\right)\right)
 "
I think there should be no "\exp" in the "\mu(x)"'s formula, right? The code seems to be correct though.

Thanks.

**Comment by CamDavidsonPilon** [comment]
Ah I believe you are right. I’ll correct shortly
