### ISSUE TITLE
Regarding Long Format

### ISSUE THREAD

**Issue by ahlusar1989** [CamDavidsonPilon/lifelines#910]
Good Morning,

Regarding this [line](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/utils/__init__.py#L1486):

- I am curious as to why this value is chosen?

Sincerely,
Saran

**Comment by CamDavidsonPilon** [comment]
Did you link the right url, @ahlusar1989?

**Comment by ahlusar1989** [comment]
My apologies @CamDavidsonPilon. The original comment has been updated.

**Comment by CamDavidsonPilon** [comment]
Looking at my tests and testing if I drop that line, the problem is that Pandas `pivot_table` behaves strangely when NAs are present in the dataset. So, a plausible default is `np.inf`, as one can think that a subject that never has the event == has the event at time inf.

**Comment by ahlusar1989** [comment]
Ah, yes, that makes sense. Thank you for the clarification.
