### ISSUE TITLE
Regarding Deprecation of left_censorship_cdf_plot

### ISSUE THREAD

**Issue by ahlusar1989** [CamDavidsonPilon/lifelines#911]
Good Morning,

I welcome feedback on on how to create a similar plot as provided [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/examples/left_censoring_experiments.py).

Sincerely,
Saran

**Comment by CamDavidsonPilon** [comment]
Good eye! Looking at my unit tests, this is the new function:

```python
            model.fit_left_censoring(T, E)
            ax = cdf_plot(model)
```

`cdf_plot` will handle left-censoring datasets & models internally.
