### ISSUE TITLE
Why the use of year**2 in US Presidential Example

### ISSUE THREAD

**Issue by ahlusar1989** [CamDavidsonPilon/lifelines#913]
Good Afternoon,

I was reviewing some of the results of the various parametric and non-parametric results and was puzzling about the use of the the year and year**2 covariates. 

At this point, I have exhausted my understanding of the hazard function and time-varying regression and was wondering if I could punt this over to you for an explanation 😄. I was going to post this on cross-validated but felt like this medium would be more appropriate given the specificity of the question.

**Comment by CamDavidsonPilon** [comment]
Hey there, sorry about missing this. 

It's to add a non-linear relationship to year. The hypothesis is that governments change _faster_ now than prior, so to reflect that, we can add a non-linear (quadratic) term.

**Comment by ahlusar1989** [comment]
Thank you for clarifying and for the intuitive.
