### ISSUE TITLE
Did you compare your code performance vs pure machine learning approach

### ISSUE THREAD

**Issue by Sandy4321** [CamDavidsonPilon/lifelines#918]
Did you compare your code performance vs pure machine learning approach

**Comment by CamDavidsonPilon** [comment]
Hi @Sandy4321 can you please elaborate?

**Comment by Sandy4321** [comment]
sorry for dealy
https://www.youtube.com/watch?v=6q-UFJUZK0g
Survival Ensembles: Survival Plus Classification for Improved Time-Based Predictions in R

he shows that usual Survival  is not much better than Classification 
or
https://stats.stackexchange.com/questions/29135/difference-between-survival-analysis-and-classification
or 
https://www.kaggle.com/questions-and-answers/47831

or
https://arxiv.org/abs/1909.11171
Survival analysis as a classification problem

etc
