### ISSUE TITLE
Method for parameter estimation and initialization

### ISSUE THREAD

**Issue by zisu-mis** [CamDavidsonPilon/lifelines#920]
Hi, first of all, I wish to thank you for your contribution. The package is really awesome!

However, I do have some questions regarding how ```lifelines``` estimates and initializes parameters. I assume that it first calculates the likelihood, and then applies autograd for optimization as it is required to import autograd at the beginning.  I am not fully aware of how the autograd exactly works like which optimization method or what learning rate it is using.

Another issue is about how ```lifelines``` initializes model parameters. These days I am customizing parametric baseline hazards to model survival data. However, these parametric specifications require parameters to be positive (e.g., Weibull function) and if the parameters are initialized as zeros, then the log-likelihood would be ill-posed. It is doable if we use some transformation on parameters, such as exponential function. However, the optimization quickly fails as some coefficients grow exponentially.  I am wondering if there is a certain way to impose the range of parameters and also initialize it to be some small positive value.

**Comment by CamDavidsonPilon** [comment]
Hi @zisu-mis, good questions! 

For your first question:

> I assume that it first calculates the likelihood, and then applies autograd for optimization as it is required to import autograd at the beginning.

Yes, and then no. We use `scipy.optimize.minimize` for optimization. What really helps converge is supplying the gradient, which autograd provides us. We also use autograd to help us with sensitivity analysis. Also, Scipy's minimize code doesn't use gradient descent, so there are no learning rates. Instead, Scipy uses more classic optimization algorithm which work great for convex problems (which we have). 

You can follow this logic in my tutorial repo: https://github.com/CamDavidsonPilon/PyDataNY_2019_tutorial

Model parameter initialization is always something I am thinking about, in fact. Let's use your Weibull example. You can do the `exp` transformation, _or_ you can use Scipy's minimizations to add a bounds (see the `bounds` argument [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize)). We do both, depending on the model.

**Comment by zisu-mis** [comment]
Thanks for your help! I will take a look at the tutorials you shared.

And I have encountered another issue while running the code and thought I could probably bring it up here. When running the customized regression models, such error prompts out:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\utils\__init__.py", line 49, in f
    return function(self, *args, **kwargs)
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\fitters\__init__.py", line 1324, in fit
    entry_col=entry_col,
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\fitters\__init__.py", line 1424, in _fit
    initial_point=initial_point,
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\fitters\__init__.py", line 1501, in _fit_model
    self._check_values_post_fitting(Xs.df, utils.coalesce(Ts[1], Ts[0]), E, weights, entries)
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\fitters\__init__.py", line 1133, in _check_values_post_fitting
    utils.check_complete_separation(df, E, T, self.event_col)
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\utils\__init__.py", line 1150, in check_complete_separation
    check_complete_separation_close_to_perfect_correlation(df, durations)
  File "C:\Users\*\Anaconda2\envs\*\lib\site-packages\lifelines\utils\__init__.py", line 1133, in check_complete_separation_close_to_perfect_correlation
    durations = durations.sample(n=500, random_state=0)
AttributeError: 'numpy.ndarray' object has no attribute 'sample'
```
I run the model with the same feature set and a different set of durations with no error message.  Seems that the original set of durations triggers the code to sample the data and as the ```durations``` is a numpy array instead of a pandas data frame, the error comes out.

**Comment by CamDavidsonPilon** [comment]
Yup! That was a bug I just fixed and pushed. Try updating to v0.23.5

**Comment by zisu-mis** [comment]
Thanks!
