### ISSUE TITLE
Syntax Error: lifelines/__init__.py

### ISSUE THREAD

**Issue by Kunalgroy** [CamDavidsonPilon/lifelines#925]
python version: 3.5.7
lifelines version: 0.23.6

`
>>> import lifelines
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/lifelines/__init__.py", line 28
    __all__: List[str] = [
                ^
SyntaxError: invalid syntax

`

**Comment by CamDavidsonPilon** [comment]
Weird! I will investigate today

**Comment by Kunalgroy** [comment]
Later, I'd downloaded and compiled python 3.6.10. Now, It is working perfectly.

I believe, the following kind of syntax is not supported by python3.5.

`__all__: List[str] = ['x', 'y'] `

But still, let me know if there is any better way out than changing the python version.

**Comment by CamDavidsonPilon** [comment]
Shoot, thats probably it. Looks like I implicitly bumped the min version to 3.6. I’ll likely push out a bug fix as I want to keep supporting 3.5

**Comment by CamDavidsonPilon** [comment]
Hi @Kunalgroy, try the latest v0.23.7 (on pypi). That should support py35 again.

**Comment by Kunalgroy** [comment]
Thanks @CamDavidsonPilon , I'll check again.
