### ISSUE TITLE
Inconsistent ValueError raised using KaplanMeierFitter.fit with input of different number of elements

### ISSUE THREAD

**Issue by CielAl** [CamDavidsonPilon/lifelines#933]
It appears that while using 

> kmf.fit(T, event_observed=E) # kmf as a KaplanMeierFitter instance

The dtype of each element in E and T(no matter whether it is a np.ndarray or pd.Series) is guarded by
line:979 in lifelines\utils\__init__.py (pass_for_numeric_dtypes_or_raise_array(x)), such that a value error will be raised if the dtype is object.

> raise ValueError("Values must be numeric: no strings, datetimes, objects, etc.")

However, this clause only works if T and E have only one element. This creates inconsistency when the input data is not explicitly cast, the exception is only raised when the selection of a certain group from the input data yields series/array of a single element, e.g. T1 = T[some_condition], T2 = T[~some_condition].

**Comment by CamDavidsonPilon** [comment]
Hi @CielAl, thanks for the issue. I'm having a hard time understanding what you mean, can you give an example in Python? 

Specifically, what do you mean by: 

> However, this clause only works if T and E have only one element.
