### ISSUE TITLE
Column labels disappear for predict_survival_function

### ISSUE THREAD

**Issue by david-bowman** [CamDavidsonPilon/lifelines#937]
Hi,

I'm using your package for some survival analysis of customer accounts. When I try to fit predictions for all accounts I lose the account number (which is my index) tagging for each column. For instance:

cphbaseline = CoxPHFitter()   ## Instantiate the class to create a cph object
cphbaseline.fit(df, 'Days_Ahead', event_col='Loss', show_progress=True, step_size = 0.3)   ## Fit the data to train the model

This code retains the account numbers as the column names:
cphbaseline.predict_survival_function(df.iloc[1:10]).head()

Whereas this defaults to numbers 0-99 for the column names:
cphbaseline.predict_survival_function(df.iloc[1:100]).head()

I'm pretty sure this has changed recently, looks like there is some cut off for carrying the labels through? I'm a bit uncomfortable tagging the columns by assuming they are in the same order as the original data.

Thanks,

David

**Comment by CamDavidsonPilon** [comment]
Hi @david-bowman, thanks for bringing this up. Is the only difference between your code the number of samples (10 vs 100)?

Can you also let me know what version of lifelines you are using? 
```python
import lifelines; lifelines.__version__
```

**Comment by david-bowman** [comment]
Hi - Apologies for this, I think I have now found the cause of the issue. There was a duplicated record erroneously added to a table I was using for the initial data pull, meaning one account_id was duplicated in the index. I believe that this is the reason the predictions defaulted to numbering rather than labelling the accounts.

Thanks for the quick response!

David

**Comment by CamDavidsonPilon** [comment]
I just hit this "bug" myself! It's maybe a bit too surprising that we drop labels if the index is not unique - I may add a warning to help the user debug this.
