### ISSUE TITLE
Implementation of Cox' time-varying phm, centered or not?

### ISSUE THREAD

**Issue by LordFinzenz** [CamDavidsonPilon/lifelines#946]
https://lifelines.readthedocs.io/en/latest/Time%20varying%20survival%20regression.html says that the model is using _x_i(t) - mean(x_i(t))_, whereas the API reference (https://lifelines.readthedocs.io/en/latest/lifelines.fitters.html#lifelines.fitters.cox_time_varying_fitter.CoxTimeVaryingFitter) simply gives _x_i(t) * ..._ - which one is true?

**Comment by CamDavidsonPilon** [comment]
Thanks for reporting this. It should be centered in both docs.
