### ISSUE TITLE
Kaplan Meier Fitter predict function return probabilities greater than 1

### ISSUE THREAD

**Issue by adityajumde** [CamDavidsonPilon/lifelines#957]
What might be the reason for the above issue? We are recently seeing this issue, when we call the predict function in the fitter we are seeing probabilities greater than 1

**Comment by CamDavidsonPilon** [comment]
Hm, I'm not able to reproduce this. Can you provide an example? 

If not, can you describe to me _which_ value you are predicting relative to when the deaths occur? I wonder if it's interpolating in a area with little information.

**Comment by adityajumde** [comment]
Thanks @CamDavidsonPilon . I think the comment you made on interpolating in an area with little information makes sense. I'll dig into that and keep you posted
