### ISSUE TITLE
cph.fit(X_train, y_train) taking huge time to execute and also randomized optimisation 

### ISSUE THREAD

**Issue by pradipmoon** [CamDavidsonPilon/lifelines#964]
Hi Cameron,

I am using lifelines packages for my Genesclinical dataset and its taking huge time for executing the cph.fit(X_train, y_train) while training (it will take more than 7 days and sometimes its terminate) and randomized optimisation.

Also, let me know the penalizer parameter assumptions can we used the values of (penalizer=100.0, 200.0, 300,0, 400.0, 500.0, 600.0, 700.0, 800.0, 900.0, 1000.0) in randomized optimisation or their is some appropriate values to used.

Download the files from below link;
https://drive.google.com/open?id=14eNqvSTvSbI3L7Aw9t2qKG-SY_B3TadU

Please suggest.

**Comment by CamDavidsonPilon** [comment]
I'm almost afraid to download that file! Can you tell me the dimensions of your dataset? Some advice:

1. Think about if you need to use _all_ the samples. After some number of samples, the std. errors on the hazards shrink to enough that it's sufficiently small. I would start with a random subsample that runs fast on your machine, and see if the std. errors are small enough. If not, increase the subsample size. 

2. If you have lots of covariates, well, that's a much more difficult problem for all of computational statistics, and I can't give reliable advice there - possibly googling for best practices would lead you to good solutions.

**Comment by pradipmoon** [comment]
The dimension 

> I'm almost afraid to download that file! Can you tell me the dimensions of your dataset? Some advice:
> 
> 1. Think about if you need to use _all_ the samples. After some number of samples, the std. errors on the hazards shrink to enough that it's sufficiently small. I would start with a random subsample that runs fast on your machine, and see if the std. errors are small enough. If not, increase the subsample size.
> 2. If you have lots of covariates, well, that's a much more difficult problem for all of computational statistics, and I can't give reliable advice there - possibly googling for best practices would lead you to good solutions.

**Comment by pradipmoon** [comment]
> The dimension
> 
> > I'm almost afraid to download that file! Can you tell me the dimensions of your dataset? Some advice:
> > 
> > 1. Think about if you need to use _all_ the samples. After some number of samples, the std. errors on the hazards shrink to enough that it's sufficiently small. I would start with a random subsample that runs fast on your machine, and see if the std. errors are small enough. If not, increase the subsample size.
> > 2. If you have lots of covariates, well, that's a much more difficult problem for all of computational statistics, and I can't give reliable advice there - possibly googling for best practices would lead you to good solutions.

The dimension of dataset is 517 x 14957. I am using randomized hyperparameter optimisation and using the penalizer values (penalizer=100.0, 200.0, 300,0, 400.0, 500.0, 600.0, 700.0, 800.0, 900.0, 1000.0). These are appropriate penalizer values or I need to used the lower values like 1.0, 2.0,......till 100.0.

**Comment by CamDavidsonPilon** [comment]
It depends on your covariates, but likely lower. Less than 1-ish.
