### ISSUE TITLE
CoxPHFitter with Splines gives increasing survival function

### ISSUE THREAD

**Issue by mathbrus** [CamDavidsonPilon/lifelines#965]
Hello,

Was just playing around a bit with the library. Really good work ! However, I stumbled upon a surprising result when trying to use a parametric model (cubic splines) for the baseline hazard function in the CoxPHFitter.

<img width="573" alt="Screenshot 2020-02-25 at 10 58 32" src="https://user-images.githubusercontent.com/37703961/75236224-c6904300-57bd-11ea-8590-81d959097b53.png">

Code snippet : 
```
cph_sp = CoxPHFitter(baseline_estimation_method='spline')
cph_sp.fit(spline_data, duration_col='DURATION_COL')
ax = cph_sp.plot_covariate_groups('error_model', [0, 0.05, 0.10, 0.15, 0.20, 0.25], cmap='coolwarm', )
```

Any idea what might cause this behaviour ?

Best, Mathieu

**Comment by CamDavidsonPilon** [comment]
Oh boy. I was worried this could happen and it occurred within a week. Are you able to provide the dataset?

**Comment by mathbrus** [comment]
Hi again,
Cannot provide the actual dataset unfortunately, but I could reproduce the error as follows  :

```
import numpy as np

# Generating random correlated data
mean = [6, 0, 60]
cov = [[5, 0, 0], [0, 5, 0], [0, 0, 5]]  # diagonal covariance
days, cov1, cov2 = np.random.multivariate_normal(mean, cov, 5000).T

# This is probably what causes the issue : some of the data has extreme values
days[4500:] = np.multiply(days[4500:], 50)

test_data = pd.DataFrame({'Days' : days, 'Cov1' : cov1, 'Cov2' : cov2})
test_data = test_data[test_data['Days'] > 0]

cph_sp = CoxPHFitter(baseline_estimation_method="spline")
cph_sp.fit(test_data, duration_col='Days')
cph_sp.plot_covariate_groups('Cov1', [0, 0.05, 0.10, 0.15, 0.20, 0.25], cmap='coolwarm', )
```

Hope this can help !

Best,
Mathieu
