### ISSUE TITLE
Using my own hazard score in the Cox model to draw survival probability curve

### ISSUE THREAD

**Issue by Lucius-lsr** [CamDavidsonPilon/lifelines#966]
I have used my own Deep-Learning method to get the hazard score in the Cox model for each sample. And that is p(x) in h(t|x)=h(t)exp^(p(x)) . 

I wonder how to draw the corresponding survival probability curve for each sample x in this case. 

Thanks a lot if you can help me.

**Comment by CamDavidsonPilon** [comment]
I don't think lifelines can help you, but you'll have to do some additional coding and reimplement the estimation of h(t), see https://stats.stackexchange.com/questions/46532/cox-baseline-hazard
