### ISSUE TITLE
Predict risk scores of subjects in fitted model

### ISSUE THREAD

**Issue by jgrinaveckis** [CamDavidsonPilon/lifelines#970]
Hello,

It's more a question than an issue - is it in plan to add a method which enable to predict risk scores for subjects in fitted model? (a la predict() in scikit-survival or predict_risk() in PySurvival)

Many thanks for answer!

**Comment by CamDavidsonPilon** [comment]
Hi @jgrinaveckis, 

It depends on what you mean by predicting risk? What is risk? I looked at PySurvival definition of risk, and it looks like it's just a way to turn things into a scalar value s.t. it can be sorted / ordered. There's no good interpretation to how they are defining risk. 

If you are looking for a scalar value, there are lots of options: `predict_median`, `predict_expectation`
