### ISSUE TITLE
Reporting spline formulas for Cox PH fitted with splines as the baseline hazard estimation method

### ISSUE THREAD

**Issue by hansdeferrante** [CamDavidsonPilon/lifelines#986]
Thanks for the awesome package!

We're fitting Cox proportional hazards models and want to report the full model, including a formula for the cumulative baseline hazard. We thought using the recently implemented splines to estimate the cumulative baseline hazard would be ideal for this, but haven't been able to retrieve coefficients (whereas for the `SplineFitter` we can retrieve phi's using summary()). Is there an option to do so we are unaware of?

Thanks in advance!

**Comment by CamDavidsonPilon** [comment]
hi @hansdeferrante, 

There's no option to display the coefficients for the splines. I wanted to keep the API between splines and non-splines the same. For your problem, you may need to use the more "raw" API. Let me show you: 

```
from lifelines.datasets import load_regression_dataset
df = load_regression_dataset()


from lifelines.fitters.coxph_fitter import _PHSplineFitter

# "T" and "E" the the duration and event columns

df_ = df.copy()
df_["constant"] = 1.0

regressors = {
    "beta_": df_.columns.difference(["T", "E"]), 
    "phi1_": ["constant"],
    "phi2_": ["constant"],
}

cph = _PHSplineFitter()
cph.fit(df_, "T", "E", regressors=regressors)
cph.print_summary()
```

**Comment by hansdeferrante** [comment]
Awesome! Thanks a lot. That should do it :).

**Comment by CamDavidsonPilon** [comment]
Let me know if you need more help!
