### ISSUE TITLE
Dead links in the sidebar

### ISSUE THREAD

**Issue by NapsterInBlue** [CamDavidsonPilon/lifelines#987]
Hey there,

Not sure if this a temporary bug in need of a refresh or something that needs rewriting, but the [documentation site](https://lifelines.readthedocs.io/en/latest/index.html) has several dead links in the navigation pane. e.g.:

* [Time Lagged Conversion Rates](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Modelling%20time-lagged%20conversion%20rates.html)
* [Survival Regression](https://lifelines.readthedocs.io/en/latest/Survival%20Regression.html)
* [Testing Proportional Hazard Assumptions](https://lifelines.readthedocs.io/en/latest/jupyter_notebooks/Proportional%20hazard%20assumption.html)

They also break when going to a prior section and hitting the "Next ->" prompt

Thanks!

**Comment by CamDavidsonPilon** [comment]
Yes, I just noticed this too. 

 - Some other sites are experiencing this as of 3:36pm EST: https://zepid.readthedocs.io/en/latest/, but others are fine: https://patsy.readthedocs.io/en/latest/
 - I tried rebuilding on RTD, no change.
 - I'm seeing a "Not Secure" beside the URL: 
<img width="178" alt="Screen Shot 2020-03-31 at 3 37 23 PM" src="https://user-images.githubusercontent.com/884032/78067971-a4ae5100-7365-11ea-91f8-3b2989d91aad.png">

Maybe some config error on RTD side?

**Comment by CamDavidsonPilon** [comment]
This pdf can be used for now: https://lifelines.readthedocs.io/_/downloads/en/latest/pdf/

**Comment by CamDavidsonPilon** [comment]
It may have something to do with a new RTD release today? https://docs.readthedocs.io/en/stable/changelog.html#version-4-1-2

I've posted a issue in their repo: https://github.com/readthedocs/readthedocs.org/issues/6842

**Comment by CamDavidsonPilon** [comment]
Fixed
