### ISSUE TITLE
restricted cubic splines for survival analysis - CoxPHFitter

### ISSUE THREAD

**Issue by nyousefi2020** [CamDavidsonPilon/lifelines#993]
Hi,
I have a survival analysis model in R and have been trying to replicate it in Python. I use CoxPHFitter for the analysis. I would like to use restricted cubic splines for two of the continuous variables in the model, but I suppose it is not possible in lifelines. I mean a function similar to rcs() in R package **rms** . 
Can you please help if there is a way of doing that in lifelines? Thanks

**Comment by CamDavidsonPilon** [comment]
Wow sorry about missing this. I've made the choice to push all transformations (things as simple as a log transform, to more complicated RCS) to _outside_ the library. The library [patsy](https://patsy.readthedocs.io/en/latest/) can do these transformation, and then lifelines can accept them.

**Comment by nyousefi2020** [comment]
Thanks for your reply!
